# Generated by Django 2.2.5 on 2020-03-06 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import poms.schedules.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('pricing', '0040_auto_20200304_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('cron_expr', models.CharField(blank=True, default='', help_text='Format is "* * * * *" (minute / hour / day_month / month / day_week)', max_length=255, validators=[poms.schedules.models.validate_crontab], verbose_name='cron expr')),
                ('last_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last run at')),
                ('next_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='next run at')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_procedures', models.ManyToManyField(blank=True, to='pricing.PricingProcedure', verbose_name='pricing procedures')),
            ],
            options={
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('user_code', 'master_user')},
            },
        ),
    ]
