# Generated by Django 4.1.3 on 2022-12-07 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import poms.schedules.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('cron_expr', models.CharField(blank=True, default='', help_text='Format is "* * * * *" (minute / hour / day_month / month / day_week)', max_length=255, validators=[poms.schedules.models.validate_crontab], verbose_name='cron expr')),
                ('last_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last run at')),
                ('next_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='next run at')),
                ('error_handler', models.CharField(choices=[['break', 'Break'], ['continue', 'Continue']], default='break', max_length=255)),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
            ],
            options={
                'ordering': ['user_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('current_processing_procedure_number', models.IntegerField(default=0, verbose_name='current processing procedure number')),
                ('status', models.CharField(choices=[('I', 'Init'), ('P', 'Pending'), ('D', 'Done'), ('E', 'Error')], default='I', max_length=1, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=25, null=True, verbose_name='type')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='schedules.schedule', verbose_name='schedule')),
            ],
        ),
    ]
