# Generated by Django 2.2.5 on 2020-08-14 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import poms.schedules.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_userprofile_active_master_user'),
        ('integrations', '0039_transactionfileresult_transactionprovider'),
        ('schedules', '0003_auto_20200525_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFileDownloadSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('cron_expr', models.CharField(blank=True, default='', help_text='Format is "* * * * *" (minute / hour / day_month / month / day_week)', max_length=255, validators=[poms.schedules.models.validate_crontab], verbose_name='cron expr')),
                ('last_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last run at')),
                ('next_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='next run at')),
                ('scheme_name', models.CharField(max_length=255)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.TransactionProvider', verbose_name='provider')),
            ],
            options={
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('user_code', 'master_user')},
            },
        ),
    ]
