# Generated by Django 2.2.5 on 2020-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_schedule_scheduleprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprocedure',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleprocedure',
            unique_together={('user_code', 'order', 'type')},
        ),
    ]
