# Generated by Django 4.1.3 on 2023-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_schedule_name_alter_schedule_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='configuration_code',
            field=models.CharField(max_length=255, verbose_name='Configuration Code'),
        ),
    ]
