# Generated by Django 2.2.5 on 2020-08-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0039_transactionfileresult_transactionprovider'),
        ('users', '0033_userprofile_active_master_user'),
        ('schedules', '0005_schedule_scheduleprocedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFileDownloadProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('scheme_name', models.CharField(max_length=255)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.TransactionProvider', verbose_name='provider')),
            ],
            options={
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
        migrations.DeleteModel(
            name='TransactionFileDownloadSchedule',
        ),
    ]
