# Generated by Django 2.2.5 on 2020-09-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20200916_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingSchedule',
        ),
    ]
