# Generated by Django 2.2.5 on 2020-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_delete_pricingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='error_handler',
            field=models.CharField(choices=[['break', 'Break'], ['continue', 'Continue']], default='break', max_length=255),
        ),
    ]
