# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('view_group', 'Can view group')], 'verbose_name': 'group', 'verbose_name_plural': 'group'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'member', 'verbose_name_plural': 'member'},
        ),
        migrations.AddField(
            model_name='masteruser',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=20, verbose_name='timezone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=20, verbose_name='timezone'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('master_user', 'user')]),
        ),
    ]
