# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
