# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakesequence',
            name='name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='fakesequence',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.Account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.AccountType', verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='counterparties.Counterparty', verbose_name='counterparty'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='counterparty_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='counterparties.CounterpartyGroup', verbose_name='counterparty group'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='instruments.InstrumentType', verbose_name='instrument type'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='mismatch_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_mismatch_account', to='accounts.Account',
                                    verbose_name='mismatch account'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='mismatch_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_mismatch_portfolio', to='portfolios.Portfolio',
                                    verbose_name='mismatch portfolio'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='portfolios.Portfolio', verbose_name='portfolio'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='counterparties.Responsible', verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='responsible_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='counterparties.ResponsibleGroup', verbose_name='responsible group'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy1', to='strategies.Strategy1',
                                    verbose_name='strategy1'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy1_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy1_group', to='strategies.Strategy1Group',
                                    verbose_name='strategy1 group'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy1_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy1_subgroup', to='strategies.Strategy1Subgroup',
                                    verbose_name='strategy1 subgroup'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy2', to='strategies.Strategy2',
                                    verbose_name='strategy2'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy2_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy2_group', to='strategies.Strategy2Group',
                                    verbose_name='strategy2 group'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy2_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy2_subgroup', to='strategies.Strategy2Subgroup',
                                    verbose_name='strategy2 subgroup'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy3', to='strategies.Strategy3',
                                    verbose_name='strategy3'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy3_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy3_group', to='strategies.Strategy3Group',
                                    verbose_name='strategy3 group'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy3_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_strategy3_subgroup', to='strategies.Strategy3Subgroup',
                                    verbose_name='strategy3 subgroup'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='thread_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='master_user_thread_group', to='chats.ThreadGroup',
                                    verbose_name='thread group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='', editable=False, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='username'),
        ),
    ]
