# Generated by Django 4.1.3 on 2023-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='journal_status',
            field=models.CharField(choices=[('full', 'Full'), ('disabled', 'Disabled')], default='full', max_length=25, verbose_name='journal status'),
        ),
    ]
