# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 09:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0008_auto_20170327_1122'),
        ('users', '0002_auto_20170125_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='transaction_type_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='transactions.TransactionTypeGroup', verbose_name='transaction type group'),
        ),
    ]
