# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160305_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='privategroup',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
