# Generated by Django 4.1.3 on 2023-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_masteruser_journal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="masteruser",
            name="journal_storage_policy",
            field=models.CharField(
                default="month",
                help_text="period to keep records (week, month, quarter & etc)",
                max_length=32,
                verbose_name="journal_policy",
            ),
        ),
        migrations.AlterField(
            model_name="masteruser",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="timezone to use",
                max_length=20,
                verbose_name="timezone",
            ),
        ),
        migrations.AlterField(
            model_name="masteruser",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="access token",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="token",
            ),
        ),
    ]
