# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160531_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value', models.PositiveIntegerField(default=0)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_sequences', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name_plural': 'fake sequence',
                'verbose_name': 'fake sequence',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fakesequence',
            unique_together=set([('master_user', 'name')]),
        ),
    ]
