# Generated by Django 4.1.3 on 2023-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_masteruser_journal_storage_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='deleted_user_code',
            field=models.CharField(blank=True, help_text='Stores original user_code of object. Deleted objects has null user_code which makes it available again.', max_length=255, null=True, verbose_name='deleted user code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark object as deleted. Does not actually delete the object.', verbose_name='is deleted'),
        ),
    ]
