# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakesequence',
            options={'ordering': ['name'], 'verbose_name': 'fake sequence', 'verbose_name_plural': 'fake sequences'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['username'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
