# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
