# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160313_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
