# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160614_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='first name'),
        ),
    ]
