# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-28 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_invitetomasteruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitetomasteruser',
            name='to_user',
        ),
        migrations.AddField(
            model_name='invitetomasteruser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
