# Generated by Django 4.2.3 on 2023-08-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_invitetomasteruser_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('deleted', 'Deleted'), ('invited', 'Invited')], default='active', max_length=255),
        ),
    ]
