# Generated by Django 4.2.3 on 2023-09-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('deleted', 'Deleted'), ('invited', 'Invited'), ('invite_declined', 'Invite Declined')], default='active', max_length=255),
        ),
    ]
