# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-28 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetomasteruser',
            name='from_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invites_to_users', to='users.Member', verbose_name='from_member'),
        ),
        migrations.AlterField(
            model_name='invitetomasteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invites_to_master_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
