# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_auto_20161017_0916'),
        ('accounts', '0015_auto_20161017_0916'),
        ('users', '0007_masteruser_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='mismatch_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_mismatch_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='mismatch_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_mismatch_portfolio', to='portfolios.Portfolio'),
        ),
    ]
