# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160622_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.Group', verbose_name='groups'),
        ),
    ]
