# Generated by Django 4.2.3 on 2024-03-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_masteruser_base_api_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masteruser',
            old_name='base_api_url',
            new_name='space_code',
        ),
    ]
