# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-25 14:24
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0024_auto_20181107_1607'),
        ('users', '0010_masteruser_pricing_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='transactions.TransactionType', verbose_name='transaction type'),
        ),
    ]
