# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0010_auto_20160804_1212'),
        ('users', '0010_auto_20160801_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='strategy1_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy1_group', to='strategies.Strategy1Group'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='strategy1_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy1_subgroup', to='strategies.Strategy1Subgroup'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='strategy2_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy2_group', to='strategies.Strategy2Group'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='strategy2_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy2_subgroup', to='strategies.Strategy2Subgroup'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='strategy3_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy3_group', to='strategies.Strategy3Group'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='strategy3_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy3_subgroup', to='strategies.Strategy3Subgroup'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy1', to='strategies.Strategy1'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy2', to='strategies.Strategy2'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='strategy3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_user_strategy3', to='strategies.Strategy3'),
        ),
    ]
