# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160329_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group2',
            options={'verbose_name': 'group2', 'verbose_name_plural': 'group2'},
        ),
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, to='users.Group2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
