# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_auto_20181220_1340'),
        ('users', '0011_masteruser_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='price_download_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.PriceDownloadScheme', verbose_name='price download scheme'),
        ),
    ]
