# Generated by Django 4.2.8 on 2024-03-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_masteruser_realm_code_alter_masteruser_space_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteruser',
            options={'verbose_name': 'master user', 'verbose_name_plural': 'master users'},
        ),
    ]
