# Generated by Django 4.2.8 on 2024-06-18 13:41

from django.db import migrations
from django.db import connection

def remove_columns(apps, schema_editor):
    sql_statements = [
        """
        DO $$
        BEGIN
            ALTER TABLE users_ecosystemdefault DROP COLUMN currency_pricing_scheme_id;
            ALTER TABLE users_ecosystemdefault DROP COLUMN instrument_pricing_scheme_id;
   
        END$$;
        """
    ]
    with connection.cursor() as cursor:
        for sql in sql_statements:
            try:
                cursor.execute(sql)
            except Exception as e:
                print(f"Failed to execute SQL: {e}")




class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_masteruser_options"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="ecosystemdefault",
        #     name="currency_pricing_scheme",
        # ),
        # migrations.RemoveField(
        #     model_name="ecosystemdefault",
        #     name="instrument_pricing_scheme",
        # ),
        migrations.RunPython(remove_columns, reverse_code=migrations.RunPython.noop)


    ]
