# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_masteruser_price_download_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notification_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Do not notify'), (2, 'Show & Email notifications'), (3, 'Email notifications'), (4, 'Show notifications')], db_index=True, default=4, verbose_name='notification level'),
        ),
    ]
