# Generated by Django 4.2.3 on 2024-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_ecosystemdefault_currency_pricing_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='deleted at'),
        ),
    ]
