# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-02 14:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_member_notification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='user_code_counters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
