# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 06:47
from __future__ import unicode_literals

from django.db import migrations
import poms.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_attrscheme_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attrscheme',
            name='member',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=poms.common.fields.LanguageField(blank=True, choices=[('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('ru', 'Russian')], default='en', max_length=5, null=True, verbose_name='language'),
        ),
    ]
