# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_auto_20190614_1035'),
        ('portfolios', '0005_portfolio_attrs'),
        ('chats', '0003_auto_20170125_1037'),
        ('accounts', '0004_auto_20170512_0739'),
        ('instruments', '0011_auto_20190614_1035'),
        ('strategies', '0003_auto_20170125_1037'),
        ('currencies', '0005_currency_default_fx_rate'),
        ('counterparties', '0003_auto_20170125_1037'),
        ('transactions', '0031_auto_20190614_1035'),
        ('users', '0014_masteruser_user_code_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Account', verbose_name='account')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.AccountType', verbose_name='account type')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.Counterparty', verbose_name='counterparty')),
                ('counterparty_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.CounterpartyGroup', verbose_name='counterparty group')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.Currency', verbose_name='currency')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.Instrument', verbose_name='instrument')),
                ('instrument_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentType', verbose_name='instrument type')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecosystem_default', to='users.MasterUser', verbose_name='master user')),
                ('mismatch_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecosystem_default_mismatch_account', to='accounts.Account', verbose_name='mismatch account')),
                ('mismatch_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecosystem_default_mismatch_portfolio', to='portfolios.Portfolio', verbose_name='mismatch portfolio')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolios.Portfolio', verbose_name='portfolio')),
                ('price_download_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.PriceDownloadScheme', verbose_name='price download scheme')),
                ('pricing_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.Responsible', verbose_name='responsible')),
                ('responsible_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.ResponsibleGroup', verbose_name='responsible group')),
                ('strategy1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy1', verbose_name='strategy1')),
                ('strategy1_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy1Group', verbose_name='strategy1 group')),
                ('strategy1_subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy1Subgroup', verbose_name='strategy1 subgroup')),
                ('strategy2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy2', verbose_name='strategy2')),
                ('strategy2_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy2Group', verbose_name='strategy2 group')),
                ('strategy2_subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy2Subgroup', verbose_name='strategy2 subgroup')),
                ('strategy3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy3', verbose_name='strategy3')),
                ('strategy3_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy3Group', verbose_name='strategy3 group')),
                ('strategy3_subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy3Subgroup', verbose_name='strategy3 subgroup')),
                ('thread_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.ThreadGroup', verbose_name='thread group')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionType', verbose_name='transaction type')),
                ('transaction_type_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionTypeGroup', verbose_name='transaction type group')),
            ],
        ),
    ]
