# Generated by Django 4.2.20 on 2025-05-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_ecosystemdefault_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='public key'),
        ),
        migrations.CreateModel(
            name='MasterUserSymmetricKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.BinaryField(help_text='Store AES key encrypted by member public key')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symmetric_keys', to='users.masteruser')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_keys', to='users.member')),
            ],
        ),
    ]
