# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0031_auto_20160407_0808'),
        ('portfolios', '0017_auto_20160407_0808'),
        ('transactions', '0026_auto_20160407_0808'),
        ('counterparties', '0011_auto_20160407_0808'),
        ('accounts', '0014_auto_20160407_0808'),
        ('users', '0016_auto_20160406_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attrscheme',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attrscheme',
            name='master_user',
        ),
        migrations.DeleteModel(
            name='AttrScheme',
        ),
    ]
