# Generated by Django 4.2.20 on 2025-06-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_member_public_key_masterusersymmetrickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystemdefault',
            name='license_key',
            field=models.CharField(blank=True, default='', editable=False, help_text='License Key (For Marketplace Access and Finmars Activation)', max_length=255, verbose_name='License Key'),
        ),
    ]
