# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import poms.common.fields
import poms.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160407_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'Deutsch'), ('ru', 'Russian')], default='en', max_length=5, null=True, verbose_name='language'),
        ),
    ]
