# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160412_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.Currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='', editable=False, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, to='users.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='join date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
