# Generated by Django 2.2.5 on 2019-10-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_member_deleted_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'User')], db_index=True, default=2, verbose_name='role'),
        ),
    ]
