# Generated by Django 2.2.5 on 2019-10-31 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_group_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetomasteruser',
            name='master_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.MasterUser', verbose_name='master user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invitetomasteruser',
            unique_together={('user', 'master_user')},
        ),
    ]
