# Generated by Django 2.2.5 on 2019-10-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20191031_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetomasteruser',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_to_users', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
