# Generated by Django 2.2.5 on 2019-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20191031_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetomasteruser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='invites', to='users.Group', verbose_name='groups'),
        ),
    ]
