# Generated by Django 2.2.5 on 2019-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20191111_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='permission_table_json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
        migrations.DeleteModel(
            name='GroupPermissionTable',
        ),
    ]
