# Generated by Django 2.2.5 on 2019-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_verification',
            field=models.BooleanField(default=False, verbose_name='two factor verification'),
        ),
    ]
