# Generated by Django 2.2.5 on 2020-06-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0023_auto_20200525_1351'),
        ('users', '0030_auto_20200520_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystemdefault',
            name='pricing_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PricingCondition', verbose_name='pricing condition'),
        ),
    ]
