# Generated by Django 2.2.5 on 2020-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_ecosystemdefault_pricing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Online'), (2, 'Offline'), (3, 'Backup')], default=1, verbose_name='status'),
        ),
    ]
