# Generated by Django 2.2.5 on 2020-09-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_userprofile_active_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
