# Generated by Django 2.2.5 on 2020-12-22 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0034_otptoken_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecosystemdefault',
            name='daily_pricing_model',
        ),
        migrations.RemoveField(
            model_name='ecosystemdefault',
            name='price_download_scheme',
        ),
        migrations.RemoveField(
            model_name='masteruser',
            name='price_download_scheme',
        ),
    ]
