# Generated by Django 2.2.5 on 2021-03-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0035_auto_20201222_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsercodePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80, verbose_name='prefix')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser',
                                                  verbose_name='master user')),
            ],
        ),
    ]
