# Generated by Django 2.2.5 on 2021-03-30 16:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0038_masteruser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
