# Generated by Django 2.2.5 on 2022-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0041_member_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted user code'),
        ),
    ]
