# Generated by Django 2.2.5 on 2019-12-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0055_auto_20191203_1235'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationbankfilefield',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Matched'), (2, 'Conflict'), (3, 'Resolved')], db_index=True, default=2, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='TransactionTypeReconField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=255, verbose_name='reference name ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('value_string', models.CharField(blank=True, default='', max_length=1024, verbose_name='value string')),
                ('value_float', models.CharField(blank=True, default='', max_length=1024, verbose_name='value float')),
                ('value_date', models.CharField(blank=True, default='', max_length=1024, verbose_name='value date')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_fields', to='transactions.TransactionType', verbose_name='transaction type')),
            ],
        ),
    ]
