# Generated by Django 2.2.5 on 2019-12-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_auto_20191211_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationcomplextransactionfield',
            name='complex_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_fields', to='transactions.ComplexTransaction', verbose_name='complex transaction'),
        ),
    ]
