# Generated by Django 2.2.5 on 2019-12-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('reconciliation', '0004_auto_20191223_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reconciliationbankfilefield',
            unique_together={('master_user', 'source_id', 'reference_name', 'import_scheme_name')},
        ),
    ]
