# Generated by Django 2.2.5 on 2020-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_auto_20200624_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationbankfilefield',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value float'),
        ),
        migrations.AlterField(
            model_name='reconciliationcomplextransactionfield',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value float'),
        ),
    ]
