# Generated by Django 4.0.6 on 2022-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reconciliation', '0007_auto_20200624_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypereconfield',
            name='value_date',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='value date'),
        ),
        migrations.AlterField(
            model_name='transactiontypereconfield',
            name='value_float',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='value float'),
        ),
        migrations.AlterField(
            model_name='transactiontypereconfield',
            name='value_string',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='value string'),
        ),
    ]
