# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventtohandle',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetype',
            unique_together=set([('master_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypegroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypeuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontypegroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontypeuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
    ]
