# Generated by Django 4.1.3 on 2023-02-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complextransaction',
            name='deleted_user_code',
        ),
        migrations.RemoveField(
            model_name='complextransaction',
            name='is_deleted',
        ),
    ]
