# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20160902_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value',
            field=models.CharField(blank=True, help_text='is expression', max_length=255, null=True),
        ),
    ]
