# Generated by Django 4.1.3 on 2023-02-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0003_initial'),
        ('transactions', '0003_remove_complextransaction_deleted_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransaction',
            name='linked_import_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='celery_tasks.celerytask', verbose_name='linked import task'),
        ),
    ]
