# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20160525_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='transactionattributetypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='transactionattributetypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='transactionattributetypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='transactiontypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='transactiontypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='transactiontypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='transactiontypeuserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='TransactionAttributeTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='TransactionTypeUserObjectPermission',
        ),
    ]
