# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0003_auto_20161215_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='date_expr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
