# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0004_auto_20170113_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='position_amount',
            field=models.FloatField(default=0.0,
                                    help_text='Absolute value of Position with Sign (for calculations on the form)',
                                    verbose_name='position amount'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='position_amount',
            field=models.CharField(default='0.0', max_length=255),
        ),
    ]
