# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160306_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='carry_amount',
            field=models.FloatField(blank=True, help_text='Absolute value of Carry with Sign (for calculations on the form)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Transaction Counterparty', null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.Counterparty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty_text',
            field=models.CharField(blank=True, help_text='Text for non-frequent Counterparty', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='factor',
            field=models.FloatField(blank=True, help_text='Multiplier (for calculations on the form)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_canceled',
            field=models.BooleanField(default=False, help_text='If checked – transaction is cancelled'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If checked – transaction cannot be changed '),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes_front_office',
            field=models.TextField(blank=True, help_text='text', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes_middle_office',
            field=models.TextField(blank=True, help_text='text', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overheads',
            field=models.FloatField(blank=True, help_text='Absolute value of Carry with Sign (for calculations on the form)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='principal_amount',
            field=models.FloatField(blank=True, help_text='Absolute value of Principal with Sign (for calculations on the form)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_price',
            field=models.FloatField(blank=True, help_text='Price (for calculations on the form)', null=True),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='internal code'),
        ),
    ]
