# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactiontype_is_valid_for_all_portfolios'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='is_valid_for_all_instruments',
            field=models.BooleanField(default=True),
        ),
    ]
