# Generated by Django 4.1.3 on 2023-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_complextransaction_source_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
    ]
