# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20160525_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtohandle',
            options={'verbose_name': 'event to handle', 'verbose_name_plural': 'events to handle'},
        ),
        migrations.AddField(
            model_name='eventtohandle',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='transactionattributetype',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
    ]
