# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactiontype_is_valid_for_all_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='transactions.TransactionAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='transactionclassifier',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='transactions.TransactionAttributeType', verbose_name='attribute type'),
        ),
    ]
