# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0006_auto_20170125_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='maturity_price',
            field=models.CharField(default='0.0', max_length=255, verbose_name='default price'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='accrued_multiplier',
            field=models.CharField(default='0.0', max_length=255, verbose_name='accrued multiplier'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='default_accrued',
            field=models.CharField(default='0.0', max_length=255, verbose_name='default accrued'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='default_price',
            field=models.CharField(default='0.0', max_length=255, verbose_name='default price'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='price_multiplier',
            field=models.CharField(default='0.0', max_length=255, verbose_name='price multiplier'),
        ),
    ]
