# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20160311_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, help_text='Min of accounting_date and cash_date'),
        ),
    ]
