# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20160908_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionclassifier',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
