# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0007_auto_20170214_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinput',
            name='value_expr',
            field=models.CharField(blank=True, help_text='this is expression for recalculate value', max_length=255,
                                   null=True, verbose_name='value expression'),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value',
            field=models.CharField(blank=True, help_text='this is expression for default value', max_length=255,
                                   null=True, verbose_name='value'),
        ),
    ]
