# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20160311_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionclass',
            name='code',
        ),
        migrations.AddField(
            model_name='transactionclass',
            name='system_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='system code'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=1, serialize=False),
        ),
    ]
