# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20160324_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('view_transaction', 'Can view transaction')], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
