# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20160908_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='carry_amount',
            field=models.FloatField(default=0.0, help_text='Absolute value of Carry with Sign (for calculations on the form)', null=True, verbose_name='carry amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='carry_with_sign',
            field=models.FloatField(default=0.0, null=True, verbose_name='carry with sign'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cash_consideration',
            field=models.FloatField(default=0.0, null=True, verbose_name='cash consideration'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='factor',
            field=models.FloatField(default=0.0, help_text='Multiplier (for calculations on the form)', null=True, verbose_name='factor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overheads',
            field=models.FloatField(default=0.0, help_text='Absolute value of Carry with Sign (for calculations on the form)', null=True, verbose_name='overheads'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overheads_with_sign',
            field=models.FloatField(default=0.0, null=True, verbose_name='overheads with sign'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='position_size_with_sign',
            field=models.FloatField(default=0.0, null=True, verbose_name='position size with sign'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='principal_amount',
            field=models.FloatField(default=0.0, help_text='Absolute value of Principal with Sign (for calculations on the form)', null=True, verbose_name='principal amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='principal_with_sign',
            field=models.FloatField(default=0.0, null=True, verbose_name='principal with sign'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_fx_rate',
            field=models.FloatField(default=0.0, help_text='FX rate to convert from Settlement ccy to Instrument Ccy on Accounting Date (trade date)', null=True, verbose_name='reference fx-rate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_price',
            field=models.FloatField(default=0.0, help_text='Price (for calculations on the form)', null=True, verbose_name='trade price'),
        ),
    ]
