# Generated by Django 4.1.3 on 2023-04-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_complextransaction_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_1',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 1'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_10',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 10'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_11',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 11'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_12',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 12'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_13',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 13'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_14',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 14'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_15',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 15'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_16',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 16'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_17',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 17'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_18',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 18'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_19',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 19'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_2',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 2'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_20',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 20'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_21',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 21'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_22',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 22'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_23',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 23'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_24',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 24'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_25',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 25'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_26',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 26'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_27',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 27'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_28',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 28'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_29',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 29'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_3',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 3'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_30',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 30'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_4',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 4'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_5',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 5'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_6',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 6'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_7',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 7'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_8',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 8'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_text_9',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='user text 9'),
        ),
    ]
