# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transactions', '0010_auto_20160606_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='display_expr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiontypeinput',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='accounting_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='cash_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (100, 'Relation')], default=20, verbose_name='value type'),
        ),
    ]
