# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_auto_20160329_0834'),
        ('transactions', '0010_auto_20160329_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='strategy_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_cash_set', to='strategies.Strategy'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='strategy_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_position_set', to='strategies.Strategy'),
        ),
    ]
