# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-31 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20170512_0739'),
        ('transactions', '0010_transactiontypeactioninstrumentfactorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeActionInstrumentManualPricingFormula',
            fields=[
                ('transactiontypeaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.TransactionTypeAction')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('notes', models.CharField(default='', max_length=1024, verbose_name='notes')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.Instrument', verbose_name='instrument')),
                ('instrument_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput', verbose_name='instrument input')),
                ('instrument_phantom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='instrument phantom')),
                ('pricing_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('pricing_policy_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput', verbose_name='pricing policy input')),
            ],
            options={
                'verbose_name_plural': 'transaction type action instrument manual pricing formula',
                'verbose_name': 'transaction type action instrument manual pricing formula',
            },
            bases=('transactions.transactiontypeaction',),
        ),
    ]
