# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20160401_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Transaction counterparty', null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.Counterparty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty_text',
            field=models.CharField(blank=True, help_text='Text for non-frequent counterparty', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes_front_office',
            field=models.TextField(blank=True, help_text='Notes front office', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes_middle_office',
            field=models.TextField(blank=True, help_text='Notes middle office', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio', verbose_name='portfolio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy', verbose_name='temporary strategy cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy', verbose_name='temporary strategy position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionClass', verbose_name='class'),
        ),
    ]
