# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20160908_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cash_consideration',
            field=models.FloatField(default=0.0, verbose_name='cash consideration'),
        ),
    ]
