# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20160607_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinput',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='transactions.TransactionType'),
        ),
    ]
