# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20170512_0739'),
        ('transactions', '0011_transactiontypeactioninstrumentmanualpricingformula'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinput',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
    ]
