# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20160607_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionType')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='complex_transaction_order',
            field=models.PositiveSmallIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeActionInstrument'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='complex_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.ComplexTransaction'),
        ),
    ]
