# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20160401_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='strategy_cash',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy', verbose_name='temporary strategy cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy_position',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy', verbose_name='temporary strategy position'),
        ),
    ]
