# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20160531_0610'),
        ('transactions', '0013_auto_20160608_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='portfolios.Portfolio'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='portfolio_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
    ]
