# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160404_1010'),
        ('transactions', '0013_auto_20160401_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_types', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name': 'transaction type',
                'verbose_name_plural': 'transaction types',
                'permissions': [('view_transactiontype', 'Can view instrument type')],
            },
        ),
        migrations.CreateModel(
            name='TransactionTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactiontype_tags', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name': 'transaction type tag',
                'verbose_name_plural': 'transaction type tags',
                'permissions': [('view_transactiontypetag', 'Can view instrument type tag')],
            },
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transactions.TransactionTypeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontypetag',
            unique_together=set([('master_user', 'user_code'), ('master_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontype',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
