# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20160606_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (110, 'Account'), (120, 'Instrument'), (130, 'Currency'), (140, 'Counterparty'), (150, 'Responsible'), (161, 'Strategy 1'), (162, 'Strategy 2'), (163, 'Strategy 3'), (170, 'Daily pricing model'), (180, 'Payment size detail'), (190, 'Instrument type')], default=20, verbose_name='value type'),
        ),
    ]
