# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-31 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20170512_0739'),
        ('transactions', '0014_auto_20181031_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinput',
            name='accrual_calculation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.AccrualCalculationModel', verbose_name='accrual calculation model'),
        ),
        migrations.AddField(
            model_name='transactiontypeinput',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.Periodicity', verbose_name='periodicity'),
        ),
    ]
