# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0012_auto_20160531_0610'),
        ('transactions', '0015_auto_20160608_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='carry_amount',
            field=models.CharField(default='0.', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='counterparties.Counterparty'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='counterparty_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='factor',
            field=models.CharField(default='0.', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='overheads',
            field=models.CharField(default='0.', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='principal_amount',
            field=models.CharField(default='0.', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='reference_fx_rate',
            field=models.CharField(default='0.', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='counterparties.Responsible'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='responsible_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='trade_price',
            field=models.CharField(default='0.', max_length=255),
        ),
    ]
