# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-02 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20181101_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontypeactioninstrumenteventaction',
            name='action_transaction_type',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactioninstrumenteventaction',
            name='action_transaction_type_input',
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrumenteventaction',
            name='transaction_type_from_instrument_type',
            field=models.CharField(default='', max_length=1024, verbose_name='text'),
        ),
    ]
