# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20160908_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade_price',
            field=models.FloatField(default=0.0, help_text='Price (for calculations on the form)', verbose_name='trade price'),
        ),
    ]
