# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20160405_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='complex_transactions',
            new_name='complex_transaction',
        ),
    ]
