# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20160614_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complextransaction',
            options={'verbose_name': 'complex transaction', 'verbose_name_plural': 'complex transactions'},
        ),
    ]
