# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20160405_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurred_count', models.PositiveIntegerField(default=0)),
                ('complex_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.ComplexTransaction')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveSmallIntegerField(choices=[(1, 'one-time'), (2, 'daily'), (3, 'weekly'), (4, 'monthly'), (5, 'quarterly'), (6, 'yearly')], default=1)),
                ('total_count', models.PositiveIntegerField(default=1)),
                ('timedelta', models.PositiveIntegerField(default=0)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionType')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.EventType'),
        ),
    ]
