# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20160405_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly'), (4, 'quarterly'), (5, 'yearly')], default=1),
        ),
    ]
