# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20181102_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='event_schedule_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionTypeActionInstrumentEventSchedule', verbose_name='event schedule phantom'),
        ),
    ]
