# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20160405_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexTransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('next_trigger_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('complex_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.ComplexTransaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='complex_transaction',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='complex_transaction',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.AddField(
            model_name='complextransactionitem',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
