# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20181102_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeaction',
            name='rebook_reaction',
            field=models.IntegerField(choices=[(0, 'Create'), (1, 'Skip'), (2, 'Overwrite'), (3, 'Clear all & Create'), (4, 'Create if not exist')], default=0),
        ),
    ]
