# Generated by Django 4.1.3 on 2023-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0021_transactiontype_configuration_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtohandle",
            name="user_code",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="user code"
            ),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="user_code",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="user code"
            ),
        ),
        migrations.AlterField(
            model_name="transactiontypegroup",
            name="user_code",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="user code"
            ),
        ),
    ]
