# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20160621_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionTypeGroup'),
        ),
    ]
