# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20160405_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('interval', models.PositiveIntegerField(default=2)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='complextransactionitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.RenameField(
            model_name='complextransactionitem',
            old_name='next_trigger_date',
            new_name='trigger_date',
        ),
        migrations.AddField(
            model_name='complextransactionitem',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.EventType'),
        ),
    ]
