# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import poms.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_transactiontype_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='accounting_date',
            field=models.DateField(default=poms.common.utils.date_now, verbose_name='accounting date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cash_date',
            field=models.DateField(default=poms.common.utils.date_now, verbose_name='cash date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=poms.common.utils.date_now, editable=False, verbose_name='transaction date'),
        ),
    ]
