# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_auto_20160406_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionattr',
            old_name='strategy_cash_root',
            new_name='strategy_cash',
        ),
        migrations.RenameField(
            model_name='transactionattr',
            old_name='strategy_position_root',
            new_name='strategy_position',
        ),
    ]
