# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_auto_20181107_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactioninput',
            name='event_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.EventClass', verbose_name='event class'),
        ),
        migrations.AddField(
            model_name='complextransactioninput',
            name='notification_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.NotificationClass', verbose_name='notification class'),
        ),
        migrations.AddField(
            model_name='transactiontypeinput',
            name='event_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.EventClass', verbose_name='event class'),
        ),
        migrations.AddField(
            model_name='transactiontypeinput',
            name='notification_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.NotificationClass', verbose_name='notification class'),
        ),
    ]
