# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20160908_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeaction',
            name='action_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
