# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-21 11:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_member_notification_level'),
        ('transactions', '0024_auto_20181107_1607'),
    ]

    operations = [

        migrations.AddField(
            model_name='complextransaction',
            name='master_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='complex_transactions', to='users.MasterUser',
                                    verbose_name='master user'),
            preserve_default=False,
        )

    ]
