# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def fix_transactions(apps, schema_editor):
    ComplexTransaction = apps.get_model("transactions", "ComplexTransaction")

    print('work?')

    for complexTransaction in ComplexTransaction.objects.all():
        complexTransaction.master_user = complexTransaction.transaction_type.master_user
        print(
            'complexTransaction.transaction_type.master_user.id %s ' % complexTransaction.transaction_type.master_user.id)

        if complexTransaction.master_user is None:
            complexTransaction.master_user = 1

        complexTransaction.save()


def rev(apps, schema_editor):
    # the reverse goes here if you want to copy company names into customer again if you migrate backwards.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_member_notification_level'),
        ('transactions', '0025_complextransaction_master_user'),
    ]

    operations = [
        migrations.RunPython(fix_transactions, rev)
    ]
