# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20160630_0806'),
        ('tags', '0009_auto_20160531_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='portfolios',
        ),
    ]
