# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_transactiontypeaction_action_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transactiontypegroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
