# Generated by Django 4.1.3 on 2023-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_transactiontypegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='configuration_code',
            field=models.CharField(max_length=255, verbose_name='Configuration Code'),
        ),
        migrations.AlterField(
            model_name='transactiontypegroup',
            name='configuration_code',
            field=models.CharField(max_length=255, verbose_name='Configuration Code'),
        ),
    ]
