# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_complextransaction_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='is_auto_generated',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='is autogenerated'),
        ),
    ]
