# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_remove_transactiontype_portfolios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionattributetype',
            options={'permissions': [('view_transactionattributetype', 'Can view transaction attribute type'), ('manage_transactionattributetype', 'Can manage transaction attribute type')], 'verbose_name': 'transaction attribute type', 'verbose_name_plural': 'transaction attribute types'},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'permissions': [('view_transactiontype', 'Can view transaction type'), ('manage_transactiontype', 'Can manage transaction type')], 'verbose_name': 'transaction type', 'verbose_name_plural': 'transaction types'},
        ),
        migrations.AlterModelOptions(
            name='transactiontypegroup',
            options={'permissions': [('view_transactiontypegroup', 'Can view transaction type group'), ('manage_transactiontypegroup', 'Can manage transaction type group')], 'verbose_name': 'transaction type group', 'verbose_name_plural': 'transaction type groups'},
        ),
    ]
