# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_auto_20160404_1051'),
        ('obj_attrs', '0014_auto_20160411_1247'),
        ('users', '0018_auto_20160407_0945'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('transactions', '0027_auto_20160411_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAttribute',
            fields=[
                ('attributebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='obj_attrs.AttributeBase')),
            ],
            bases=('obj_attrs.attributebase',),
        ),
        migrations.CreateModel(
            name='TransactionAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('order', models.IntegerField(default=0)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser')),
                ('strategy_cash_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy')),
                ('strategy_position_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionAttributeTypeGroupObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='transactions.TransactionAttributeType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionAttributeTypeUserObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='transactions.TransactionAttributeType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactionattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='transactions.TransactionAttributeType'),
        ),
        migrations.AddField(
            model_name='transactionattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='transactionattribute',
            name='strategy_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy'),
        ),
        migrations.AddField(
            model_name='transactionattribute',
            name='strategy_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypeuserobjectpermissionbase',
            unique_together=set([('member', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypegroupobjectpermissionbase',
            unique_together=set([('group', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetype',
            unique_together=set([('master_user', 'name')]),
        ),
    ]
