# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_transactiontypeactioninstrumenteventschedule_is_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
