# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_auto_20160705_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actionclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='name',
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='actionclass',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='notificationclass',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='periodicitygroup',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='transactionclass',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
    ]
