# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-25 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_complextransaction_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='accrual_calculation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.AccrualCalculationModel', verbose_name='accrual calculation model'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='accrual_calculation_model_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='accrual calculation model input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='instrument_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='instrument input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='instrument phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Periodicity', verbose_name='periodicity'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='periodicity_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='periodicity input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='event_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.EventClass', verbose_name='event class'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='event_class_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='event class input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='instrument_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='instrument input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='instrument phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='notification_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.NotificationClass', verbose_name='notification class'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='notification_class_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='notification class input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Periodicity', verbose_name='periodicity'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='periodicity_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='periodicity input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='event_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.EventSchedule', verbose_name='event schedule'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='event_schedule_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='event schedule input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentfactorschedule',
            name='instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='instrument phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='instrument_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='instrument input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='instrument phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='pricing_policy_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeInput', verbose_name='pricing policy input'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='allocation balance phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='allocation pl phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='instrument phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrument', verbose_name='linked instrument phantom'),
        ),
    ]
