# Generated by Django 4.1.3 on 2023-06-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_remove_transactiontype_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='group',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='group'),
        ),
    ]
