# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0013_remove_currencyhistory_master_user'),
        ('instruments', '0032_auto_20160411_1254'),
        ('accounts', '0015_auto_20160411_1247'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('transactions', '0028_auto_20160411_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Relation'), (40, 'Expression')], default=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionType')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTypeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('position_size_with_sign', models.FloatField(blank=True, null=True)),
                ('cash_consideration', models.FloatField(blank=True, null=True)),
                ('instrument_expr', models.CharField(blank=True, max_length=255)),
                ('transaction_currency_expr', models.CharField(blank=True, max_length=255)),
                ('position_size_with_sign_expr', models.CharField(blank=True, max_length=255)),
                ('settlement_currency_expr', models.CharField(blank=True, max_length=255)),
                ('cash_consideration_expr', models.CharField(blank=True, max_length=255)),
                ('account_position_expr', models.CharField(blank=True, max_length=255)),
                ('account_cash_expr', models.CharField(blank=True, max_length=255)),
                ('account_interim_expr', models.CharField(blank=True, max_length=255)),
                ('account_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Account')),
                ('account_interim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Account')),
                ('account_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Account')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instruments.Instrument')),
                ('settlement_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='currencies.Currency')),
                ('transaction_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionClass')),
                ('transaction_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='currencies.Currency')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionType')),
            ],
        ),
    ]
