# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_auto_20161003_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionclass',
            options={'ordering': ['name'], 'verbose_name': 'action class', 'verbose_name_plural': 'action classes'},
        ),
        migrations.AlterModelOptions(
            name='complextransaction',
            options={'ordering': ['transaction_type', 'code'], 'verbose_name': 'complex transaction', 'verbose_name_plural': 'complex transactions'},
        ),
        migrations.AlterModelOptions(
            name='eventclass',
            options={'ordering': ['name'], 'verbose_name': 'event class', 'verbose_name_plural': 'event classes'},
        ),
        migrations.AlterModelOptions(
            name='eventtohandle',
            options={'ordering': ['master_user', 'user_code'], 'verbose_name': 'event to handle', 'verbose_name_plural': 'events to handle'},
        ),
        migrations.AlterModelOptions(
            name='notificationclass',
            options={'ordering': ['name'], 'verbose_name': 'notification class', 'verbose_name_plural': 'notification classes'},
        ),
        migrations.AlterModelOptions(
            name='periodicitygroup',
            options={'ordering': ['name'], 'verbose_name': 'periodicity group', 'verbose_name_plural': 'periodicity group'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['master_user', 'transaction_date', 'transaction_code'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionattribute',
            options={'ordering': ['content_object', 'attribute_type'], 'verbose_name': 'transaction attribute', 'verbose_name_plural': 'transaction attributes'},
        ),
        migrations.AlterModelOptions(
            name='transactionattributetype',
            options={'ordering': ['master_user', 'name'], 'permissions': [('view_transactionattributetype', 'Can view transaction attribute type'), ('manage_transactionattributetype', 'Can manage transaction attribute type')], 'verbose_name': 'transaction attribute type', 'verbose_name_plural': 'transaction attribute types'},
        ),
        migrations.AlterModelOptions(
            name='transactionclass',
            options={'ordering': ['name'], 'verbose_name': 'transaction class', 'verbose_name_plural': 'transaction classes'},
        ),
        migrations.AlterModelOptions(
            name='transactionclassifier',
            options={'ordering': ['attribute_type', 'tree_id', 'level', 'name'], 'verbose_name': 'transaction classifier', 'verbose_name_plural': 'transaction classifiers'},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['master_user', 'group', 'user_code'], 'permissions': [('view_transactiontype', 'Can view transaction type'), ('manage_transactiontype', 'Can manage transaction type')], 'verbose_name': 'transaction type', 'verbose_name_plural': 'transaction types'},
        ),
        migrations.AlterModelOptions(
            name='transactiontypegroup',
            options={'ordering': ['master_user', 'user_code'], 'permissions': [('view_transactiontypegroup', 'Can view transaction type group'), ('manage_transactiontypegroup', 'Can manage transaction type group')], 'verbose_name': 'transaction type group', 'verbose_name_plural': 'transaction type groups'},
        ),
        migrations.AlterModelOptions(
            name='transactiontypeinput',
            options={'ordering': ['transaction_type', 'name'], 'verbose_name': 'transaction type input', 'verbose_name_plural': 'transaction type inputs'},
        ),
    ]
