# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complextransaction',
            options={'ordering': ['code'], 'verbose_name': 'complex transaction', 'verbose_name_plural': 'complex transactions'},
        ),
        migrations.AlterModelOptions(
            name='eventtohandle',
            options={'ordering': ['user_code'], 'verbose_name': 'event to handle', 'verbose_name_plural': 'events to handle'},
        ),
        migrations.AlterModelOptions(
            name='externalcashflow',
            options={'ordering': ['date'], 'verbose_name': 'external cash flow', 'verbose_name_plural': 'external cash flows'},
        ),
        migrations.AlterModelOptions(
            name='externalcashflowstrategy',
            options={'ordering': ['order'], 'verbose_name': 'external cash flow strategy', 'verbose_name_plural': 'external cash flow strtegies'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date', 'transaction_code'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionattribute',
            options={'ordering': ['attribute_type'], 'verbose_name': 'transaction attribute', 'verbose_name_plural': 'transaction attributes'},
        ),
        migrations.AlterModelOptions(
            name='transactionattributetype',
            options={'ordering': ['name'], 'permissions': [('view_transactionattributetype', 'Can view transaction attribute type'), ('manage_transactionattributetype', 'Can manage transaction attribute type')], 'verbose_name': 'transaction attribute type', 'verbose_name_plural': 'transaction attribute types'},
        ),
        migrations.AlterModelOptions(
            name='transactionclassifier',
            options={'ordering': ['tree_id', 'level', 'name'], 'verbose_name': 'transaction classifier', 'verbose_name_plural': 'transaction classifiers'},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['user_code'], 'permissions': [('view_transactiontype', 'Can view transaction type'), ('manage_transactiontype', 'Can manage transaction type')], 'verbose_name': 'transaction type', 'verbose_name_plural': 'transaction types'},
        ),
        migrations.AlterModelOptions(
            name='transactiontypeaction',
            options={'ordering': ['order'], 'verbose_name': 'action', 'verbose_name_plural': 'actions'},
        ),
        migrations.AlterModelOptions(
            name='transactiontypegroup',
            options={'ordering': ['user_code'], 'permissions': [('view_transactiontypegroup', 'Can view transaction type group'), ('manage_transactiontypegroup', 'Can manage transaction type group')], 'verbose_name': 'transaction type group', 'verbose_name_plural': 'transaction type groups'},
        ),
        migrations.AlterModelOptions(
            name='transactiontypeinput',
            options={'ordering': ['name'], 'verbose_name': 'transaction type input', 'verbose_name_plural': 'transaction type inputs'},
        ),
    ]
