# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_auto_20160804_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcashflowstrategy',
            name='strategy1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_cash_flow_strategies1', to='strategies.Strategy1', verbose_name='strategy1'),
        ),
        migrations.AlterField(
            model_name='externalcashflowstrategy',
            name='strategy2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_cash_flow_strategies2', to='strategies.Strategy2', verbose_name='strategy2'),
        ),
        migrations.AlterField(
            model_name='externalcashflowstrategy',
            name='strategy3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_cash_flow_strategies3', to='strategies.Strategy3', verbose_name='strategy3'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy1_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_as_cash1', to='strategies.Strategy1', verbose_name='strategy - 1 - position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy1_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_as_position1', to='strategies.Strategy1', verbose_name='strategy - 1 - cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy2_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_as_cash2', to='strategies.Strategy2', verbose_name='strategy - 2 - position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy2_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_as_position2', to='strategies.Strategy2', verbose_name='strategy - 2 - cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy3_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_as_cash3', to='strategies.Strategy3', verbose_name='strategy - 3 - position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy3_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_as_position3', to='strategies.Strategy3', verbose_name='strategy - 3 - cash'),
        ),
    ]
