# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-14 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_auto_20190516_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionclass',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='actionclass',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='actionclass',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='actionclass',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='actionclass',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='actionclass',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='notificationclass',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='periodicitygroup',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='transactionclass',
            name='name_ru',
        ),
    ]
