# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0033_auto_20160411_1311'),
        ('transactions', '0031_transactiontypeinput_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='instrument_types',
            field=models.ManyToManyField(blank=True, related_name='transaction_types', to='instruments.InstrumentType'),
        ),
    ]
