# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160407_0945'),
        ('transactions', '0032_transactiontype_instrument_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAccountAttributeTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_options', to='transactions.TransactionAttributeType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_attribute_type_options', to='users.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'permissions': [('view_transactiontype', 'Can view transaction type')], 'verbose_name': 'transaction type', 'verbose_name_plural': 'transaction types'},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioaccountattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
    ]
