# Generated by Django 4.2.3 on 2023-09-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0015_accrualcalculationschedule_eom'),
        ('transactions', '0032_alter_complextransaction_user_number_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='Link to Instrument, could be null if we describing cash', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False, help_text='Transaction will be filtered out from report calculation', verbose_name='is canceled'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_class',
            field=models.ForeignKey(help_text='Important entity, depending on class will be applied different method to calculate report (e.g. Buy, Sell, Transfer)', on_delete=django.db.models.deletion.PROTECT, to='transactions.transactionclass', verbose_name='transaction class'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.IntegerField(db_index=True, help_text='More Human Readable ID, like Complex Transaction has 100, then Transaction will have 101', unique=True, verbose_name='transaction code'),
        ),
    ]
