# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_auto_20190715_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.InstrumentType', verbose_name='instrument type'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentfactorschedule',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='instrument'),
        ),
    ]
