# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160407_0945'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('transactions', '0033_auto_20160411_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='transactions.TransactionType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'transaction types - group permission',
                'verbose_name_plural': 'transaction types - group permissions',
            },
        ),
        migrations.CreateModel(
            name='TransactionTypeUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='transactions.TransactionType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'transaction types - user permission',
                'verbose_name_plural': 'transaction types - user permissions',
            },
        ),
        migrations.RenameModel(
            old_name='PortfolioAccountAttributeTypeOption',
            new_name='TransactionAttributeTypeOption',
        ),
        migrations.AlterModelOptions(
            name='transactionattribute',
            options={'verbose_name': 'transaction attribute', 'verbose_name_plural': 'transaction attributes'},
        ),
        migrations.AlterModelOptions(
            name='transactionattributetype',
            options={'verbose_name': 'transaction attribute type', 'verbose_name_plural': 'transaction attribute types'},
        ),
        migrations.AlterModelOptions(
            name='transactionattributetypegroupobjectpermission',
            options={'verbose_name': 'transaction attribute types - group permission', 'verbose_name_plural': 'transaction attribute types - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='transactionattributetypeoption',
            options={'verbose_name': 'transaction attribute types - option', 'verbose_name_plural': 'transaction attribute types - options'},
        ),
        migrations.AlterModelOptions(
            name='transactionattributetypeuserobjectpermission',
            options={'verbose_name': 'transaction attribute types - user permission', 'verbose_name_plural': 'transaction attribute types - user permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetype',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypeoption',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
    ]
