# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_auto_20160411_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontypeitem',
            name='account_cash_expr',
        ),
        migrations.RemoveField(
            model_name='transactiontypeitem',
            name='account_interim_expr',
        ),
        migrations.RemoveField(
            model_name='transactiontypeitem',
            name='account_position_expr',
        ),
        migrations.RemoveField(
            model_name='transactiontypeitem',
            name='instrument_expr',
        ),
        migrations.RemoveField(
            model_name='transactiontypeitem',
            name='settlement_currency_expr',
        ),
        migrations.RemoveField(
            model_name='transactiontypeitem',
            name='transaction_currency_expr',
        ),
        migrations.AddField(
            model_name='transactiontypeitem',
            name='account_cash_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeitem',
            name='account_interim_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeitem',
            name='account_position_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeitem',
            name='instrument_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeitem',
            name='settlement_currency_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeitem',
            name='transaction_currency_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Expression'), (100, 'Relation')], default=20),
        ),
    ]
