# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_auto_20190715_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='allocation balance'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='allocation pl'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instruments.Instrument', verbose_name='linked instrument'),
        ),
    ]
