# Generated by Django 4.2.3 on 2024-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_complextransaction_owner_transaction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinput',
            name='expression_iterations_count',
            field=models.IntegerField(default=1, help_text='Number of iterations for expression when recalculate', verbose_name='expression_iterations_count'),
        ),
    ]
