# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0022_auto_20161026_0738'),
        ('transactions', '0035_complextransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_linked', to='instruments.Instrument', verbose_name='linked instrument'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.Instrument'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeActionInstrument'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_account_cash', to='accounts.Account', verbose_name='account cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_interim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_account_interim', to='accounts.Account', verbose_name='account interim'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_account_position', to='accounts.Account', verbose_name='account position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='counterparties.Counterparty', verbose_name='counterparty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Trader or transaction executor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='counterparties.Responsible', verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_settlement_currency', to='currencies.Currency', verbose_name='settlement currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy1_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_strategy1_cash', to='strategies.Strategy1', verbose_name='strategy - 1 - position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy1_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_strategy1_position', to='strategies.Strategy1', verbose_name='strategy - 1 - cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy2_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_strategy2_cash', to='strategies.Strategy2', verbose_name='strategy - 2 - position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy2_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_strategy2_position', to='strategies.Strategy2', verbose_name='strategy - 2 - cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy3_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_strategy3_cash', to='strategies.Strategy3', verbose_name='strategy - 3 - position'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strategy3_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_strategy3_position', to='strategies.Strategy3', verbose_name='strategy - 3 - cash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='currencies.Currency', verbose_name='transaction currency'),
        ),
    ]
