# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_auto_20160412_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='strategy_cash',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='strategy_position',
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='transactions.TransactionType'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.TransactionType'),
        ),
    ]
