# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_auto_20190807_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeaction',
            name='rebook_reaction',
            field=models.IntegerField(choices=[(0, 'Create'), (1, 'Skip'), (2, 'Overwrite'), (3, 'Clear all & Create'), (4, 'Create if not exist'), (6, 'If book: Clear & Append. If rebook: Skip')], default=0),
        ),
    ]
