# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0022_auto_20161026_0738'),
        ('transactions', '0036_auto_20161028_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='allocation_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_allocation_balance', to='instruments.Instrument', verbose_name='allocation balance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='allocation_pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_allocation_pl', to='instruments.Instrument', verbose_name='allocation P&L'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.Instrument'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeActionInstrument'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.Instrument'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeActionInstrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='carry_amount',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='factor',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='overheads',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='principal_amount',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='reference_fx_rate',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='trade_price',
            field=models.CharField(default='0.0', max_length=255),
        ),
    ]
