# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_actionclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionclass',
            options={'verbose_name': 'action class', 'verbose_name_plural': 'action classes'},
        ),
        migrations.AlterField(
            model_name='transactionattributetype',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10),
        ),
    ]
