# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_auto_20190828_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinput',
            name='reference_table',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reference table'),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (100, 'Relation'), (110, 'Selector')], default=20, verbose_name='value type'),
        ),
    ]
