# Generated by Django 2.2.5 on 2019-09-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_auto_20190902_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['user_code'], 'permissions': [('manage_transactiontype', 'Can manage transaction type')], 'verbose_name': 'transaction type', 'verbose_name_plural': 'transaction types'},
        ),
        migrations.AlterModelOptions(
            name='transactiontypegroup',
            options={'ordering': ['user_code'], 'permissions': [('manage_transactiontypegroup', 'Can manage transaction type group')], 'verbose_name': 'transaction type group', 'verbose_name_plural': 'transaction type groups'},
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='event_schedule_phantom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.TransactionTypeActionInstrumentEventSchedule', verbose_name='event schedule phantom'),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
