# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_auto_20160412_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='transactionattribute',
            name='attributebase_ptr',
        ),
        migrations.RemoveField(
            model_name='transactionattribute',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='transactionattribute',
            name='strategy_cash',
        ),
        migrations.RemoveField(
            model_name='transactionattribute',
            name='strategy_position',
        ),
        migrations.DeleteModel(
            name='TransactionAttribute',
        ),
    ]
