# Generated by Django 2.1.12 on 2019-10-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_auto_20190930_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is canceled'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is locked'),
        ),
    ]
