# Generated by Django 4.2.22 on 2026-01-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_alter_complextransaction_source_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='platform_version',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='platform_version'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='platform_version_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transactiontypeinput', verbose_name='platform_version input'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='provider_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transactiontypeinput', verbose_name='provider input'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='provider_version',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='provider_version'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='provider_version_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transactiontypeinput', verbose_name='provider_version input'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='source',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='source_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transactiontypeinput', verbose_name='source_input input'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='source_version',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='source_version'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='source_version_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transactiontypeinput', verbose_name='source_version input'),
        ),
    ]
