# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160412_1421'),
        ('transactions', '0044_auto_20160418_0919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashFlow',
            new_name='ExternalCashFlow',
        ),
        migrations.RenameModel(
            old_name='CashFlowStrategy',
            new_name='ExternalCashFlowStrategy',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='event_class',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='notification_class',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='transaction_type',
        ),
        migrations.AlterModelOptions(
            name='externalcashflowstrategy',
            options={'ordering': ['external_cash_flow', 'order']},
        ),
        migrations.RenameField(
            model_name='externalcashflowstrategy',
            old_name='cash_flow',
            new_name='external_cash_flow',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='counterparty_text',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='notes_front_office',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='notes_middle_office',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='responsible_text',
        ),
        migrations.RemoveField(
            model_name='transactionattributetypeoption',
            name='order',
        ),
        migrations.AddField(
            model_name='eventtohandle',
            name='master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_to_handle', to='users.MasterUser'),
        ),
        migrations.DeleteModel(
            name='EventSchedule',
        ),
    ]
