# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_auto_20160419_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtohandle',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_to_handle', to='users.MasterUser'),
        ),
    ]
