# Generated by Django 2.2.5 on 2019-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_auto_20191003_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='visibility_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Show Parameters'), (2, 'Hide Parameters')], db_index=True, default=1, verbose_name='visibility_status'),
        ),
    ]
