# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_transaction_transaction_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicityGroup',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('system_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='system code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'periodicity group',
                'verbose_name_plural': 'periodicity group',
            },
        ),
    ]
