# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0048_periodicitygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtohandle',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionType'),
        ),
        migrations.AlterField(
            model_name='externalcashflow',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='externalcashflow',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='externalcashflow',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.Portfolio'),
        ),
        migrations.AlterField(
            model_name='externalcashflowstrategy',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_cashs', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_interim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_interims', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_positions', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Transaction counterparty', null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.Counterparty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.Portfolio', verbose_name='portfolio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Trader or transaction executer', null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.Responsible'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionClass', verbose_name='transaction class'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_instrument', to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='transactionattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='transactions.TransactionAttributeType'),
        ),
        migrations.AlterField(
            model_name='transactionattribute',
            name='strategy_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactionattribute',
            name='strategy_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactionattributetype',
            name='strategy_cash_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactionattributetype',
            name='strategy_position_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='account_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='account_cash_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='account_interim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='account_interim_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='account_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='account_position_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='instrument_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='settlement_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='settlement_currency_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='transaction_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionClass'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='transaction_currency_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionTypeInput'),
        ),
        migrations.AlterField(
            model_name='transactiontypeitem',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='transactions.TransactionType'),
        ),
    ]
