# Generated by Django 2.2.5 on 2019-10-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0048_transactiontype_visibility_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complextransaction',
            options={'ordering': ['code'], 'permissions': (('view_complextransaction_show_parameters', 'Show Parameters'), ('view_complextransaction_hide_parameters', 'Hide Parameters')), 'verbose_name': 'complex transaction', 'verbose_name_plural': 'complex transactions'},
        ),
    ]
