# Generated by Django 2.2.5 on 2019-11-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0050_auto_20191106_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeActionExecuteCommand',
            fields=[
                ('transactiontypeaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.TransactionTypeAction')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
            ],
            options={
                'verbose_name': 'transaction type action execute command action',
                'verbose_name_plural': 'transaction type action execute command actions',
            },
            bases=('transactions.transactiontypeaction',),
        ),
    ]
