# Generated by Django 2.2.5 on 2019-11-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0051_transactiontypeactionexecutecommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Default'), (2, 'Procedure')], db_index=True, default=1, verbose_name='type'),
        ),
    ]
