# Generated by Django 2.2.5 on 2019-11-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0053_auto_20191114_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date', 'transaction_code'], 'permissions': (('partial_view_transaction', 'Partial View'),), 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
