# Generated by Django 2.2.5 on 2019-12-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0054_auto_20191115_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deleted_user_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_deleted',
        ),
    ]
