# Generated by Django 2.2.5 on 2020-01-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0055_auto_20191203_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeInputSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_inputs_names', models.TextField(blank=True, default='', verbose_name='linked_input_names')),
                ('transaction_type_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='transactions.TransactionTypeInput', verbose_name='transaction type input')),
            ],
        ),
    ]
