# Generated by Django 2.2.5 on 2020-01-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0058_auto_20200128_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontypeinput',
            name='settings',
        ),
        migrations.AddField(
            model_name='transactiontypeinputsettings',
            name='transaction_type_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='transactions.TransactionTypeInput', verbose_name='settings'),
        ),
    ]
