# Generated by Django 2.2.5 on 2020-01-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0059_auto_20200128_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeinputsettings',
            name='transaction_type_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='transactions.TransactionTypeInput', verbose_name='transaction type input'),
        ),
    ]
