# Generated by Django 2.2.5 on 2020-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0060_auto_20200128_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeinputsettings',
            name='linked_inputs_names',
            field=models.TextField(blank=True, default='', null=True, verbose_name='linked_input_names'),
        ),
    ]
