# Generated by Django 2.2.5 on 2020-03-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0062_auto_20200128_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeinputsettings',
            name='transaction_type_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='transactions.TransactionTypeInput', unique=True, verbose_name='transaction type input'),
        ),
    ]
