# Generated by Django 2.2.5 on 2020-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0063_auto_20200303_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_1',
            field=models.IntegerField(null=True, verbose_name='user number 1'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_10',
            field=models.IntegerField(null=True, verbose_name='user number 10'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_11',
            field=models.IntegerField(null=True, verbose_name='user number 11'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_12',
            field=models.IntegerField(null=True, verbose_name='user number 12'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_13',
            field=models.IntegerField(null=True, verbose_name='user number 13'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_14',
            field=models.IntegerField(null=True, verbose_name='user number 14'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_15',
            field=models.IntegerField(null=True, verbose_name='user number 15'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_16',
            field=models.IntegerField(null=True, verbose_name='user number 16'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_17',
            field=models.IntegerField(null=True, verbose_name='user number 17'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_18',
            field=models.IntegerField(null=True, verbose_name='user number 18'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_19',
            field=models.IntegerField(null=True, verbose_name='user number 19'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_2',
            field=models.IntegerField(null=True, verbose_name='user number 2'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_20',
            field=models.IntegerField(null=True, verbose_name='user number 20'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_3',
            field=models.IntegerField(null=True, verbose_name='user number 3'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_4',
            field=models.IntegerField(null=True, verbose_name='user number 4'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_5',
            field=models.IntegerField(null=True, verbose_name='user number 5'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_6',
            field=models.IntegerField(null=True, verbose_name='user number 6'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_7',
            field=models.IntegerField(null=True, verbose_name='user number 7'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_8',
            field=models.IntegerField(null=True, verbose_name='user number 8'),
        ),
        migrations.AlterField(
            model_name='complextransaction',
            name='user_number_9',
            field=models.IntegerField(null=True, verbose_name='user number 9'),
        ),
    ]
