# Generated by Django 2.2.5 on 2020-05-25 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0064_auto_20200513_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified'),
        ),
    ]
