# Generated by Django 2.2.5 on 2020-08-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0066_transactiontypeinput_tooltip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionclass',
            options={'base_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'transaction class', 'verbose_name_plural': 'transaction classes'},
        ),
    ]
