# Generated by Django 2.2.5 on 2020-09-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0067_auto_20200818_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='transaction_unique_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction unique code'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='transaction_unique_code_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='transaction unique code expr'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='transaction_unique_code_options',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Book without unique code'), (2, 'Skip')], default=1, verbose_name='transaction unique code options'),
        ),
    ]
