# Generated by Django 2.2.5 on 2020-10-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0069_auto_20201005_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeinputsettings',
            name='transaction_type_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_old', to='transactions.TransactionTypeInput', verbose_name='transaction type input'),
        ),
    ]
