# Generated by Django 2.2.5 on 2020-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0070_auto_20201005_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinputsettings',
            name='recalc_on_change_linked_inputs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='recalc on change linked inputs'),
        ),
    ]
