# Generated by Django 2.2.5 on 2020-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0071_transactiontypeinputsettings_recalc_on_change_linked_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ytm',
            field=models.FloatField(default=0.0, verbose_name='ytm'),
        ),
    ]
