# Generated by Django 2.2.5 on 2020-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0073_remove_transaction_ytm'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeinput',
            name='json_button_data',
            field=models.TextField(blank=True, null=True, verbose_name='json button data'),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button')], default=20, verbose_name='value type'),
        ),
    ]
