# Generated by Django 2.2.5 on 2020-12-03 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0074_auto_20201201_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complextransactioninput',
            name='price_download_scheme',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='price_download_scheme',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='price_download_scheme_input',
        ),
        migrations.RemoveField(
            model_name='transactiontypeinput',
            name='price_download_scheme',
        ),
    ]
