# Generated by Django 2.2.5 on 2021-02-06 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0075_auto_20201203_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='complex_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.ComplexTransaction', verbose_name='complex transaction'),
        ),
    ]
