# Generated by Django 2.2.5 on 2021-02-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0076_auto_20210206_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='complex_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.ComplexTransaction', verbose_name='complex transaction'),
            preserve_default=False,
        ),
    ]
