# Generated by Django 2.2.5 on 2021-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0077_auto_20210210_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionclass',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='eventclass',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='notificationclass',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='periodicitygroup',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='transactionclass',
            old_name='system_code',
            new_name='user_code'
        )
    ]
