# Generated by Django 2.2.5 on 2021-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0079_auto_20210210_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtohandle',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='transactiontypegroup',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
    ]
