# Generated by Django 2.2.5 on 2021-05-26 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0080_auto_20210312_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionclass',
            options={'ordering': ['name'], 'verbose_name': 'transaction class',
                     'verbose_name_plural': 'transaction classes'},
        ),
    ]
