# Generated by Django 2.2.5 on 2021-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0081_auto_20210526_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_21',
            field=models.TextField(blank=True, null=True, verbose_name='user text 21'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_22',
            field=models.TextField(blank=True, null=True, verbose_name='user text 22'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_23',
            field=models.TextField(blank=True, null=True, verbose_name='user text 23'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_24',
            field=models.TextField(blank=True, null=True, verbose_name='user text 24'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_25',
            field=models.TextField(blank=True, null=True, verbose_name='user text 25'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_26',
            field=models.TextField(blank=True, null=True, verbose_name='user text 26'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_27',
            field=models.TextField(blank=True, null=True, verbose_name='user text 27'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_28',
            field=models.TextField(blank=True, null=True, verbose_name='user text 28'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_29',
            field=models.TextField(blank=True, null=True, verbose_name='user text 29'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='user_text_30',
            field=models.TextField(blank=True, null=True, verbose_name='user text 30'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_21',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 21'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_22',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 22'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_23',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 23'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_24',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 24'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_25',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 25'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_26',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 26'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_27',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 27'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_28',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 28'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_29',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 29'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_text_30',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='user text 30'),
        ),
    ]
