# Generated by Django 2.2.5 on 2021-10-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0087_auto_20211027_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='transactions.ComplexTransactionStatus', verbose_name='status'),
        )
    ]
