# Generated by Django 2.2.5 on 2021-10-27 19:09

from django.db import migrations


def fix_transactions(apps, schema_editor):
    ComplexTransaction = apps.get_model("transactions", "ComplexTransaction")

    for complexTransaction in ComplexTransaction.objects.all():
        complexTransaction.status_id = complexTransaction.status_old

        complexTransaction.save()


def rev(apps, schema_editor):
    # the reverse goes here if you want to copy company names into customer again if you migrate backwards.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0088_complextransaction_status'),
    ]

    operations = [

        migrations.RunPython(fix_transactions, rev)
    ]
