# Generated by Django 2.2.5 on 2021-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0090_auto_20211102_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionstatus',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='complextransactionstatus',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
    ]
