# Generated by Django 2.2.5 on 2022-01-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0092_auto_20220104_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactioninput',
            name='value_relation',
            field=models.TextField(blank=True, default='', verbose_name='value relation'),
        ),
    ]
