# Generated by Django 2.2.5 on 2022-01-05 14:49

# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-21 11:34
from __future__ import unicode_literals

from django.db import migrations


def fix_transactions(apps, schema_editor):
    ComplexTransactionInput = apps.get_model("transactions", "ComplexTransactionInput")

    counter = 0

    for input in ComplexTransactionInput.objects.select_related('instrument').all():

        if input.instrument:
            input.value_relation = input.instrument.user_code

        input.save()

        counter = counter + 1

    print('Inputs processed %s' % counter)


def rev(apps, schema_editor):
    # the reverse goes here if you want to copy company names into customer again if you migrate backwards.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0094_complextransactioninput_value_relation_fill'),
    ]

    operations = [
        migrations.RunPython(fix_transactions, rev)
    ]
