# Generated by Django 2.2.5 on 2022-01-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0095_complextransactioninput_value_relation_fill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeContextParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('value_type',
                 models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10,
                                                  verbose_name='value type')),
                ('order', models.IntegerField(default=1, verbose_name='order')),
                ('transaction_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_parameters',
                                   to='transactions.TransactionType', verbose_name='transaction type')),
            ],
        ),
    ]
