# Generated by Django 2.2.5 on 2022-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0097_transactiontype_context_parameters_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
    ]
