# Generated by Django 2.2.5 on 2022-02-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0098_auto_20220127_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='daily_pricing_model',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='daily_pricing_model_input',
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='accrued_currency_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='accrued currency'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='instrument_type_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='instrument type'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='payment_size_detail_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='payment_size detail'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='pricing_currency_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='pricing currency'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='account_cash_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='account cash'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='account_interim_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='account interim'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='account_position_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='account position'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='allocation balance'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='allocation pl'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='counterparty_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='responsible'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='instrument_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='linked instrument'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='portfolio_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='portfolio'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='responsible_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='responsible'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='settlement_currency_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='settlement currency'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='strategy1_cash_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='strategy1 cash'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='strategy1_position_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='strategy1 position'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='strategy2_cash_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='strategy2 cash'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='strategy2_position_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='strategy2 position'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='strategy3_cash_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='strategy3 cash'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='strategy3_position_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='strategy3 position'),
        ),
        migrations.AddField(
            model_name='transactiontypeactiontransaction',
            name='transaction_currency_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='transaction currency'),
        ),
    ]
