# Generated by Django 2.2.5 on 2022-02-10 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0100_complextransactioninput_put_usercodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='accrued_currency',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='instrument_type',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='payment_size_detail',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactioninstrument',
            name='pricing_currency',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='account_cash',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='account_interim',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='account_position',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='settlement_currency',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='strategy1_cash',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='strategy1_position',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='strategy2_cash',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='strategy2_position',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='strategy3_cash',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='strategy3_position',
        ),
        migrations.RemoveField(
            model_name='transactiontypeactiontransaction',
            name='transaction_currency',
        ),
    ]
