# Generated by Django 2.2.5 on 2022-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0104_auto_20220211_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='accrual_calculation_model',
            field=models.CharField(blank=True, default='', max_length=1024, null=True,
                                   verbose_name='accrual calculation model'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='periodicity',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='periodicity'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='event_class',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='event class'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='notification_class',
            field=models.CharField(blank=True, default='', max_length=1024, null=True,
                                   verbose_name='notification class'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='periodicity',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='periodicity'),
        ),
    ]
