# Generated by Django 2.2.5 on 2022-02-15 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0105_auto_20220215_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='pricing_condition',
            field=models.CharField(blank=True, default='', max_length=1024, null=True,
                                   verbose_name='pricing condition'),
        ),
        migrations.AddField(
            model_name='transactiontypeactioninstrument',
            name='pricing_condition_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='transactions.TransactionTypeInput',
                                    verbose_name='pricing condition input'),
        ),
    ]
