# Generated by Django 2.2.5 on 2022-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0107_auto_20220314_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeaction',
            name='rebook_reaction',
            field=models.IntegerField(choices=[(0, 'Create'), (1, 'Skip'), (2, 'Overwrite'), (3, 'Clear all & Create'),
                                               (4, 'Create if not exist'),
                                               (6, 'If book: Clear & Append. If rebook: Skip'),
                                               (8, 'Try download if error create default')], default=0),
        ),
    ]
