# Generated by Django 4.0.6 on 2022-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0110_alter_transactiontype_date_expr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='date_expr',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='date expr'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='display_expr',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='display expr'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='transaction_unique_code_expr',
            field=models.CharField(blank=True, default='', max_length=4096,
                                   verbose_name='transaction unique code expr'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_date_1',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user date 1'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_date_2',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user date 2'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_date_3',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user date 3'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_date_4',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user date 4'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_date_5',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user date 5'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_1',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 1'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_10',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 10'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_11',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 11'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_12',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 12'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_13',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 13'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_14',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 14'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_15',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 15'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_16',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 16'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_17',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 17'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_18',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 18'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_19',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 19'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_2',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 2'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_20',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 20'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_3',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 3'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_4',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 4'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_5',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 5'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_6',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 6'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_7',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 7'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_8',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 8'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_number_9',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user number 9'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_1',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 1'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_10',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 10'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_11',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 11'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_12',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 12'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_13',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 13'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_14',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 14'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_15',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 15'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_16',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 16'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_17',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 17'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_18',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 18'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_19',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 19'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_2',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 2'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_20',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 20'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_21',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 21'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_22',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 22'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_23',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 23'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_24',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 24'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_25',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 25'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_26',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 26'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_27',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 27'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_28',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 28'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_29',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 29'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_3',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 3'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_30',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 30'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_4',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 4'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_5',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 5'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_6',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 6'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_7',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 7'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_8',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 8'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_text_9',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 9'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactionexecutecommand',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='accrued_currency',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='accrued currency'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='accrued_multiplier',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='accrued multiplier'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='default_accrued',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='default accrued'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='default_price',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='default price'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='instrument_type',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='instrument type'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='maturity_date',
            field=models.CharField(default='now()', max_length=4096, verbose_name='maturity date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='maturity_price',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='default price'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='name',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='payment_size_detail',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='payment_size detail'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='price_multiplier',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='price multiplier'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='pricing_condition',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='pricing condition'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='pricing_currency',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='pricing currency'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='public_name',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='public name'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='user_code',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='user_text_1',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 1'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='user_text_2',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 2'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrument',
            name='user_text_3',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 3'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='accrual_calculation_model',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='accrual calculation model'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='accrual_size',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='accrual size'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='accrual_start_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='accrual start date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='first_payment_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='first payment date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='notes',
            field=models.CharField(default='', max_length=4096, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='periodicity',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='periodicity'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentaccrualcalculationschedules',
            name='periodicity_n',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='periodicity n'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='description',
            field=models.CharField(default='', max_length=4096, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='effective_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='effective date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='event_class',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='event class'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='final_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='final date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='is_auto_generated',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='is autogenerated'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='name',
            field=models.CharField(default='', max_length=4096, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='notification_class',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='notification class'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='notify_in_n_days',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='notify in n days'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='periodicity',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='periodicity'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventschedule',
            name='periodicity_n',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='periodicity n'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='button_position',
            field=models.CharField(default='0', max_length=4096, verbose_name='button position'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='is_book_automatic',
            field=models.CharField(default=False, help_text='If checked - is book automatic', max_length=4096,
                                   verbose_name='is book automatic'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='is_sent_to_pending',
            field=models.CharField(default=False, help_text='If checked - is sent to pending', max_length=4096,
                                   verbose_name='is sent to pending'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='text',
            field=models.CharField(default='', max_length=4096, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumenteventscheduleaction',
            name='transaction_type_from_instrument_type',
            field=models.CharField(default='', max_length=4096, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentfactorschedule',
            name='effective_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='effective date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentfactorschedule',
            name='factor_value',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='factor value'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentfactorschedule',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactioninstrumentmanualpricingformula',
            name='notes',
            field=models.CharField(default='', max_length=4096, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='account_cash',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='account cash'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='account_interim',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='account interim'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='account_position',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='account position'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='accounting_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='accounting date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='allocation_balance',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='allocation balance'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='allocation_pl',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='allocation pl'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='carry_amount',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='carry amount'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='carry_with_sign',
            field=models.CharField(default='0.', max_length=4096, verbose_name='carry with sign'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='cash_consideration',
            field=models.CharField(default='0.', max_length=4096, verbose_name='cash consideration'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='cash_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='cash date'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='counterparty',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='factor',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='factor'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='linked_instrument',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='linked instrument'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='overheads',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='overheads'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='overheads_with_sign',
            field=models.CharField(default='0.', max_length=4096, verbose_name='overheads with sign'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='portfolio',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='portfolio'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='position_amount',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='position amount'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='position_size_with_sign',
            field=models.CharField(default='0.', max_length=4096, verbose_name='position size with sign'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='principal_amount',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='principal amount'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='principal_with_sign',
            field=models.CharField(default='0.', max_length=4096, verbose_name='principal with sign'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='reference_fx_rate',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='reference FX-rate'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='responsible',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='settlement_currency',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='settlement currency'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='strategy1_cash',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='strategy1 cash'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='strategy1_position',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='strategy1 position'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='strategy2_cash',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='strategy2 cash'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='strategy2_position',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='strategy2 position'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='strategy3_cash',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='strategy3 cash'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='strategy3_position',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='strategy3 position'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='trade_price',
            field=models.CharField(default='0.0', max_length=4096, verbose_name='trade price'),
        ),
        migrations.AlterField(
            model_name='transactiontypeactiontransaction',
            name='transaction_currency',
            field=models.CharField(blank=True, default='', max_length=4096, null=True,
                                   verbose_name='transaction currency'),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value',
            field=models.CharField(blank=True, help_text='this is expression for default value', max_length=4096,
                                   null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value_expr',
            field=models.CharField(blank=True, help_text='this is expression for recalculate value', max_length=4096,
                                   null=True, verbose_name='value expression'),
        ),
    ]
