# Generated by Django 4.0.6 on 2022-09-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0012_auto_20210206_0655'),
        ('transactions', '0111_alter_transactiontype_date_expr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='linked_import_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='celery_tasks.celerytask', verbose_name='linked import task'),
        ),
    ]
