# Generated by Django 4.2.3 on 2023-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_balancereportinstance_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='account',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='cost_method',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='exposure_currency',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='member',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='pricing_currency',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='pricing_policy',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='report_currency',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='report_instance',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='strategy1',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='strategy2',
        ),
        migrations.RemoveField(
            model_name='plreportinstanceitem',
            name='strategy3',
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='data',
            field=models.JSONField(blank=True, help_text='Content of whole report representation', null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='data',
            field=models.JSONField(blank=True, help_text='Content of whole report representation', null=True, verbose_name='Data'),
        ),
        migrations.DeleteModel(
            name='BalanceReportInstanceItem',
        ),
        migrations.DeleteModel(
            name='PLReportInstanceItem',
        ),
    ]
