# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0003_auto_20170125_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='layout_json',
            field=models.TextField(blank=True, null=True, verbose_name='layout json'),
        ),
    ]
