# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0005_auto_20170228_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='expr',
            field=models.CharField(max_length=1024, verbose_name='expression'),
        ),
    ]
