# Generated by Django 4.2.3 on 2023-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportsummaryinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='currency user_code'),
        ),
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='date_from',
            field=models.DateField(db_index=True, null=True, verbose_name='date from'),
        ),
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='date_to',
            field=models.DateField(db_index=True, null=True, verbose_name='date to'),
        ),
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='portfolios',
            field=models.TextField(blank=True, null=True, verbose_name='portfolios user_codes'),
        ),
    ]
