# Generated by Django 4.2.3 on 2023-09-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reportsummaryinstance_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancereportcustomfield',
            name='configuration_code',
            field=models.CharField(default='-', max_length=255, verbose_name='Configuration Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plreportcustomfield',
            name='configuration_code',
            field=models.CharField(default='-', max_length=255, verbose_name='Configuration Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionreportcustomfield',
            name='configuration_code',
            field=models.CharField(default='-', max_length=255, verbose_name='Configuration Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancereportcustomfield',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='User Code'),
        ),
    ]
