# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190522_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancereportcustomfield',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type'),
        ),
        migrations.AddField(
            model_name='plreportcustomfield',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type'),
        ),
        migrations.AddField(
            model_name='transactionreportcustomfield',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type'),
        ),
    ]
