# Generated by Django 4.2.3 on 2023-10-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_balancereportcustomfield_configuration_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='pricing_policy',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='pricing policy user_code'),
        ),
    ]
