# Generated by Django 4.2.3 on 2023-10-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportsummaryinstance_pricing_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='allocation_mode',
            field=models.IntegerField(default=0, verbose_name='allocation_mode'),
        ),
    ]
