# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190614_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancereportcustomfield',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='plreportcustomfield',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='transactionreportcustomfield',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
    ]
