# Generated by Django 4.2.3 on 2023-11-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_member_status'),
        ('reports', '0010_reportsummaryinstance_allocation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancereportinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionreportinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancereportinstance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_report_instances_as_member', to='users.member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='performancereportinstance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report_instances_as_member', to='users.member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='plreportinstance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_report_instances_as_member', to='users.member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='reportsummaryinstance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_summary_instances_as_member', to='users.member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='transactionreportinstance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_report_instances_as_member', to='users.member', verbose_name='member'),
        ),
    ]
