# Generated by Django 2.2.5 on 2022-06-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strategies', '0013_auto_20220314_1202'),
        ('instruments', '0077_auto_20220314_1202'),
        ('accounts', '0016_auto_20220314_1202'),
        ('users', '0042_auto_20220314_1202'),
        ('portfolios', '0021_portfolioregisterrecord_previous_date_record'),
        ('currencies', '0021_auto_20220314_1202'),
        ('reports', '0011_balancereportinstance_balancereportinstanceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLReportInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('report_date', models.DateField(db_index=True, verbose_name='report date')),
                ('pl_first_date', models.DateField(db_index=True, verbose_name='pl first date')),
                ('report_settings_data', models.TextField(blank=True, null=True, verbose_name='report settings data')),
                ('cost_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='instruments.CostMethod', verbose_name='cost method')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser',
                                                  verbose_name='master user')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member',
                                             verbose_name='member')),
                ('pricing_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('report_currency',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency',
                                   verbose_name='report currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fixed_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fixed_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fixed_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fixed_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fx_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fx_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fx_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_fx_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='carry_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fixed_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fixed_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fixed_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fixed_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fx_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fx_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fx_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_fx_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='overheads_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fixed_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fixed_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fixed_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fixed_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fx_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fx_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fx_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_fx_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='principal_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fixed_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fixed_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fixed_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fixed_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fx_closed',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fx_closed_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fx_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_fx_opened_loc',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_opened',
        ),
        migrations.RemoveField(
            model_name='balancereportinstanceitem',
            name='total_opened_loc',
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='carry',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='carry'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='carry_fixed',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='carry_fixed'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='carry_fixed_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='carry_fixed_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='carry_fx',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='carry_fx'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='carry_fx_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='carry_fx_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='carry_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='carry_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='overheads',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='overheads'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='overheads_fixed',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='overheads_fixed'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='overheads_fixed_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='overheads_fixed_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='overheads_fx',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='overheads_fx'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='overheads_fx_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='overheads_fx_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='overheads_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='overheads_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='principal',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='principal'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='principal_fixed',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='principal_fixed'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='principal_fixed_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='principal_fixed_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='principal_fx',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='principal_fx'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='principal_fx_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='principal_fx_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='principal_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='principal_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='total_fixed',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total_fixed'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='total_fixed_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total_fixed_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='total_fx',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total_fx'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='total_fx_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total_fx_loc'),
        ),
        migrations.AddField(
            model_name='balancereportinstanceitem',
            name='total_loc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total_loc'),
        ),
        migrations.AlterField(
            model_name='balancereportinstanceitem',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='balance_report_instance_item_currency', to='currencies.Currency',
                                    verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='balancereportinstanceitem',
            name='exposure_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='balance_report_instance_item_exposure_currency',
                                    to='currencies.Currency', verbose_name='exposure currency'),
        ),
        migrations.AlterField(
            model_name='balancereportinstanceitem',
            name='pricing_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='balance_report_instance_item_pricing_currency',
                                    to='currencies.Currency', verbose_name='pricing currency'),
        ),
        migrations.CreateModel(
            name='PLReportInstanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='report date')),
                ('pl_first_date', models.DateField(db_index=True, verbose_name='pl first date')),
                ('report_settings_data', models.TextField(blank=True, null=True, verbose_name='report settings data')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='short name')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('item_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='item id')),
                ('item_type', models.IntegerField(default=0, verbose_name='portfolio')),
                ('item_type_name',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='item type name')),
                ('custom_field_text_1',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='custom_field_text_1')),
                ('custom_field_text_2',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='custom_field_text_2')),
                ('custom_field_text_3',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='custom_field_text_3')),
                ('custom_field_text_4',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='custom_field_text_4')),
                ('custom_field_text_5',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='custom_field_text_5')),
                ('custom_field_number_1',
                 models.FloatField(blank=True, default=0.0, null=True, verbose_name='custom_field_number_1')),
                ('custom_field_number_2',
                 models.FloatField(blank=True, default=0.0, null=True, verbose_name='custom_field_number_2')),
                ('custom_field_number_3',
                 models.FloatField(blank=True, default=0.0, null=True, verbose_name='custom_field_number_3')),
                ('custom_field_number_4',
                 models.FloatField(blank=True, default=0.0, null=True, verbose_name='custom_field_number_4')),
                ('custom_field_number_5',
                 models.FloatField(blank=True, default=0.0, null=True, verbose_name='custom_field_number_5')),
                ('custom_field_date_1', models.DateField(blank=True, null=True, verbose_name='custom_field_date_1')),
                ('custom_field_date_2', models.DateField(blank=True, null=True, verbose_name='custom_field_date_2')),
                ('custom_field_date_3', models.DateField(blank=True, null=True, verbose_name='custom_field_date_3')),
                ('custom_field_date_4', models.DateField(blank=True, null=True, verbose_name='custom_field_date_4')),
                ('custom_field_date_5', models.DateField(blank=True, null=True, verbose_name='custom_field_date_5')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='accounts.Account', verbose_name='account')),
                ('cost_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='instruments.CostMethod', verbose_name='cost method')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='pl_report_instance_item_currency',
                                               to='currencies.Currency', verbose_name='currency')),
                ('exposure_currency',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='pl_report_instance_item_exposure_currency', to='currencies.Currency',
                                   verbose_name='exposure currency')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to='instruments.Instrument', verbose_name='instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser',
                                                  verbose_name='master user')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member',
                                             verbose_name='member')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to='portfolios.Portfolio', verbose_name='portfolio')),
                ('pricing_currency',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='pl_report_instance_item_pricing_currency', to='currencies.Currency',
                                   verbose_name='pricing currency')),
                ('pricing_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('report_currency',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency',
                                   verbose_name='report currency')),
                ('report_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                                      to='reports.PLReportInstance', verbose_name='report instance')),
                ('strategy1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to='strategies.Strategy1', verbose_name='strategy1')),
                ('strategy2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to='strategies.Strategy2', verbose_name='strategy2')),
                ('strategy3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to='strategies.Strategy3', verbose_name='strategy3')),
            ],
            options={
                'verbose_name': 'balance report instance item',
                'verbose_name_plural': 'balance reports instance item',
            },
        ),
    ]
