# Generated by Django 4.2.3 on 2023-11-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_member_status'),
        ('reports', '0011_balancereportinstance_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancereportcustomfield',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plreportcustomfield',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionreportcustomfield',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
    ]
