# Generated by Django 4.2.3 on 2024-01-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_balancereportcustomfield_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereportinstance',
            name='grand_absolute_pl',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='grand absolute pl'),
        ),
    ]
