# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_performancereportinstance_grand_absolute_pl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancereportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='performancereportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='plreportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='reportsummaryinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionreportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='balancereportinstance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='balancereportinstance',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='performancereportinstance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='performancereportinstance',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='plreportinstance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='plreportinstance',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='reportsummaryinstance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reportsummaryinstance',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='transactionreportinstance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transactionreportinstance',
            name='modified',
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportsummaryinstance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='transactionreportinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionreportinstance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
    ]
