# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_performancereportinstance_grand_absolute_pl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancereportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='performancereportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='plreportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='reportsummaryinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionreportinstance',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='balancereportinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='balancereportinstance',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='performancereportinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='performancereportinstance',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='plreportinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='plreportinstance',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='reportsummaryinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reportsummaryinstance',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='transactionreportinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transactionreportinstance',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
