# Generated by Django 2.2.5 on 2022-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20220628_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereportinstance',
            name='grand_cash_inflow',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='grand cash inflow'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='grand_cash_outflow',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='grand cash outflow'),
        ),
        migrations.AddField(
            model_name='performancereportinstanceitem',
            name='cash_inflow',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='cash inflow'),
        ),
        migrations.AddField(
            model_name='performancereportinstanceitem',
            name='cash_outflow',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='cash outflow'),
        ),
    ]
