# Generated by Django 4.0.6 on 2022-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0022_auto_20220703_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereportcustomfield',
            name='expr',
            field=models.CharField(max_length=2048, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='plreportcustomfield',
            name='expr',
            field=models.CharField(max_length=2048, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='transactionreportcustomfield',
            name='expr',
            field=models.CharField(max_length=2048, verbose_name='expression'),
        ),
    ]
