# Generated by Django 4.0.6 on 2022-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_alter_balancereportcustomfield_expr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereportcustomfield',
            name='expr',
            field=models.CharField(max_length=4096, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='plreportcustomfield',
            name='expr',
            field=models.CharField(max_length=4096, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='transactionreportcustomfield',
            name='expr',
            field=models.CharField(max_length=4096, verbose_name='expression'),
        ),
    ]
