# Generated by Django 4.1.3 on 2023-05-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_memberaccesspolicy_configuration_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessPolicyTemplate',
            new_name='AccessPolicy',
        ),
    ]
