# Generated by Django 4.1.3 on 2023-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0009_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
