# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0012_accesspolicy_created_accesspolicy_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspolicy',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='accesspolicy',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
