# Generated by Django 4.2.3 on 2024-08-28 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0014_alter_accesspolicy_members_resourcegroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcegroup",
            name="created",
        ),
        migrations.RemoveField(
            model_name="resourcegroup",
            name="modified",
        ),
        migrations.AddField(
            model_name="resourcegroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcegroup",
            name="modified_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="modified at"
            ),
        ),
    ]
