# Generated by Django 4.2.3 on 2024-09-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("iam", "0015_remove_resourcegroup_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcegroup",
            name="group",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_group",
                to="auth.group",
                verbose_name="Django User Group",
            ),
            preserve_default=False,
        ),
    ]
