# Generated by Django 4.2.3 on 2024-09-26 17:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_member_deleted_at"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("iam", "0016_resourcegroup_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesspolicy",
            name="resource_group",
        ),
        migrations.RemoveField(
            model_name="resourcegroup",
            name="group",
        ),
        migrations.RemoveField(
            model_name="resourcegroup",
            name="is_enabled",
        ),
        migrations.RemoveField(
            model_name="resourcegroup",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="resourcegroup",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="resourcegroup",
            name="public_name",
        ),
        migrations.RemoveField(
            model_name="resourcegroup",
            name="short_name",
        ),
        migrations.AddField(
            model_name="accesspolicy",
            name="resource_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                default=[],
                size=None,
                verbose_name="List of ResourceGroup user_codes",
            ),
        ),
        migrations.AddField(
            model_name="resourcegroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="master_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_groups",
                to="users.masteruser",
            ),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="user_code",
            field=models.CharField(
                help_text="Unique code of the ResourceGroup. Used in Configuration and Permissions Logic",
                max_length=1024,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ResourceGroupAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "object_user_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique Code for referenced object.",
                        max_length=1024,
                        null=True,
                        verbose_name="user code",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "resource_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="iam.resourcegroup",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="resourcegroupassignment",
            constraint=models.UniqueConstraint(
                fields=("resource_group", "content_type", "object_id"),
                name="resource_group_object_assignment",
            ),
        ),
    ]
