# Generated by Django 4.2.16 on 2024-10-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0018_alter_accesspolicy_resource_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcegroup",
            name="master_user",
        ),
    ]
