EXPECTED_INSTRUMENT = {
    "id": 22,
    "instrument_type": 17,
    "instrument_type_object": {
        "id": 17,
        "instrument_class": 1,
        "instrument_class_object": {
            "id": 1,
            "user_code": "GENERAL",
            "name": "General Class",
            "description": "General Class",
        },
        "user_code": "local.poms.space00000:stock",
        "name": "stock",
        "short_name": "stock",
        "public_name": "stock",
        "instrument_form_layouts": None,
        "deleted_user_code": None,
        "meta": {
            "content_type": "instruments.instrumenttype",
            "app_label": "instruments",
            "model_name": "instrumenttype",
            "space_code": "space00000",
        },
    },
    "user_code": "CSVJGHVZFC",
    "name": "BOXUGKLYWOR",
    "short_name": "BSH",
    "public_name": None,
    "notes": None,
    "is_active": True,
    "is_deleted": False,
    "has_linked_with_portfolio": False,
    "pricing_currency": 28,
    "pricing_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "price_multiplier": 1.0,
    "accrued_currency": 28,
    "accrued_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "accrued_multiplier": 1.0,
    "payment_size_detail": 1,
    "payment_size_detail_object": {
        "id": 1,
        "user_code": "PERCENT",
        "name": "% per annum",
        "description": "% per annum",
    },
    "default_price": 0.0,
    "default_accrued": 0.0,
    "user_text_1": "JBYWDPLZLI",
    "user_text_2": "FHHMHMVRER",
    "user_text_3": "SHASFYKQLJ",
    "reference_for_pricing": "",
    "daily_pricing_model": 6,
    "daily_pricing_model_object": {
        "id": 6,
        "user_code": "-",
        "name": "Use Default Price (no Price History)",
        "description": "Use Default Price (no Price History)",
    },
    "pricing_condition": 1,
    "pricing_condition_object": {
        "id": 1,
        "user_code": "NO_VALUATION",
        "name": "Don't Run Valuation",
        "description": "Don't Run Valuation",
    },
    "maturity_date": None,
    "maturity_price": 0.0,
    "manual_pricing_formulas": [],
    "accrual_calculation_schedules": [
        {
            "id": 4,
            "accrual_start_date": None,
            "accrual_start_date_value_type": 40,
            "first_payment_date": None,
            "first_payment_date_value_type": 40,
            "accrual_size": "0.598345055004762",
            "accrual_size_value_type": 20,
            "periodicity_n": "30",
            "periodicity_n_value_type": 20,
            "accrual_calculation_model": 2,
            "accrual_calculation_model_object": {
                "id": 2,
                "user_code": "ACT_ACT",
                "name": "ACT/ACT",
                "description": "ACT/ACT",
            },
            "periodicity": 1,
            "periodicity_object": {
                "id": 1,
                "user_code": "N_DAY",
                "name": "N Days",
                "description": "N Days",
            },
            "notes": "",
        }
    ],
    "factor_schedules": [
        {
            "effective_date": "2024-05-21",
            "factor_value": 0.2278459186631061,
        }
    ],
    "event_schedules": [],
    "is_enabled": True,
    "pricing_policies": [],
    "exposure_calculation_model": 1,
    "exposure_calculation_model_object": {
        "id": 1,
        "user_code": "MARKET_VALUE",
        "name": "Market value",
        "description": "Market value",
    },
    "co_directional_exposure_currency": 28,
    "counter_directional_exposure_currency": None,
    "co_directional_exposure_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "counter_directional_exposure_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "long_underlying_instrument": None,
    "short_underlying_instrument": None,
    "long_underlying_instrument_object": None,
    "short_underlying_instrument_object": None,
    "underlying_long_multiplier": 1.0,
    "underlying_short_multiplier": 1.0,
    "long_underlying_exposure": 1,
    "short_underlying_exposure": 1,
    "position_reporting": 1,
    "country": 112,
    "country_object": {
        "id": 112,
        "name": "Italy",
        "user_code": "Italy",
        "country_code": "380",
        "region": "Europe",
        "region_code": "150",
        "alpha_2": "IT",
        "alpha_3": "ITA",
        "sub_region": "Southern Europe",
        "sub_region_code": "039",
    },
    "deleted_user_code": None,
    "attributes": [
        {
            "id": 4,
            "attribute_type": 4,
            "value_string": "PGBZBAEROP",
            "value_float": 6897.0,
            "value_date": "2023-07-21",
            "classifier": None,
            "attribute_type_object": {
                "id": 4,
                "user_code": "local.poms.space00000:auth.permission:tbylo",
                "name": "",
                "short_name": "PC",
                "public_name": None,
                "notes": None,
                "can_recalculate": False,
                "value_type": 20,
                "order": 0,
                "is_hidden": False,
                "kind": 1,
            },
            "classifier_object": None,
        }
    ],
    "owner": {
        "id": 1,
        "username": "finmars_bot",
        "first_name": "",
        "last_name": "",
        "display_name": "finmars_bot",
        "is_owner": True,
        "is_admin": True,
        "user": 1
    },
    "files": [],
    "meta": {
        "content_type": "instruments.instrument",
        "app_label": "instruments",
        "model_name": "instrument",
        "space_code": "space00000",
    },
    "identifier": {},
    "created_at": "20240823T16:41:00.0Z",
    "modified_at": "20240823T16:41:00.0Z",
    "deleted_at": None,
    "actual_at": None,
    "source_type": "manual",
    "source_origin": None,
    "external_id": None,
    "is_manual_locked": False,
    "is_locked": True,
    "first_transaction_date": None,
    "resource_groups": [],
    "resource_groups_object": [],
    "accrual_events": [],
    "registration_date": "2020-01-01",
}

INSTRUMENT_CREATE_DATA = {
    "user_code": "Apple",
    "name": "Apple",
    "short_name": "Apple",
    "public_name": "",
    "notes": "",
    "user_text_1": "",
    "user_text_2": "",
    "user_text_3": "",
}

EXPECTED_INSTRUMENT_TYPE = {
    "id": 9,
    "user_code": "local.poms.space00000:bond",
    "name": "bond",
    "short_name": "bond",
    "public_name": "bond",
    "notes": None,
    "is_deleted": False,
    "instrument_form_layouts": None,
    "instrument_class": 1,
    "instrument_class_object": {
        "id": 1,
        "user_code": "GENERAL",
        "name": "General Class",
        "description": "General Class",
    },
    "one_off_event": None,
    "one_off_event_object": None,
    "regular_event": None,
    "regular_event_object": None,
    "factor_same": None,
    "factor_same_object": None,
    "factor_up": None,
    "factor_up_object": None,
    "factor_down": None,
    "factor_down_object": None,
    "is_enabled": True,
    "pricing_policies": [],
    "has_second_exposure_currency": False,
    "accruals": [],
    "events": [],
    "instrument_attributes": [],
    "instrument_factor_schedules": [],
    "payment_size_detail": None,
    "payment_size_detail_object": None,
    "accrued_currency": None,
    "accrued_currency_object": None,
    "accrued_multiplier": 1.0,
    "default_accrued": 0.0,
    "exposure_calculation_model": None,
    "co_directional_exposure_currency": None,
    "counter_directional_exposure_currency": None,
    "co_directional_exposure_currency_value_type": 100,
    "counter_directional_exposure_currency_value_type": 100,
    "long_underlying_instrument": None,
    "short_underlying_instrument": None,
    "underlying_long_multiplier": 1.0,
    "underlying_short_multiplier": 1.0,
    "long_underlying_exposure": None,
    "short_underlying_exposure": None,
    "position_reporting": 1,
    "instrument_factor_schedule_data": None,
    "pricing_currency": None,
    "pricing_currency_object": None,
    "price_multiplier": 1.0,
    "pricing_condition": None,
    "pricing_condition_object": None,
    "default_price": 0.0,
    "maturity_date": None,
    "maturity_price": 0.0,
    "reference_for_pricing": "",
    "configuration_code": "local.poms.space00000",
    "attributes": [],
    "deleted_user_code": None,
    "owner": {
        "id": 1,
        "username": "finmars_bot",
        "first_name": "",
        "last_name": "",
        "display_name": "finmars_bot",
        "is_owner": True,
        "is_admin": True,
        "user": 1
    },
    "meta": {
        "content_type": "instruments.instrumenttype",
        "app_label": "instruments",
        "model_name": "instrumenttype",
        "space_code": "space00000",
    },
    "created_at": "20240823T16:41:00.0Z",
    "modified_at": "20240823T16:41:00.0Z",
    "deleted_at": None,
}

INSTRUMENT_FOR_SELECT = {
    "count": 3,
    "next": None,
    "previous": None,
    "results": [
        {
            "id": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "modified_at": "2023-09-18T17:15:58.872171Z",
            "instrument_type": 1,
            "instrument_type_object": {
                "id": 1,
                "instrument_class": 1,
                "instrument_class_object": {
                    "id": 1,
                    "user_code": "GENERAL",
                    "name": "General Class",
                    "description": "General Class",
                },
                "user_code": "local.poms.space00000:_",
                "name": "-",
                "short_name": "-",
                "public_name": None,
                "instrument_form_layouts": None,
                "deleted_user_code": None,
                "meta": {
                    "content_type": "instruments.instrumenttype",
                    "app_label": "instruments",
                    "model_name": "instrumenttype",
                    "space_code": "space00000",
                },
            },
            "public_name": None,
            "is_active": True,
            "is_deleted": False,
            "is_enabled": True,
            "has_linked_with_portfolio": False,
            "deleted_user_code": None,
            "meta": {
                "content_type": "instruments.instrument",
                "app_label": "instruments",
                "model_name": "instrument",
                "space_code": "space00000",
            },
        },
        {
            "id": 2,
            "user_code": "Apple",
            "name": "Apple",
            "short_name": "Apple",
            "modified_at": "2023-09-18T17:15:59.159401Z",
            "instrument_type": 2,
            "instrument_type_object": {
                "id": 2,
                "instrument_class": 1,
                "instrument_class_object": {
                    "id": 1,
                    "user_code": "GENERAL",
                    "name": "General Class",
                    "description": "General Class",
                },
                "user_code": "local.poms.space00000:stock",
                "name": "stock",
                "short_name": "stock",
                "public_name": "stock",
                "instrument_form_layouts": None,
                "deleted_user_code": None,
                "meta": {
                    "content_type": "instruments.instrumenttype",
                    "app_label": "instruments",
                    "model_name": "instrumenttype",
                    "space_code": "space00000",
                },
            },
            "public_name": None,
            "is_active": True,
            "is_deleted": False,
            "is_enabled": True,
            "has_linked_with_portfolio": False,
            "deleted_user_code": None,
            "meta": {
                "content_type": "instruments.instrument",
                "app_label": "instruments",
                "model_name": "instrument",
                "space_code": "space00000",
            },
        },
        {
            "id": 3,
            "user_code": "Tesla B.",
            "name": "Tesla B.",
            "short_name": "Tesla B.",
            "modified_at": "2023-09-18T17:15:59.168410Z",
            "instrument_type": 3,
            "instrument_type_object": {
                "id": 3,
                "instrument_class": 1,
                "instrument_class_object": {
                    "id": 1,
                    "user_code": "GENERAL",
                    "name": "General Class",
                    "description": "General Class",
                },
                "user_code": "local.poms.space00000:bond",
                "name": "bond",
                "short_name": "bond",
                "public_name": "bond",
                "instrument_form_layouts": None,
                "deleted_user_code": None,
                "meta": {
                    "content_type": "instruments.instrumenttype",
                    "app_label": "instruments",
                    "model_name": "instrumenttype",
                    "space_code": "space00000",
                },
            },
            "public_name": None,
            "is_active": True,
            "is_deleted": False,
            "is_enabled": True,
            "has_linked_with_portfolio": False,
            "deleted_user_code": None,
            "meta": {
                "content_type": "instruments.instrument",
                "app_label": "instruments",
                "model_name": "instrument",
                "space_code": "space00000",
            },
        },
    ],
}
