# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0021_auto_20160712_0842'),
        ('users', '0008_auto_20160622_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloombergRequestLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('token', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('is_success', models.NullBooleanField(db_index=True)),
                ('is_user_got_response', models.NullBooleanField(db_index=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
            ],
            options={
                'verbose_name': 'bloomberg request log',
                'verbose_name_plural': 'bloomberg request logs',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='InstrumentAttributeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('attribute_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentAttributeType')),
            ],
            options={
                'ordering': ('attribute_type__name',),
            },
        ),
        migrations.CreateModel(
            name='InstrumentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(max_length=255)),
                ('user_code', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=32)),
                ('short_name', models.CharField(blank=True, max_length=32, null=True)),
                ('public_name', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.CharField(blank=True, max_length=32, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=32, null=True)),
                ('pricing_currency', models.CharField(blank=True, max_length=32, null=True)),
                ('price_multiplier', models.CharField(blank=True, max_length=32, null=True)),
                ('accrued_currency', models.CharField(blank=True, max_length=32, null=True)),
                ('accrued_multiplier', models.CharField(blank=True, max_length=32, null=True)),
                ('daily_pricing_model', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_size_detail', models.CharField(blank=True, max_length=32, null=True)),
                ('default_price', models.CharField(blank=True, max_length=32, null=True)),
                ('default_accrued', models.CharField(blank=True, max_length=32, null=True)),
                ('user_text_1', models.CharField(blank=True, max_length=32, null=True)),
                ('user_text_2', models.CharField(blank=True, max_length=32, null=True)),
                ('user_text_3', models.CharField(blank=True, max_length=32, null=True)),
                ('price_download_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser')),
            ],
            options={
                'permissions': [('view_instrumentmapping', 'Can view instrument mapping'), ('manage_instrumentmapping', 'Can manage instrument mapping')],
                'verbose_name': 'instrument mapping',
                'verbose_name_plural': 'instrument mappings',
            },
        ),
        migrations.AddField(
            model_name='instrumentattributemapping',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='integrations.InstrumentMapping'),
        ),
        migrations.AlterIndexTogether(
            name='instrumentmapping',
            index_together=set([('master_user', 'mapping_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributemapping',
            unique_together=set([('mapping', 'attribute_type')]),
        ),
    ]
