# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_attrscheme_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_policies', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name_plural': 'pricing policies',
                'verbose_name': 'pricing policy',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicy',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
