# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicyAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Disabled'), (1, 'Bloomberg')], default=0),
        ),
        migrations.AddField(
            model_name='pricingpolicyattr',
            name='pricing_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.PricingPolicy'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicyattr',
            unique_together=set([('pricing_policy', 'name')]),
        ),
    ]
