# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('users', '0001_initial'),
        ('instruments', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloomberg_tasks', to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloomberg_tasks', to='users.Member'),
        ),
        migrations.AddField(
            model_name='task',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='periodicitymapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='periodicitymapping',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Periodicity'),
        ),
        migrations.AddField(
            model_name='periodicitymapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='instrumenttypemapping',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentType'),
        ),
        migrations.AddField(
            model_name='instrumenttypemapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='instrumenttypemapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadschemeinput',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='integrations.InstrumentDownloadScheme'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadschemeattribute',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentAttributeType'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadschemeattribute',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='integrations.InstrumentDownloadScheme'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='accrual_calculation_schedule_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.AccrualScheduleDownloadMethod'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='factor_schedule_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.FactorScheduleDownloadMethod'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentAttributeType', verbose_name='attribute type'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentClassifier', verbose_name='classifier'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='importconfig',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_configs', to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='importconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='currencymapping',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='currencymapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='currencymapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AddField(
            model_name='accrualcalculationmodelmapping',
            name='accrual_calculation_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.AccrualCalculationModel'),
        ),
        migrations.AddField(
            model_name='accrualcalculationmodelmapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='accrualcalculationmodelmapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
        ),
        migrations.AlterIndexTogether(
            name='task',
            index_together=set([('master_user', 'created')]),
        ),
        migrations.AlterUniqueTogether(
            name='pricedownloadscheme',
            unique_together=set([('master_user', 'scheme_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentdownloadschemeinput',
            unique_together=set([('scheme', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentdownloadschemeattribute',
            unique_together=set([('scheme', 'attribute_type')]),
        ),
        migrations.AlterIndexTogether(
            name='instrumentdownloadscheme',
            index_together=set([('master_user', 'scheme_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='importconfig',
            unique_together=set([('master_user', 'provider')]),
        ),
    ]
