# Generated by Django 4.1.3 on 2022-12-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obj_attrs', '0001_initial'),
        ('integrations', '0001_initial'),
        ('portfolios', '0002_initial'),
        ('accounts', '0002_initial'),
        ('procedures', '0002_initial'),
        ('transactions', '0001_initial'),
        ('instruments', '0003_initial'),
        ('strategies', '0002_initial'),
        ('users', '0001_initial'),
        ('currencies', '0003_initial'),
        ('counterparties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfileresult',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='transactionfileresult',
            name='procedure_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.requestdatafileprocedureinstance', verbose_name='procedure'),
        ),
        migrations.AddField(
            model_name='transactionfileresult',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.dataprovider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='task',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='integrations.task', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='task',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='strategy3mapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy3', verbose_name='strategy3'),
        ),
        migrations.AddField(
            model_name='strategy3mapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy3mapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='strategy2mapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy2', verbose_name='strategy2'),
        ),
        migrations.AddField(
            model_name='strategy2mapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy2mapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='strategy1mapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy1', verbose_name='strategy1'),
        ),
        migrations.AddField(
            model_name='strategy1mapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy1mapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='responsiblemapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.responsible', verbose_name='responsible'),
        ),
        migrations.AddField(
            model_name='responsiblemapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='responsiblemapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='responsibleclassifiermapping',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericattributetype'),
        ),
        migrations.AddField(
            model_name='responsibleclassifiermapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericclassifier'),
        ),
        migrations.AddField(
            model_name='responsibleclassifiermapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='responsibleclassifiermapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='pricingpolicymapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.pricingpolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='pricingpolicymapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricingpolicymapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='pricingconditionmapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.pricingcondition', verbose_name='pricing condition'),
        ),
        migrations.AddField(
            model_name='pricingconditionmapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricingconditionmapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='pricingautomatedschedule',
            name='last_run_task',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.task', verbose_name='last run task'),
        ),
        migrations.AddField(
            model_name='pricingautomatedschedule',
            name='master_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_automated_schedule', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricedownloadschememapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.pricedownloadscheme', verbose_name='price download scheme'),
        ),
        migrations.AddField(
            model_name='pricedownloadschememapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricedownloadschememapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='portfoliomapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio', verbose_name='portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliomapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='portfoliomapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='portfolioclassifiermapping',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericattributetype'),
        ),
        migrations.AddField(
            model_name='portfolioclassifiermapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericclassifier'),
        ),
        migrations.AddField(
            model_name='portfolioclassifiermapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='portfolioclassifiermapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='periodicitymapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.periodicity', verbose_name='periodicity'),
        ),
        migrations.AddField(
            model_name='periodicitymapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='periodicitymapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='paymentsizedetailmapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.paymentsizedetail', verbose_name='payment size detail'),
        ),
        migrations.AddField(
            model_name='paymentsizedetailmapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='paymentsizedetailmapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='instrumenttypemapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumenttype', verbose_name='instrument type'),
        ),
        migrations.AddField(
            model_name='instrumenttypemapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='instrumenttypemapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='instrumentmapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='instrumentmapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='instrumentmapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadschemeinput',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='integrations.instrumentdownloadscheme', verbose_name='scheme'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadschemeattribute',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obj_attrs.genericattributetype', verbose_name='attribute_ type'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadschemeattribute',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='integrations.instrumentdownloadscheme', verbose_name='scheme'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='accrual_calculation_schedule_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.accrualscheduledownloadmethod', verbose_name='accrual calculation schedule method'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='daily_pricing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.dailypricingmodel', verbose_name='daily pricing model'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='factor_schedule_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.factorscheduledownloadmethod', verbose_name='factor schedule method'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='payment_size_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.paymentsizedetail', verbose_name='payment size detail'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='instrumentclassifiermapping',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericattributetype'),
        ),
        migrations.AddField(
            model_name='instrumentclassifiermapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericclassifier'),
        ),
        migrations.AddField(
            model_name='instrumentclassifiermapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='instrumentclassifiermapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obj_attrs.genericclassifier', verbose_name='classifier'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obj_attrs.genericattributetype', verbose_name='attribute type'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='instrumentattributevaluemapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='importconfig',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_configs', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='importconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='dailypricingmodelmapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.dailypricingmodel', verbose_name='daily pricing model'),
        ),
        migrations.AddField(
            model_name='dailypricingmodelmapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='dailypricingmodelmapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='currencymapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency', verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='currencymapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='currencymapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='counterpartymapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.counterparty', verbose_name='counterparty'),
        ),
        migrations.AddField(
            model_name='counterpartymapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='counterpartymapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifiermapping',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericattributetype'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifiermapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericclassifier'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifiermapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifiermapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemeselectorvalue',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selector_values', to='integrations.complextransactionimportscheme', verbose_name='scheme'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_scenarios', to='integrations.complextransactionimportscheme', verbose_name='scheme'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='selector_values',
            field=models.ManyToManyField(blank=True, related_name='rule_selector_values', to='integrations.complextransactionimportschemeselectorvalue', verbose_name='selector values'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiontype', verbose_name='transaction type'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemereconscenario',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_scenarios', to='integrations.complextransactionimportscheme', verbose_name='scheme'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemereconscenario',
            name='selector_values',
            field=models.ManyToManyField(blank=True, related_name='recon_selector_values', to='integrations.complextransactionimportschemeselectorvalue', verbose_name='selector values'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemereconfield',
            name='recon_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.complextransactionimportschemereconscenario', verbose_name='recon scenario'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemeinput',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='integrations.complextransactionimportscheme', verbose_name='scheme'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemefield',
            name='rule_scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.complextransactionimportschemerulescenario', verbose_name='rule scenario'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemefield',
            name='transaction_type_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiontypeinput', verbose_name='transaction type input'),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemecalculatedinput',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_inputs', to='integrations.complextransactionimportscheme', verbose_name='scheme'),
        ),
        migrations.AddField(
            model_name='complextransactionimportscheme',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='bloombergdataprovidercredential',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='accrualcalculationmodelmapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.accrualcalculationmodel', verbose_name='accrual calculation model'),
        ),
        migrations.AddField(
            model_name='accrualcalculationmodelmapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='accrualcalculationmodelmapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='accounttypemapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype', verbose_name='account type'),
        ),
        migrations.AddField(
            model_name='accounttypemapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='accounttypemapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='accountclassifiermapping',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericattributetype'),
        ),
        migrations.AddField(
            model_name='accountclassifiermapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.genericclassifier'),
        ),
        migrations.AddField(
            model_name='accountclassifiermapping',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='accountclassifiermapping',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.providerclass', verbose_name='provider'),
        ),
        migrations.AlterIndexTogether(
            name='task',
            index_together={('master_user', 'created')},
        ),
        migrations.AlterUniqueTogether(
            name='strategy3mapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='strategy2mapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='strategy1mapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='responsiblemapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifiermapping',
            unique_together={('master_user', 'provider', 'value', 'attribute_type')},
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicymapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='pricingconditionmapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterIndexTogether(
            name='pricingautomatedschedule',
            index_together={('is_enabled', 'next_run_at')},
        ),
        migrations.AlterUniqueTogether(
            name='pricedownloadschememapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='pricedownloadscheme',
            unique_together={('master_user', 'scheme_name')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliomapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifiermapping',
            unique_together={('master_user', 'provider', 'value', 'attribute_type')},
        ),
        migrations.AlterUniqueTogether(
            name='periodicitymapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentsizedetailmapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypemapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentmapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentdownloadschemeinput',
            unique_together={('scheme', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentdownloadschemeattribute',
            unique_together={('scheme', 'attribute_type')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifiermapping',
            unique_together={('master_user', 'provider', 'value', 'attribute_type')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributevaluemapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='importconfig',
            unique_together={('master_user', 'provider')},
        ),
        migrations.AlterUniqueTogether(
            name='dailypricingmodelmapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='currencymapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='counterpartymapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyclassifiermapping',
            unique_together={('master_user', 'provider', 'value', 'attribute_type')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='complextransactionimportschemerulescenario',
            order_with_respect_to='scheme',
        ),
        migrations.AlterOrderWithRespectTo(
            name='complextransactionimportschemeinput',
            order_with_respect_to='scheme',
        ),
        migrations.AlterOrderWithRespectTo(
            name='complextransactionimportschemecalculatedinput',
            order_with_respect_to='scheme',
        ),
        migrations.AlterUniqueTogether(
            name='complextransactionimportscheme',
            unique_together={('master_user', 'user_code')},
        ),
        migrations.AlterUniqueTogether(
            name='accrualcalculationmodelmapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='accounttypemapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='accountmapping',
            unique_together={('master_user', 'provider', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='accountclassifiermapping',
            unique_together={('master_user', 'provider', 'value', 'attribute_type')},
        ),
    ]
