# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20160727_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloombergrequestlogentry',
            name='action',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bloombergrequestlogentry',
            name='token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
