# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20160727_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloombergrequestlogentry',
            options={'ordering': ('-created',), 'verbose_name': 'bloomberg request log', 'verbose_name_plural': 'bloomberg request logs'},
        ),
    ]
