# Generated by Django 4.1.3 on 2023-02-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_complextransactionimportschemerulescenario_is_error_rule_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='status',
            field=models.CharField(choices=[['active', 'active'], ['skip', 'skip']], default='active', max_length=255),
        ),
    ]
