# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import poms.integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('integrations', '0003_task_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingAutomatedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('cron_expr', models.CharField(blank=True, default='', help_text='Format is "* * * * *" (m/h/d/dM/MY)', max_length=255, validators=[poms.integrations.models.validate_crontab])),
                ('balance_day', models.SmallIntegerField(default=0)),
                ('override_existed', models.BooleanField(default=True)),
                ('fill_days', models.SmallIntegerField(default=0)),
                ('master_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_automated_schedule', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name': 'pricing automated schedule',
                'verbose_name_plural': 'pricing automated schedules',
            },
        ),
    ]
