# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_pricingautomatedschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingautomatedschedule',
            name='load_days',
            field=models.SmallIntegerField(default=1),
        ),
    ]
