# Generated by Django 4.1.3 on 2023-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_task_index_together_remove_task_master_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportscheme',
            name='expression_iterations_count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
