# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models

import poms.integrations.models
import poms.integrations.storage


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0005_auto_20160728_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloombergconfig',
            name='cert',
            field=models.FileField(blank=True, null=True, storage=poms.integrations.storage.ImportConfigStorage(),
                                   upload_to=poms.integrations.models.import_cert_upload_to),
        ),
        migrations.AlterField(
            model_name='bloombergconfig',
            name='key',
            field=models.FileField(blank=True, null=True, storage=poms.integrations.storage.ImportConfigStorage(),
                                   upload_to=poms.integrations.models.import_cert_upload_to),
        ),
        migrations.AlterField(
            model_name='bloombergconfig',
            name='p12cert',
            field=models.FileField(blank=True, null=True, storage=poms.integrations.storage.ImportConfigStorage(),
                                   upload_to=poms.integrations.models.import_cert_upload_to),
        ),
    ]
