# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_pricingautomatedschedule_load_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.MasterUser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.Member'),
        ),
    ]
