# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0017_remove_currencyhistory_pricing_policy'),
        ('integrations', '0006_auto_20160420_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessdata',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='accessdata',
            name='pricing_policy',
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicy',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pricingpolicy',
            name='master_user',
        ),
        migrations.DeleteModel(
            name='AccessData',
        ),
        migrations.DeleteModel(
            name='PricingPolicy',
        ),
    ]
