# Generated by Django 4.1.3 on 2023-04-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_complextransactionimportscheme_expression_iterations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransactionimportscheme',
            name='book_uniqueness_settings',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Skip'), (2, 'Book without Unique Code'), (3, 'Overwrite'), (4, 'Treat as error'), (5, 'Use Transaction Type Setting')], default=1, verbose_name='book uniqueness settings'),
        ),
    ]
