# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_auto_20160728_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentattributemapping',
            name='name',
        ),
        migrations.AddField(
            model_name='instrumentattributemapping',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='accrued_currency',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='accrued_multiplier',
            field=models.CharField(blank=True, default='1.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='daily_pricing_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='default_accrued',
            field=models.CharField(blank=True, default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='default_price',
            field=models.CharField(blank=True, default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='instrument_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='payment_size_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='price_download_mode',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='price_multiplier',
            field=models.CharField(blank=True, default='1.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='pricing_currency',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='user_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='user_text_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='user_text_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentmapping',
            name='user_text_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
