# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20160809_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentMappingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='integrations.InstrumentMapping')),
            ],
            options={
                'ordering': ('attribute_type__name',),
            },
        ),
        migrations.RenameModel(
            old_name='InstrumentAttributeMapping',
            new_name='InstrumentMappingAttribute',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentmappinginput',
            unique_together=set([('mapping', 'name')]),
        ),
    ]
