# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_task_celery_tasks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingautomatedschedule',
            name='latest_running',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pricingautomatedschedule',
            name='latest_task',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.Task'),
        ),
    ]
