# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_auto_20160824_0530'),
        ('integrations', '0008_auto_20160826_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='daily_pricing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.DailyPricingModel', verbose_name='daily pricing model'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='default_accrued',
            field=models.FloatField(default=0.0, verbose_name='default accrued'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='default_price',
            field=models.FloatField(default=0.0, verbose_name='default price'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='payment_size_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PaymentSizeDetail', verbose_name='payment size detail'),
        ),
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='price_download_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.PriceDownloadScheme', verbose_name='price download scheme'),
        ),
    ]
