# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_auto_20160901_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdownloadscheme',
            name='maturity_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
