# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_masteruser_thread_group'),
        ('currencies', '0013_auto_20160809_0548'),
        ('instruments', '0024_auto_20160804_0615'),
        ('integrations', '0009_auto_20160809_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderClass',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='system code')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)')),
                ('name_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)')),
                ('name_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description (en)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description (ru)')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description (es)')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description (de)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderCurrencyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderInstrumentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPricingFieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_multiplier', models.FloatField(default=1.0)),
                ('bid0', models.CharField(blank=True, max_length=50)),
                ('bid1', models.CharField(blank=True, max_length=50)),
                ('bid2', models.CharField(blank=True, max_length=50)),
                ('bid_history', models.CharField(blank=True, max_length=50)),
                ('ask_multiplier', models.FloatField(default=1.0)),
                ('ask0', models.CharField(blank=True, max_length=50)),
                ('ask1', models.CharField(blank=True, max_length=50)),
                ('ask2', models.CharField(blank=True, max_length=50)),
                ('ask_history', models.CharField(blank=True, max_length=50)),
                ('last', models.CharField(blank=True, max_length=50)),
                ('mid', models.CharField(blank=True, max_length=50)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser')),
                ('pricing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.DailyPricingModel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderValueCurrencyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderValueInstrumentAttributeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('value_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='value (String)')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='value (Float)')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='value (Date)')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentAttributeType', verbose_name='attribute type')),
                ('classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentClassifier', verbose_name='classifier')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderValueInstrumentTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('instrument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentType')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='providerpricingfieldmapping',
            unique_together=set([('master_user', 'provider')]),
        ),
    ]
