# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-11 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0003_auto_20170125_1037'),
        ('integrations', '0009_auto_20180511_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioclassifiermapping',
            name='classifier_object',
        ),
        migrations.AddField(
            model_name='portfolioclassifiermapping',
            name='attribute_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericAttributeType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioclassifiermapping',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericClassifier'),
        ),
    ]
