# Generated by Django 4.1.3 on 2023-04-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_instrumentdownloadscheme_configuration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransactionimportscheme',
            name='name',
            field=models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportscheme',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportscheme',
            name='public_name',
            field=models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportscheme',
            name='short_name',
            field=models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='name',
            field=models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='public_name',
            field=models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='short_name',
            field=models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name'),
        ),
    ]
