# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0025_instrument_isin'),
        ('currencies', '0014_currency_isin'),
        ('users', '0013_masteruser_thread_group'),
        ('integrations', '0010_auto_20160812_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualCalculationScheduleMethod',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='system code')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)')),
                ('name_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)')),
                ('name_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description (en)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description (ru)')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description (es)')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description (de)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='FactorScheduleMethod',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='system code')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)')),
                ('name_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)')),
                ('name_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description (en)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description (ru)')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description (es)')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description (de)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentAttributeValueMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('value_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='value (String)')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='value (Float)')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='value (Date)')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentAttributeType', verbose_name='attribute type')),
                ('classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentClassifier', verbose_name='classifier')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('instrument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentType')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.CreateModel(
            name='PricingFieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_multiplier', models.FloatField(default=1.0)),
                ('bid0', models.CharField(blank=True, max_length=50)),
                ('bid1', models.CharField(blank=True, max_length=50)),
                ('bid2', models.CharField(blank=True, max_length=50)),
                ('bid_history', models.CharField(blank=True, max_length=50)),
                ('ask_multiplier', models.FloatField(default=1.0)),
                ('ask0', models.CharField(blank=True, max_length=50)),
                ('ask1', models.CharField(blank=True, max_length=50)),
                ('ask2', models.CharField(blank=True, max_length=50)),
                ('ask_history', models.CharField(blank=True, max_length=50)),
                ('last', models.CharField(blank=True, max_length=50)),
                ('mid', models.CharField(blank=True, max_length=50)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser')),
                ('pricing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.DailyPricingModel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
        ),
        migrations.RemoveField(
            model_name='providercurrencycode',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='providercurrencycode',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providerinstrumentcode',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='providerinstrumentcode',
            name='provider',
        ),
        migrations.AlterUniqueTogether(
            name='providerpricingfieldmapping',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='providerpricingfieldmapping',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='providerpricingfieldmapping',
            name='pricing_model',
        ),
        migrations.RemoveField(
            model_name='providerpricingfieldmapping',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providervaluecurrencymapping',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='providervaluecurrencymapping',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providervalueinstrumentattributemapping',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='providervalueinstrumentattributemapping',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='providervalueinstrumentattributemapping',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providervalueinstrumenttypemapping',
            name='instrument_type',
        ),
        migrations.RemoveField(
            model_name='providervalueinstrumenttypemapping',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='instrumentmapping',
            name='daily_pricing_model',
        ),
        migrations.RemoveField(
            model_name='instrumentmapping',
            name='default_accrued',
        ),
        migrations.RemoveField(
            model_name='instrumentmapping',
            name='default_price',
        ),
        migrations.RemoveField(
            model_name='instrumentmapping',
            name='payment_size_detail',
        ),
        migrations.RemoveField(
            model_name='instrumentmapping',
            name='price_download_mode',
        ),
        migrations.AddField(
            model_name='instrumentmapping',
            name='isin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='instrumentmapping',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentmappinginput',
            name='field',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='instrumentmappinginput',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentmappinginput',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='ProviderCurrencyCode',
        ),
        migrations.DeleteModel(
            name='ProviderInstrumentCode',
        ),
        migrations.DeleteModel(
            name='ProviderPricingFieldMapping',
        ),
        migrations.DeleteModel(
            name='ProviderValueCurrencyMapping',
        ),
        migrations.DeleteModel(
            name='ProviderValueInstrumentAttributeMapping',
        ),
        migrations.DeleteModel(
            name='ProviderValueInstrumentTypeMapping',
        ),
        migrations.AddField(
            model_name='instrumentmapping',
            name='accrual_calculation_schedule_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.AccrualCalculationScheduleMethod'),
        ),
        migrations.AddField(
            model_name='instrumentmapping',
            name='factor_schedule_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.FactorScheduleMethod'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingfieldmapping',
            unique_together=set([('master_user', 'provider')]),
        ),
    ]
