# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_instrumentdownloadscheme_maturity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentattributevaluemapping',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.InstrumentClassifier', verbose_name='classifier'),
        ),
    ]
