# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0003_auto_20170125_1037'),
        ('users', '0003_masteruser_transaction_type_group'),
        ('integrations', '0011_auto_20180511_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyClassifierMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=255, verbose_name='value')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericAttributeType')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericClassifier')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'responsible classifier mapping',
                'verbose_name_plural': 'responsible classifier mappings',
                'ordering': ['value'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibleClassifierMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=255, verbose_name='value')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericAttributeType')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericClassifier')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'responsible classifier mapping',
                'verbose_name_plural': 'responsible classifier mappings',
                'ordering': ['value'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value')]),
        ),
    ]
