# Generated by Django 4.1.3 on 2023-05-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_alter_complextransactionimportscheme_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complextransactionimportschemerulescenario',
            old_name='transaction_type',
            new_name='transaction_type_old',
        ),
    ]
