# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 10:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import poms.integrations.models
import poms.integrations.storage


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0014_currency_isin'),
        ('users', '0013_masteruser_thread_group'),
        ('instruments', '0025_instrument_isin'),
        ('integrations', '0011_auto_20160812_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p12cert', models.FileField(blank=True, null=True, storage=poms.integrations.storage.ImportConfigStorage(), upload_to=poms.integrations.models.import_cert_upload_to)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('cert', models.FileField(blank=True, null=True, storage=poms.integrations.storage.ImportConfigStorage(), upload_to=poms.integrations.models.import_cert_upload_to)),
                ('key', models.FileField(blank=True, null=True, storage=poms.integrations.storage.ImportConfigStorage(), upload_to=poms.integrations.models.import_cert_upload_to)),
                ('master_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloomberg_config', to='users.MasterUser')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
            options={
                'verbose_name_plural': 'import configs',
                'verbose_name': 'import config',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('status', models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'REQUEST_SENT'), (2, 'WAIT_RESPONSE'), (3, 'DONE'), (-1, 'ERROR'), (-2, 'TIMEOUT')], default=0)),
                ('action', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('isin', models.CharField(max_length=100)),
                ('response_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('currencies', models.ManyToManyField(blank=True, to='currencies.Currency')),
                ('instruments', models.ManyToManyField(blank=True, to='instruments.Instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloomberg_tasks', to='users.MasterUser')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloomberg_tasks', to='users.Member')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'ordering': ('-created',),
                'verbose_name': 'task',
            },
        ),
        migrations.RemoveField(
            model_name='bloombergconfig',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='bloombergtask',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='bloombergtask',
            name='member',
        ),
        migrations.DeleteModel(
            name='BloombergConfig',
        ),
        migrations.DeleteModel(
            name='BloombergTask',
        ),
        migrations.AlterUniqueTogether(
            name='importconfig',
            unique_together=set([('master_user', 'provider')]),
        ),
    ]
