# Generated by Django 4.1.3 on 2023-05-12 09:50

from django.db import connection
from django.db import migrations, models


def get_all_records(table_name):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM %s" % table_name)
        columns = [col[0] for col in cursor.description]
        rows = [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    return rows


def forwards_func(apps, schema_editor):
    # print("forwards_func")

    from poms.integrations.models import ComplexTransactionImportSchemeRuleScenario
    from poms.transactions.models import TransactionType
    items = get_all_records('integrations_complextransactionimportschemerulescenario')

    print('items count %s' % len(items))
    if len(items):
        print('item %s' % items[0])

    index = 0

    for item in items:

        scenario = ComplexTransactionImportSchemeRuleScenario.objects.get(id=item['id'])

        if item.get('transaction_type_old_id', None):
            transaction_type = TransactionType.objects.get(id=item['transaction_type_old_id'])

            scenario.transaction_type = transaction_type.user_code
            index = index + 1

            scenario.save()

    print('items updated %s' % index)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            'integrations',
            '0012_rename_transaction_type_complextransactionimportschemerulescenario_transaction_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='transaction_type',
            field=models.CharField(default='-', max_length=1024, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
