# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 11:25
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import poms.integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_auto_20160815_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='action',
        ),
    ]
