# Generated by Django 4.1.3 on 2023-05-12 09:50

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # print("forwards_func")

    from poms.integrations.models import ComplexTransactionImportSchemeRuleScenario
    items = ComplexTransactionImportSchemeRuleScenario.objects.all()

    print('items count %s' % len(items))

    index = 0

    for item in items:

        if item.transaction_type_old:
            item.transaction_type = item.transaction_type_old.user_code
            index = index + 1

        item.save()

    print('items updated %s' % index)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
        'integrations', '0012_rename_transaction_type_complextransactionimportschemerulescenario_transaction_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='transaction_type',
            field=models.CharField(default='-', max_length=1024, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
