# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_auto_20160908_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentattributevaluemapping',
            name='value_string',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='value (String)'),
        ),
    ]
