# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20170512_0739'),
        ('users', '0009_auto_20181128_1247'),
        ('integrations', '0013_auto_20181031_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=255, verbose_name='value')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'pricing policy mapping',
                'verbose_name_plural': 'pricing policy mappings',
                'abstract': False,
                'ordering': ['value'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicymapping',
            unique_together=set([('master_user', 'provider', 'value')]),
        ),
    ]
