# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_auto_20160815_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'instrument'), (2, 'pricing_latest'), (3, 'pricing_history')], db_index=True, default=1),
            preserve_default=False,
        ),
    ]
