# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-27 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_masteruser_price_download_scheme'),
        ('integrations', '0014_auto_20181220_1340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentdownloadscheme',
            unique_together=set([('master_user', 'scheme_name')]),
        ),
    ]
