# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_task_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='isin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
