# Generated by Django 4.1.3 on 2023-05-12 10:03

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # print("forwards_func")

    from poms.integrations.models import ComplexTransactionImportSchemeField
    items = ComplexTransactionImportSchemeField.objects.all()

    print('items count %s' % len(items))

    index = 0

    for item in items:

        if item.transaction_type_input_old:
            item.transaction_type_input = item.transaction_type_input_old.name
            index = index + 1

        item.save()

    print('items updated %s' % index)


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_rename_transaction_type_input_complextransactionimportschemefield_transaction_type_input_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportschemefield',
            name='transaction_type_input',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction type input'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
