# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-26 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_member_notification_level'),
        ('integrations', '0015_auto_20181227_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricedownloadscheme',
            unique_together=set([('master_user', 'scheme_name')]),
        ),
    ]
