# Generated by Django 4.1.3 on 2023-05-12 10:03

from django.db import migrations, models
from django.db import connection

def get_all_records(table_name):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM %s" % table_name)
        columns = [col[0] for col in cursor.description]
        rows = [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    return rows

def forwards_func(apps, schema_editor):
    # print("forwards_func")

    from poms.integrations.models import ComplexTransactionImportSchemeField
    from poms.transactions.models import TransactionTypeInput
    items = get_all_records('integrations_complextransactionimportschemefield')

    print('items count %s' % len(items))

    index = 0

    for item in items:

        field = ComplexTransactionImportSchemeField.objects.get(id=item['id'])

        if item.get('transaction_type_input_old_id', None):

            input = TransactionTypeInput.objects.get(id=item['transaction_type_input_old_id'])

            field.transaction_type_input = input.name
            index = index + 1

            field.save()

    print('items updated %s' % index)


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_rename_transaction_type_input_complextransactionimportschemefield_transaction_type_input_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportschemefield',
            name='transaction_type_input',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction type input'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
