# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_auto_20160922_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualscheduledownloadmethod',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='accrualscheduledownloadmethod',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='factorscheduledownloadmethod',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='factorscheduledownloadmethod',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='providerclass',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='providerclass',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
    ]
