# Generated by Django 4.1.3 on 2023-05-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_complextransactionimportschemefield_transaction_type_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complextransactionimportschemefield',
            name='transaction_type_input_old',
        ),
    ]
