# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0005_auto_20180717_1147'),
        ('users', '0013_member_notification_level'),
        ('integrations', '0016_auto_20190126_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentClassifierMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=255, verbose_name='value')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericAttributeType')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericClassifier')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass', verbose_name='provider')),
            ],
            options={
                'ordering': ['value'],
                'verbose_name': 'instrument classifier mapping',
                'verbose_name_plural': 'instrument classifier mappings',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value')]),
        ),
    ]
