# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_member_notification_level'),
        ('accounts', '0004_auto_20170512_0739'),
        ('integrations', '0017_auto_20190313_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=255, verbose_name='value')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountType', verbose_name='account type')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.ProviderClass', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'account type mapping',
                'ordering': ['value'],
                'verbose_name_plural': 'account type mappings',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='accounttypemapping',
            unique_together=set([('master_user', 'provider', 'value')]),
        ),
    ]
