# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrualcalculationmodelmapping',
            options={'ordering': ['value'], 'verbose_name': 'accrual calculation model mapping', 'verbose_name_plural': 'accrual calculation model  mappings'},
        ),
        migrations.AlterModelOptions(
            name='currencymapping',
            options={'ordering': ['value'], 'verbose_name': 'currency mapping', 'verbose_name_plural': 'currency mappings'},
        ),
        migrations.AlterModelOptions(
            name='instrumentattributevaluemapping',
            options={'ordering': ['value'], 'verbose_name': 'instrument attribute value mapping', 'verbose_name_plural': 'instrument attribute value mappings'},
        ),
        migrations.AlterModelOptions(
            name='instrumentdownloadscheme',
            options={'ordering': ['scheme_name'], 'verbose_name': 'instrument download scheme', 'verbose_name_plural': 'instrument download schemes'},
        ),
        migrations.AlterModelOptions(
            name='instrumentdownloadschemeattribute',
            options={'ordering': ['attribute_type'], 'verbose_name': 'instrument download scheme attribute', 'verbose_name_plural': 'instrument download schemes attribute'},
        ),
        migrations.AlterModelOptions(
            name='instrumentdownloadschemeinput',
            options={'ordering': ['name'], 'verbose_name': 'instrument download scheme input', 'verbose_name_plural': 'instrument download scheme inputs'},
        ),
        migrations.AlterModelOptions(
            name='instrumenttypemapping',
            options={'ordering': ['value'], 'verbose_name': 'instrument type mapping', 'verbose_name_plural': 'instrument type mappings'},
        ),
        migrations.AlterModelOptions(
            name='periodicitymapping',
            options={'ordering': ['value'], 'verbose_name': 'periodicity mapping', 'verbose_name_plural': 'periodicity  mappings'},
        ),
        migrations.AlterModelOptions(
            name='pricedownloadscheme',
            options={'ordering': ['scheme_name'], 'verbose_name': 'price download scheme', 'verbose_name_plural': 'price download schemes'},
        ),
        migrations.AlterModelOptions(
            name='pricingautomatedschedule',
            options={'ordering': ['is_enabled'], 'verbose_name': 'pricing automated schedule', 'verbose_name_plural': 'pricing automated schedules'},
        ),
    ]
