# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-05 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_masteruser_user_code_counters'),
        ('obj_attrs', '0005_auto_20180717_1147'),
        ('integrations', '0018_auto_20190320_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifiermapping',
            unique_together=set([('master_user', 'provider', 'value', 'attribute_type')]),
        ),
    ]
