# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_auto_20190405_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportschemeinput',
            name='name_expr',
            field=models.CharField(default='', max_length=1000, verbose_name='name expression'),
        ),
    ]
