# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_auto_20160818_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isin',
            new_name='instrument_code',
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='ask_history_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='bid_history_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='currency_fxrate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='currency_fxrate_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='last_history',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='last_history_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='last_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='mid_history',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='mid_history_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pricedownloadscheme',
            name='mid_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='task',
            name='instrument_download_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.InstrumentDownloadScheme'),
        ),
        migrations.AddField(
            model_name='task',
            name='price_download_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.PriceDownloadScheme'),
        ),
        migrations.AddField(
            model_name='task',
            name='request_id',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='importconfig',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_configs', to='users.MasterUser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='response_id',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
