# Generated by Django 4.2.3 on 2023-07-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_invitetomasteruser_unique_together_and_more'),
        ('integrations', '0019_mappingtable_mappingtablekeyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtable',
            name='master_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
            preserve_default=False,
        ),
    ]
