# Generated by Django 4.2.3 on 2023-07-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_mappingtable_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtablekeyvalue',
            name='mapping_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.mappingtable', verbose_name='mapping table'),
        ),
    ]
