# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-11 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_complextransactionimportschemeinput_name_expr'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdownloadschemeinput',
            name='name_expr',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='name expression'),
        ),
    ]
