# Generated by Django 2.2.5 on 2019-12-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0055_auto_20191203_1235'),
        ('integrations', '0024_auto_20190916_1943'),
    ]
    operations = [
        migrations.CreateModel(
            name='ComplexTransactionImportSchemeSelectorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='value ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selector_values', to='integrations.ComplexTransactionImportScheme', verbose_name='scheme')),
            ],
        ),

        migrations.CreateModel(
            name='ComplexTransactionImportSchemeReconScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name', blank=True, null=True)),
                ('line_reference_id', models.CharField(max_length=1024, verbose_name='line reference id')),
                ('reference_date', models.CharField(max_length=1024, verbose_name='reference_date')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_scenarios', to='integrations.ComplexTransactionImportScheme', verbose_name='scheme')),
            ],
        ),
        migrations.AddField(
            model_name='complextransactionimportschemereconscenario',
            name='selector_values',
            field=models.ManyToManyField(blank=True, related_name='recon_selector_values', to='integrations.ComplexTransactionImportSchemeSelectorValue', verbose_name='selector values'),
        ),

        migrations.RenameModel('ComplexTransactionImportSchemeRule', 'ComplexTransactionImportSchemeRuleScenario'),
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name', blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='complextransactionimportschemerulescenario',
            name='value',
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemerulescenario',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_scenarios', to='integrations.ComplexTransactionImportScheme', verbose_name='scheme'),
        ),

        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='selector_values',
            field=models.ManyToManyField(blank=True, related_name='rule_selector_values', to='integrations.ComplexTransactionImportSchemeSelectorValue', verbose_name='selector values'),
        ),

        migrations.CreateModel(
            name='ComplexTransactionImportSchemeReconField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=255, verbose_name='reference name ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('value_string', models.CharField(max_length=1024, verbose_name='value string')),
                ('value_float', models.CharField(max_length=1024, verbose_name='value float')),
                ('value_date', models.CharField(max_length=1024, verbose_name='value date')),
                ('recon_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.ComplexTransactionImportSchemeReconScenario', verbose_name='recon scenario')),
            ],
        ),
        # migrations.RenameField(
        #     model_name='complextransactionimportschemefield',
        #     old_name='rule',
        #     new_name='rule_scenario'
        # ),
        # migrations.AlterField(
        #     model_name='complextransactionimportschemefield',
        #     name='rule_scenario',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.ComplexTransactionImportSchemeRuleScenario', verbose_name='rule scenario'),
        # ),
        migrations.AlterOrderWithRespectTo(
            name='complextransactionimportschemefield',
            order_with_respect_to=None,
        ),
    ]

