# Generated by Django 2.2.5 on 2019-12-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_auto_20191209_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complextransactionimportschemefield',
            old_name='rule',
            new_name='rule_scenario'
        ),
        # migrations.AlterField(
        #     model_name='complextransactionimportschemefield',
        #     name='rule_scenario',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.ComplexTransactionImportSchemeRuleScenario', verbose_name='rule scenario'),
        # ),
    ]
