# Generated by Django 2.2.5 on 2019-12-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0027_auto_20191212_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complextransactionimportschemereconscenario',
            options={'verbose_name': 'complex transaction import scheme recon scenario', 'verbose_name_plural': 'complex transaction import scheme recon scenarios'},
        ),
        migrations.AlterModelOptions(
            name='complextransactionimportschemerulescenario',
            options={'verbose_name': 'complex transaction import scheme rule scenario', 'verbose_name_plural': 'complex transaction import scheme rules scenarios'},
        ),
    ]
