# Generated by Django 2.2.5 on 2020-01-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0028_auto_20191212_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexTransactionImportSchemeCalculatedInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column', models.SmallIntegerField()),
                ('name_expr', models.CharField(default='', max_length=1000, verbose_name='name expression')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_inputs', to='integrations.ComplexTransactionImportScheme', verbose_name='scheme')),
            ],
            options={
                'verbose_name': 'complex transaction import scheme calculated input',
                'verbose_name_plural': 'complex transaction import scheme calculated inputs',
                'order_with_respect_to': 'scheme',
            },
        ),
    ]
