# Generated by Django 2.2.5 on 2020-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0029_complextransactionimportschemecalculatedinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingautomatedschedule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
    ]
