# Generated by Django 2.2.5 on 2020-05-20 15:06

from django.db import migrations, models
import django.db.models.deletion
import poms.integrations.models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_auto_20200323_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloombergDataProviderCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False, verbose_name='is valid')),
                ('p12cert', models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=poms.integrations.models.bloomberg_cert_upload_to, verbose_name='p12cert')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='password')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
        ),
    ]
