# Generated by Django 2.2.5 on 2020-08-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
        ('integrations', '0039_transactionfileresult_transactionprovider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionProvider',
            new_name='DataProvider',
        ),
    ]
