# Generated by Django 2.2.5 on 2020-09-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0008_auto_20200922_1248'),
        ('integrations', '0042_complextransactionimportscheme_book_uniqueness_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfileresult',
            name='procedure_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='procedures.RequestDataFileProcedureInstance', verbose_name='procedure'),
            preserve_default=False,
        ),
    ]
