# Generated by Django 2.2.5 on 2020-10-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0043_transactionfileresult_procedure_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfileresult',
            name='file',
        ),
        migrations.AddField(
            model_name='transactionfileresult',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionfileresult',
            name='file_path',
            field=models.TextField(blank=True, default='', verbose_name='File Path'),
        ),
    ]
