# Generated by Django 2.2.5 on 2021-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0047_auto_20210210_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrualscheduledownloadmethod',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='factorscheduledownloadmethod',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='providerclass',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
    ]
