# Generated by Django 2.2.5 on 2021-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0052_auto_20210210_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentdownloadscheme',
            options={'verbose_name': 'instrument download scheme',
                     'verbose_name_plural': 'instrument download schemes'},
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentdownloadscheme',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='instrumentdownloadscheme',
            index_together=set(),
        ),
    ]
