# Generated by Django 2.2.5 on 2021-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0056_instrumentdownloadscheme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportschemerulescenario',
            name='is_default_rule_scenario',
            field=models.BooleanField(default=False, verbose_name='is default rule scenario'),
        ),
    ]
