# Generated by Django 2.2.5 on 2021-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0057_complextransactionimportschemerulescenario_is_default_rule_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualscheduledownloadmethod',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='factorscheduledownloadmethod',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='providerclass',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='short name'),
        ),
    ]
