# Generated by Django 2.2.5 on 2022-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0062_complextransactionimportscheme_spreadsheet_active_tab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportscheme',
            name='column_matcher',
            field=models.CharField(choices=[['index', 'Index'], ['name', 'Name']], default='index', max_length=255),
        ),
        migrations.AddField(
            model_name='complextransactionimportschemeinput',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
