# Generated by Django 2.2.5 on 2022-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0064_complextransactionimportscheme_filter_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransactionimportscheme',
            name='has_header_row',
            field=models.BooleanField(default=True, verbose_name='has header row'),
        ),
    ]
