# Generated by Django 4.0.6 on 2022-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0066_alter_complextransactionimportscheme_rule_expr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransactionimportscheme',
            name='rule_expr',
            field=models.CharField(max_length=4096, verbose_name='rule expressions'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemecalculatedinput',
            name='name_expr',
            field=models.CharField(default='', max_length=4096, verbose_name='name expression'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemefield',
            name='value_expr',
            field=models.CharField(max_length=4096, verbose_name='value expression'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemeinput',
            name='name_expr',
            field=models.CharField(default='', max_length=4096, verbose_name='name expression'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemereconfield',
            name='value_date',
            field=models.CharField(max_length=4096, verbose_name='value date'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemereconfield',
            name='value_float',
            field=models.CharField(max_length=4096, verbose_name='value float'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemereconfield',
            name='value_string',
            field=models.CharField(max_length=4096, verbose_name='value string'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemereconscenario',
            name='line_reference_id',
            field=models.CharField(max_length=4096, verbose_name='line reference id'),
        ),
        migrations.AlterField(
            model_name='complextransactionimportschemereconscenario',
            name='reference_date',
            field=models.CharField(max_length=4096, verbose_name='reference_date'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='accrued_currency',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='accrued currency'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='accrued_multiplier',
            field=models.CharField(blank=True, default='1.0', max_length=4096, verbose_name='accrued multiplier'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='instrument_name',
            field=models.CharField(max_length=4096, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='instrument_notes',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='instrument_public_name',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='public name'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='instrument_short_name',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='instrument_type',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='instrument type'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='instrument_user_code',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='maturity_date',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='maturity date'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='maturity_price',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='maturity price'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='price_multiplier',
            field=models.CharField(blank=True, default='1.0', max_length=4096, verbose_name='price multiplier'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='pricing_currency',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='pricing currency'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='user_text_1',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 1'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='user_text_2',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 2'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadscheme',
            name='user_text_3',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='user text 3'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadschemeattribute',
            name='value',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='instrumentdownloadschemeinput',
            name='name_expr',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='name expression'),
        ),
    ]
