# Generated by Django 4.0.6 on 2022-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0069_alter_bloombergdataprovidercredential_p12cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloombergdataprovidercredential',
            name='p12cert',
            field=models.TextField(blank=True, default='', verbose_name='File URL'),
        ),
    ]
