# Generated by Django 4.1.3 on 2022-12-07 21:52

from django.db import migrations, models
import django.db.models.deletion
import poms.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('currencies', '0001_initial'),
        ('users', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('report_settings_data', models.TextField(blank=True, null=True, verbose_name='report settings data')),
                ('nav', models.FloatField(blank=True, default=0.0, null=True, verbose_name='nav')),
                ('cost_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.costmethod', verbose_name='cost method')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_report_histories', to='users.masteruser', verbose_name='master user')),
                ('portfolio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio', verbose_name='portfolio')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.pricingpolicy', verbose_name='pricing policy')),
                ('report_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency', verbose_name='report currency')),
            ],
            options={
                'unique_together': {('master_user', 'date', 'portfolio')},
            },
        ),
        migrations.CreateModel(
            name='PLReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('pl_first_date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='pl first date')),
                ('report_settings_data', models.TextField(blank=True, null=True, verbose_name='report settings data')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='total')),
                ('cost_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.costmethod', verbose_name='cost method')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
                ('portfolio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio', verbose_name='portfolio')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.pricingpolicy', verbose_name='pricing policy')),
                ('report_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency', verbose_name='report currency')),
            ],
            options={
                'unique_together': {('master_user', 'date', 'portfolio')},
            },
        ),
        migrations.CreateModel(
            name='PLReportHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=255, verbose_name='category')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='key')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='value')),
                ('pl_report_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='widgets.plreporthistory', verbose_name='pl report history')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceReportHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=255, verbose_name='category')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='key')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='value')),
                ('balance_report_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='widgets.balancereporthistory', verbose_name='balance report history')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('benchmark', models.CharField(blank=True, default='', max_length=255, verbose_name='benchmark')),
                ('nav', models.FloatField(blank=True, default=0.0, null=True, verbose_name='nav')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='total')),
                ('cumulative_return', models.FloatField(blank=True, default=0.0, null=True, verbose_name='cumulative return')),
                ('annualized_return', models.FloatField(blank=True, default=0.0, null=True, verbose_name='annualized return')),
                ('portfolio_volatility', models.FloatField(blank=True, default=0.0, null=True, verbose_name='portfolio volatility')),
                ('annualized_portfolio_volatility', models.FloatField(blank=True, default=0.0, null=True, verbose_name='annualized portfolio volatility')),
                ('sharpe_ratio', models.FloatField(blank=True, default=0.0, null=True, verbose_name='sharpe_ratio')),
                ('max_annualized_drawdown', models.FloatField(blank=True, default=0.0, null=True, verbose_name='max_annualized_drawdown')),
                ('betta', models.FloatField(blank=True, default=0.0, null=True, verbose_name='betta')),
                ('alpha', models.FloatField(blank=True, default=0.0, null=True, verbose_name='alpha')),
                ('correlation', models.FloatField(blank=True, default=0.0, null=True, verbose_name='correlation')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
                ('portfolio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio', verbose_name='portfolio')),
            ],
            options={
                'unique_together': {('master_user', 'date', 'portfolio')},
            },
        ),
    ]
