# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancereporthistory',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='balancereporthistory',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='plreporthistory',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='plreporthistory',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
