# Generated by Django 4.0.6 on 2022-09-21 16:14

import django.db.models.deletion
from django.db import migrations, models

import poms.common.utils


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0083_country_description_country_short_name_and_more'),
        ('accounts', '0018_alter_accounttype_transaction_details_expr'),
        ('portfolios', '0029_rename_groups_portfoliobundle_registers'),
        ('users', '0043_ecosystemdefault_currency_pricing_scheme_and_more'),
        ('currencies', '0021_auto_20220314_1202'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('pl_first_date',
                 models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='pl first date')),
                ('report_settings_data', models.TextField(blank=True, null=True, verbose_name='report settings data')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='total')),
                ('accounts', models.ManyToManyField(blank=True, to='accounts.account', verbose_name='accounts')),
                ('cost_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='instruments.costmethod', verbose_name='cost method')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser',
                                                  verbose_name='master user')),
                (
                'portfolios', models.ManyToManyField(blank=True, to='portfolios.portfolio', verbose_name='portfolios')),
                ('pricing_policy',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.pricingpolicy',
                                   verbose_name='pricing policy')),
                ('report_currency',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   to='currencies.currency', verbose_name='report currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PLReportHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=255, verbose_name='category')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='key')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='value')),
                ('pl_report_history',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                   to='widgets.plreporthistory', verbose_name='pl report history')),
            ],
        ),
    ]
