# Generated by Django 4.0.6 on 2022-09-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0029_rename_groups_portfoliobundle_registers'),
        ('widgets', '0002_plreporthistory_plreporthistoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancereporthistory',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='balancereporthistory',
            name='portfolios',
        ),
        migrations.RemoveField(
            model_name='plreporthistory',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='plreporthistory',
            name='portfolios',
        ),
        migrations.AddField(
            model_name='balancereporthistory',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio', verbose_name='portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plreporthistory',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio', verbose_name='portfolio'),
            preserve_default=False,
        ),
    ]
