# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereport',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_reports', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='cashflowreport',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_reports', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='expr',
            field=models.CharField(max_length=255, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='plreport',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_reports', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='transactionreport',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_reports', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
