# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190522_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereportcustomfield',
            name='user_code',
            field=models.CharField(max_length=255, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='plreportcustomfield',
            name='user_code',
            field=models.CharField(max_length=255, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='transactionreportcustomfield',
            name='user_code',
            field=models.CharField(max_length=255, verbose_name='user code'),
        ),
    ]
