# Generated by Django 2.2.5 on 2022-06-23 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0015_performancereportinstance_performancereportinstanceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereportinstance',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='performancereportinstance',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='report_date_from',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='report_date_to',
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='begin_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='begin date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='end_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereportinstanceitem',
            name='begin_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='begin date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereportinstanceitem',
            name='end_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='end date'),
            preserve_default=False,
        ),
    ]
