# Generated by Django 2.2.5 on 2022-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20220623_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereportinstance',
            name='registers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='registers'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='registers_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='registers names'),
        ),
        migrations.AddField(
            model_name='performancereportinstanceitem',
            name='registers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='registers'),
        ),
        migrations.AddField(
            model_name='performancereportinstanceitem',
            name='registers_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='registers names'),
        ),
    ]
