# Generated by Django 2.2.5 on 2022-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0017_auto_20220623_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_date_1',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_date_2',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_date_3',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_date_4',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_date_5',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_number_1',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_number_2',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_number_3',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_number_4',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_number_5',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_text_1',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_text_2',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_text_3',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_text_4',
        ),
        migrations.RemoveField(
            model_name='performancereportinstanceitem',
            name='custom_field_text_5',
        ),
    ]
