# Generated by Django 2.2.5 on 2022-06-26 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_performancereportinstanceitem_cumulative_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancereportinstance',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='balancereportinstance',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='performancereportinstance',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='plreportinstance',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
    ]
