# Generated by Django 4.1.3 on 2022-12-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('current_step', models.IntegerField(default=0, verbose_name='current step')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member', verbose_name='member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('I', 'INIT'), ('P', 'PENDING'), ('D', 'DONE'), ('E', 'ERROR'), ('T', 'TIMEOUT'), ('C', 'CANCELED')], default='I', max_length=1, null=True, verbose_name='status')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log')),
                ('result', models.TextField(blank=True, null=True, verbose_name='result')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('code', models.TextField(blank=True, null=True, verbose_name='code')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow', verbose_name='master user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
