INSTRUMENT = {
    "instrument_type": 17,
    "instrument_type_object": {
        "id": 17,
        "instrument_class": 1,
        "instrument_class_object": {
            "id": 1,
            "user_code": "GENERAL",
            "name": "General Class",
            "description": "General Class",
        },
        "user_code": "local.poms.space00000:stock",
        "name": "stock",
        "short_name": "stock",
        "public_name": "stock",
        "instrument_form_layouts": None,
        "deleted_user_code": None,
        "meta": {
            "content_type": "instruments.instrumenttype",
            "app_label": "instruments",
            "model_name": "instrumenttype",
            "space_code": "space00000",
        },
    },
    "user_code": "CSVJGHVZFC",
    "name": "BOXUGKLYWOR",
    "short_name": "BSH",
    "public_name": None,
    "notes": None,
    "is_active": True,
    "is_deleted": False,
    "has_linked_with_portfolio": False,
    "pricing_currency": 28,
    "pricing_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "price_multiplier": 1.0,
    "accrued_currency": 28,
    "accrued_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "accrued_multiplier": 1.0,
    "payment_size_detail": 1,
    "payment_size_detail_object": {
        "id": 1,
        "user_code": "PERCENT",
        "name": "% per annum",
        "description": "% per annum",
    },
    "default_price": 0.0,
    "default_accrued": 0.0,
    "user_text_1": "JBYWDPLZLI",
    "user_text_2": "FHHMHMVRER",
    "user_text_3": "SHASFYKQLJ",
    "reference_for_pricing": "",
    "daily_pricing_model": 6,
    "daily_pricing_model_object": {
        "id": 6,
        "user_code": "-",
        "name": "Use Default Price (no Price History)",
        "description": "Use Default Price (no Price History)",
    },
    "pricing_condition": 1,
    "pricing_condition_object": {
        "id": 1,
        "user_code": "NO_VALUATION",
        "name": "Don't Run Valuation",
        "description": "Don't Run Valuation",
    },
    "maturity_date": None,
    "maturity_price": 0.0,
    "manual_pricing_formulas": [],
    "accrual_calculation_schedules": [
        {
            "id": 4,
            "accrual_start_date": None,
            "accrual_start_date_value_type": 40,
            "first_payment_date": None,
            "first_payment_date_value_type": 40,
            "accrual_size": "0.598345055004762",
            "accrual_size_value_type": 20,
            "periodicity_n": "30",
            "periodicity_n_value_type": 20,
            "accrual_calculation_model": 2,
            "accrual_calculation_model_object": {
                "id": 2,
                "user_code": "ACT_ACT",
                "name": "ACT/ACT",
                "description": "ACT/ACT",
            },
            "periodicity": 1,
            "periodicity_object": {
                "id": 1,
                "user_code": "N_DAY",
                "name": "N Days",
                "description": "N Days",
            },
            "notes": "",
        }
    ],
    "factor_schedules": [
        {
            "effective_date": "2024-05-21",
            "factor_value": 0.2278459186631061,
        }
    ],
    "event_schedules": [],
    "is_enabled": True,
    "pricing_policies": [],
    "exposure_calculation_model": 1,
    "exposure_calculation_model_object": {
        "id": 1,
        "user_code": "MARKET_VALUE",
        "name": "Market value",
        "description": "Market value",
    },
    "co_directional_exposure_currency": 28,
    "counter_directional_exposure_currency": None,
    "co_directional_exposure_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "counter_directional_exposure_currency_object": {
        "id": 28,
        "user_code": "EUR",
        "name": "EUR - Euro",
        "short_name": "EUR",
        "deleted_user_code": None,
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "long_underlying_instrument": None,
    "short_underlying_instrument": None,
    "long_underlying_instrument_object": None,
    "short_underlying_instrument_object": None,
    "underlying_long_multiplier": 1.0,
    "underlying_short_multiplier": 1.0,
    "long_underlying_exposure": 1,
    "short_underlying_exposure": 1,
    "position_reporting": 1,
    "country": 112,
    "country_object": {
        "id": 112,
        "name": "Italy",
        "user_code": "Italy",
        "country_code": "380",
        "region": "Europe",
        "region_code": "150",
        "alpha_2": "IT",
        "alpha_3": "ITA",
        "sub_region": "Southern Europe",
        "sub_region_code": "039",
    },
    "deleted_user_code": None,
    "attributes": [
        {
            "id": 4,
            "attribute_type": 4,
            "value_string": "PGBZBAEROP",
            "value_float": 6897.0,
            "value_date": "2023-07-21",
            "classifier": None,
            "attribute_type_object": {
                "id": 4,
                "user_code": "local.poms.space00000:auth.permission:tbylo",
                "name": "",
                "short_name": "PC",
                "public_name": None,
                "notes": None,
                "can_recalculate": False,
                "value_type": 20,
                "order": 0,
                "is_hidden": False,
                "kind": 1,
            },
            "classifier_object": None,
        }
    ],
    "meta": {
        "content_type": "instruments.instrument",
        "app_label": "instruments",
        "model_name": "instrument",
        "space_code": "space00000",
    },
}
