# Generated by Django 2.2.5 on 2020-03-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutArchetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, unique=True, verbose_name='name')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
        ),
    ]
