# Generated by Django 2.2.5 on 2020-03-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0029_userprofile_two_factor_verification'),
        ('layout_recovery', '0002_auto_20200324_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutarchetype',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='layoutarchetype',
            unique_together={('name', 'master_user', 'content_type')},
        ),
    ]
