# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDataImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_status', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(choices=[['skip', 'Skip if exists'], ['overwrite', 'Overwrite']], default='skip', max_length=255)),
                ('delimiter', models.CharField(choices=[[',', 'Comma'], [';', 'Semicolon'], ['\t', 'Tab']], default=',', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_handler', models.CharField(choices=[['break', 'Break'], ['continue', 'Continue']], default='break', max_length=255)),
                ('missing_data_handler', models.CharField(choices=[['throw_error', 'Treat as Error'], ['set_defaults', 'Replace with Default Value']], default='throw_error', max_length=255)),
                ('classifier_handler', models.CharField(choices=[['skip', 'Skip'], ['append', 'Append']], default='skip', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CsvField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_expr', models.CharField(default='', max_length=4096, verbose_name='name expression')),
            ],
            options={
                'verbose_name': 'csv field',
                'verbose_name_plural': 'csv fields',
            },
        ),
        migrations.CreateModel(
            name='CsvImportScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('filter_expr', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='filter expression')),
                ('mode', models.CharField(choices=[['skip', 'Skip if exists'], ['overwrite', 'Overwrite']], default='skip', max_length=255)),
                ('delimiter', models.CharField(choices=[[',', 'Comma'], [';', 'Semicolon'], ['\t', 'Tab']], default=',', max_length=255)),
                ('error_handler', models.CharField(choices=[['break', 'Break'], ['continue', 'Continue']], default='break', max_length=255)),
                ('missing_data_handler', models.CharField(choices=[['throw_error', 'Treat as Error'], ['set_defaults', 'Replace with Default Value']], default='throw_error', max_length=255)),
                ('classifier_handler', models.CharField(choices=[['skip', 'Skip'], ['append', 'Append']], default='skip', max_length=255)),
                ('instrument_reference_column', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('spreadsheet_start_cell', models.CharField(default='A1', max_length=255)),
                ('spreadsheet_active_tab_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('column_matcher', models.CharField(choices=[['index', 'Index'], ['name', 'Name']], default='index', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
            ],
        ),
        migrations.CreateModel(
            name='EntityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expression', models.CharField(blank=True, default='', max_length=4096)),
                ('use_default', models.BooleanField(default=True, verbose_name='use default')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('system_property_key', models.CharField(max_length=255, null=True)),
                ('dynamic_attribute_id', models.IntegerField(null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_fields', to='csv_import.csvimportscheme')),
            ],
            options={
                'verbose_name': 'entity field',
                'verbose_name_plural': 'entity fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CsvImportSchemeCalculatedInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column', models.SmallIntegerField()),
                ('name_expr', models.CharField(default='', max_length=4096, verbose_name='name expression')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_inputs', to='csv_import.csvimportscheme', verbose_name='scheme')),
            ],
            options={
                'verbose_name': 'csv import scheme calculated input',
                'verbose_name_plural': 'csv import scheme calculated inputs',
            },
        ),
    ]
