# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-12 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(default=0)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EntityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=255)),
                ('expression', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
            ],
        ),
        migrations.AddField(
            model_name='entityfield',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_import.Scheme'),
        ),
        migrations.AddField(
            model_name='csvfield',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_import.Scheme'),
        ),
    ]
