# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('users', '0001_initial'),
        ('csv_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimportscheme',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='csvfield',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_fields', to='csv_import.csvimportscheme'),
        ),
        migrations.AddField(
            model_name='csvdataimport',
            name='master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.masteruser'),
        ),
        migrations.AddField(
            model_name='csvdataimport',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_import.csvimportscheme'),
        ),
        migrations.AlterIndexTogether(
            name='entityfield',
            index_together={('scheme', 'order')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='csvimportschemecalculatedinput',
            order_with_respect_to='scheme',
        ),
        migrations.AlterUniqueTogether(
            name='csvimportscheme',
            unique_together={('content_type', 'user_code', 'master_user')},
        ),
        migrations.AlterIndexTogether(
            name='csvfield',
            index_together={('scheme',)},
        ),
    ]
