# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-12 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfield',
            old_name='schema',
            new_name='scheme',
        ),
        migrations.RenameField(
            model_name='entityfield',
            old_name='schema',
            new_name='scheme',
        ),
    ]
