# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0002_auto_20180412_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityfield',
            old_name='attribute',
            new_name='name',
        ),
        migrations.AddField(
            model_name='entityfield',
            name='dynamic_attribute_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entityfield',
            name='system_property_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csvfield',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_fields', to='csv_import.Scheme'),
        ),
        migrations.AlterField(
            model_name='entityfield',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_fields', to='csv_import.Scheme'),
        ),
    ]
