# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-14 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0004_csvdataimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdataimport',
            name='error_handler',
            field=models.CharField(choices=[['break', 'Break'], ['continue', 'Continue']], default='break', max_length=255),
        ),
    ]
