# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-17 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0006_auto_20180414_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdataimport',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_import.Scheme'),
        ),
        migrations.AlterField(
            model_name='entityfield',
            name='dynamic_attribute_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
