# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0007_auto_20180417_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityfield',
            name='dynamic_attribute_id',
            field=models.IntegerField(null=True),
        ),
    ]
