# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0011_auto_20190401_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scheme',
            new_name='CsvImportScheme',
        ),
        migrations.RenameField(
            model_name='csvfield',
            old_name='value',
            new_name='name',
        ),
        migrations.AddField(
            model_name='csvdataimport',
            name='delimiter',
            field=models.CharField(choices=[[',', 'Comma'], [';', 'Semicolon'], ['\t', 'Tab']], default=',', max_length=255),
        ),
        migrations.AddField(
            model_name='csvdataimport',
            name='mode',
            field=models.CharField(choices=[['skip', 'Skip if exists'], ['overwrite', 'Overwrite']], default='skip', max_length=255),
        ),
    ]
