# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-17 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0014_masteruser_user_code_counters'),
        ('csv_import', '0012_auto_20190415_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvimportscheme',
            old_name='name',
            new_name='scheme_name',
        ),
        migrations.AlterUniqueTogether(
            name='csvimportscheme',
            unique_together=set([('content_type', 'scheme_name', 'master_user')]),
        ),
    ]
