# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0015_csvfield_name_expr'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdataimport',
            name='classifier_handler',
            field=models.CharField(choices=[['skip', 'Skip'], ['append', 'Append']], default='skip', max_length=255),
        ),
    ]
