# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-16 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0016_csvdataimport_classifier_handler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityfield',
            options={'ordering': ['order'], 'verbose_name': 'entity field', 'verbose_name_plural': 'entity fields'},
        ),
        migrations.AddField(
            model_name='entityfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterIndexTogether(
            name='entityfield',
            index_together=set([('scheme', 'order')]),
        ),
    ]
