# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0014_masteruser_user_code_counters'),
        ('csv_import', '0017_auto_20190516_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimportscheme',
            name='filter_expr',
            field=models.CharField(default='', max_length=1000, verbose_name='filter expression'),
        ),
        migrations.AlterUniqueTogether(
            name='csvimportscheme',
            unique_together=set([('content_type', 'scheme_name', 'master_user', 'filter_expr')]),
        ),
    ]
