# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0019_auto_20190521_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdataimport',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvdataimport',
            name='task_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
