# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-06 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0020_auto_20190806_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdataimport',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='csvdataimport',
            name='filesize',
        ),
        migrations.RemoveField(
            model_name='csvdataimport',
            name='status',
        ),
    ]
