# Generated by Django 2.2.5 on 2021-02-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('csv_import', '0024_auto_20201103_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimportscheme',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='csvimportscheme',
            name='name',
            field=models.CharField(default='Default', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvimportscheme',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='csvimportscheme',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object',
                                   max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='csvimportscheme',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short name'),
        ),
        migrations.RenameField(
            model_name='csvimportscheme',
            old_name='scheme_name',
            new_name='user_code'
        ),
        migrations.AlterUniqueTogether(
            name='csvimportscheme',
            unique_together={('content_type', 'user_code', 'master_user')},
        ),
    ]
