# Generated by Django 2.2.5 on 2021-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('csv_import', '0025_auto_20210210_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimportscheme',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
    ]
