# Generated by Django 2.2.5 on 2021-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('csv_import', '0027_csvimportschemecalculatedinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimportscheme',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
    ]
