# Generated by Django 2.2.5 on 2022-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('csv_import', '0030_csvimportscheme_spreadsheet_start_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfield',
            name='use_default',
            field=models.BooleanField(default=True, verbose_name='use default'),
        ),
    ]
