# Generated by Django 2.2.5 on 2022-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('csv_import', '0032_csvimportscheme_spreadsheet_active_tab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfield',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvimportscheme',
            name='column_matcher',
            field=models.CharField(choices=[['index', 'Index'], ['name', 'Name']], default='index', max_length=255),
        ),
    ]
