# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name',
                 models.CharField(blank=True, help_text='used if user does not have permissions to view object',
                                  max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('accounts', models.ManyToManyField(blank=True, related_name='portfolios', to='accounts.Account')),
                ('counterparties',
                 models.ManyToManyField(blank=True, related_name='portfolios', to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
                'permissions': (('view_portfolio', 'Can view portfolio'), ('manage_portfolio', 'Can manage portfolio')),
                'verbose_name': 'portfolio',
                'ordering': ['user_code'],
                'verbose_name_plural': 'portfolios',
            },
        ),
    ]
