# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('users', '0001_initial'),
        ('counterparties', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios',
                                    to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='counterparties.Responsible'),
        ),
    ]
