# Generated by Django 4.1.3 on 2022-12-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('transactions', '0001_initial'),
        ('instruments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='complex_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_record_complex_transaction', to='transactions.complextransaction', verbose_name='complex transaction'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument', verbose_name='instrument'),
        )
    ]
