# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioattributetype',
            unique_together=set([('master_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypegroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypeuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifier',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifiergroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifieruserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliogroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliouserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
    ]
