# Generated by Django 4.1.3 on 2022-12-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0002_initial'),
        ('accounts', '0002_initial'),
        ('transactions', '0001_initial'),
        ('instruments', '0003_initial'),
        ('users', '0001_initial'),
        ('currencies', '0003_initial'),
        ('counterparties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_register_records', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio', verbose_name='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='portfolio_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioregister', verbose_name='portfolio register'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='previous_date_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.portfolioregisterrecord', verbose_name='previous date record'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_record_transaction', to='transactions.transaction', verbose_name='transaction'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='transaction_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_record_transaction_class', to='transactions.transactionclass', verbose_name='transaction class'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='valuation_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_record_valuation_currency', to='currencies.currency', verbose_name='valuation currency'),
        ),
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='cash_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_record_cash_currency', to='currencies.currency', verbose_name='cash currency'),
        ),
        migrations.AddField(
            model_name='portfolioregister',
            name='linked_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.instrument', verbose_name='linked instrument'),
        ),
        migrations.AddField(
            model_name='portfolioregister',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_registers', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='portfolioregister',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='portfolios.portfolio', verbose_name='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioregister',
            name='valuation_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency', verbose_name='valuation currency'),
        ),
        migrations.AddField(
            model_name='portfolioregister',
            name='valuation_pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.pricingpolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='portfoliobundle',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_bundles', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='portfoliobundle',
            name='registers',
            field=models.ManyToManyField(blank=True, related_name='portfolio_bundles', related_query_name='bundle', to='portfolios.portfolioregister', verbose_name='registers'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='accounts.account', verbose_name='accounts'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='counterparties',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='counterparties.counterparty', verbose_name='counterparties'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='counterparties.responsible', verbose_name='responsibles'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='transaction_types',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='transactions.transactiontype', verbose_name='transaction types'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioregister',
            unique_together={('master_user', 'user_code')},
        ),
        migrations.AlterIndexTogether(
            name='portfolioregister',
            index_together={('master_user', 'is_deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliobundle',
            unique_together={('master_user', 'user_code')},
        ),
        migrations.AlterIndexTogether(
            name='portfoliobundle',
            index_together={('master_user', 'is_deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('master_user', 'user_code')},
        ),
        migrations.AlterIndexTogether(
            name='portfolio',
            index_together={('master_user', 'is_deleted')},
        ),
    ]
