# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20160425_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioattributetype',
            options={'permissions': [('view_portfolioattributetype', 'Can view portfolio attribute type')], 'verbose_name': 'portfolio attribute type', 'verbose_name_plural': 'portfolio attribute types'},
        ),
    ]
