# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('portfolios', '0002_auto_20161205_1227'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='transaction_types',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='transactions.TransactionType'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterIndexTogether(
            name='portfolio',
            index_together=set([('master_user', 'is_deleted')]),
        ),
    ]
