# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-14 08:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('portfolios', '0004_auto_20170125_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
