# Generated by Django 4.1.3 on 2023-04-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0004_alter_portfolioregisterrecord_cash_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioregisterrecord",
            name="share_price_calculation_type",
            field=models.CharField(
                default="Automatic",
                max_length=255,
                verbose_name="price calculation type",
            ),
        ),
    ]
