# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20160525_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioattributetype',
            name='classifier_root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolios.PortfolioClassifier', verbose_name='classifier'),
        ),
    ]
