# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20160309_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'permissions': [('view_portfolio', 'Can view portfolio')], 'verbose_name': 'portfolio', 'verbose_name_plural': 'portfolios'},
        ),
        migrations.AlterModelOptions(
            name='portfolioclassifier',
            options={'permissions': [('view_portfolioclassifier', 'Can view portfolio classifier')], 'verbose_name': 'portfolio classifier', 'verbose_name_plural': 'portfolio classifiers'},
        ),
    ]
