# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20160525_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioclassifier',
            options={'verbose_name': 'portfolio classifier', 'verbose_name_plural': 'portfolio classifiers'},
        ),
        migrations.RemoveField(
            model_name='portfolioattributetype',
            name='classifier_root',
        ),
        migrations.AddField(
            model_name='portfolioclassifier',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='portfolios.PortfolioAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifier',
            unique_together=set([('attribute_type', 'user_code')]),
        ),
    ]
