# Generated by Django 4.1.3 on 2023-04-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_alter_portfolio_deleted_user_code_and_more'),
        ('portfolios', '0006_portfolioregisterrecord_share_price_calculation_type'),
    ]

    operations = [
    ]
