# Generated by Django 4.1.3 on 2023-06-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_merge_20230426_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioregisterrecord',
            name='previous_date_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.portfolioregisterrecord', verbose_name='previous date record'),
        ),
    ]
