# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0009_auto_20160404_1051'),
        ('accounts', '0011_auto_20160404_1207'),
        ('portfolios', '0009_auto_20160404_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='accounts.Account', verbose_name='accounts'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='counterparties',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='counterparties.Counterparty', verbose_name='counterparties'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='counterparties.Responsible', verbose_name='responsibles'),
        ),
    ]
