# Generated by Django 4.2.3 on 2023-08-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_alter_portfoliobundle_index_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliobundle',
            name='deleted_user_code',
        ),
        migrations.RemoveField(
            model_name='portfoliobundle',
            name='is_deleted',
        ),
    ]
