# Generated by Django 4.2.3 on 2023-11-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_member_status'),
        ('portfolios', '0010_remove_portfoliobundle_deleted_user_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliobundle',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioregister',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner'),
            preserve_default=False,
        ),
    ]
