# Generated by Django 4.2.3 on 2023-11-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_portfolio_owner_portfoliobundle_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioregisterrecord',
            name='nav_valuation_currency',
            field=models.FloatField(default=0.0, verbose_name='nav valuation currency'),
        ),
    ]
