# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_portfolioattr_portfolioattrvalue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioattrvalue',
            unique_together=set([('portfolio', 'attr')]),
        ),
    ]
