# Generated by Django 2.2.5 on 2021-07-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0040_auto_20210409_1154'),
        ('instruments', '0055_pricehistory_nav'),
        ('currencies', '0017_auto_20210526_0911'),
        ('portfolios', '0012_auto_20210526_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name',
                 models.CharField(blank=True, help_text='used if user does not have permissions to view object',
                                  max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_user_code',
                 models.CharField(blank=True, max_length=25, null=True, verbose_name='deleted user code')),
                ('linked_instrument',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument',
                                   verbose_name='linked instrument')),
                ('master_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_registers',
                                   to='users.MasterUser', verbose_name='master user')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio',
                                                verbose_name='portfolio')),
                ('valuation_currency',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.Currency',
                                   verbose_name='valuation currency')),
                ('valuation_pricing_policy',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='instruments.PricingPolicy', verbose_name='pricing policy')),
            ],
            options={
                'verbose_name': 'portfolio register',
                'verbose_name_plural': 'portfolio registers',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
                'index_together': {('master_user', 'is_deleted')},
            },
        ),
    ]
