# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_auto_20160405_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='classifiers',
        ),
    ]
