# Generated by Django 2.2.5 on 2021-07-22 16:07

import django.db.models.deletion
from django.db import migrations, models

import poms.common.utils


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0056_instrument_has_linked_with_portfolio'),
        ('users', '0040_auto_20210409_1154'),
        ('transactions', '0081_auto_20210526_0911'),
        ('currencies', '0017_auto_20210526_0911'),
        ('portfolios', '0013_portfolioregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioRegisterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.PositiveSmallIntegerField(default=0, verbose_name='transaction type')),
                ('transaction_code', models.IntegerField(default=0, verbose_name='transaction code')),
                ('transaction_date', models.DateField(db_index=True, default=poms.common.utils.date_now, editable=False,
                                                      verbose_name='transaction date')),
                ('cash_amount', models.FloatField(default=0.0, help_text='Cash amount', verbose_name='cash amount')),
                ('fx_rate', models.FloatField(default=0.0, verbose_name='fx rate')),
                ('cash_amount_valuation_currency',
                 models.FloatField(default=0.0, help_text='Cash amount valuation currency',
                                   verbose_name='cash amount valuation currency')),
                ('nav_previous_day_valuation_currency',
                 models.FloatField(default=0.0, verbose_name='nav previous day valuation currency')),
                ('n_shares_previous_day', models.FloatField(default=0.0, verbose_name='n shares previous day')),
                ('n_shares_added', models.FloatField(default=0.0, verbose_name='n shares added')),
                ('dealing_price_valuation_currency',
                 models.FloatField(default=0.0, help_text='Dealing price valuation currency',
                                   verbose_name='dealing price valuation currency')),
                ('n_shares_end_of_the_day', models.FloatField(default=0.0, verbose_name='n shares end of the day')),
                ('cash_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='register_record_cash_currency',
                                                    to='currencies.Currency', verbose_name='cash currency')),
                ('complex_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          related_name='register_record_complex_transaction',
                                                          to='transactions.ComplexTransaction',
                                                          verbose_name='complex transaction')),
                ('instrument',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument',
                                   verbose_name='instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='portfolio_register_records', to='users.MasterUser',
                                                  verbose_name='master user')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio',
                                                verbose_name='portfolio')),
                ('portfolio_register',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.PortfolioRegister',
                                   verbose_name='portfolio register')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='register_record_transaction',
                                                  to='transactions.Transaction', verbose_name='transaction')),
                ('valuation_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                         related_name='register_record_valuation_currency',
                                                         to='currencies.Currency', verbose_name='valuation currency')),
            ],
            options={
                'verbose_name': 'portfolio register record',
                'verbose_name_plural': 'portfolio registers record',
            },
        ),
    ]
