# Generated by Django 4.2.3 on 2023-11-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_portfoliohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if any', null=True, verbose_name='error_message'),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='status',
            field=models.CharField(choices=[('ok', 'Ok'), ('error', 'error')], default='ok', max_length=255, verbose_name='status'),
        ),
    ]
