# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_auto_20161003_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioattributetypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypegroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypegroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypegroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='portfoliogroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfoliogroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='portfoliogroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='portfoliogroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='portfoliouserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfoliouserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='portfoliouserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='portfoliouserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='PortfolioAttributeTypeGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='PortfolioAttributeTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='PortfolioGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='PortfolioUserObjectPermission',
        ),
    ]
