# Generated by Django 4.2.3 on 2023-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_portfoliohistory_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='weighted_duration',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='weighted_duration'),
        ),
    ]
