# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 14:20
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_auto_20160404_1051'),
        ('portfolios', '0014_auto_20160406_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='strategies',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='portfolios', to='strategies.Strategy', verbose_name='strategies'),
        ),
    ]
