# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_auto_20161017_0828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioattribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfolioattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='portfolioattribute',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='portfolioattribute',
            name='content_object',
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfolioattributetype',
            name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypeoption',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypeoption',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='portfolioattributetypeoption',
            name='member',
        ),
        migrations.RemoveField(
            model_name='portfolioclassifier',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='portfolioclassifier',
            name='parent',
        ),
        migrations.DeleteModel(
            name='PortfolioAttribute',
        ),
        migrations.DeleteModel(
            name='PortfolioAttributeType',
        ),
        migrations.DeleteModel(
            name='PortfolioAttributeTypeOption',
        ),
        migrations.DeleteModel(
            name='PortfolioClassifier',
        ),
    ]
