# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_portfolio_strategies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliotag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfoliotag',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='counterparties',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='responsibles',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='strategies',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PortfolioTag',
        ),
    ]
