# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0016_auto_20160407_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioattr',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='portfolioattr',
            name='scheme',
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattrvalue',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portfolioattrvalue',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='portfolioattrvalue',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='portfolioattrvalue',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioAttr',
        ),
        migrations.DeleteModel(
            name='PortfolioAttrValue',
        ),
    ]
