# Generated by Django 2.2.5 on 2022-06-13 10:16

from django.db import migrations, models

import poms.common.utils


class Migration(migrations.Migration):
    dependencies = [
        ('portfolios', '0017_auto_20220314_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioregisterrecord',
            name='transaction_date',
            field=models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='transaction date'),
        ),
    ]
