# Generated by Django 4.2.3 on 2023-12-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_portfolioregisterrecord_nav_previous_business_day_valuation_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioregisterrecord',
            old_name='nav_previous_day_valuation_currency',
            new_name='nav_previous_register_record_day_valuation_currency',
        ),
    ]
