# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0018_auto_20160411_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioAttributeTypeGroupObjectPermissionBase',
            new_name='PortfolioAttributeTypeGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='PortfolioAttributeTypeUserObjectPermissionBase',
            new_name='PortfolioAttributeTypeUserObjectPermission',
        ),
        migrations.RenameModel(
            old_name='PortfolioGroupObjectPermissionBase',
            new_name='PortfolioClassifierGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='PortfolioClassifierUserObjectPermissionBase',
            new_name='PortfolioClassifierUserObjectPermission',
        ),
        migrations.RenameModel(
            old_name='PortfolioClassifierGroupObjectPermissionBase',
            new_name='PortfolioGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='PortfolioUserObjectPermissionBase',
            new_name='PortfolioUserObjectPermission',
        ),
        migrations.AlterField(
            model_name='portfolioclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='portfolios.PortfolioClassifier'),
        ),
        migrations.AlterField(
            model_name='portfoliogroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='portfolios.Portfolio'),
        ),
    ]
