# Generated by Django 2.2.5 on 2022-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolios', '0018_auto_20220613_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='default_price',
            field=models.FloatField(default=100.0, verbose_name='default price'),
        ),
    ]
