# Generated by Django 4.2.3 on 2024-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0019_alter_portfolioregisterrecord_nav_previous_register_record_day_valuation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='first_cash_flow_date',
            field=models.DateField(null=True, verbose_name='first cash flow date'),
        ),
    ]
