# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0020_auto_20160411_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioAccountAttributeTypeOption',
            new_name='PortfolioAttributeTypeOption',
        ),
        migrations.AlterModelOptions(
            name='portfolioattribute',
            options={'verbose_name': 'portfolio attribute', 'verbose_name_plural': 'portfolio attributes'},
        ),
        migrations.AlterModelOptions(
            name='portfolioattributetype',
            options={'verbose_name': 'portfolio attribute type', 'verbose_name_plural': 'portfolio attribute types'},
        ),
        migrations.AlterModelOptions(
            name='portfolioattributetypegroupobjectpermission',
            options={'verbose_name': 'portfolio attribute types - group permission', 'verbose_name_plural': 'portfolio attribute types - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='portfolioattributetypeoption',
            options={'verbose_name': 'portfolio attribute types - option', 'verbose_name_plural': 'portfolio attribute types - options'},
        ),
        migrations.AlterModelOptions(
            name='portfolioattributetypeuserobjectpermission',
            options={'verbose_name': 'portfolio attribute types - user permission', 'verbose_name_plural': 'portfolio attribute types - user permissions'},
        ),
        migrations.AlterModelOptions(
            name='portfolioclassifiergroupobjectpermission',
            options={'verbose_name': 'portfolio classifiers - group permission', 'verbose_name_plural': 'portfolio classifiers - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='portfolioclassifieruserobjectpermission',
            options={'verbose_name': 'portfolio classifiers - user permission', 'verbose_name_plural': 'portfolio classifiers - user permissions'},
        ),
        migrations.AlterModelOptions(
            name='portfoliogroupobjectpermission',
            options={'verbose_name': 'portfolio - group permission', 'verbose_name_plural': 'portfolio - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='portfoliouserobjectpermission',
            options={'verbose_name': 'portfolio - user permission', 'verbose_name_plural': 'portfolio - user permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetype',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypeoption',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifiergroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioclassifieruserobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliogroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliouserobjectpermission',
            unique_together=set([]),
        ),
    ]
