# Generated by Django 2.2.5 on 2022-06-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolios', '0021_portfolioregisterrecord_previous_date_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioregisterrecord',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='register_record_transaction_type', to='transactions.TransactionType',
                                    verbose_name='transaction type'),
        ),
    ]
