# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0021_auto_20160411_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliogroupobjectpermission',
            options={'verbose_name': 'portfolios - group permission', 'verbose_name_plural': 'portfolios - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='portfoliouserobjectpermission',
            options={'verbose_name': 'portfolios - user permission', 'verbose_name_plural': 'portfolios - user permissions'},
        ),
    ]
