# Generated by Django 4.2.3 on 2024-02-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0023_portfolioreconcilegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioreconcilegroup',
            name='deleted_user_code',
            field=models.CharField(blank=True, help_text='Stores original user_code of object. Deleted objects has null user_code which makes it available again.', max_length=255, null=True, verbose_name='deleted user code'),
        ),
        migrations.AddField(
            model_name='portfolioreconcilegroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark object as deleted. Does not actually delete the object.', verbose_name='is deleted'),
        ),
    ]
