# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0023_auto_20160412_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='portfolioattribute',
            name='attributebase_ptr',
        ),
        migrations.RemoveField(
            model_name='portfolioattribute',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='portfolioattribute',
            name='content_object',
        ),
        migrations.DeleteModel(
            name='PortfolioAttribute',
        ),
    ]
