# Generated by Django 4.2.3 on 2024-02-03 03:24

from django.db import migrations, models
import django.db.models.deletion
import poms.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0012_alter_celeryworker_status_and_more'),
        ('users', '0008_alter_member_status'),
        ('portfolios', '0024_portfolioreconcilegroup_deleted_user_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioReconcileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('user_code', models.CharField(help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, unique=True, verbose_name='user code')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('error_message', models.TextField(blank=True, help_text='Error message if any', null=True, verbose_name='error_message')),
                ('verbose_result', models.TextField(blank=True, null=True, verbose_name='verbose result')),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'error')], default='ok', max_length=255, verbose_name='status')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='celery_tasks.celerytask', verbose_name='linked task')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
                ('portfolio_reconcile_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioreconcilegroup', verbose_name='portfolio reconcile group')),
            ],
            options={
                'unique_together': {('master_user', 'user_code')},
            },
        ),
    ]
