# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0024_auto_20160413_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='portfolios.PortfolioAttributeType')),
                ('classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.PortfolioClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio')),
            ],
            options={
                'verbose_name_plural': 'portfolio attributes',
                'verbose_name': 'portfolio attribute',
            },
        ),
    ]
