# Generated by Django 4.0.6 on 2022-07-06 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('portfolios', '0025_auto_20220701_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='attrs',
        ),
    ]
