# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0025_portfolioattribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioattribute',
            unique_together=set([('content_object', 'attribute_type')]),
        ),
    ]
