# Generated by Django 4.2.3 on 2024-02-04 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_reports', '0002_initial'),
        ('portfolios', '0025_portfolioreconcilehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioreconcilehistory',
            name='file_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_reports.filereport', verbose_name='file report'),
        ),
    ]
