# Generated by Django 4.2.3 on 2024-03-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0026_portfolioreconcilehistory_file_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='gav',
            field=models.FloatField(blank=True, default=0.0, help_text='Gross Asset Value', null=True, verbose_name='gav'),
        ),
    ]
