# Generated by Django 4.0.6 on 2022-09-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0043_ecosystemdefault_currency_pricing_scheme_and_more'),
        ('portfolios', '0027_alter_portfolioregister_linked_instrument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='short name')),
                ('public_name',
                 models.CharField(blank=True, help_text='used if user does not have permissions to view object',
                                  max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_user_code',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted user code')),
                ('groups',
                 models.ManyToManyField(blank=True, related_name='portfolio_bundles', related_query_name='bundle',
                                        to='portfolios.portfolioregister', verbose_name='registers')),
                ('master_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_bundles',
                                   to='users.masteruser', verbose_name='master user')),
            ],
            options={
                'verbose_name': 'portfolio bundle',
                'verbose_name_plural': 'portfolio bundles',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
                'index_together': {('master_user', 'is_deleted')},
            },
        ),
    ]
