# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0027_remove_portfolioattributetypeoption_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='portfolios.PortfolioAttributeType'),
        ),
        migrations.AlterField(
            model_name='portfolioattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolios.PortfolioClassifier'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolios.PortfolioClassifier'),
        ),
    ]
