# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0028_portfolio_actual_at_portfolio_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='portfoliobundle',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfoliobundle',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='portfolioreconcilegroup',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfolioreconcilegroup',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='portfolioreconcilehistory',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfolioreconcilehistory',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='portfolioregister',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfolioregister',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='portfolioregisterrecord',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfolioregisterrecord',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='portfoliotype',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='portfoliotype',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
