# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0028_auto_20160419_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='portfolios.PortfolioAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='portfolioattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolios.PortfolioClassifier', verbose_name='classifier'),
        ),
        migrations.AlterField(
            model_name='portfolioattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='portfolioattribute',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='value (Date)'),
        ),
        migrations.AlterField(
            model_name='portfolioattribute',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value (Float)'),
        ),
        migrations.AlterField(
            model_name='portfolioattribute',
            name='value_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='value (String)'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolios.PortfolioClassifier', verbose_name='classifier (root)'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetype',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10, verbose_name='value type'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='portfolios.PortfolioAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypeoption',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_options', to='portfolios.PortfolioAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypeoption',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_attribute_type_options', to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='portfolios.PortfolioAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='portfolioattributetypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='portfolioclassifier',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portfolios.PortfolioClassifier', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='portfolioclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='portfolios.PortfolioClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='portfolioclassifiergroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='portfolioclassifiergroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='portfolioclassifieruserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='portfolios.PortfolioClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='portfolioclassifieruserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='portfolioclassifieruserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='portfoliogroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='portfolios.Portfolio', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='portfoliogroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='portfoliogroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='portfoliouserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='portfolios.Portfolio', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='portfoliouserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='portfoliouserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
    ]
