# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0029_auto_20160420_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='portfolios.Portfolio', verbose_name='content object'),
        ),
    ]
