# Generated by Django 4.2.16 on 2024-10-14 16:18

import django.contrib.postgres.fields
from django.db import migrations, models
import poms.portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolios",
            "0029_remove_portfolio_created_remove_portfolio_modified_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="resource_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                default=poms.portfolios.models.default_list,
                size=None,
                verbose_name="list of resource groups user_codes, to which portfolio belongs",
            ),
        ),
    ]
