# Generated by Django 4.2.22 on 2025-07-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0012_currencyhistory_is_temporary_fx_rate'),
        ('instruments', '0032_alter_accrualevent_options_and_more'),
        ('portfolios', '0032_portfolioreconcilegroup_last_calculated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='register_currency',
            field=models.ForeignKey(help_text='Configure Currency of Default Portfolio Register', null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency', verbose_name='register currency'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='register_instrument_type',
            field=models.ForeignKey(help_text='Configure Instrument Type of Default Portfolio Register', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.instrumenttype', verbose_name='register instrument type'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='register_pricing_policy',
            field=models.ForeignKey(help_text='Configure Pricing Policy of Default Portfolio Register', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.pricingpolicy', verbose_name='register pricing policy'),
        ),
    ]
