EXPECTED_RESPONSE_DATA = {
    "id": 1,
    "master_user": 1,
    "currency": 2,
    "account_type": 1,
    "account": 1,
    "counterparty_group": 1,
    "counterparty": 1,
    "responsible_group": 1,
    "responsible": 1,
    "instrument_type": 1,
    "instrument": 1,
    "portfolio": 1,
    "strategy1_group": 1,
    "strategy1_subgroup": 1,
    "strategy1": 1,
    "strategy2_group": 1,
    "strategy2_subgroup": 1,
    "strategy2": 1,
    "strategy3_group": 1,
    "strategy3_subgroup": 1,
    "strategy3": 1,
    "mismatch_portfolio": 1,
    "mismatch_account": 1,
    "pricing_policy": 1,
    "transaction_type": 1,
    "instrument_class": 6,
    "accrual_calculation_model": 100,
    "pricing_condition": 1,
    "payment_size_detail": 7,
    "periodicity": 13,
    "accrual_calculation_model_object": {
        "id": 100,
        "user_code": "DAY_COUNT_SIMPLE",
        "name": "Simple",
    },
    "pricing_condition_object": {
        "id": 1,
        "user_code": "NO_VALUATION",
        "name": "Don't Run Valuation",
    },
    "payment_size_detail_object": {"id": 7, "user_code": "-", "name": "Default"},
    "periodicity_object": {"id": 13, "user_code": "-", "name": "-"},
    "instrument_class_object": {"id": 6, "user_code": "-", "name": "Default"},
    "currency_object": {
        "id": 2,
        "user_code": "USD",
        "name": "US Dollar (USD)",
        "short_name": "USD",
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "currencies.currency",
            "app_label": "currencies",
            "model_name": "currency",
            "space_code": "space00000",
        },
    },
    "account_type_object": {
        "id": 1,
        "user_code": "local.poms.space00000:_",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "accounts.accounttype",
            "app_label": "accounts",
            "model_name": "accounttype",
            "space_code": "space00000",
        },
    },
    "account_object": {
        "id": 1,
        "type": 1,
        "type_object": {
            "id": 1,
            "user_code": "local.poms.space00000:_",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "accounts.accounttype",
                "app_label": "accounts",
                "model_name": "accounttype",
                "space_code": "space00000",
            },
        },
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "accounts.account",
            "app_label": "accounts",
            "model_name": "account",
            "space_code": "space00000",
        },
    },
    "counterparty_group_object": {
        "id": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
    },
    "counterparty_object": {
        "id": 1,
        "group": 1,
        "group_object": {
            "id": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
        },
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "counterparties.counterparty",
            "app_label": "counterparties",
            "model_name": "counterparty",
            "space_code": "space00000",
        },
    },
    "responsible_group_object": {
        "id": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
    },
    "responsible_object": {
        "id": 1,
        "group": 1,
        "group_object": {
            "id": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
        },
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
    },
    "instrument_object": {
        "id": 1,
        "instrument_type": 1,
        "instrument_type_object": {
            "id": 1,
            "instrument_class": 1,
            "instrument_class_object": {
                "id": 1,
                "user_code": "GENERAL",
                "name": "General Class",
                "description": "General Class",
            },
            "user_code": "local.poms.space00000:_",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "instrument_form_layouts": None,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "instruments.instrumenttype",
                "app_label": "instruments",
                "model_name": "instrumenttype",
                "space_code": "space00000",
            },
        },
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_active": True,
        "is_deleted": False,
        "has_linked_with_portfolio": False,
        "user_text_1": None,
        "user_text_2": None,
        "user_text_3": None,
        "maturity_date": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "instruments.instrument",
            "app_label": "instruments",
            "model_name": "instrument",
            "space_code": "space00000",
        },
    },
    "instrument_type_object": {
        "id": 1,
        "instrument_class": 1,
        "instrument_class_object": {
            "id": 1,
            "user_code": "GENERAL",
            "name": "General Class",
            "description": "General Class",
        },
        "user_code": "local.poms.space00000:_",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "instrument_form_layouts": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "instruments.instrumenttype",
            "app_label": "instruments",
            "model_name": "instrumenttype",
            "space_code": "space00000",
        },
    },
    "portfolio_object": {
        "id": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "portfolios.portfolio",
            "app_label": "portfolios",
            "model_name": "portfolio",
            "space_code": "space00000",
        },
    },
    "strategy1_group_object": {
        "id": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy1group",
            "app_label": "strategies",
            "model_name": "strategy1group",
            "space_code": "space00000",
        },
    },
    "strategy1_subgroup_object": {
        "id": 1,
        "group": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "is_deleted": False,
        "notes": None,
        "group_object": {
            "id": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "notes": None,
            "is_deleted": False,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "strategies.strategy1group",
                "app_label": "strategies",
                "model_name": "strategy1group",
                "space_code": "space00000",
            },
        },
        "is_enabled": True,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy1subgroup",
            "app_label": "strategies",
            "model_name": "strategy1subgroup",
            "space_code": "space00000",
        },
    },
    "strategy1_object": {
        "id": 1,
        "subgroup": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "subgroup_object": {
            "id": 1,
            "group": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "is_deleted": False,
            "notes": None,
            "group_object": {
                "id": 1,
                "user_code": "-",
                "name": "-",
                "short_name": "-",
                "public_name": None,
                "notes": None,
                "is_deleted": False,
                "deleted_user_code": None,
                "owner": {
                    "id": 1,
                    "username": "finmars_bot",
                    "first_name": "",
                    "last_name": "",
                    "display_name": "finmars_bot",
                    "is_owner": False,
                    "is_admin": True,
                    "user": 1,
                },
                "meta": {
                    "content_type": "strategies.strategy1group",
                    "app_label": "strategies",
                    "model_name": "strategy1group",
                    "space_code": "space00000",
                },
            },
            "is_enabled": True,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "strategies.strategy1subgroup",
                "app_label": "strategies",
                "model_name": "strategy1subgroup",
                "space_code": "space00000",
            },
        },
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy1",
            "app_label": "strategies",
            "model_name": "strategy1",
            "space_code": "space00000",
        },
    },
    "strategy2_group_object": {
        "id": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy2group",
            "app_label": "strategies",
            "model_name": "strategy2group",
            "space_code": "space00000",
        },
    },
    "strategy2_subgroup_object": {
        "id": 1,
        "group": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "is_deleted": False,
        "notes": None,
        "group_object": {
            "id": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "notes": None,
            "is_deleted": False,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "strategies.strategy2group",
                "app_label": "strategies",
                "model_name": "strategy2group",
                "space_code": "space00000",
            },
        },
        "is_enabled": True,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy2subgroup",
            "app_label": "strategies",
            "model_name": "strategy2subgroup",
            "space_code": "space00000",
        },
    },
    "strategy2_object": {
        "id": 1,
        "subgroup": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "subgroup_object": {
            "id": 1,
            "group": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "is_deleted": False,
            "notes": None,
            "group_object": {
                "id": 1,
                "user_code": "-",
                "name": "-",
                "short_name": "-",
                "public_name": None,
                "notes": None,
                "is_deleted": False,
                "deleted_user_code": None,
                "owner": {
                    "id": 1,
                    "username": "finmars_bot",
                    "first_name": "",
                    "last_name": "",
                    "display_name": "finmars_bot",
                    "is_owner": False,
                    "is_admin": True,
                    "user": 1,
                },
                "meta": {
                    "content_type": "strategies.strategy2group",
                    "app_label": "strategies",
                    "model_name": "strategy2group",
                    "space_code": "space00000",
                },
            },
            "is_enabled": True,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "strategies.strategy2subgroup",
                "app_label": "strategies",
                "model_name": "strategy2subgroup",
                "space_code": "space00000",
            },
        },
        "attributes": [],
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy2",
            "app_label": "strategies",
            "model_name": "strategy2",
            "space_code": "space00000",
        },
    },
    "strategy3_group_object": {
        "id": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy3group",
            "app_label": "strategies",
            "model_name": "strategy3group",
            "space_code": "space00000",
        },
    },
    "strategy3_subgroup_object": {
        "id": 1,
        "group": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "is_deleted": False,
        "notes": None,
        "group_object": {
            "id": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "notes": None,
            "is_deleted": False,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "strategies.strategy3group",
                "app_label": "strategies",
                "model_name": "strategy3group",
                "space_code": "space00000",
            },
        },
        "is_enabled": True,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy3subgroup",
            "app_label": "strategies",
            "model_name": "strategy3subgroup",
            "space_code": "space00000",
        },
    },
    "strategy3_object": {
        "id": 1,
        "subgroup": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "subgroup_object": {
            "id": 1,
            "group": 1,
            "user_code": "-",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "is_deleted": False,
            "notes": None,
            "group_object": {
                "id": 1,
                "user_code": "-",
                "name": "-",
                "short_name": "-",
                "public_name": None,
                "notes": None,
                "is_deleted": False,
                "deleted_user_code": None,
                "owner": {
                    "id": 1,
                    "username": "finmars_bot",
                    "first_name": "",
                    "last_name": "",
                    "display_name": "finmars_bot",
                    "is_owner": False,
                    "is_admin": True,
                    "user": 1,
                },
                "meta": {
                    "content_type": "strategies.strategy3group",
                    "app_label": "strategies",
                    "model_name": "strategy3group",
                    "space_code": "space00000",
                },
            },
            "is_enabled": True,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "strategies.strategy3subgroup",
                "app_label": "strategies",
                "model_name": "strategy3subgroup",
                "space_code": "space00000",
            },
        },
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "strategies.strategy3",
            "app_label": "strategies",
            "model_name": "strategy3",
            "space_code": "space00000",
        },
    },
    "pricing_policy_object": {
        "id": 1,
        "user_code": "local.poms.space00000:_",
        "name": "-",
        "short_name": "-",
        "notes": None,
        "expr": "(ask+bid)/2",
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "instruments.pricingpolicy",
            "app_label": "instruments",
            "model_name": "pricingpolicy",
            "space_code": "space00000",
        },
    },
    "transaction_type_object": {
        "id": 1,
        "group": None,
        "user_code": "local.poms.space00000:_",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "notes": None,
        "is_valid_for_all_portfolios": True,
        "is_valid_for_all_instruments": True,
        "is_deleted": False,
        "transaction_unique_code_expr": "",
        "transaction_unique_code_options": 2,
        "user_text_1": "",
        "user_text_2": "",
        "user_text_3": "",
        "user_text_4": "",
        "user_text_5": "",
        "user_text_6": "",
        "user_text_7": "",
        "user_text_8": "",
        "user_text_9": "",
        "user_text_10": "",
        "user_text_11": "",
        "user_text_12": "",
        "user_text_13": "",
        "user_text_14": "",
        "user_text_15": "",
        "user_text_16": "",
        "user_text_17": "",
        "user_text_18": "",
        "user_text_19": "",
        "user_text_20": "",
        "user_text_21": "",
        "user_text_22": "",
        "user_text_23": "",
        "user_text_24": "",
        "user_text_25": "",
        "user_text_26": "",
        "user_text_27": "",
        "user_text_28": "",
        "user_text_29": "",
        "user_text_30": "",
        "user_number_1": "",
        "user_number_2": "",
        "user_number_3": "",
        "user_number_4": "",
        "user_number_5": "",
        "user_number_6": "",
        "user_number_7": "",
        "user_number_8": "",
        "user_number_9": "",
        "user_number_10": "",
        "user_number_11": "",
        "user_number_12": "",
        "user_number_13": "",
        "user_number_14": "",
        "user_number_15": "",
        "user_number_16": "",
        "user_number_17": "",
        "user_number_18": "",
        "user_number_19": "",
        "user_number_20": "",
        "user_date_1": "",
        "user_date_2": "",
        "user_date_3": "",
        "user_date_4": "",
        "user_date_5": "",
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "transactions.transactiontype",
            "app_label": "transactions",
            "model_name": "transactiontype",
            "space_code": "space00000",
        },
        "group_object": None,
    },
    "mismatch_portfolio_object": {
        "id": 1,
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "portfolios.portfolio",
            "app_label": "portfolios",
            "model_name": "portfolio",
            "space_code": "space00000",
        },
    },
    "mismatch_account_object": {
        "id": 1,
        "type": 1,
        "type_object": {
            "id": 1,
            "user_code": "local.poms.space00000:_",
            "name": "-",
            "short_name": "-",
            "public_name": None,
            "deleted_user_code": None,
            "owner": {
                "id": 1,
                "username": "finmars_bot",
                "first_name": "",
                "last_name": "",
                "display_name": "finmars_bot",
                "is_owner": False,
                "is_admin": True,
                "user": 1,
            },
            "meta": {
                "content_type": "accounts.accounttype",
                "app_label": "accounts",
                "model_name": "accounttype",
                "space_code": "space00000",
            },
        },
        "user_code": "-",
        "name": "-",
        "short_name": "-",
        "public_name": None,
        "deleted_user_code": None,
        "owner": {
            "id": 1,
            "username": "finmars_bot",
            "first_name": "",
            "last_name": "",
            "display_name": "finmars_bot",
            "is_owner": False,
            "is_admin": True,
            "user": 1,
        },
        "meta": {
            "content_type": "accounts.account",
            "app_label": "accounts",
            "model_name": "account",
            "space_code": "space00000",
        },
    },
}
