# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-create_date']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='unread',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
