# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 09:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0004_auto_20170428_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='notifications', to='users.Member', verbose_name='recipient member'),
        ),
    ]
