# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160326_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_object_repr',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='actor_repr',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='emailed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_repr',
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
