# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20160328_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(10, 'debug'), (20, 'info'), (25, 'success'), (30, 'warning'), (40, 'error')], default=20),
        ),
    ]
