# Generated by Django 4.2.8 on 2024-10-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_member_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, null=True, verbose_name='user code')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Mark object as deleted. Does not actually delete the object.', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('deleted_user_code', models.CharField(blank=True, help_text='Stores original user_code of object. Deleted objects has null user_code which makes it available again.', max_length=255, null=True, verbose_name='deleted user code')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clietn', to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'clietn',
                'verbose_name_plural': 'clietns',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
                'index_together': {('master_user', 'is_deleted')},
            },
        ),
    ]
