# Generated by Django 4.2.8 on 2024-10-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['user_code'], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterIndexTogether(
            name='client',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='client',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='deleted_user_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_deleted',
        ),
    ]
