# Generated by Django 4.2.16 on 2024-11-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_member_deleted_at'),
        ('clients', '0003_alter_client_master_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, verbose_name='user code')),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_secrets', to='clients.client', verbose_name='client')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_secrets', to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'client secret',
                'verbose_name_plural': 'client secrets',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
    ]
