# Generated by Django 4.2.16 on 2024-12-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_email_client_first_name_client_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsecret',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientsecret',
            name='path_to_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
