# Generated by Django 4.2.16 on 2024-12-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_email_client_first_name_client_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of client', max_length=255, null=True),
        ),
    ]
