# Generated by Django 4.2.16 on 2024-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientsecret_portfolio_clientsecret_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsecret',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientsecret',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
