# Generated by Django 4.2.20 on 2025-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_email_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the email address', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the first name', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the last name', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the telephone number', max_length=64, null=True),
        ),
    ]
