# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csv_import', '0012_auto_20190415_2058'),
        ('integrations', '0019_auto_20190405_1000'),
        ('users', '0014_masteruser_user_code_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComplexImportScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexImportSchemeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_notes', models.TextField(default='', verbose_name='action notes')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'action',
                'ordering': ['order'],
                'verbose_name_plural': 'actions',
            },
        ),
        migrations.CreateModel(
            name='ComplexImportSchemeActionCsvImport',
            fields=[
                ('compleximportschemeaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complex_import.ComplexImportSchemeAction')),
                ('mode', models.CharField(choices=[['skip', 'Skip if exists'], ['overwrite', 'Overwrite']], default='', max_length=255)),
                ('delimiter', models.CharField(choices=[[',', 'Comma'], [';', 'Semicolon'], ['\t', 'Tab']], default=',', max_length=255)),
                ('error_handler', models.CharField(choices=[['break', 'Break'], ['continue', 'Continue']], default='break', max_length=255)),
                ('csv_import_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='csv_import.CsvImportScheme', verbose_name='csv import scheme')),
            ],
            bases=('complex_import.compleximportschemeaction',),
        ),
        migrations.CreateModel(
            name='ComplexImportSchemeActionTransactionImport',
            fields=[
                ('compleximportschemeaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complex_import.ComplexImportSchemeAction')),
                ('delimiter', models.CharField(choices=[[',', 'Comma'], [';', 'Semicolon'], ['\t', 'Tab']], default=',', max_length=255)),
                ('error_handler', models.CharField(choices=[['break', 'Break'], ['continue', 'Continue']], default='break', max_length=255)),
                ('complex_transaction_import_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.ComplexTransactionImportScheme', verbose_name='complex transaction import scheme')),
            ],
            bases=('complex_import.compleximportschemeaction',),
        ),
        migrations.AddField(
            model_name='compleximportschemeaction',
            name='complex_import_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='complex_import.ComplexImportScheme'),
        ),
        migrations.AddField(
            model_name='compleximport',
            name='complex_import_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex_import.ComplexImportScheme'),
        ),
        migrations.AddField(
            model_name='compleximport',
            name='master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
        migrations.AlterIndexTogether(
            name='compleximportschemeaction',
            index_together=set([('complex_import_scheme', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='compleximportscheme',
            unique_together=set([('name', 'master_user')]),
        ),
    ]
