# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-17 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_masteruser_user_code_counters'),
        ('complex_import', '0002_auto_20190416_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compleximportscheme',
            old_name='name',
            new_name='scheme_name',
        ),
        migrations.AlterUniqueTogether(
            name='compleximportscheme',
            unique_together=set([('scheme_name', 'master_user')]),
        ),
    ]
