# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_import', '0003_auto_20190417_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compleximportschemeactioncsvimport',
            name='delimiter',
        ),
        migrations.RemoveField(
            model_name='compleximportschemeactiontransactionimport',
            name='delimiter',
        ),
        migrations.AddField(
            model_name='compleximportschemeactioncsvimport',
            name='missing_data_handler',
            field=models.CharField(choices=[['throw_error', 'Treat as Error'], ['set_defaults', 'Replace with Default Value']], default='throw_error', max_length=255),
        ),
        migrations.AddField(
            model_name='compleximportschemeactiontransactionimport',
            name='missing_data_handler',
            field=models.CharField(choices=[['throw_error', 'Treat as Error'], ['set_defaults', 'Replace with Default Value']], default='throw_error', max_length=255),
        ),
    ]
