# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_import', '0004_auto_20190426_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='compleximportschemeactioncsvimport',
            name='classifier_handler',
            field=models.CharField(choices=[['skip', 'Skip'], ['append', 'Append']], default='skip', max_length=255),
        ),
    ]
