# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex_import', '0006_auto_20190511_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compleximportschemeaction',
            name='complex_import_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='complex_import.ComplexImportScheme'),
        ),
    ]
