# Generated by Django 2.2.5 on 2020-08-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0033_userprofile_active_master_user'),
        ('integrations', '0040_auto_20200827_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Username with password'), (2, 'SSH username with private key')], db_index=True, default=1, verbose_name='type')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password')),
                ('key', models.TextField(blank=True, null=True, verbose_name='key')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.DataProvider', verbose_name='provider')),
            ],
            options={
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
    ]
