# Generated by Django 2.2.5 on 2020-08-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Username with password'), (2, 'SSH username with private key'), (2, 'Username with password and private key')], db_index=True, default=1, verbose_name='type'),
        ),
    ]
