# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('credentials', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='credentials',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.dataprovider', verbose_name='provider'),
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together={('master_user', 'user_code')},
        ),
    ]
