# Generated by Django 2.2.5 on 2020-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('credentials', '0004_credentials_path_to_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='key',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='path_to_key',
        ),
        migrations.AddField(
            model_name='credentials',
            name='path_to_private_key',
            field=models.TextField(blank=True, default='', verbose_name='Path to private key'),
        ),
        migrations.AddField(
            model_name='credentials',
            name='path_to_public_key',
            field=models.TextField(blank=True, default='', verbose_name='Path to public key'),
        ),
        migrations.AddField(
            model_name='credentials',
            name='private_key',
            field=models.TextField(blank=True, null=True, verbose_name='private key'),
        ),
        migrations.AddField(
            model_name='credentials',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='public key'),
        ),
    ]
