# Generated by Django 2.2.5 on 2020-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatafileprocedure',
            name='price_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='price date from'),
        ),
        migrations.AddField(
            model_name='requestdatafileprocedure',
            name='price_date_from_expr',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='price date from expr'),
        ),
        migrations.AddField(
            model_name='requestdatafileprocedure',
            name='price_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='price date to'),
        ),
        migrations.AddField(
            model_name='requestdatafileprocedure',
            name='price_date_to_expr',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='price date to expr'),
        ),
    ]
