# Generated by Django 4.1.3 on 2023-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_delete_expressionprocedureinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingprocedureinstance',
            name='status',
            field=models.CharField(choices=[('I', 'Init'), ('P', 'Pending'), ('D', 'Done'), ('E', 'Error'), ('C', 'Canceled')], default='I', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='requestdatafileprocedureinstance',
            name='status',
            field=models.CharField(choices=[('I', 'Init'), ('P', 'Pending'), ('D', 'Done'), ('E', 'Error'), ('C', 'Canceled')], default='I', max_length=1, verbose_name='status'),
        ),
    ]
