# Generated by Django 4.1.3 on 2023-04-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0005_alter_pricingprocedureinstance_status_and_more'),
        ('procedures', '0006_alter_expressionprocedure_user_code_and_more'),
    ]

    operations = [
    ]
