# Generated by Django 2.2.5 on 2020-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0008_auto_20200922_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatafileprocedureinstance',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestdatafileprocedureinstance',
            name='action_verbose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestdatafileprocedureinstance',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestdatafileprocedureinstance',
            name='provider_verbose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
