# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0010_expressionprocedure_owner_pricingprocedure_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingparentprocedureinstance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='requestdatafileprocedureinstance',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='expressionprocedure',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='expressionprocedure',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='pricingparentprocedureinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pricingparentprocedureinstance',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='pricingprocedure',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pricingprocedure',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='pricingprocedureinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pricingprocedureinstance',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='requestdatafileprocedure',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requestdatafileprocedure',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='requestdatafileprocedureinstance',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requestdatafileprocedureinstance',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
