# Generated by Django 2.2.5 on 2020-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0010_auto_20201102_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatafileprocedure',
            name='scheme_type',
            field=models.CharField(
                choices=[['transaction_import', 'Transaction Import'], ['simple_Import', 'Simple Import']],
                default='transaction_import', max_length=255),
        ),
    ]
