# Generated by Django 2.2.5 on 2020-11-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0011_requestdatafileprocedure_scheme_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdatafileprocedure',
            name='scheme_type',
            field=models.CharField(
                choices=[['transaction_import', 'Transaction Import'], ['simple_import', 'Simple Import']],
                default='transaction_import', max_length=255),
        ),
    ]
