# Generated by Django 2.2.5 on 2020-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0012_auto_20201103_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatafileprocedure',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
    ]
