# Generated by Django 2.2.5 on 2020-11-25 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0013_requestdatafileprocedure_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdatafileprocedure',
            old_name='price_date_from',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='requestdatafileprocedure',
            old_name='price_date_from_expr',
            new_name='date_from_expr',
        ),
        migrations.RenameField(
            model_name='requestdatafileprocedure',
            old_name='price_date_to',
            new_name='date_to',
        ),
        migrations.RenameField(
            model_name='requestdatafileprocedure',
            old_name='price_date_to_expr',
            new_name='date_to_expr',
        ),
    ]
