# Generated by Django 2.2.5 on 2021-02-11 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0014_auto_20201125_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdatafileprocedure',
            old_name='scheme_name',
            new_name='scheme_user_code',
        ),
    ]
