# Generated by Django 2.2.5 on 2022-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0020_pricingprocedureinstance_json_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingprocedure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='pricingprocedureinstance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='requestdatafileprocedure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='requestdatafileprocedureinstance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
    ]
