# Generated by Django 2.2.5 on 2022-06-23 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0022_expressionprocedure_expressionprocedureinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expressionprocedure',
            old_name='options_data',
            new_name='json_data',
        ),
    ]
