# Generated by Django 2.2.5 on 2022-06-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0024_expressionprocedureinstance_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionprocedureinstance',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.ExpressionProcedure',
                                    verbose_name='procedure'),
        ),
    ]
