# Generated by Django 2.2.5 on 2022-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0025_auto_20220623_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionprocedure',
            name='use_dates',
            field=models.BooleanField(default=False, verbose_name='use_dates'),
        ),
    ]
