# Generated by Django 2.2.5 on 2022-06-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0026_expressionprocedure_use_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionProcedureContextVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    choices=[['transaction_import', 'Transaction Import'], ['simple_import', 'Simple Import']],
                    default='name', max_length=255)),
                ('expression',
                 models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='expression')),
                ('procedure',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.ExpressionProcedure',
                                   verbose_name='procedure')),
            ],
        ),
    ]
