# Generated by Django 2.2.5 on 2022-06-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0028_auto_20220630_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionprocedurecontextvariable',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_variables',
                                    to='procedures.ExpressionProcedure', verbose_name='procedure'),
        ),
    ]
