# Generated by Django 2.2.5 on 2022-06-30 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('procedures', '0029_auto_20220630_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionprocedure',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='expressionprocedure',
            name='date_from_expr',
        ),
        migrations.RemoveField(
            model_name='expressionprocedure',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='expressionprocedure',
            name='date_to_expr',
        ),
        migrations.RemoveField(
            model_name='expressionprocedure',
            name='use_dates',
        ),
    ]
