# Generated by Django 4.0.6 on 2022-10-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0038_pricingprocedureinstance_response_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingprocedureinstance',
            old_name='response_data',
            new_name='json_response_data',
        ),
    ]
