# Generated by Django 4.1.3 on 2023-04-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='notes',
            new_name='description',
        ),
    ]
