# Generated by Django 4.1.3 on 2023-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_remove_configuration_from_marketplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMemberSetupConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_code', models.CharField(default='com.finmars.local', max_length=255, verbose_name='Configuration Code')),
                ('user_code', models.CharField(blank=True, help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, null=True, verbose_name='user code')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('target_configuration_code', models.CharField(blank=True, max_length=255, null=True)),
                ('target_configuration_version', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.TextField(blank=True, default='', verbose_name='File URL')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
