# Generated by Django 4.1.3 on 2023-05-31 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_newmembersetupconfiguration_target_configuration_is_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'get_latest_by': 'modified', 'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='configuration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified'),
        ),
    ]
