# Generated by Django 4.2.8 on 2024-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0011_configuration_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="newmembersetupconfiguration",
            name="target_configuration_channel",
            field=models.CharField(
                choices=[["stable", "Stable"], ["rc", "Release Candidate"]],
                default="stable",
                max_length=255,
            ),
        ),
    ]
