# Generated by Django 4.2.22 on 2025-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='manifest_data',
            field=models.JSONField(blank=True, null=True, verbose_name='manifest_data'),
        ),
    ]
