from rest_framework import routers

import poms.explorer.views as explorer

router = routers.DefaultRouter()

router.register(
    "explorer",
    explorer.ExplorerViewSet,
    "explorer",
)
router.register(
    "view",
    explorer.ExplorerViewFileViewSet,
    "explorer_view",
)
router.register(
    "upload",
    explorer.ExplorerUploadViewSet,
    "explorer_upload",
)
router.register(
    "delete",
    explorer.ExplorerDeleteViewSet,
    "explorer_delete",
)
router.register(
    "create-folder",
    explorer.ExplorerCreateFolderViewSet,
    "explorer_create_folder",
)
router.register(
    "delete-folder",
    explorer.ExplorerDeleteFolderViewSet,
    "explorer_delete_folder",
)
router.register(
    "download-as-zip",
    explorer.DownloadAsZipViewSet,
    "download_as_zip",
)
router.register(
    "download",
    explorer.DownloadViewSet,
    "explorer_download",
)
router.register(
    "move",
    explorer.MoveViewSet,
    "explorer_move",
)
router.register(
    "unzip",
    explorer.UnZipViewSet,
    "explorer_unzip",
)
router.register(
    "sync",
    explorer.SyncViewSet,
    "explorer_sync",
)
router.register(
    "search",
    explorer.SearchViewSet,
    "explorer_search",
)
router.register(
    "set-access-policy",
    explorer.StorageObjectAccessPolicyViewSet,
    "explorer_set_access_policy",
)
router.register(
    "rename",
    explorer.RenameViewSet,
    "explorer_rename",
)
router.register(
    "copy",
    explorer.CopyViewSet,
    "explorer_copy",
)
