# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecthistory4entry',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_histories',
                                    to='users.MasterUser'),
        ),
        migrations.AddField(
            model_name='objecthistory4entry',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='object_histories', to='users.Member'),
        ),
        migrations.AddField(
            model_name='objecthistory4entry',
            name='old_value_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='objecthistory4entry',
            name='value_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='authlogentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='user'),
        ),
        migrations.AlterIndexTogether(
            name='objecthistory4entry',
            index_together=set([('master_user', 'created')]),
        ),
    ]
