# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20160824_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authlogentry',
            options={'ordering': ['user', 'date'], 'verbose_name': 'authenticate log', 'verbose_name_plural': 'authenticate logs'},
        ),
        migrations.AlterModelOptions(
            name='objecthistory4entry',
            options={'ordering': ['master_user', 'member', 'created'], 'verbose_name': 'object history (v4)', 'verbose_name_plural': 'object histories (v4)'},
        ),
    ]
