# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160314_0709'),
        ('reversion', '0002_auto_20141216_1509'),
        ('audit', '0002_auto_20160323_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='reversion.Revision')),
            ],
        ),
    ]
