# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authlogentry',
            options={'ordering': ['-date'], 'verbose_name': 'authenticate log', 'verbose_name_plural': 'authenticate logs'},
        ),
        migrations.AlterModelOptions(
            name='objecthistory4entry',
            options={'ordering': ['-created'], 'verbose_name': 'object history (v4)', 'verbose_name_plural': 'object histories (v4)'},
        ),
    ]
