# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0008_auto_20160622_0720'),
        ('audit', '0003_auto_20160711_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version', models.IntegerField(default=0)),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, 'Added'), (2, 'Changed'), (3, 'Deleted')])),
                ('message', models.TextField(blank=True, null=True)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='contenttypes.ContentType')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='users.MasterUser')),
                ('member', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='users.Member')),
            ],
            options={
                'verbose_name': 'object history',
                'ordering': ['-created'],
                'verbose_name_plural': 'object histories',
            },
        ),
        migrations.AlterIndexTogether(
            name='objecthistoryentry',
            index_together=set([('master_user', 'created')]),
        ),
    ]
