# Generated by Django 2.2.5 on 2019-09-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20170125_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecthistory4entry',
            name='actor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType', verbose_name='actor content type'),
        ),
        migrations.AlterField(
            model_name='objecthistory4entry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='objecthistory4entry',
            name='old_value_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType', verbose_name='old value content type'),
        ),
        migrations.AlterField(
            model_name='objecthistory4entry',
            name='value_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType', verbose_name='value content type'),
        ),
    ]
