# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20160721_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioninfo',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='versioninfo',
            name='member',
        ),
        migrations.RemoveField(
            model_name='versioninfo',
            name='revision',
        ),
        migrations.DeleteModel(
            name='VersionInfo',
        ),
    ]
