TRANSACTION_TYPE_DICT = {
    "id": 26,
    "group": 10,
    "user_code": "local.poms.space00000:ksyvcrp",
    "name": "DMXOVPNWKG",
    "short_name": "UVK",
    "public_name": None,
    "notes": None,
    "date_expr": "",
    "display_expr": "",
    "visibility_status": 1,
    "type": 1,
    "transaction_unique_code_expr": "QTIVCWLRRG",
    "transaction_unique_code_options": 3,
    "user_text_1": "ZGRCADCBWU",
    "user_text_2": "NQPFFFXMKA",
    "user_text_3": "",
    "user_text_4": "",
    "user_text_5": "",
    "user_text_6": "",
    "user_text_7": "",
    "user_text_8": "",
    "user_text_9": "",
    "user_text_10": "",
    "user_text_11": "",
    "user_text_12": "",
    "user_text_13": "",
    "user_text_14": "",
    "user_text_15": "",
    "user_text_16": "",
    "user_text_17": "",
    "user_text_18": "",
    "user_text_19": "",
    "user_text_20": "",
    "user_text_21": "",
    "user_text_22": "",
    "user_text_23": "",
    "user_text_24": "",
    "user_text_25": "",
    "user_text_26": "",
    "user_text_27": "",
    "user_text_28": "",
    "user_text_29": "",
    "user_text_30": "",
    "user_number_1": "5202",
    "user_number_2": "2079",
    "user_number_3": "",
    "user_number_4": "",
    "user_number_5": "",
    "user_number_6": "",
    "user_number_7": "",
    "user_number_8": "",
    "user_number_9": "",
    "user_number_10": "",
    "user_number_11": "",
    "user_number_12": "",
    "user_number_13": "",
    "user_number_14": "",
    "user_number_15": "",
    "user_number_16": "",
    "user_number_17": "",
    "user_number_18": "",
    "user_number_19": "",
    "user_number_20": "",
    "user_date_1": "2024-03-26",
    "user_date_2": "2023-09-20",
    "user_date_3": "",
    "user_date_4": "",
    "user_date_5": "",
    "is_valid_for_all_portfolios": True,
    "is_valid_for_all_instruments": True,
    "is_deleted": False,
    "book_transaction_layout": {"test": "test"},
    "instrument_types": [],
    "portfolios": [],
    "inputs": [],
    "actions": [],
    "recon_fields": [],
    "context_parameters": [],
    "context_parameters_notes": None,
    "is_enabled": True,
    "configuration_code": "local.poms.space00000",
    "attributes": [
        {
            "id": 2,
            "attribute_type": 2,
            "value_string": "NRNFLUWEZS",
            "value_float": 9207.0,
            "value_date": "2023-07-26",
            "classifier": None,
            "attribute_type_object": {
                "id": 2,
                "user_code": "local.poms.space00000:auth.permission:tkwkb",
                "name": "",
                "short_name": "IV",
                "public_name": None,
                "notes": None,
                "can_recalculate": False,
                "value_type": 20,
                "order": 0,
                "is_hidden": False,
                "kind": 1,
            },
            "classifier_object": None,
        }
    ],
    "deleted_user_code": None,
    "instrument_types_object": [],
    "portfolios_object": [],
    "owner": {
        "id": 1,
        "username": "finmars_bot",
        "first_name": "",
        "last_name": "",
        "display_name": "finmars_bot",
        "is_owner": True,
        "is_admin": True,
        "user": 1,
    },
    "meta": {
        "content_type": "transactions.transactiontype",
        "app_label": "transactions",
        "model_name": "transactiontype",
        "space_code": "space00000",
    },
    "group_object": {
        "id": 10,
        "user_code": "local.poms.space00000:ranorwp",
        "name": "XLQMQEQYZS",
        "short_name": "XLQMQEQYZS",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "deleted_user_code": None,
        "meta": {
            "content_type": "transactions.transactiontypegroup",
            "app_label": "transactions",
            "model_name": "transactiontypegroup",
            "space_code": "space00000",
        },
    },
    "created_at": "20240823T16:41:00.0Z",
    "modified_at": "20240823T16:41:00.0Z",
    "deleted_at": None,
}

TRANSACTION_TYPE_WITH_INPUTS_DICT = {
    "id": 34,
    "group": 10,
    "user_code": "PFCARVKBPS:ocuzymd",
    "name": "HOLRKTJFHC",
    "short_name": "LPT",
    "public_name": None,
    "notes": None,
    "date_expr": "",
    "display_expr": "",
    "user_text_1": "VUXKLEUHCQ",
    "user_text_2": "HDBKXYUSVC",
    "user_text_3": "",
    "user_text_4": "",
    "user_text_5": "",
    "user_text_6": "",
    "user_text_7": "",
    "user_text_8": "",
    "user_text_9": "",
    "user_text_10": "",
    "user_text_11": "",
    "user_text_12": "",
    "user_text_13": "",
    "user_text_14": "",
    "user_text_15": "",
    "user_text_16": "",
    "user_text_17": "",
    "user_text_18": "",
    "user_text_19": "",
    "user_text_20": "",
    "user_text_21": "",
    "user_text_22": "",
    "user_text_23": "",
    "user_text_24": "",
    "user_text_25": "",
    "user_text_26": "",
    "user_text_27": "",
    "user_text_28": "",
    "user_text_29": "",
    "user_text_30": "",
    "user_number_1": "4862",
    "user_number_2": "8775",
    "user_number_3": "",
    "user_number_4": "",
    "user_number_5": "",
    "user_number_6": "",
    "user_number_7": "",
    "user_number_8": "",
    "user_number_9": "",
    "user_number_10": "",
    "user_number_11": "",
    "user_number_12": "",
    "user_number_13": "",
    "user_number_14": "",
    "user_number_15": "",
    "user_number_16": "",
    "user_number_17": "",
    "user_number_18": "",
    "user_number_19": "",
    "user_number_20": "",
    "user_date_1": "2024-02-21",
    "user_date_2": "2024-01-01",
    "user_date_3": "",
    "user_date_4": "",
    "user_date_5": "",
    "is_valid_for_all_portfolios": True,
    "is_valid_for_all_instruments": True,
    "is_deleted": False,
    "instrument_types": [],
    "portfolios": [],
    "inputs": [
        {
            "id": 1,
            "name": "ZPLTIJHUSD",
            "verbose_name": (
                "RXXNRHSOKYSPMEVIHQGTASUZRNQUFDFRXAIWIHTLUJFUIUFIWKKTOLQZNDDAGSJRBNYIDKZKVSAOMCXNUWAJVLASCIUSWVLYWALH"
            ),
            "value_type": 20,
            "reference_table": "WLXFKDWHRO",
            "content_type": None,
            "order": 0,
            "can_recalculate": False,
            "value_expr": None,
            "tooltip": "AQULCAVWIX",
            "value": "8805",
            "settings": {
                "linked_inputs_names": "EVYKHTXOXY",
                "recalc_on_change_linked_inputs": "EBRJHVNPFE",
            },
            "button_data": None,
        }
    ],
    "context_parameters_notes": None,
    "context_parameters": [],
    "deleted_user_code": None,
    "instrument_types_object": [],
    "portfolios_object": [],
    "owner": {
        "id": 1,
        "username": "finmars_bot",
        "first_name": "",
        "last_name": "",
        "display_name": "finmars_bot",
        "is_owner": True,
        "is_admin": True,
        "user": 1,
    },
    "meta": {
        "content_type": "transactions.transactiontype",
        "app_label": "transactions",
        "model_name": "transactiontype",
        "space_code": "space00000",
    },
    "group_object": {
        "id": 10,
        "user_code": "local.poms.space00000:unified",
        "name": "Unified",
        "short_name": "Unified",
        "public_name": None,
        "notes": None,
        "is_deleted": False,
        "deleted_user_code": None,
        "meta": {
            "content_type": "transactions.transactiontypegroup",
            "app_label": "transactions",
            "model_name": "transactiontypegroup",
            "space_code": "space00000",
        },
    },
}

TRANSACTION_TYPE_BOOK_DICT = {
    "transaction_type": 7,
    "complex_transaction_status": None,
    "process_mode": "book",
    "values": {},
    "recalculate_inputs": [],
    "has_errors": False,
    "value_errors": [],
    "instruments_errors": [],
    "complex_transaction_errors": [],
    "transactions_errors": [],
    "general_errors": [],
    "instruments": [],
    "complex_transaction": {
        "id": 0,
        "date": None,
        "status": 1,
        "code": None,
        "text": None,
        "transaction_type": 7,
        "transactions": [],
        "is_locked": False,
        "is_canceled": False,
        "is_deleted": False,
        "error_code": None,
        "visibility_status": 1,
        "transaction_unique_code": None,
        "user_text_1": None,
        "user_text_2": None,
        "user_text_3": None,
        "user_text_4": None,
        "user_text_5": None,
        "user_text_6": None,
        "user_text_7": None,
        "user_text_8": None,
        "user_text_9": None,
        "user_text_10": None,
        "user_text_11": None,
        "user_text_12": None,
        "user_text_13": None,
        "user_text_14": None,
        "user_text_15": None,
        "user_text_16": None,
        "user_text_17": None,
        "user_text_18": None,
        "user_text_19": None,
        "user_text_20": None,
        "user_text_21": None,
        "user_text_22": None,
        "user_text_23": None,
        "user_text_24": None,
        "user_text_25": None,
        "user_text_26": None,
        "user_text_27": None,
        "user_text_28": None,
        "user_text_29": None,
        "user_text_30": None,
        "user_number_1": None,
        "user_number_2": None,
        "user_number_3": None,
        "user_number_4": None,
        "user_number_5": None,
        "user_number_6": None,
        "user_number_7": None,
        "user_number_8": None,
        "user_number_9": None,
        "user_number_10": None,
        "user_number_11": None,
        "user_number_12": None,
        "user_number_13": None,
        "user_number_14": None,
        "user_number_15": None,
        "user_number_16": None,
        "user_number_17": None,
        "user_number_18": None,
        "user_number_19": None,
        "user_number_20": None,
        "user_date_1": None,
        "user_date_2": None,
        "user_date_3": None,
        "user_date_4": None,
        "user_date_5": None,
        "recon_fields": [],
        "execution_log": (
            "[2023-07-27 14:21:32] Booking Complex Transaction\n"
            "[2023-07-27 14:21:32] Start 2023-07-27 \n"
            "[2023-07-27 14:21:32] Transaction Type: XGYMAARJPZ:bhihepr\n"
            "[2023-07-27 14:21:32] Member: \n"
            "[2023-07-27 14:21:32] Execution_context: manual\n"
            "[2023-07-27 14:21:32] ==== SETTINGS VALUES ====\n"
            "[2023-07-27 14:21:32] ==== COMPLEX TRANSACTION VALUES ====\n"
            "{\n"
            '    "context_instrument": null,\n'
            '    "context_pricing_currency": null,\n'
            '    "context_accrued_currency": null,\n'
            '    "context_portfolio": null,\n'
            '    "context_account": null,\n'
            '    "context_strategy1": null,\n'
            '    "context_strategy2": null,\n'
            '    "context_strategy3": null,\n'
            '    "context_position_size": null,\n'
            '    "context_effective_date": null,\n'
            '    "context_currency": null,\n'
            '    "context_report_date": null,\n'
            '    "context_report_start_date": null,\n'
            '    "context_pricing_policy": null,\n'
            '    "context_allocation_balance": null,\n'
            '    "context_allocation_pl": null,\n'
            '    "context_parameter": null,\n'
            '    "phantom_instrument_0": null,\n'
            '    "phantom_instrument_1": null,\n'
            '    "phantom_instrument_2": null,\n'
            '    "phantom_instrument_3": null,\n'
            '    "phantom_instrument_4": null,\n'
            '    "phantom_instrument_5": null,\n'
            '    "phantom_instrument_6": null,\n'
            '    "phantom_instrument_7": null,\n'
            '    "phantom_instrument_8": null,\n'
            '    "phantom_instrument_9": null\n'
            "}\n"
            "[2023-07-27 14:21:32] ==== CALCULATED INPUTS ====\n"
            "[2023-07-27 14:21:32] Key: context_instrument. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_pricing_currency. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_accrued_currency. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_portfolio. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_account. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_strategy1. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_strategy2. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_strategy3. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_position_size. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_effective_date. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_currency. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_report_date. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_report_start_date. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_pricing_policy. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_allocation_balance. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_allocation_pl. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: context_parameter. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_0. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_1. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_2. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_3. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_4. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_5. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_6. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_7. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_8. Value: None. Type: NoneType\n"
            "[2023-07-27 14:21:32] Key: phantom_instrument_9. Value: None. Type: NoneType\n"
        ),
        "source": None,
        "attributes": [],
        "transaction_type_object": {
            "id": 7,
            "group": 2,
            "user_code": "XGYMAARJPZ:bhihepr",
            "name": "ZCTGRBRJVR",
            "short_name": "JHA",
            "public_name": None,
            "notes": None,
            "is_valid_for_all_portfolios": True,
            "is_valid_for_all_instruments": True,
            "is_deleted": False,
            "transaction_unique_code_expr": "",
            "transaction_unique_code_options": 2,
            "user_text_1": "VDBWTIKAPP",
            "user_text_2": "KLBIUYZRVQ",
            "user_text_3": "",
            "user_text_4": "",
            "user_text_5": "",
            "user_text_6": "",
            "user_text_7": "",
            "user_text_8": "",
            "user_text_9": "",
            "user_text_10": "",
            "user_text_11": "",
            "user_text_12": "",
            "user_text_13": "",
            "user_text_14": "",
            "user_text_15": "",
            "user_text_16": "",
            "user_text_17": "",
            "user_text_18": "",
            "user_text_19": "",
            "user_text_20": "",
            "user_text_21": "",
            "user_text_22": "",
            "user_text_23": "",
            "user_text_24": "",
            "user_text_25": "",
            "user_text_26": "",
            "user_text_27": "",
            "user_text_28": "",
            "user_text_29": "",
            "user_text_30": "",
            "user_number_1": "2911",
            "user_number_2": "2814",
            "user_number_3": "",
            "user_number_4": "",
            "user_number_5": "",
            "user_number_6": "",
            "user_number_7": "",
            "user_number_8": "",
            "user_number_9": "",
            "user_number_10": "",
            "user_number_11": "",
            "user_number_12": "",
            "user_number_13": "",
            "user_number_14": "",
            "user_number_15": "",
            "user_number_16": "",
            "user_number_17": "",
            "user_number_18": "",
            "user_number_19": "",
            "user_number_20": "",
            "user_date_1": "2023-09-02",
            "user_date_2": "2024-04-15",
            "user_date_3": "",
            "user_date_4": "",
            "user_date_5": "",
            "deleted_user_code": None,
            "meta": {
                "content_type": "transactions.transactiontype",
                "app_label": "transactions",
                "model_name": "transactiontype",
                "space_code": "space00000",
            },
            "group_object": {
                "id": 2,
                "user_code": "local.poms.space00000:unified",
                "name": "Unified",
                "short_name": "Unified",
                "public_name": None,
                "notes": None,
                "is_deleted": False,
                "deleted_user_code": None,
                "meta": {
                    "content_type": "transactions.transactiontypegroup",
                    "app_label": "transactions",
                    "model_name": "transactiontypegroup",
                    "space_code": "space00000",
                },
            },
        },
        "transactions_object": [],
    },
    "transaction_type_object": {
        "id": 7,
        "group": 2,
        "user_code": "XGYMAARJPZ:bhihepr",
        "name": "ZCTGRBRJVR",
        "short_name": "JHA",
        "public_name": None,
        "notes": None,
        "date_expr": "",
        "display_expr": "",
        "visibility_status": 1,
        "type": 1,
        "transaction_unique_code_expr": "",
        "transaction_unique_code_options": 2,
        "user_text_1": "VDBWTIKAPP",
        "user_text_2": "KLBIUYZRVQ",
        "user_text_3": "",
        "user_text_4": "",
        "user_text_5": "",
        "user_text_6": "",
        "user_text_7": "",
        "user_text_8": "",
        "user_text_9": "",
        "user_text_10": "",
        "user_text_11": "",
        "user_text_12": "",
        "user_text_13": "",
        "user_text_14": "",
        "user_text_15": "",
        "user_text_16": "",
        "user_text_17": "",
        "user_text_18": "",
        "user_text_19": "",
        "user_text_20": "",
        "user_text_21": "",
        "user_text_22": "",
        "user_text_23": "",
        "user_text_24": "",
        "user_text_25": "",
        "user_text_26": "",
        "user_text_27": "",
        "user_text_28": "",
        "user_text_29": "",
        "user_text_30": "",
        "user_number_1": "2911",
        "user_number_2": "2814",
        "user_number_3": "",
        "user_number_4": "",
        "user_number_5": "",
        "user_number_6": "",
        "user_number_7": "",
        "user_number_8": "",
        "user_number_9": "",
        "user_number_10": "",
        "user_number_11": "",
        "user_number_12": "",
        "user_number_13": "",
        "user_number_14": "",
        "user_number_15": "",
        "user_number_16": "",
        "user_number_17": "",
        "user_number_18": "",
        "user_number_19": "",
        "user_number_20": "",
        "user_date_1": "2023-09-02",
        "user_date_2": "2024-04-15",
        "user_date_3": "",
        "user_date_4": "",
        "user_date_5": "",
        "is_valid_for_all_portfolios": True,
        "is_valid_for_all_instruments": True,
        "is_deleted": False,
        "book_transaction_layout": {"test": "test"},
        "instrument_types": [],
        "portfolios": [],
        "inputs": [],
        "actions": [],
        "recon_fields": [],
        "context_parameters": [],
        "context_parameters_notes": None,
        "is_enabled": True,
        "configuration_code": "XGYMAARJPZ",
        "attributes": [
            {
                "id": 1,
                "attribute_type": 1,
                "value_string": "OPFCOLOOOQ",
                "value_float": 2797.0,
                "value_date": "2023-07-27",
                "classifier": None,
                "attribute_type_object": {
                    "id": 1,
                    "user_code": "local.poms.space00000:auth.permission:swvbn",
                    "name": "",
                    "short_name": "FZ",
                    "public_name": None,
                    "notes": None,
                    "can_recalculate": False,
                    "value_type": 20,
                    "order": 0,
                    "is_hidden": False,
                    "kind": 1,
                },
                "classifier_object": None,
            }
        ],
        "deleted_user_code": None,
        "instrument_types_object": [],
        "portfolios_object": [],
        "meta": {
            "content_type": "transactions.transactiontype",
            "app_label": "transactions",
            "model_name": "transactiontype",
            "space_code": "space00000",
        },
        "group_object": {
            "id": 2,
            "user_code": "local.poms.space00000:unified",
            "name": "Unified",
            "short_name": "Unified",
            "public_name": None,
            "notes": None,
            "is_deleted": False,
            "deleted_user_code": None,
            "meta": {
                "content_type": "transactions.transactiontypegroup",
                "app_label": "transactions",
                "model_name": "transactiontypegroup",
                "space_code": "space00000",
            },
        },
    },
    "book_transaction_layout": {"test": "test"},
}

TRANSACTION_TYPE_RECALCULATE_DICT = {
    "id": 6,
    "user_code": "local.poms.space0xheq:developing",
    "configuration_code": "local.poms.space0xheq",
    "name": "Developing",
    "short_name": "Dev",
    "public_name": None,
    "notes": None,
    "is_deleted": False,
    "is_enabled": True,
    "deleted_user_code": None,
    "meta": {
        "content_type": "transactions.transactiontypegroup",
        "app_label": "transactions",
        "model_name": "transactiontypegroup",
        "space_code": "space0xheq",
    },
}

RECALCULATE_PAYLOAD = {
    "transaction_type": 34,
    "recalculate_inputs": ["input_to_recalculate", "input_to_recalculate2"],
    "process_mode": "recalculate",
    "values": {
        "input1": 5,
        "input2": 5,
        "input_to_recalculate": 10,
        "input_to_recalculate2": 5,
    },
}

EXPECTED_COMPLEX_TRANSACTION = {
    "id": 1,
    "date": "2023-10-23",
    "status": 2,
    "code": 100,
    "text": None,
    "transaction_type": 13,
    "transactions": [],
    "transaction_unique_code": "87648176382763",
    "is_locked": False,
    "is_canceled": False,
    "error_code": None,
    "is_deleted": False,
    "user_text_1": "QKARGVBJML",
    "user_text_2": "VMBKMMTZPB",
    "user_text_3": None,
    "user_text_4": None,
    "user_text_5": None,
    "user_text_6": None,
    "user_text_7": None,
    "user_text_8": None,
    "user_text_9": None,
    "user_text_10": None,
    "user_text_11": None,
    "user_text_12": None,
    "user_text_13": None,
    "user_text_14": None,
    "user_text_15": None,
    "user_text_16": None,
    "user_text_17": None,
    "user_text_18": None,
    "user_text_19": None,
    "user_text_20": None,
    "user_text_21": None,
    "user_text_22": None,
    "user_text_23": None,
    "user_text_24": None,
    "user_text_25": None,
    "user_text_26": None,
    "user_text_27": None,
    "user_text_28": None,
    "user_text_29": None,
    "user_text_30": None,
    "user_number_1": None,
    "user_number_2": None,
    "user_number_3": None,
    "user_number_4": None,
    "user_number_5": None,
    "user_number_6": None,
    "user_number_7": None,
    "user_number_8": None,
    "user_number_9": None,
    "user_number_10": None,
    "user_number_11": None,
    "user_number_12": None,
    "user_number_13": None,
    "user_number_14": None,
    "user_number_15": None,
    "user_number_16": None,
    "user_number_17": None,
    "user_number_18": None,
    "user_number_19": None,
    "user_number_20": None,
    "user_date_1": None,
    "user_date_2": None,
    "user_date_3": None,
    "user_date_4": None,
    "user_date_5": None,
    "recon_fields": [],
    "execution_log": None,
    "source": None,
    "inputs": [],
    "attributes": [
        {
            "id": 2,
            "attribute_type": 2,
            "value_string": "ELQMDDKLRI",
            "value_float": 1289.0,
            "value_date": "2023-07-24",
            "classifier": None,
            "attribute_type_object": {
                "id": 2,
                "user_code": "local.poms.space00000:auth.permission:skbii",
                "name": "",
                "short_name": "CC",
                "public_name": None,
                "notes": None,
                "can_recalculate": False,
                "value_type": 20,
                "order": 0,
                "is_hidden": False,
                "kind": 1,
            },
            "classifier_object": None,
        }
    ],
    "transaction_type_object": {
        "id": 13,
        "group": 5,
        "user_code": "local.poms.space00000:kpprwgt",
        "name": "MYTRGYVSEZ",
        "short_name": "CKQ",
        "public_name": None,
        "notes": None,
        "is_valid_for_all_portfolios": True,
        "is_valid_for_all_instruments": True,
        "is_deleted": False,
        "transaction_unique_code_expr": "WYDRYHRAMX",
        "transaction_unique_code_options": 3,
        "user_text_1": "ACEUWUDLUO",
        "user_text_2": "TLUEHXJRAE",
        "user_text_3": "",
        "user_text_4": "",
        "user_text_5": "",
        "user_text_6": "",
        "user_text_7": "",
        "user_text_8": "",
        "user_text_9": "",
        "user_text_10": "",
        "user_text_11": "",
        "user_text_12": "",
        "user_text_13": "",
        "user_text_14": "",
        "user_text_15": "",
        "user_text_16": "",
        "user_text_17": "",
        "user_text_18": "",
        "user_text_19": "",
        "user_text_20": "",
        "user_text_21": "",
        "user_text_22": "",
        "user_text_23": "",
        "user_text_24": "",
        "user_text_25": "",
        "user_text_26": "",
        "user_text_27": "",
        "user_text_28": "",
        "user_text_29": "",
        "user_text_30": "",
        "user_number_1": "EIGSNVITEP",
        "user_number_2": "CRSMCTSCZL",
        "user_number_3": "",
        "user_number_4": "",
        "user_number_5": "",
        "user_number_6": "",
        "user_number_7": "",
        "user_number_8": "",
        "user_number_9": "",
        "user_number_10": "",
        "user_number_11": "",
        "user_number_12": "",
        "user_number_13": "",
        "user_number_14": "",
        "user_number_15": "",
        "user_number_16": "",
        "user_number_17": "",
        "user_number_18": "",
        "user_number_19": "",
        "user_number_20": "",
        "user_date_1": "2024-01-21",
        "user_date_2": "2024-05-31",
        "user_date_3": "",
        "user_date_4": "",
        "user_date_5": "",
        "deleted_user_code": None,
        "meta": {
            "content_type": "transactions.transactiontype",
            "app_label": "transactions",
            "model_name": "transactiontype",
            "space_code": "space00000",
        },
        "group_object": {
            "id": 5,
            "user_code": "local.poms.space00000:lzzrpsw",
            "name": "YXJHQKXBUH",
            "short_name": "YXJHQKXBUH",
            "public_name": None,
            "notes": None,
            "is_deleted": False,
            "deleted_user_code": None,
            "meta": {
                "content_type": "transactions.transactiontypegroup",
                "app_label": "transactions",
                "model_name": "transactiontypegroup",
                "space_code": "space00000",
            },
        },
    },
    "transactions_object": [],
    "meta": {
        "content_type": "transactions.complextransaction",
        "app_label": "transactions",
        "model_name": "complextransaction",
        "space_code": "space00000",
    },
    "created_at": "20240823T16:41:00.0Z",
    "modified_at": "20240823T16:41:00.0Z",
}
