# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_layouts',
                                             to='users.Member')),
            ],
            options={
                'abstract': False,
                'ordering': ['content_type'],
            },
        ),
        migrations.CreateModel(
            name='ListLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('member',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_list_layouts',
                                   to='users.Member')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEditLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('master_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_layouts',
                                   to='users.MasterUser')),
            ],
            options={
                'abstract': False,
                'ordering': ['content_type'],
            },
        ),
        migrations.CreateModel(
            name='TemplateListLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('master_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_list_layouts',
                                   to='users.MasterUser')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='templatelistlayout',
            unique_together=set([('master_user', 'content_type', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='templateeditlayout',
            unique_together=set([('master_user', 'content_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='listlayout',
            unique_together=set([('member', 'content_type', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='editlayout',
            unique_together=set([('member', 'content_type')]),
        ),
    ]
