# Generated by Django 4.1.3 on 2022-12-07 21:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
        ('configuration_sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
            ],
            options={
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='PortalInterfaceAccessModel',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=255, unique=True, verbose_name='user code')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, default='', max_length=255, verbose_name='short name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('value', models.PositiveSmallIntegerField(default=1, verbose_name='value')),
            ],
            options={
                'verbose_name': 'portal interface access',
                'verbose_name_plural': 'portal interface accesses',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionUserFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='key')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user_fields', to='users.masteruser', verbose_name='master user')),
            ],
        ),
        migrations.CreateModel(
            name='ListLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_systemic', models.BooleanField(default=False, verbose_name='is systemic')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='is fixeds')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_list_layouts', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('member', 'content_type', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentUserFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='key')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_user_fields', to='users.masteruser', verbose_name='master user')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='users.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='ColumnSortData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('column_key', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='column key')),
                ('is_common', models.BooleanField(default=False, verbose_name='is common')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_sort_data', to='users.member', verbose_name='member')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('uri', models.CharField(blank=True, max_length=256, null=True, verbose_name='uri')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('list_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='ui.listlayout', verbose_name='list layout')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ui.bookmark', verbose_name='parent')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'verbose_name': 'bookmark',
                'verbose_name_plural': 'bookmarks',
                'ordering': ['tree_id', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('type', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='type')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_layouts', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('member', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EntityTooltip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='key')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
            ],
            options={
                'unique_together': {('master_user', 'content_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='EditLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('user_code', models.CharField(max_length=255, verbose_name='user code')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_layouts', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('member', 'content_type', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('member', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='CrossEntityAttributeExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_from', models.CharField(blank=True, default='', max_length=255, verbose_name='key from')),
                ('key_to', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='key to')),
                ('value_to', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='value to')),
                ('extension_type', models.CharField(blank=True, choices=[('NULL', 'Null'), ('CONSTANT', 'Constant'), ('ATTRIBUTE', 'Attribute')], default='NULL', max_length=255, null=True, verbose_name='value type')),
                ('content_type_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_entity_attribute_extensions_by_from', to='contenttypes.contenttype', verbose_name='content type from')),
                ('content_type_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_entity_attribute_extensions_by_to', to='contenttypes.contenttype', verbose_name='content type to')),
                ('context_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_entity_attribute_extensions_by_context', to='contenttypes.contenttype', verbose_name='context content type')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
            ],
            options={
                'unique_together': {('master_user', 'context_content_type', 'content_type_from', 'key_from')},
            },
        ),
        migrations.CreateModel(
            name='ContextMenuLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('type', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='type')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_menu_layouts', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('member', 'type', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='ConfigurationExportLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_export_layouts', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('member', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_files', to='users.masteruser', verbose_name='master user')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'abstract': False,
                'unique_together': {('master_user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ColorPaletteColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('value', models.CharField(blank=True, default='', max_length=255, verbose_name='value')),
                ('tooltip', models.TextField(blank=True, null=True, verbose_name='tooltip')),
                ('color_palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='ui.colorpalette', verbose_name='color palette')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('color_palette', 'order')},
            },
        ),
    ]
