# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlayout',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='editlayout',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='editlayout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_layouts', to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='listlayout',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='listlayout',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='listlayout',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='listlayout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_list_layouts', to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='listlayout',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='templateeditlayout',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='templateeditlayout',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='templateeditlayout',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_layouts', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='templatelistlayout',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='templatelistlayout',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='templatelistlayout',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='templatelistlayout',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_list_layouts', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='templatelistlayout',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name'),
        ),
    ]
