# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20160616_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='listlayout',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatelistlayout',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editlayout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_layouts', to='users.Member'),
        ),
        migrations.AlterField(
            model_name='listlayout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_list_layouts', to='users.Member'),
        ),
        migrations.AlterField(
            model_name='templateeditlayout',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_layouts', to='users.MasterUser'),
        ),
        migrations.AlterField(
            model_name='templatelistlayout',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_list_layouts', to='users.MasterUser'),
        ),
    ]
