# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170125_1037'),
        ('ui', '0002_auto_20170125_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('uri', models.CharField(blank=True, max_length=256, null=True, verbose_name='uri')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('list_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='ui.ListLayout', verbose_name='list layout')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='users.Member', verbose_name='member')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ui.Bookmark', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'bookmarks',
                'verbose_name': 'bookmark',
                'ordering': ['tree_id', 'level', 'name'],
            },
        ),
    ]
