# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editlayout',
            options={'ordering': ['content_type']},
        ),
        migrations.AlterModelOptions(
            name='listlayout',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='templateeditlayout',
            options={'ordering': ['content_type']},
        ),
        migrations.AlterModelOptions(
            name='templatelistlayout',
            options={'ordering': ['name']},
        ),
    ]
