# Generated by Django 4.1.3 on 2023-04-07 08:15

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_masteruser_journal_status'),
        ('ui', '0003_rename_transactionuserfieldmodel_complextransactionuserfieldmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransactionuserfieldmodel',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='instrumentuserfieldmodel',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
    ]
