# Generated by Django 4.1.3 on 2023-04-07 08:15

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):

    from poms.reports.sql_builders.helpers import dictfetchall
    from django.db import connection

    try:

        query = '''
        alter table ui_complextransactionuserfieldmodel
        rename constraint ui_transactionuserfieldmodel_pkey to ui_complextransactionuserfieldmodel_pkey;
        '''



        with connection.cursor() as cursor:

            cursor.execute(query)

    except Exception as e:
        print('Django DB Migration error %s' % e)

    try:
        with connection.cursor() as cursor:
            query_fetch = '''
            select *
                from pg_indexes where tablename='ui_complextransactionuserfieldmodel';
            '''

            cursor.execute(query_fetch)
            indexes = dictfetchall(cursor)

            print('indexes %s' % indexes)

            for index in indexes:

                try:

                    if 'ui_transactionuserfieldmodel' in index['indexname']:
                        print("Going to drop index %s" % indexes['indexname'])
                        query = '''
                        drop index %s;
                        ''' % index['indexname']

                        cursor.execute(query)

                except Exception as e:
                    print("e %s " % e)

    except Exception as e:
        print('Django DB delete old index error %s' % e)



def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_masteruser_journal_status'),
        ('ui', '0003_rename_transactionuserfieldmodel_complextransactionuserfieldmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransactionuserfieldmodel',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='instrumentuserfieldmodel',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.RunPython(forwards_func, reverse_func),

    ]
