# Generated by Django 4.1.3 on 2023-04-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_masteruser_journal_status'),
        ('ui', '0004_alter_complextransactionuserfieldmodel_master_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionUserFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='key')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
            ],
        ),
    ]
