# Generated by Django 4.1.3 on 2023-04-07 08:17

from django.db import migrations, models
import django.db.models.deletion



def forwards_func(apps, schema_editor):

    from poms.reports.sql_builders.helpers import dictfetchall
    from django.db import connection

    try:

        query = '''
        alter table ui_complextransactionuserfieldmodel
        rename constraint ui_transactionuserfieldmodel_pkey to ui_complextransactionuserfieldmodel_pkey;
        '''



        with connection.cursor() as cursor:

            cursor.execute(query)

    except Exception as e:
        print('Django DB Migration error %s' % e)

    try:
        with connection.cursor() as cursor:
            query_fetch = '''
            select *
                from pg_indexes where tablename='ui_complextransactionuserfieldmodel';
            '''

            cursor.execute(query_fetch)
            indexes = dictfetchall(cursor)

            print('indexes %s' % indexes)

            for index in indexes:

                try:

                    if 'ui_transactionuserfieldmodel' in index['indexname']:
                        print("Going to drop index %s" % indexes['indexname'])

                        changed_index = index['indexname'].replace('ui_transactionuserfieldmodel', 'ui_complextransactionuserfieldmodel')

                        query = '''
                        alter index %s rename to %s;
                        ''' % (index['indexname'], changed_index)

                        cursor.execute(query)

                except Exception as e:
                    print("e %s " % e)

    except Exception as e:
        print('Django DB delete old index error %s' % e)



def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_masteruser_journal_status'),
        ('ui', '0004_alter_complextransactionuserfieldmodel_master_user_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.CreateModel(
            name='TransactionUserFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='key')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
            ],
        ),
    ]
