# Generated by Django 4.1.3 on 2023-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_transactionuserfieldmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='configuration_code',
            field=models.CharField(default='com.finmars.local', max_length=255, verbose_name='Configuration Code'),
        ),
        migrations.AddField(
            model_name='complextransactionuserfieldmodel',
            name='configuration_code',
            field=models.CharField(default='com.finmars.local', max_length=255, verbose_name='Configuration Code'),
        ),
        migrations.AddField(
            model_name='complextransactionuserfieldmodel',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='User Code'),
        ),
        migrations.AddField(
            model_name='instrumentuserfieldmodel',
            name='configuration_code',
            field=models.CharField(default='com.finmars.local', max_length=255, verbose_name='Configuration Code'),
        ),
        migrations.AddField(
            model_name='instrumentuserfieldmodel',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='User Code'),
        ),
        migrations.AddField(
            model_name='transactionuserfieldmodel',
            name='configuration_code',
            field=models.CharField(default='com.finmars.local', max_length=255, verbose_name='Configuration Code'),
        ),
        migrations.AddField(
            model_name='transactionuserfieldmodel',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='User Code'),
        ),
    ]
