# Generated by Django 4.1.3 on 2023-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_bookmark_configuration_code_bookmark_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='columnsortdata',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='contextmenulayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='editlayout',
            name='user_code',
            field=models.CharField(max_length=1024, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='listlayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='templatelayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code'),
        ),
    ]
