# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-26 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_member_notification_level'),
        ('ui', '0008_auto_20190126_0803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurationexportlayout',
            unique_together=set([('member', 'name')]),
        ),
    ]
