# Generated by Django 4.1.3 on 2023-05-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_invitetomasteruser_unique_together_and_more'),
        ('ui', '0009_alter_colorpalette_notes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionUserFieldModel',
            new_name='ComplexTransactionUserField',
        ),
        migrations.RenameModel(
            old_name='InstrumentUserFieldModel',
            new_name='InstrumentUserField',
        ),
        migrations.RenameModel(
            old_name='ComplexTransactionUserFieldModel',
            new_name='TransactionUserField',
        ),
    ]
