# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-28 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_configurationexportlayout_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationexportlayout',
            name='notes',
        ),
    ]
