# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_masteruser_user_code_counters'),
        ('ui', '0012_remove_configurationexportlayout_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentUserFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='key')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_user_fields', to='users.MasterUser', verbose_name='master user')),
            ],
        ),
    ]
