# Generated by Django 4.1.3 on 2023-05-31 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_sharing', '0002_initial'),
        ('users', '0006_alter_invitetomasteruser_unique_together_and_more'),
        ('ui', '0013_mobilelayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('configuration_code', models.CharField(default='com.finmars.local', max_length=255, verbose_name='Configuration Code')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('user_code', models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_layouts', to='users.member', verbose_name='member')),
                ('origin_for_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_origins', to='configuration_sharing.sharedconfigurationfile', verbose_name='origin for global layout')),
                ('sourced_from_global_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subscribers', to='configuration_sharing.sharedconfigurationfile', verbose_name='sourced for global layout')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('member', 'user_code')},
            },
        ),
    ]
