# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-31 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_portalinterfaceaccessmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinterfaceaccessmodel',
            name='value',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='value'),
        ),
    ]
