# Generated by Django 4.1.3 on 2023-06-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_alter_bookmark_configuration_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransactionuserfield',
            name='key',
            field=models.CharField(max_length=255, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='transactionuserfield',
            name='key',
            field=models.CharField(max_length=255, verbose_name='key'),
        ),
    ]
