# Generated by Django 2.2.5 on 2019-11-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_invitetomasteruser_groups'),
        ('ui', '0019_templatelayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelayout',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_layouts', to='users.MasterUser', verbose_name='member'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='templatelayout',
            unique_together={('member', 'type', 'name')},
        ),
        migrations.RemoveField(
            model_name='templatelayout',
            name='master_user',
        ),
    ]
