# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0020_alter_memberlayout_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationexportlayout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='configurationexportlayout',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='contextmenulayout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contextmenulayout',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='dashboardlayout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dashboardlayout',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='editlayout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='editlayout',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='instrumentuserfield',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='instrumentuserfield',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='listlayout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='listlayout',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='memberlayout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='memberlayout',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='mobilelayout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mobilelayout',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='transactionuserfield',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transactionuserfield',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
