# Generated by Django 2.2.5 on 2019-11-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_grouppermssiontableoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermssiontableoption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_table', to='users.Group', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='grouppermssiontableoption',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permission_table', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
