# Generated by Django 2.2.5 on 2019-11-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20191111_1521'),
        ('ui', '0024_delete_grouppermssiontableoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextMenuLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('type', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='type')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_menu_layouts', to='users.Member', verbose_name='member')),
            ],
            options={
                'abstract': False,
                'unique_together': {('member', 'type', 'name')},
            },
        ),
    ]
