# Generated by Django 2.2.5 on 2020-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0026_auto_20200116_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='listlayout',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='is fixeds'),
        ),
    ]
