# Generated by Django 2.2.5 on 2020-04-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ui', '0027_listlayout_is_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextmenulayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
        migrations.AddField(
            model_name='dashboardlayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
        migrations.AddField(
            model_name='listlayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
        migrations.AddField(
            model_name='templatelistlayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
        migrations.AlterUniqueTogether(
            name='contextmenulayout',
            unique_together={('member', 'type', 'user_code')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardlayout',
            unique_together={('member', 'user_code')},
        ),
        migrations.AlterUniqueTogether(
            name='listlayout',
            unique_together={('member', 'content_type', 'user_code')},
        ),
        migrations.AlterUniqueTogether(
            name='templatelistlayout',
            unique_together={('master_user', 'content_type', 'user_code')},
        ),
    ]
