# Generated by Django 2.2.5 on 2020-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0028_auto_20200415_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelayout',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
    ]
