# Generated by Django 2.2.5 on 2020-04-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0029_templatelayout_user_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatelistlayout',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templatelistlayout',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='templatelistlayout',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='templatelistlayout',
            name='origin_for_global_layout',
        ),
        migrations.RemoveField(
            model_name='templatelistlayout',
            name='sourced_from_global_layout',
        ),
        migrations.DeleteModel(
            name='TemplateEditLayout',
        ),
        migrations.DeleteModel(
            name='TemplateListLayout',
        ),
    ]
