# Generated by Django 2.2.5 on 2020-06-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_ecosystemdefault_pricing_condition'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ui', '0031_entitytooltipmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityTooltipModel',
            new_name='EntityTooltip',
        ),
    ]
