# Generated by Django 2.2.5 on 2020-06-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0035_colorpalette_colorpalettecolor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colorpalettecolor',
            unique_together={('color_palette', 'order')},
        ),
    ]
