# Generated by Django 2.2.5 on 2020-07-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0037_colorpalettecolor_tooltip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextmenulayout',
            options={'ordering': ['name']},
        ),
    ]
