# Generated by Django 2.2.5 on 2021-02-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0039_auto_20201013_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalinterfaceaccessmodel',
            old_name='system_code',
            new_name='user_code'
        ),
    ]
