# Generated by Django 2.2.5 on 2021-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0042_auto_20210211_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlayout',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='editlayout',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
    ]
