# Generated by Django 2.2.5 on 2021-03-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0035_auto_20201222_1103'),
        ('ui', '0043_auto_20210211_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossEntityAttributeExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_from', models.CharField(blank=True, default='', max_length=255, verbose_name='key from')),
                ('key_to', models.CharField(blank=True, default='', max_length=255, verbose_name='key to')),
                ('value_to', models.CharField(blank=True, default='', max_length=255, verbose_name='value to')),
                ('context_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_entity_attribute_extensions_by_context', to='contenttypes.ContentType', verbose_name='context content type')),
                ('content_type_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_entity_attribute_extensions_by_from', to='contenttypes.ContentType', verbose_name='content type from')),
                ('content_type_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_entity_attribute_extensions_by_to', to='contenttypes.ContentType', verbose_name='content type to')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'unique_together': {('master_user', 'context_content_type', 'content_type_from', 'key_from')},
            },
        ),
    ]
