# Generated by Django 2.2.5 on 2021-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0044_crossentityattributeextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossentityattributeextension',
            name='key_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='key to'),
        ),
        migrations.AlterField(
            model_name='crossentityattributeextension',
            name='value_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='value to'),
        ),
    ]
