# Generated by Django 2.2.5 on 2021-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0046_columnsortdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnsortdata',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='is common'),
        ),
    ]
