# Generated by Django 2.2.5 on 2021-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0050_auto_20210312_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinterfaceaccessmodel',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='short name'),
        ),
    ]
