# Generated by Django 2.2.5 on 2021-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0052_auto_20211027_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionuserfieldmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
