# Generated by Django 4.0.6 on 2022-07-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0056_alter_bookmark_origin_for_global_layout_and_more'),
        ('ui', '0056_listlayout_is_systemic'),
    ]

    operations = [
    ]
