# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chats', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='closed',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is closed'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads',
                                    to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='groups', to='chats.ThreadGroup', verbose_name='thread group'),
        ),
        migrations.AlterField(
            model_name='threadgroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='threadgroup',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_groups',
                                    to='users.MasterUser', verbose_name='master user'),
        ),
    ]
