# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20160824_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='threadgroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
