# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20160401_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'direct message', 'verbose_name_plural': 'direct messages'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': [('view_thread', 'Can view thread'), ('manage_thread', 'Can manage thread')], 'verbose_name': 'thread', 'verbose_name_plural': 'threads'},
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='status_date',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 4, 6, 7, 19, 49, 544542, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directmessage',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 4, 6, 7, 19, 52, 896924, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 4, 6, 7, 19, 55, 563241, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 4, 6, 7, 19, 57, 284393, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 4, 6, 7, 19, 59, 50587, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 4, 6, 7, 20, 1, 199257, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent_messages', to='users.Member'),
        ),
    ]
