# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20160922_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
