# Generated by Django 2.1.12 on 2019-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20190916_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='deleted user code'),
        ),
        migrations.AddField(
            model_name='threadgroup',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='deleted user code'),
        ),
    ]
