# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20160531_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': [('view_thread', 'Can view thread')], 'verbose_name': 'thread', 'verbose_name_plural': 'threads'},
        ),
    ]
