# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_thread_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'modified', 'ordering': ['thread', 'created'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'get_latest_by': 'modified', 'ordering': ['master_user', 'thread_group', 'subject'], 'permissions': [('view_thread', 'Can view thread'), ('manage_thread', 'Can manage thread')], 'verbose_name': 'thread', 'verbose_name_plural': 'threads'},
        ),
        migrations.AlterModelOptions(
            name='threadgroup',
            options={'ordering': ['master_user', 'name'], 'permissions': [('view_threadgroup', 'Can view thread group'), ('manage_threadgroup', 'Can manage thread group')], 'verbose_name': 'thread group', 'verbose_name_plural': 'thread groups'},
        ),
    ]
