# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'get_latest_by': 'modified', 'ordering': ['created'], 'verbose_name': 'direct message', 'verbose_name_plural': 'direct messages'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'modified', 'ordering': ['created'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'get_latest_by': 'modified', 'ordering': ['subject'], 'permissions': [('view_thread', 'Can view thread'), ('manage_thread', 'Can manage thread')], 'verbose_name': 'thread', 'verbose_name_plural': 'threads'},
        ),
        migrations.AlterModelOptions(
            name='threadgroup',
            options={'ordering': ['name'], 'permissions': [('view_threadgroup', 'Can view thread group'), ('manage_threadgroup', 'Can manage thread group')], 'verbose_name': 'thread group', 'verbose_name_plural': 'thread groups'},
        ),
    ]
