# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20160614_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_received_direct_messages', to='users.Member', verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent_direct_messages', to='users.Member', verbose_name='sender'),
        ),
    ]
