# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_auto_20160411_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadgroupobjectpermission',
            options={'verbose_name': 'threads - group permission', 'verbose_name_plural': 'threads - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='threaduserobjectpermission',
            options={'verbose_name': 'threads - user permission', 'verbose_name_plural': 'threads - user permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='threadgroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='threaduserobjectpermission',
            unique_together=set([]),
        ),
    ]
