# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_auto_20160614_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': [('view_thread', 'Can view thread'), ('manage_thread', 'Can manage thread')], 'verbose_name': 'thread', 'verbose_name_plural': 'threads'},
        ),
    ]
