# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_auto_20160704_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threadstatus',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='threadstatus',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='status',
        ),
        migrations.AddField(
            model_name='thread',
            name='closed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='ThreadStatus',
        ),
    ]
