# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_auto_20160411_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_received_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent_messages', to='users.Member', verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Thread', verbose_name='thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.ThreadStatus', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='threadgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='chats.Thread', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='threadgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='threadgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='threadstatus',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is closed'),
        ),
        migrations.AlterField(
            model_name='threadstatus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='threaduserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='chats.Thread', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='threaduserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='threaduserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
    ]
