# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160622_0720'),
        ('chats', '0011_auto_20160713_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threadgroups', to='users.MasterUser')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('name',),
                'verbose_name': 'thread group',
                'abstract': False,
                'verbose_name_plural': 'thread groups',
                'permissions': [('view_threadgroup', 'Can view thread group'), ('manage_threadgroup', 'Can manage thread group')],
            },
        ),
        migrations.AlterField(
            model_name='thread',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='users.MasterUser'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='chats.ThreadGroup'),
        ),
    ]
