# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160804_1250'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('chats', '0012_auto_20160719_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadGroupGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='chats.ThreadGroup', verbose_name='content object')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'verbose_name': 'thread groups - group permission',
                'abstract': False,
                'verbose_name_plural': 'thread groups - group permissions',
            },
        ),
        migrations.CreateModel(
            name='ThreadGroupUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='chats.ThreadGroup', verbose_name='content object')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'verbose_name': 'thread groups - user permission',
                'abstract': False,
                'verbose_name_plural': 'thread groups - user permissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='threadgroupuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='threadgroupgroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
    ]
