# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_auto_20160809_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_received_direct_messages', to='users.Member', verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_sent_direct_messages', to='users.Member', verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.Thread', verbose_name='thread'),
        ),
        migrations.AlterField(
            model_name='threadgroup',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_groups', to='users.MasterUser'),
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together=set([('thread', 'created')]),
        ),
    ]
