# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(max_length=50, verbose_name='short name')),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartyClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'counterparty classifiers',
                'verbose_name': 'counterparty classifier',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(max_length=50, verbose_name='short name')),
            ],
        ),
    ]
