# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='responsibleuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='responsiblegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.Responsible', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='responsiblegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='responsiblegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='responsibleclassifieruserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.ResponsibleClassifier', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='responsibleclassifieruserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='responsibleclassifieruserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='responsibleclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.ResponsibleClassifier', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='responsibleclassifiergroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='responsibleclassifiergroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='responsibleclassifier',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_classifiers', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='responsibleclassifier',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='counterparties.ResponsibleClassifier', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.ResponsibleAttributeType', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypeoption',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='counterparties.ResponsibleAttributeType', verbose_name='attribute type'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_attribute_type_options', to='users.Member', verbose_name='meber'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.ResponsibleAttributeType', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='responsibleattributetypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='responsibleattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.ResponsibleClassifier', verbose_name='classifier (root)'),
        ),
        migrations.AddField(
            model_name='responsibleattributetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='responsibleattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='counterparties.ResponsibleAttributeType', verbose_name='attribute type'),
        ),
        migrations.AddField(
            model_name='responsibleattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.ResponsibleClassifier', verbose_name='classifier'),
        ),
        migrations.AddField(
            model_name='responsibleattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='counterparties.Responsible', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='counterpartyuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.Counterparty', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='counterpartyuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='counterpartyuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='counterpartygroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.Counterparty', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='counterpartygroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='counterpartygroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifieruserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.CounterpartyClassifier', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifieruserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifieruserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.CounterpartyClassifier', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifiergroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifiergroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifier',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_classifiers', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='counterpartyclassifier',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='counterparties.CounterpartyClassifier', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.CounterpartyAttributeType', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypeoption',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='counterparties.CounterpartyAttributeType', verbose_name='attribute type'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_attribute_type_options', to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.CounterpartyAttributeType', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.CounterpartyClassifier', verbose_name='classifier (root)'),
        ),
        migrations.AddField(
            model_name='counterpartyattributetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='counterpartyattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='counterparties.CounterpartyAttributeType', verbose_name='attribute type'),
        ),
        migrations.AddField(
            model_name='counterpartyattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.CounterpartyClassifier', verbose_name='classifier'),
        ),
        migrations.AddField(
            model_name='counterpartyattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='counterparties.Counterparty', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattribute',
            unique_together=set([('content_object', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsible',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattribute',
            unique_together=set([('content_object', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterparty',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
