# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_auto_20160425_0912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counterpartyattributetype',
            unique_together=set([('master_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattributetypegroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattributetypeuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyclassifier',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyclassifiergroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyclassifieruserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartygroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattributetype',
            unique_together=set([('master_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattributetypegroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattributetypeuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifier',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifiergroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifieruserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsiblegroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
    ]
