# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('counterparties', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='counterparties', to='counterparties.CounterpartyGroup',
                                    verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='is_valid_for_all_portfolios',
            field=models.BooleanField(default=True, verbose_name='is valid for all portfolios'),
        ),
        migrations.AlterField(
            model_name='counterpartygroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='responsibles', to='counterparties.ResponsibleGroup',
                                    verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='is_valid_for_all_portfolios',
            field=models.BooleanField(default=True, verbose_name='is valid for all portfolios'),
        ),
        migrations.AlterField(
            model_name='responsiblegroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
    ]
