# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_auto_20160907_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterpartygroup',
            options={'permissions': [('view_counterpartygroup', 'Can view counterparty group'), ('manage_counterpartygroup', 'Can manage counterparty group')], 'verbose_name': 'counterparty group', 'verbose_name_plural': 'counterparty groups'},
        ),
        migrations.AlterModelOptions(
            name='responsiblegroup',
            options={'permissions': [('view_responsiblegroup', 'Can view responsible group'), ('manage_responsiblegroup', 'Can manage responsible group')], 'verbose_name': 'responsible group', 'verbose_name_plural': 'responsible groups'},
        ),
        migrations.AlterField(
            model_name='counterpartyattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='counterparties.CounterpartyAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifier',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='counterparties.CounterpartyAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='responsibleattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='counterparties.ResponsibleAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_attribute_type_options', to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifier',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='counterparties.ResponsibleAttributeType', verbose_name='attribute type'),
        ),
    ]
