# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_auto_20160305_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
