# Generated by Django 2.1.12 on 2019-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0004_auto_20190916_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='deleted user code'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='counterpartygroup',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='deleted user code'),
        ),
        migrations.AddField(
            model_name='counterpartygroup',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='deleted user code'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='responsiblegroup',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='deleted user code'),
        ),
        migrations.AddField(
            model_name='responsiblegroup',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is enabled'),
        ),
    ]
