# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0004_auto_20160305_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short name'),
        ),
    ]
