# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0005_auto_20160306_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsible',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='counterparty',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsible',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
