# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0007_auto_20160525_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterpartyclassifier',
            options={'verbose_name': 'counterparty classifier', 'verbose_name_plural': 'counterparty classifiers'},
        ),
        migrations.RemoveField(
            model_name='counterpartyattributetype',
            name='classifier_root',
        ),
        migrations.RemoveField(
            model_name='responsibleattributetype',
            name='classifier_root',
        ),
        migrations.AddField(
            model_name='counterpartyclassifier',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='counterparties.CounterpartyAttributeType', verbose_name='attribute type'),
        ),
        migrations.AddField(
            model_name='responsibleclassifier',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='counterparties.ResponsibleAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyclassifier',
            unique_together=set([('attribute_type', 'user_code')]),
        ),
    ]
