# Generated by Django 2.2.5 on 2021-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('counterparties', '0007_auto_20200525_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='counterpartygroup',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='responsiblegroup',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
    ]
