# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0008_auto_20160525_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibleclassifier',
            options={'verbose_name': 'responsible classifier', 'verbose_name_plural': 'responsible classifiers'},
        ),
        migrations.RemoveField(
            model_name='counterpartyclassifier',
            name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifier',
            unique_together=set([('attribute_type', 'user_code')]),
        ),
    ]
