# Generated by Django 2.2.5 on 2021-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('counterparties', '0008_auto_20210312_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='counterpartygroup',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='responsiblegroup',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
    ]
