# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0009_auto_20160525_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibleclassifier',
            name='master_user',
        ),
    ]
