# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160407_0945'),
        ('counterparties', '0012_auto_20160411_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyAccountAttributeTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_options', to='counterparties.CounterpartyAttributeType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_attribute_type_options', to='users.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAccountAttributeTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_options', to='counterparties.ResponsibleAttributeType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_attribute_type_options', to='users.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='responsibleaccountattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyaccountattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
    ]
