# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0013_auto_20160704_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counterpartyclassifier',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleclassifier',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='counterpartyclassifier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='counterpartyclassifier',
            name='public_name',
        ),
        migrations.RemoveField(
            model_name='counterpartyclassifier',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='counterpartyclassifier',
            name='user_code',
        ),
        migrations.RemoveField(
            model_name='responsibleclassifier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='responsibleclassifier',
            name='public_name',
        ),
        migrations.RemoveField(
            model_name='responsibleclassifier',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='responsibleclassifier',
            name='user_code',
        ),
    ]
