# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0014_auto_20160411_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterpartyattribute',
            options={'verbose_name': 'counterparty attribute', 'verbose_name_plural': 'counterparty attributes'},
        ),
        migrations.AlterModelOptions(
            name='responsibleattribute',
            options={'verbose_name': 'responsible attribute', 'verbose_name_plural': 'responsible attributes'},
        ),
    ]
