# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0015_auto_20160411_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartyattributetype',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10),
        ),
        migrations.AlterField(
            model_name='responsibleattributetype',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10),
        ),
    ]
