# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0016_auto_20160412_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterpartyattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='counterpartyattribute',
            name='attributebase_ptr',
        ),
        migrations.RemoveField(
            model_name='counterpartyattribute',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='counterpartyattribute',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='responsibleattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='responsibleattribute',
            name='attributebase_ptr',
        ),
        migrations.RemoveField(
            model_name='responsibleattribute',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='responsibleattribute',
            name='content_object',
        ),
        migrations.DeleteModel(
            name='CounterpartyAttribute',
        ),
        migrations.DeleteModel(
            name='ResponsibleAttribute',
        ),
    ]
