# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0017_auto_20160413_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='counterparties.CounterpartyAttributeType')),
                ('classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.CounterpartyClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.Counterparty')),
            ],
            options={
                'verbose_name_plural': 'counterparty attributes',
                'verbose_name': 'counterparty attribute',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='counterparties.ResponsibleAttributeType')),
                ('classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.ResponsibleClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.Responsible')),
            ],
            options={
                'verbose_name_plural': 'responsible attributes',
                'verbose_name': 'responsible attribute',
            },
        ),
    ]
