# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0018_counterpartyattribute_responsibleattribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counterpartyattribute',
            unique_together=set([('content_object', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattribute',
            unique_together=set([('content_object', 'attribute_type')]),
        ),
    ]
