# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0021_auto_20160419_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartyattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='counterparties.CounterpartyAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='counterpartyattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.CounterpartyClassifier', verbose_name='classifier'),
        ),
        migrations.AlterField(
            model_name='counterpartyattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.Counterparty', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='counterpartyattribute',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='value (Date)'),
        ),
        migrations.AlterField(
            model_name='counterpartyattribute',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value (Float)'),
        ),
        migrations.AlterField(
            model_name='counterpartyattribute',
            name='value_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='value (String)'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.CounterpartyClassifier', verbose_name='classifier (root)'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetype',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10, verbose_name='value type'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.CounterpartyAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypeoption',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_options', to='counterparties.CounterpartyAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypeoption',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_attribute_type_options', to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.CounterpartyAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='counterpartyattributetypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifier',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='counterparties.CounterpartyClassifier', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.CounterpartyClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifiergroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifiergroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifieruserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.CounterpartyClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifieruserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='counterpartyclassifieruserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='counterpartygroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.Counterparty', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='counterpartygroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='counterpartygroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='counterpartyuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.Counterparty', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='counterpartyuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='counterpartyuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='responsibleattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='counterparties.ResponsibleAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='responsibleattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.ResponsibleClassifier', verbose_name='classifier'),
        ),
        migrations.AlterField(
            model_name='responsibleattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.Responsible', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='responsibleattribute',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='value (Date)'),
        ),
        migrations.AlterField(
            model_name='responsibleattribute',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value (Float)'),
        ),
        migrations.AlterField(
            model_name='responsibleattribute',
            name='value_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='value (String)'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.ResponsibleClassifier', verbose_name='classifier (root)'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetype',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10, verbose_name='value type'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.ResponsibleAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypeoption',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_options', to='counterparties.ResponsibleAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypeoption',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_attribute_type_options', to='users.Member', verbose_name='meber'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.ResponsibleAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='responsibleattributetypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifier',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='counterparties.ResponsibleClassifier', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.ResponsibleClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifiergroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifiergroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifieruserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.ResponsibleClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifieruserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='responsibleclassifieruserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='responsiblegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='counterparties.Responsible', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='responsiblegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='responsiblegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='responsibleuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='counterparties.Responsible', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='responsibleuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='responsibleuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
    ]
