# Generated by Django 4.2.3 on 2024-07-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhitelabelModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Client company name",
                        max_length=255,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "theme_code",
                    models.CharField(
                        blank=True,
                        help_text="com.finmars.client-a",
                        max_length=255,
                        null=True,
                        verbose_name="Theme Code",
                    ),
                ),
                (
                    "theme_css_url",
                    models.URLField(max_length=512, verbose_name="Theme CSS URL"),
                ),
                (
                    "logo_dark_url",
                    models.URLField(max_length=512, verbose_name="Dark Logo URL"),
                ),
                (
                    "logo_light_url",
                    models.URLField(max_length=512, verbose_name="Light Logo URL"),
                ),
                (
                    "favicon_url",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Favicon URL",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(blank=True, null=True, verbose_name="Custom CSS"),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
