# Generated by Django 4.2.3 on 2024-07-09 13:02

from django.db import migrations, models
import django.db.models.deletion
import poms.common.encrypted_field


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_ecosystemdefault_currency_pricing_scheme_and_more'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, null=True, verbose_name='user code')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('data', poms.common.encrypted_field.EncryptedTextField()),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
            ],
            options={
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
    ]
