# Generated by Django 4.2.16 on 2025-03-10 13:05

from django.db import migrations


def fill_required_fields(apps, schema_editor) -> None:
    WhitelabelModel = apps.get_model("system", "WhitelabelModel")

    for white_label in WhitelabelModel.objects.all():
        white_label.user_code = white_label.theme_code
        white_label.save()

def reverse(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_whitelabelmodel'),
    ]

    operations = [
        migrations.RunPython(fill_required_fields, reverse),
    ]
