# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='event_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.EventClass', verbose_name='event class'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='notification_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.NotificationClass', verbose_name='notification class'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='transaction_types',
            field=models.ManyToManyField(blank=True, to='transactions.TransactionType', verbose_name='transaction types'),
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='accrual_calculation_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.AccrualCalculationModel', verbose_name='accrual calculation model'),
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_calculation_schedules', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='periodicity_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PeriodicityPeriod', verbose_name='periodicity period'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicy',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterIndexTogether(
            name='pricehistory',
            index_together=set([('instrument', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='manualpricingformula',
            unique_together=set([('instrument', 'pricing_policy')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttype',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifier',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattribute',
            unique_together=set([('content_object', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
