# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpolicy',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_policies',
                                    to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices',
                                    to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='manualpricingformula',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_pricing_formulas',
                                    to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='manualpricingformula',
            name='pricing_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_pricing_formulas',
                                    to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
    ]
