# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('instruments', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpolicy',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_policies', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='manualpricingformula',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_pricing_formulas', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='manualpricingformula',
            name='pricing_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_pricing_formulas', to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='instrumentuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.Instrument', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='instrumentuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='instrumentuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='instrumenttypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentType', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='instrumenttypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='instrumenttypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='instrumenttypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentType', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='instrumenttypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='instrumenttypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='instrument_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_types', to='instruments.InstrumentClass', verbose_name='instrument class'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_types', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
