# Generated by Django 4.1.3 on 2022-12-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
        ("instruments", "0001_initial"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="pricingpolicy",
        #     name="default_currency_pricing_scheme",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         to="pricing.currencypricingscheme",
        #         verbose_name="default currency pricing scheme",
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="pricingpolicy",
        #     name="default_instrument_pricing_scheme",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         to="pricing.instrumentpricingscheme",
        #         verbose_name="default instrument pricing scheme",
        #     ),
        # ),
    ]
