# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0002_initial'),
        # ('portfolios', '0001_initial'),
        ('accounts', '0002_initial'),
        ('currencies', '0003_initial'),
        # ('strategies', '0001_initial'),
        # ('transactions', '0001_initial'),
        # ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpolicy',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_policies', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.pricingpolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='manualpricingformula',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_pricing_formulas', to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='manualpricingformula',
            name='pricing_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_pricing_formulas', to='instruments.pricingpolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_factor_schedules', to='instruments.instrumenttype', verbose_name='instrument attributes'),
        ),
        migrations.AddField(
            model_name='instrumenttypeinstrumentattribute',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_attributes', to='instruments.instrumenttype', verbose_name='instrument attributes'),
        ),
        migrations.AddField(
            model_name='instrumenttypeevent',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='instruments.instrumenttype', verbose_name='instrument type'),
        ),
        migrations.AddField(
            model_name='instrumenttypeaccrual',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='instruments.instrumenttype', verbose_name='instrument type'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='accrued_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrument_types_accrued', to='currencies.currency', verbose_name='accrued currency'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='exposure_calculation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.exposurecalculationmodel', verbose_name='exposure calculation model'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='factor_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.transactiontype', verbose_name='factor down'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='factor_same',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.transactiontype', verbose_name='factor same'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='factor_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.transactiontype', verbose_name='factor up'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='instrument_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_types', to='instruments.instrumentclass', verbose_name='instrument class'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='long_underlying_exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_type_long_instruments', to='instruments.longunderlyingexposure', verbose_name='long underlying exposure'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_types', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='one_off_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.transactiontype', verbose_name='one-off event'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='payment_size_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.paymentsizedetail', verbose_name='payment size detail'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='pricing_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.pricingcondition', verbose_name='pricing condition'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='pricing_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrument_types_pricing', to='currencies.currency', verbose_name='pricing currency'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='regular_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.transactiontype', verbose_name='regular event'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='short_underlying_exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_type_short_instruments', to='instruments.shortunderlyingexposure', verbose_name='short underlying exposure'),
        ),
        migrations.AddField(
            model_name='instrumentfactorschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_schedules', to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='accrued_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments_accrued', to='currencies.currency', verbose_name='accrued currency'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='co_directional_exposure_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_directional_exposure_currency', to='currencies.currency', verbose_name='co directional exposure currency'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='counter_directional_exposure_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_directional_exposure_currency', to='currencies.currency', verbose_name='counter directional exposure currency'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='daily_pricing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.dailypricingmodel', verbose_name='daily pricing model'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='exposure_calculation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.exposurecalculationmodel', verbose_name='exposure calculation model'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrumenttype', verbose_name='instrument type'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='long_underlying_exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_instruments', to='instruments.longunderlyingexposure', verbose_name='long underlying exposure'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='long_underlying_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_underlying_instruments', to='instruments.instrument', verbose_name='long underlying instrument'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='payment_size_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.paymentsizedetail', verbose_name='payment size detail'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='pricing_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.pricingcondition', verbose_name='pricing condition'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='pricing_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency', verbose_name='pricing currency'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='short_underlying_exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_instruments', to='instruments.shortunderlyingexposure', verbose_name='short underlying exposure'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='short_underlying_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_underlying_instruments', to='instruments.instrument', verbose_name='short underlying instrument'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='accounts.account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to='instruments.eventscheduleaction', verbose_name='action'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='complex_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to='transactions.complextransaction', verbose_name='complex transaction'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='event_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_events', to='instruments.eventschedule', verbose_name='event schedule'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_events', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='portfolios.portfolio', verbose_name='portfolio'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='strategy1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='strategies.strategy1', verbose_name='strategy1'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='strategy2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='strategies.strategy2', verbose_name='strategy2'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='strategy3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='strategies.strategy3', verbose_name='strategy3'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to='transactions.transactiontype', verbose_name='transaction type'),
        ),
        migrations.AddField(
            model_name='eventscheduleconfig',
            name='master_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_event_schedule_config', to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='eventscheduleconfig',
            name='notification_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.notificationclass', verbose_name='notification class'),
        ),
        migrations.AddField(
            model_name='eventscheduleaction',
            name='event_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='instruments.eventschedule', verbose_name='event schedule'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='accrual_calculation_schedule',
            field=models.ForeignKey(blank=True, editable=False, help_text='Used for store link when is_auto_generated is True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_schedules', to='instruments.accrualcalculationschedule', verbose_name='accrual calculation schedule'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.eventclass', verbose_name='event class'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='factor_schedule',
            field=models.ForeignKey(blank=True, editable=False, help_text='Used for store link when is_auto_generated is True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_schedules', to='instruments.instrumentfactorschedule', verbose_name='factor schedule'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='notification_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.notificationclass', verbose_name='notification class'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.periodicity', verbose_name='periodicity'),
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='accrual_calculation_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.accrualcalculationmodel', verbose_name='accrual calculation model'),
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_calculation_schedules', to='instruments.instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.periodicity', verbose_name='periodicity'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicy',
            unique_together={('master_user', 'user_code')},
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('instrument', 'pricing_policy', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='manualpricingformula',
            unique_together={('instrument', 'pricing_policy')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttype',
            unique_together={('master_user', 'user_code')},
        ),
        migrations.AlterIndexTogether(
            name='instrumenttype',
            index_together={('master_user', 'is_deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('master_user', 'user_code')},
        ),
        migrations.AlterIndexTogether(
            name='instrument',
            index_together={('master_user', 'is_deleted')},
        ),
    ]
