# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20160304_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'instrument', 'verbose_name_plural': 'instruments'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'price history', 'verbose_name_plural': 'price histories'},
        ),
    ]
