# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

import datetime

import django.utils.timezone
from django.db import migrations, models

import poms.common.utils


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0003_auto_20161205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='accrual_calculation_schedule',
            field=models.ForeignKey(blank=True, editable=False,
                                    help_text='Used for store link when is_auto_generated is True', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules',
                                    to='instruments.AccrualCalculationSchedule',
                                    verbose_name='accrual calculation schedule'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='factor_schedule',
            field=models.ForeignKey(blank=True, editable=False,
                                    help_text='Used for store link when is_auto_generated is True', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules',
                                    to='instruments.InstrumentFactorSchedule', verbose_name='factor schedule'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='final_date',
            field=models.DateField(default=datetime.date(9999, 12, 31), verbose_name='final date'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='is_auto_generated',
            field=models.BooleanField(default=False, verbose_name='is auto generated'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='notify_in_n_days',
            field=models.PositiveIntegerField(default=0, verbose_name='notify in N days'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='instruments.Periodicity', verbose_name='periodicity'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='periodicity_n',
            field=models.IntegerField(default=0, verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='button_position',
            field=models.IntegerField(default=0, verbose_name='button position'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='is_book_automatic',
            field=models.BooleanField(default=True, verbose_name='is book automatic'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='is_sent_to_pending',
            field=models.BooleanField(default=True, verbose_name='is sent to pending'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionType',
                                    verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='action_is_book_automatic',
            field=models.BooleanField(default=True, verbose_name='action is book automatic'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='action_is_sent_to_pending',
            field=models.BooleanField(default=True, verbose_name='action is sent to pending'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='accounts.Account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='generated_events', to='instruments.EventScheduleAction',
                                    verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='complex_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='transactions.ComplexTransaction',
                                    verbose_name='complex transaction'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='effective_date',
            field=models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='effective date'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='effective_date_notified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='effective date notified'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='event_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='generated_events', to='instruments.EventSchedule',
                                    verbose_name='event schedule'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='instruments.Instrument',
                                    verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_events',
                                    to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='notification_date',
            field=models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='notification date'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='notification_date_notified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='notification date notified'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='portfolios.Portfolio',
                                    verbose_name='portfolio'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='position',
            field=models.FloatField(default=0.0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'New'), (2, 'Ignored'), (3, 'Book pending'), (4, 'Booked')], db_index=True, default=1,
                verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='status_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='status date'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='strategy1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='strategies.Strategy1',
                                    verbose_name='strategy1'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='strategy2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='strategies.Strategy2',
                                    verbose_name='strategy2'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='strategy3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='strategies.Strategy3',
                                    verbose_name='strategy3'),
        ),
        migrations.AlterField(
            model_name='generatedevent',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='generated_events', to='transactions.TransactionType',
                                    verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='user_text_1',
            field=models.CharField(blank=True, help_text='User specified field 1', max_length=255, null=True,
                                   verbose_name='user text 1'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='user_text_2',
            field=models.CharField(blank=True, help_text='User specified field 2', max_length=255, null=True,
                                   verbose_name='user text 2'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='user_text_3',
            field=models.CharField(blank=True, help_text='User specified field 3', max_length=255, null=True,
                                   verbose_name='user text 3'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
    ]
