# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_auto_20160425_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentattributetype',
            options={'permissions': [('view_instrumentattributetype', 'Can view instrument attribute type')], 'verbose_name': 'instrument attribute type', 'verbose_name_plural': 'instrument attribute types'},
        ),
    ]
