# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0004_auto_20170125_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='maturity_price',
            field=models.FloatField(default=0.0, verbose_name='maturity price'),
        ),
    ]
