# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160902_1051'),
        ('users', '0001_initial'),
        ('instruments', '0004_auto_20160902_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScheduleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('notify_in_n_days', models.PositiveSmallIntegerField(default=0, verbose_name='notify in N days')),
                ('action_text', models.CharField(blank=True, default='', max_length=255, verbose_name='action text')),
                ('action_is_sent_to_pending', models.BooleanField(default=True)),
                ('action_is_book_automatic', models.BooleanField(default=True)),
                ('master_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_event_schedule_config', to='users.MasterUser', verbose_name='master user')),
                ('notification_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.NotificationClass', verbose_name='notification class')),
            ],
            options={
                'verbose_name_plural': 'event schedule configs',
                'verbose_name': 'event schedule config',
            },
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='factor_schedule',
            field=models.ForeignKey(blank=True, editable=False, help_text='Used for store link when is_auto_generated is True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='instruments.InstrumentFactorSchedule'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='accrual_calculation_schedule',
            field=models.ForeignKey(blank=True, editable=False, help_text='Used for store link when is_auto_generated is True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='instruments.AccrualCalculationSchedule'),
        ),
    ]
