# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_auto_20160505_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifieruserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentclassifieruserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumentclassifieruserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumentclassifieruserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumenttypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumenttypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumenttypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumentuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumentuserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='InstrumentAttributeTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentClassifierUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentUserObjectPermission',
        ),
    ]
