# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160902_1051'),
        ('instruments', '0005_auto_20160902_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='factor_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionType', verbose_name='factor down'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='factor_same',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionType', verbose_name='factor same'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='factor_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionType', verbose_name='factor up'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='one_off_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionType', verbose_name='one-off event'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='regular_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.TransactionType', verbose_name='regular event'),
        ),
    ]
