# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0005_instrument_maturity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='expression'),
        ),
    ]
