# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20160525_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentattributetype',
            name='classifier_root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentClassifier', verbose_name='classifier'),
        ),
    ]
