# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20170512_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Ignored'), (3, 'Book pending'), (4, 'Booked'), (5, 'Book (default)')], db_index=True, default=1, verbose_name='status'),
        ),
    ]
