# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20160905_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='instruments.InstrumentAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifier',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='instruments.InstrumentAttributeType', verbose_name='attribute type'),
        ),
    ]
