# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20160525_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentclassifier',
            options={'verbose_name': 'instrument classifier', 'verbose_name_plural': 'instrument classifiers'},
        ),
        migrations.RemoveField(
            model_name='instrumentattributetype',
            name='classifier_root',
        ),
        migrations.AddField(
            model_name='instrumentclassifier',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='instruments.InstrumentAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifier',
            unique_together=set([('attribute_type', 'user_code')]),
        ),
    ]
