# Generated by Django 4.1.3 on 2023-04-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_pricehistory_factor'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='pricehistory',
            index_together={('instrument', 'pricing_policy', 'date')},
        ),
    ]
