# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20181225_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Informed'), (3, 'Booked (system)'), (4, 'Booked (user)'), (5, 'Booked, pending (system)'), (6, 'Booked, pending (user)')], db_index=True, default=1, verbose_name='status'),
        ),
    ]
