# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_auto_20190213_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Informed'), (3, 'Booked (system, default)'), (4, 'Booked (user, actions)'), (5, 'Booked (user, default)')], db_index=True, default=1, verbose_name='status'),
        ),
    ]
