# Generated by Django 4.1.3 on 2023-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0010_instrumenttype_configuration_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="user_code",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="user code"
            ),
        ),
        migrations.AlterField(
            model_name="instrumenttype",
            name="user_code",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="user code"
            ),
        ),
        migrations.AlterField(
            model_name="pricingpolicy",
            name="user_code",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="user code"
            ),
        ),
    ]
