# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0010_auto_20160404_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentClass',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=1, serialize=False)),
                ('system_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='system code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'instrument class',
                'verbose_name_plural': 'instrument classes',
            },
        ),
    ]
