# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-03 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0011_auto_20190614_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Informed'), (3, 'Booked (system, default)'), (4, 'Booked (user, actions)'), (5, 'Booked (user, default)'), (6, 'Booked, pending (system, default)'), (7, 'Booked, pending (user, actions)'), (8, 'Booked, pending (user, default)'), (9, 'Error')], db_index=True, default=1, verbose_name='status'),
        ),
    ]
