# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160404_1010'),
        ('instruments', '0011_instrumentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('instrument_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_types', to='instruments.InstrumentClass', verbose_name='instrument class')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_types', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'permissions': [('view_instrumenttype', 'Can view instrument type')],
                'verbose_name': 'instrument type',
                'verbose_name_plural': 'instrument types',
            },
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttype',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
