# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0013_auto_20160601_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='type',
            new_name='instrument_type',
        ),
    ]
