# Generated by Django 4.1.3 on 2023-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0013_alter_instrument_deleted_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttype',
            name='configuration_code',
            field=models.CharField(max_length=255, verbose_name='Configuration Code'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='configuration_code',
            field=models.CharField(max_length=255, verbose_name='Configuration Code'),
        ),
    ]
