# Generated by Django 2.1.12 on 2019-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0014_auto_20190930_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
    ]
