# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0014_auto_20160615_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentType', verbose_name='instrument type'),
        ),
    ]
