# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160404_1010'),
        ('instruments', '0014_auto_20160404_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_tags', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'permissions': [('view_instrumenttag', 'Can view instrument tag')],
                'verbose_name': 'instrument tag',
                'verbose_name_plural': 'instrument tags',
            },
        ),
        migrations.CreateModel(
            name='InstrumentTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumenttype_tags', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'permissions': [('view_instrumenttypetag', 'Can view instrument type tag')],
                'verbose_name': 'instrument type tag',
                'verbose_name_plural': 'instrument type tags',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='tags',
            field=models.ManyToManyField(blank=True, to='instruments.InstrumentTag'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='tags',
            field=models.ManyToManyField(blank=True, to='instruments.InstrumentTypeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypetag',
            unique_together=set([('master_user', 'user_code'), ('master_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttag',
            unique_together=set([('master_user', 'user_code'), ('master_user', 'name')]),
        ),
    ]
