# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0015_auto_20161003_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrualcalculationmodel',
            options={'ordering': ['name'], 'verbose_name': 'accrual calculation model', 'verbose_name_plural': 'accrual calculation models'},
        ),
        migrations.AlterModelOptions(
            name='accrualcalculationschedule',
            options={'ordering': ['instrument', 'accrual_start_date'], 'verbose_name': 'accrual calculation schedule', 'verbose_name_plural': 'accrual calculation schedules'},
        ),
        migrations.AlterModelOptions(
            name='costmethod',
            options={'ordering': ['name'], 'verbose_name': 'cost method', 'verbose_name_plural': 'cost methods'},
        ),
        migrations.AlterModelOptions(
            name='dailypricingmodel',
            options={'ordering': ['name'], 'verbose_name': 'daily pricing model', 'verbose_name_plural': 'daily pricing models'},
        ),
        migrations.AlterModelOptions(
            name='eventschedule',
            options={'ordering': ['instrument', 'effective_date', 'name'], 'verbose_name': 'event schedule', 'verbose_name_plural': 'event schedules'},
        ),
        migrations.AlterModelOptions(
            name='eventscheduleaction',
            options={'ordering': ['event_schedule', 'is_book_automatic', 'button_position'], 'verbose_name': 'event schedule action', 'verbose_name_plural': 'event schedule actions'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['master_user', 'instrument_type', 'user_code'], 'permissions': [('view_instrument', 'Can view instrument'), ('manage_instrument', 'Can manage instrument')], 'verbose_name': 'instrument', 'verbose_name_plural': 'instruments'},
        ),
        migrations.AlterModelOptions(
            name='instrumentattribute',
            options={'ordering': ['content_object', 'attribute_type'], 'verbose_name': 'instrument attribute', 'verbose_name_plural': 'instrument attributes'},
        ),
        migrations.AlterModelOptions(
            name='instrumentattributetype',
            options={'ordering': ['master_user', 'name'], 'permissions': [('view_instrumentattributetype', 'Can view instrument attribute type'), ('manage_instrumentattributetype', 'Can manage instrument attribute type')], 'verbose_name': 'instrument attribute type', 'verbose_name_plural': 'instrument attribute types'},
        ),
        migrations.AlterModelOptions(
            name='instrumentclass',
            options={'ordering': ['name'], 'verbose_name': 'instrument class', 'verbose_name_plural': 'instrument classes'},
        ),
        migrations.AlterModelOptions(
            name='instrumentclassifier',
            options={'ordering': ['attribute_type', 'tree_id', 'level', 'name'], 'verbose_name': 'instrument classifier', 'verbose_name_plural': 'instrument classifiers'},
        ),
        migrations.AlterModelOptions(
            name='instrumentfactorschedule',
            options={'ordering': ['instrument', 'effective_date'], 'verbose_name': 'instrument factor schedule', 'verbose_name_plural': 'instrument factor schedules'},
        ),
        migrations.AlterModelOptions(
            name='instrumenttype',
            options={'ordering': ['master_user', 'user_code'], 'permissions': [('view_instrumenttype', 'Can view instrument type'), ('manage_instrumenttype', 'Can manage instrument type')], 'verbose_name': 'instrument type', 'verbose_name_plural': 'instrument types'},
        ),
        migrations.AlterModelOptions(
            name='manualpricingformula',
            options={'ordering': ['instrument', 'pricing_policy'], 'verbose_name': 'manual pricing formula', 'verbose_name_plural': 'manual pricing formulas'},
        ),
        migrations.AlterModelOptions(
            name='paymentsizedetail',
            options={'ordering': ['name'], 'verbose_name': 'payment size detail', 'verbose_name_plural': 'payment size details'},
        ),
        migrations.AlterModelOptions(
            name='periodicity',
            options={'ordering': ['name'], 'verbose_name': 'periodicity', 'verbose_name_plural': 'periodicities'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['instrument', 'pricing_policy', 'date'], 'verbose_name': 'price history', 'verbose_name_plural': 'price histories'},
        ),
        migrations.AlterModelOptions(
            name='pricingpolicy',
            options={'ordering': ['name'], 'verbose_name': 'pricing policy', 'verbose_name_plural': 'pricing policies'},
        ),
    ]
