# Generated by Django 2.2.5 on 2020-01-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('instruments', '0015_auto_20191003_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingpolicy',
            options={'ordering': ['user_code'], 'verbose_name': 'pricing policy', 'verbose_name_plural': 'pricing policies'},
        ),
        migrations.AlterUniqueTogether(
            name='pricingpolicy',
            unique_together={('master_user', 'user_code')},
        ),
    ]
