# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import poms.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0017_auto_20160621_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_start_date',
            field=models.DateField(default=poms.common.utils.date_now, verbose_name='accrual start date'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='first_payment_date',
            field=models.DateField(default=poms.common.utils.date_now, verbose_name='first payment date'),
        ),
        migrations.AlterField(
            model_name='instrumentfactorschedule',
            name='effective_date',
            field=models.DateField(default=poms.common.utils.date_now, verbose_name='effective date'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date'),
        ),
    ]
