# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0017_auto_20161003_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentattributetypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypegroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypegroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypegroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentgroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumentgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='instrumentgroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumenttypegroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumenttypegroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='instrumenttypegroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumenttypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumenttypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumenttypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='instrumentuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumentuserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='InstrumentAttributeTypeGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentAttributeTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentTypeGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='InstrumentUserObjectPermission',
        ),
    ]
