# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_auto_20161017_0916'),
        ('instruments', '0018_auto_20161017_0828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentattribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='instrumentattribute',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='instrumentattribute',
            name='content_object',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentattributetype',
            name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetypeoption',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeoption',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='instrumentattributetypeoption',
            name='member',
        ),
        migrations.RemoveField(
            model_name='instrumentclassifier',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='instrumentclassifier',
            name='parent',
        ),
        migrations.DeleteModel(
            name='InstrumentAttribute',
        ),
        migrations.DeleteModel(
            name='InstrumentAttributeType',
        ),
        migrations.DeleteModel(
            name='InstrumentAttributeTypeOption',
        ),
        migrations.DeleteModel(
            name='InstrumentClassifier',
        ),
    ]
