# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160404_1010'),
        ('instruments', '0018_auto_20160404_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPricingFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_pricing_formulas', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name': 'manual pricing formula',
                'verbose_name_plural': 'manual pricing formulas',
                'permissions': [('view_manualpricingformula', 'Can view manual pricing formula')],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='manual_pricing_formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.ManualPricingFormula'),
        ),
        migrations.AlterUniqueTogether(
            name='manualpricingformula',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
