# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import poms.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_auto_20161017_0828'),
        ('users', '0005_auto_20161003_1409'),
        ('portfolios', '0015_auto_20161017_0916'),
        ('transactions', '0034_auto_20161017_0916'),
        ('accounts', '0015_auto_20161017_0916'),
        ('instruments', '0019_auto_20161017_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(db_index=True, default=poms.common.utils.date_now)),
                ('notification_date', models.DateField(db_index=True, default=poms.common.utils.date_now)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Ignored'), (3, 'Book pending'), (4, 'Booked')], db_index=True, default=1)),
                ('status_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('position', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='accounts.Account')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to='instruments.EventScheduleAction')),
                ('event_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to='instruments.EventSchedule')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='instruments.Instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_events', to='users.MasterUser')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Member')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='portfolios.Portfolio')),
                ('strategy1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='strategies.Strategy1')),
                ('strategy2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='strategies.Strategy2')),
                ('strategy3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='strategies.Strategy3')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_events', to='transactions.TransactionType')),
            ],
            options={
                'verbose_name': 'generated event',
                'ordering': ['effective_date'],
                'verbose_name_plural': 'generated events',
            },
        ),
    ]
