# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0020_auto_20160704_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDownloadMode',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='system code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'cost method',
                'verbose_name_plural': 'cost methods',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='price_download_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.PriceDownloadMode'),
        ),
    ]
