# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0021_generatedevent_complex_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedevent',
            name='effective_date_notified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='notification_date_notified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
