# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0021_auto_20160712_0842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set([('instrument', 'pricing_policy', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='pricehistory',
            index_together=set([]),
        ),
    ]
