# Generated by Django 4.2.3 on 2024-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0021_instrumenttypepricingpolicy_instrumentpricingpolicy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accrualcalculationschedule",
            options={
                "ordering": ["instrument", "accrual_start_date"],
                "verbose_name": "accrual calculation schedule",
                "verbose_name_plural": "accrual calculation schedules",
            },
        ),
        migrations.AddConstraint(
            model_name="accrualcalculationschedule",
            constraint=models.UniqueConstraint(
                fields=("instrument", "accrual_start_date"),
                name="unique_instrument_accrual",
            ),
        ),
    ]
