# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0022_auto_20160801_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accrualcalculationmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='accrualcalculationmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='costmethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='costmethod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dailypricingmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dailypricingmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instrumentclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instrumentclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymentsizedetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentsizedetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='periodicityperiod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='periodicityperiod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pricedownloadmode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pricedownloadmode',
            name='name',
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (en)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description (es)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description (ru)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (es)'),
        ),
        migrations.AlterField(
            model_name='pricedownloadmode',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name (ru)'),
        ),
    ]
