# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0023_auto_20160802_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='factor',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifier',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumentclassifier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='instrumentclassifier',
            name='public_name',
        ),
        migrations.RemoveField(
            model_name='instrumentclassifier',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='instrumentclassifier',
            name='user_code',
        ),
    ]
