# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0024_auto_20160804_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='isin',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ISIN'),
        ),
    ]
