# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0024_manualpricingformula_expr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualCalculationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('new_accrual_start_date', models.DateField(default=django.utils.timezone.now)),
                ('new_first_payment_date', models.DateField(default=django.utils.timezone.now)),
                ('new_accrual_size', models.FloatField(default=0.0)),
                ('accrual_calculation_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.AccrualCalculationModel')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_calculation_schedule', to='instruments.Instrument')),
                ('payment_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PaymentFrequency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
