# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0024_instrument_actual_at_instrument_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.RenameField(
            model_name='country',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='country',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.RenameField(
            model_name='instrumentpricingpolicy',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='instrumentpricingpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.RenameField(
            model_name='instrumentpricingpolicy',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='instrumentpricingpolicy',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.RenameField(
            model_name='instrumenttype',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.RenameField(
            model_name='instrumenttype',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.RenameField(
            model_name='instrumenttypepricingpolicy',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='instrumenttypepricingpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.RenameField(
            model_name='instrumenttypepricingpolicy',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='instrumenttypepricingpolicy',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.RenameField(
            model_name='pricingpolicy',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.RenameField(
            model_name='pricingpolicy',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
    ]
