# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0025_instrument_isin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeriodicityPeriod',
            new_name='Periodicity',
        ),
        migrations.AlterModelOptions(
            name='periodicity',
            options={'verbose_name': 'periodicity', 'verbose_name_plural': 'periodicities'},
        ),
        migrations.RemoveField(
            model_name='accrualcalculationschedule',
            name='periodicity_period',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='price_download_mode',
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='n',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.Periodicity', verbose_name='periodicity'),
        ),
    ]
