# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0025_accrualcalculationschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='classifiers',
        ),
    ]
