# Generated by Django 4.2.3 on 2024-08-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0004_finmarsdirectory_is_file_finmarsdirectory_size"),
        ("instruments", "0025_alter_country_options_remove_country_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Files in the storage related to the instrument",
                related_name="instruments",
                through="instruments.InstrumentAttachment",
                to="explorer.finmarsdirectory",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentattachment",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="explorer.finmarsdirectory",
            ),
        ),
    ]
