# Generated by Django 4.2.3 on 2024-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0025_alter_country_options_remove_country_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='first_transaction_date',
            field=models.DateField(null=True, verbose_name='first transaction date'),
        ),
    ]
