# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0027_auto_20160406_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpricingformula',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='manualpricingformula',
            name='pricing_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.PricingPolicy'),
        ),
    ]
