# Generated by Django 4.2.16 on 2025-01-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0028_instrument_resource_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accrual",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_code", models.CharField(blank=True, default="", max_length=255, verbose_name="User code")),
                ("date", models.DateField(verbose_name="Accrual value date")),
                ("size", models.FloatField(default=0.0, verbose_name="Accrual size")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accruals",
                        to="instruments.instrument",
                        verbose_name="Instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accrual",
                "verbose_name_plural": "Accruals",
                "ordering": ["instrument", "date"],
            },
        ),
        migrations.AddConstraint(
            model_name="accrual",
            constraint=models.UniqueConstraint(
                fields=("instrument", "date"), name="unique_instrument_accrual_date"
            ),
        ),
    ]
