# Generated by Django 2.2.5 on 2020-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0028_auto_20200820_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='duration',
            field=models.FloatField(default=0.0, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='ytm',
            field=models.FloatField(default=0.0, verbose_name='ytm'),
        ),
    ]
