# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0029_auto_20160406_1424'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumenttag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumenttag',
            name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypetag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instrumenttypetag',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='tags',
        ),
        migrations.DeleteModel(
            name='InstrumentTag',
        ),
        migrations.DeleteModel(
            name='InstrumentTypeTag',
        ),
    ]
