# Generated by Django 4.2.16 on 2025-03-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0029_accrual_accrual_unique_instrument_accrual_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="accrual",
            name="accrual_calculation_model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.accrualcalculationmodel",
                verbose_name="accrual calculation model",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accrual",
            name="periodicity_n",
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="days between coupons"),
        ),
    ]
