# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0029_auto_20160818_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingpolicy',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='expression'),
        ),
    ]
