# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160407_0945'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('obj_attrs', '0014_auto_20160411_1247'),
        ('instruments', '0031_auto_20160407_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentAttribute',
            fields=[
                ('attributebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='obj_attrs.AttributeBase')),
            ],
            bases=('obj_attrs.attributebase',),
        ),
        migrations.CreateModel(
            name='InstrumentAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('order', models.IntegerField(default=0)),
                ('classifier_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentClassifier')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentAttributeTypeGroupObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentAttributeType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentAttributeTypeUserObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentAttributeType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentClassifierGroupObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentClassifier')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentClassifierUserObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentClassifier')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentGroupObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.Instrument')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentTypeGroupObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentTypeUserObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentUserObjectPermissionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.Instrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instrumentattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='instruments.InstrumentAttributeType'),
        ),
        migrations.AddField(
            model_name='instrumentattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentClassifier'),
        ),
        migrations.AddField(
            model_name='instrumentattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentuserobjectpermissionbase',
            unique_together=set([('member', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypeuserobjectpermissionbase',
            unique_together=set([('member', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypegroupobjectpermissionbase',
            unique_together=set([('group', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentgroupobjectpermissionbase',
            unique_together=set([('group', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifieruserobjectpermissionbase',
            unique_together=set([('member', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifiergroupobjectpermissionbase',
            unique_together=set([('group', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetypeuserobjectpermissionbase',
            unique_together=set([('member', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetypegroupobjectpermissionbase',
            unique_together=set([('group', 'content_object', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetype',
            unique_together=set([('master_user', 'name')]),
        ),
    ]
