# Generated by Django 2.2.5 on 2021-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0032_auto_20201118_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accrualcalculationmodel',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='costmethod',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='dailypricingmodel',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='instrumentclass',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='paymentsizedetail',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='periodicity',
            old_name='system_code',
            new_name='user_code'
        ),
        migrations.RenameField(
            model_name='pricingcondition',
            old_name='system_code',
            new_name='user_code'
        )
    ]
