# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0032_auto_20160411_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentClassifierGroupObjectPermissionBase',
            new_name='InstrumentAttributeTypeGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='InstrumentClassifierUserObjectPermissionBase',
            new_name='InstrumentAttributeTypeUserObjectPermission',
        ),
        migrations.RenameModel(
            old_name='InstrumentAttributeTypeGroupObjectPermissionBase',
            new_name='InstrumentClassifierGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='InstrumentAttributeTypeUserObjectPermissionBase',
            new_name='InstrumentClassifierUserObjectPermission',
        ),
        migrations.RenameModel(
            old_name='InstrumentTypeGroupObjectPermissionBase',
            new_name='InstrumentGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='InstrumentGroupObjectPermissionBase',
            new_name='InstrumentTypeGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='InstrumentTypeUserObjectPermissionBase',
            new_name='InstrumentTypeUserObjectPermission',
        ),
        migrations.RenameModel(
            old_name='InstrumentUserObjectPermissionBase',
            new_name='InstrumentUserObjectPermission',
        ),
        migrations.AlterField(
            model_name='instrumentattributetypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentAttributeType'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentAttributeType'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentClassifier'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifieruserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentClassifier'),
        ),
        migrations.AlterField(
            model_name='instrumentgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumenttypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentType'),
        ),
    ]
