# Generated by Django 2.2.5 on 2021-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0033_auto_20210210_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='periodicity',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='pricingcondition',
            name='user_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='user code'),
        ),
    ]
