# Generated by Django 2.2.5 on 2021-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0034_auto_20210210_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='instrument_form_layouts',
            field=models.TextField(blank=True, null=True, verbose_name='instrument form layouts'),
        ),
    ]
