# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0034_auto_20160411_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentAccountAttributeTypeOption',
            new_name='InstrumentAttributeTypeOption',
        ),
        migrations.AlterModelOptions(
            name='instrumentattribute',
            options={'verbose_name': 'instrument attribute', 'verbose_name_plural': 'instrument attributes'},
        ),
        migrations.AlterModelOptions(
            name='instrumentattributetype',
            options={'verbose_name': 'instrument attribute type', 'verbose_name_plural': 'instrument attribute types'},
        ),
        migrations.AlterModelOptions(
            name='instrumentattributetypegroupobjectpermission',
            options={'verbose_name': 'instrument attribute types - group permission', 'verbose_name_plural': 'instrument attribute types - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='instrumentattributetypeoption',
            options={'verbose_name': 'instrument attribute types - option', 'verbose_name_plural': 'instrument attribute types - options'},
        ),
        migrations.AlterModelOptions(
            name='instrumentattributetypeuserobjectpermission',
            options={'verbose_name': 'instrument attribute types - user permission', 'verbose_name_plural': 'instrument attribute types - user permissions'},
        ),
        migrations.AlterModelOptions(
            name='instrumentclassifiergroupobjectpermission',
            options={'verbose_name': 'instrument classifiers - group permission', 'verbose_name_plural': 'instrument classifiers - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='instrumentclassifieruserobjectpermission',
            options={'verbose_name': 'instrument classifiers - user permission', 'verbose_name_plural': 'instrument classifiers - user permissions'},
        ),
        migrations.AlterModelOptions(
            name='instrumentgroupobjectpermission',
            options={'verbose_name': 'instruments - group permission', 'verbose_name_plural': 'instruments - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='instrumenttypegroupobjectpermission',
            options={'verbose_name': 'instrument types - group permission', 'verbose_name_plural': 'instrument types - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='instrumenttypeuserobjectpermission',
            options={'verbose_name': 'instrument types - user permission', 'verbose_name_plural': 'instrument types - user permissions'},
        ),
        migrations.AlterModelOptions(
            name='instrumentuserobjectpermission',
            options={'verbose_name': 'instruments - user permission', 'verbose_name_plural': 'instruments - user permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetype',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetypeoption',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifiergroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentclassifieruserobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentgroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentuserobjectpermission',
            unique_together=set([]),
        ),
    ]
