# Generated by Django 2.2.5 on 2021-02-16 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0015_auto_20210125_1427'),
        ('instruments', '0035_instrumenttype_instrument_form_layouts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='exposure_currency_1',
            new_name="co_directional_exposure_currency"
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='exposure_currency_2',
            new_name="counter_directional_exposure_currency"
        )
    ]
