# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0036_auto_20160412_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpricingformula',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
