# Generated by Django 2.2.5 on 2021-02-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0037_auto_20210216_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='co_directional_exposure_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='co_directional_exposure_currency', to='currencies.Currency',
                                    verbose_name='co directional exposure currency'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='counter_directional_exposure_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='counter_directional_exposure_currency', to='currencies.Currency',
                                    verbose_name='counter directional exposure currency'),
        ),
    ]
