# Generated by Django 2.2.5 on 2021-02-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0015_auto_20210125_1427'),
        ('instruments', '0038_auto_20210216_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='accrued_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='instrument_types_accrued', to='currencies.Currency',
                                    verbose_name='accrued currency'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='accrued_multiplier',
            field=models.FloatField(default=1.0, verbose_name='accrued multiplier'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='default_accrued',
            field=models.FloatField(default=0.0, verbose_name='default accrued'),
        ),
    ]
