# Generated by Django 2.2.5 on 2021-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0041_instrumenttype_payment_size_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
    ]
