# Generated by Django 2.2.5 on 2021-03-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0043_auto_20210317_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='accrual size'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_start_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='accrual start date'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='first_payment_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first payment date'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='periodicity_n',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='periodicity n'),
        ),
    ]
