# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0043_auto_20160419_0739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentPeriod',
            new_name='PeriodicityPeriod',
        ),
        migrations.RenameField(
            model_name='accrualcalculationschedule',
            old_name='payment_period',
            new_name='periodicity_period',
        ),
    ]
