# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0044_auto_20160419_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicityperiod',
            options={'verbose_name': 'periodicity period', 'verbose_name_plural': 'periodicity periods'},
        ),
    ]
