# Generated by Django 2.2.5 on 2021-03-24 10:38

import django.db.models.deletion
from django.db import migrations, models


# import poms.cache_machine.base


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0045_auto_20210317_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureCalculationModel',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=255, unique=True, verbose_name='user code')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Exposure calculation model',
                'verbose_name_plural': 'Exposure calculation models ',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
            # bases=(poms.cache_machine.base.CachingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='instrument',
            name='exposure_calculation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='instruments.ExposureCalculationModel',
                                    verbose_name='exposure calculation model'),
        ),
    ]
