# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0046_auto_20160419_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrualcalculationschedule',
            options={'verbose_name': 'accrual calculation schedule', 'verbose_name_plural': 'accrual calculation schedules'},
        ),
        migrations.AlterModelOptions(
            name='eventschedule',
            options={'verbose_name': 'event schedule', 'verbose_name_plural': 'event schedules'},
        ),
        migrations.AlterModelOptions(
            name='instrumentfactorschedule',
            options={'verbose_name': 'instrument factor schedule', 'verbose_name_plural': 'instrument factor schedules'},
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationmodel',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_calculation_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.AccrualCalculationModel', verbose_name='accrual calculation model'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_size',
            field=models.FloatField(default=0.0, verbose_name='accrual size'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='accrual start date'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='first_payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='first payment date'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_calculation_schedules', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='periodicity_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PeriodicityPeriod', verbose_name='periodicity period'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='costmethod',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dailypricingmodel',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='effective date'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='event_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.EventClass', verbose_name='event class'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='notification_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.NotificationClass', verbose_name='notification class'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='notification date'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='transaction_types',
            field=models.ManyToManyField(blank=True, to='transactions.TransactionType', verbose_name='transaction types'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='accrued_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments_accrued', to='currencies.Currency', verbose_name='accrued currency'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='accrued_multiplier',
            field=models.FloatField(default=1.0, verbose_name='accrued multiplier'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='daily_pricing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.DailyPricingModel', verbose_name='daily pricing model'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='default_accrued',
            field=models.FloatField(default=0.0, verbose_name='default accrued'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='default_price',
            field=models.FloatField(default=0.0, verbose_name='default price'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='payment_size_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PaymentSizeDetail', verbose_name='payment size detail'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='price_multiplier',
            field=models.FloatField(default=1.0, verbose_name='price multiplier'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='pricing_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.Currency', verbose_name='pricing currency'),
        ),
        migrations.AlterField(
            model_name='instrumentattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='instruments.InstrumentAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='instrumentattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentClassifier', verbose_name='classifier'),
        ),
        migrations.AlterField(
            model_name='instrumentattribute',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumentattribute',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='value (Date)'),
        ),
        migrations.AlterField(
            model_name='instrumentattribute',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value (Float)'),
        ),
        migrations.AlterField(
            model_name='instrumentattribute',
            name='value_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='value (String)'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.InstrumentClassifier', verbose_name='classifier (root)'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetype',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10, verbose_name='value type'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypeoption',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_options', to='instruments.InstrumentAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypeoption',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_attribute_type_options', to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentAttributeType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='instrumentattributetypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='instrumentclass',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifier',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='instruments.InstrumentClassifier', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifiergroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifiergroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifiergroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifieruserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentClassifier', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifieruserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='instrumentclassifieruserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='instrumentfactorschedule',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='effective date'),
        ),
        migrations.AlterField(
            model_name='instrumentfactorschedule',
            name='factor_value',
            field=models.FloatField(default=0.0, verbose_name='factor value'),
        ),
        migrations.AlterField(
            model_name='instrumentfactorschedule',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_schedules', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='instrumentgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.Instrument', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumentgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='instrumentgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='instrumenttypegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='instruments.InstrumentType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumenttypegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='instrumenttypegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.InstrumentType', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='instrumentuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='instruments.Instrument', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='instrumentuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='instrumentuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='manualpricingformula',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='manualpricingformula',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_pricing_formulas', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='manualpricingformula',
            name='pricing_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_pricing_formulas', to='integrations.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='paymentsizedetail',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='periodicityperiod',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='accrued_price',
            field=models.FloatField(blank=True, null=True, verbose_name='accrued price'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='pricing policy'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='factor',
            field=models.FloatField(blank=True, null=True, verbose_name='factor'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='instruments.Instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='principal_price',
            field=models.FloatField(default=0.0, verbose_name='principal price'),
        ),
    ]
