# Generated by Django 2.2.5 on 2021-05-14 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0049_instrumenttypeinstrumentattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='instrument_factor_schedule_json_data',
            field=models.TextField(blank=True, null=True, verbose_name='instrument factor schedule json data'),
        ),
        migrations.CreateModel(
            name='InstrumentTypeInstrumentFactorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='effective date')),
                ('effective_date_value_type', models.PositiveSmallIntegerField(
                    choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                             (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                             (120, 'Button')], default=40, verbose_name='effective date')),
                ('position_factor_value',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='position factor value')),
                ('position_factor_value_value_type', models.PositiveSmallIntegerField(
                    choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                             (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                             (120, 'Button')], default=40, verbose_name='position factor value value type')),
                ('factor_value1', models.FloatField(default=0.0, verbose_name='factor value 1')),
                ('factor_value1_value_type', models.PositiveSmallIntegerField(
                    choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                             (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                             (120, 'Button')], default=40, verbose_name='factor value1 value type')),
                ('factor_value2', models.FloatField(default=0.0, verbose_name='factor value 2')),
                ('factor_value2_value_type', models.PositiveSmallIntegerField(
                    choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                             (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                             (120, 'Button')], default=40, verbose_name='factor value2 value type')),
                ('factor_value3', models.FloatField(default=0.0, verbose_name='factor value 3 ')),
                ('factor_value3_value_type', models.PositiveSmallIntegerField(
                    choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                             (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                             (120, 'Button')], default=40, verbose_name='factor value3 value type')),
                ('instrument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='instrument_factor_schedules',
                                                      to='instruments.InstrumentType',
                                                      verbose_name='instrument attributes')),
            ],
            options={
                'verbose_name': 'instrument type instrument factor schedule',
                'verbose_name_plural': 'instrument type  instrument factor schedules',
            },
        ),
    ]
