# Generated by Django 2.2.5 on 2021-05-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0050_auto_20210514_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='position_reporting',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Direct Position'), (2, 'Factor Adjusted Position'), (3, 'Do not show')], default=1,
                verbose_name='position reporting'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='co_directional_exposure_currency',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   verbose_name='co directional exposure currency'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='counter_directional_exposure_currency',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   verbose_name='counter directional exposure currency'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='exposure_calculation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='instruments.ExposureCalculationModel',
                                    verbose_name='exposure calculation model'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='long_underlying_exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='instrument_type_long_instruments',
                                    to='instruments.LongUnderlyingExposure', verbose_name='long underlying exposure'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='long_underlying_instrument',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='long underlying instrument'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='position_reporting',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Direct Position'), (2, 'Factor Adjusted Position'), (3, 'Do not show')], default=1,
                verbose_name='position reporting'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='short_underlying_exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='instrument_type_short_instruments',
                                    to='instruments.ShortUnderlyingExposure', verbose_name='short underlying exposure'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='short_underlying_instrument',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='short underlying instrument'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='underlying_long_multiplier',
            field=models.FloatField(default=1.0, verbose_name='underlying long multiplier'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='underlying_short_multiplier',
            field=models.FloatField(default=1.0, verbose_name='underlying short multiplier'),
        ),
    ]
