# Generated by Django 2.2.5 on 2021-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0053_auto_20210526_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='factor_value1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='factor value 1'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='factor_value2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='factor value 2'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='factor_value3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='factor value 3 '),
        ),
    ]
