# Generated by Django 2.2.5 on 2021-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0055_pricehistory_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='has_linked_with_portfolio',
            field=models.BooleanField(default=True, verbose_name='has linked with portfolio'),
        ),
    ]
