# Generated by Django 2.2.5 on 2021-09-07 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0062_eventscheduleaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventscheduleaction',
            name='transaction_type_old',
        ),
    ]
