# Generated by Django 2.2.5 on 2021-10-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0064_auto_20210929_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedevent',
            name='event_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_events', to='instruments.EventSchedule', verbose_name='event schedule'),
        ),
    ]
