# Generated by Django 2.2.5 on 2021-10-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0065_auto_20211008_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='price_download_scheme',
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_size_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=20, verbose_name='accrual size value type'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='accrual_start_date_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='accrual start date value type'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='first_payment_date_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='first payment date value type'),
        ),
        migrations.AlterField(
            model_name='accrualcalculationschedule',
            name='periodicity_n_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=20, verbose_name='periodicity n value type'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='effective_date_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='effective date value type'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='final_date_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='final_date value type'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='periodicity_n_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=20, verbose_name='periodicity n value type'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='co_directional_exposure_currency_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=100,
                verbose_name='co directional exposure currency value type'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='counter_directional_exposure_currency_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=100,
                verbose_name='counter directional exposure currency value type'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='effective_date_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='effective date'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='factor_value1_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='factor value1 value type'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='factor_value2_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='factor value2 value type'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='factor_value3_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40, verbose_name='factor value3 value type'),
        ),
        migrations.AlterField(
            model_name='instrumenttypeinstrumentfactorschedule',
            name='position_factor_value_value_type',
            field=models.PositiveSmallIntegerField(
                choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier'), (50, 'Boolean'),
                         (60, 'System Attribute'), (70, 'User Attribute'), (100, 'Relation'), (110, 'Selector'),
                         (120, 'Button'), (80, 'Datetime')], default=40,
                verbose_name='position factor value value type'),
        ),
    ]
