# Generated by Django 2.2.5 on 2021-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0066_auto_20211025_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
    ]
