# Generated by Django 2.2.5 on 2021-11-11 14:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0067_auto_20211027_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='default_price',
            field=models.FloatField(default=0.0, verbose_name='default price'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='maturity_date',
            field=models.DateField(default=datetime.date(9999, 12, 31), null=True, verbose_name='maturity date'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='maturity_price',
            field=models.FloatField(default=0.0, verbose_name='maturity price'),
        ),
    ]
