# Generated by Django 2.2.5 on 2021-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0068_auto_20211111_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
        migrations.AddField(
            model_name='generatedevent',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='json data'),
        ),
    ]
