# Generated by Django 2.2.5 on 2022-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0070_eventscheduleaction_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
    ]
