# Generated by Django 2.2.5 on 2022-02-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0071_auto_20220127_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='pricing_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='instruments.PricingCondition', verbose_name='pricing condition'),
        ),
    ]
