# Generated by Django 2.2.5 on 2022-02-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0020_auto_20220127_1536'),
        ('instruments', '0073_instrumenttype_reference_for_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='pricing_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='instrument_types_pricing', to='currencies.Currency',
                                    verbose_name='pricing currency'),
        ),
    ]
