# Generated by Django 2.2.5 on 2022-02-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0074_instrumenttype_pricing_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='pricing_multiplier',
            field=models.FloatField(default=1.0, verbose_name='pricing multiplier'),
        ),
    ]
