# Generated by Django 2.2.5 on 2022-02-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0075_instrumenttype_pricing_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumenttype',
            name='pricing_multiplier',
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='price_multiplier',
            field=models.FloatField(default=1.0, verbose_name='price multiplier'),
        ),
    ]
