# Generated by Django 2.2.5 on 2022-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0076_auto_20220214_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted user code'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted user code'),
        ),
    ]
