# Generated by Django 4.0.6 on 2022-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0078_pricehistory_cash_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='text',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='name',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='expression'),
        ),
    ]
