# Generated by Django 4.0.6 on 2022-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0079_alter_eventschedule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='name',
            field=models.CharField(max_length=4096, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventscheduleaction',
            name='text',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='description',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventscheduleconfig',
            name='name',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='expression'),
        ),
    ]
