# Generated by Django 4.0.6 on 2022-09-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0082_instrument_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='country',
            name='user_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='user code'),
        ),
    ]
