REQUEST_PAYLOAD = {
    "account_mode": 1,
    "accounts": [1, 5, 8, 7, 9, 6, 4, 3],
    "accounts_cash": [],
    "accounts_cash_object": [],
    "accounts_object": [
        {
            "deleted_user_code": None,
            "id": 1,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "-",
            "public_name": None,
            "short_name": "-",
            "type": 1,
            "type_object": {
                "deleted_user_code": None,
                "id": 1,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "-",
                "public_name": None,
                "short_name": "-",
                "user_code": "-",
            },
            "user_code": "-",
        },
        {
            "deleted_user_code": "Test_AC_4",
            "id": 5,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "(del) Test_AC_4",
            "public_name": "Test_AC_3",
            "short_name": "(del) Test_AC_3",
            "type": 1,
            "type_object": {
                "deleted_user_code": None,
                "id": 1,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "-",
                "public_name": None,
                "short_name": "-",
                "user_code": "-",
            },
            "user_code": "del00000000000000002",
        },
        {
            "deleted_user_code": "New test",
            "id": 8,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "(del) New test",
            "public_name": "New test",
            "short_name": "(del) New test",
            "type": 2,
            "type_object": {
                "deleted_user_code": None,
                "id": 2,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "House",
                "public_name": None,
                "short_name": "House",
                "user_code": "House",
            },
            "user_code": "del00000000000000029",
        },
        {
            "deleted_user_code": None,
            "id": 7,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "Expenses",
            "public_name": "Rent",
            "short_name": "Rent",
            "type": 2,
            "type_object": {
                "deleted_user_code": None,
                "id": 2,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "House",
                "public_name": None,
                "short_name": "House",
                "user_code": "House",
            },
            "user_code": "Expenses",
        },
        {
            "deleted_user_code": None,
            "id": 9,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "New test",
            "public_name": "New test",
            "short_name": "New test",
            "type": 2,
            "type_object": {
                "deleted_user_code": None,
                "id": 2,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "House",
                "public_name": None,
                "short_name": "House",
                "user_code": "House",
            },
            "user_code": "New test",
        },
        {
            "deleted_user_code": None,
            "id": 6,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "Rent",
            "public_name": "Rent",
            "short_name": "Rent",
            "type": 2,
            "type_object": {
                "deleted_user_code": None,
                "id": 2,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "House",
                "public_name": None,
                "short_name": "House",
                "user_code": "House",
            },
            "user_code": "Rent",
        },
        {
            "deleted_user_code": None,
            "id": 4,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "Test_AC_3",
            "public_name": "Test_AC_3",
            "short_name": "Test_AC_3",
            "type": 1,
            "type_object": {
                "deleted_user_code": None,
                "id": 1,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "-",
                "public_name": None,
                "short_name": "-",
                "user_code": "-",
            },
            "user_code": "Test_AC_3",
        },
        {
            "deleted_user_code": None,
            "id": 3,
            "meta": {
                "app_label": "accounts",
                "content_type": "accounts.account",
                "model_name": "account",
                "space_code": "space00000",
            },
            "name": "Test ACC 2",
            "public_name": "Test ACC 2",
            "short_name": "Test ACC 2",
            "type": 1,
            "type_object": {
                "deleted_user_code": None,
                "id": 1,
                "meta": {
                    "app_label": "accounts",
                    "content_type": "accounts.accounttype",
                    "model_name": "accounttype",
                    "space_code": "space00000",
                },
                "name": "-",
                "public_name": None,
                "short_name": "-",
                "user_code": "-",
            },
            "user_code": "Test ACC 2",
        },
    ],
    "accounts_position": [],
    "accounts_position_object": [],
    "begin_date": "2022-01-01",
    "calculationGroup": "portfolio",
    "complex_transaction_statuses_filter": "booked",
    "cost_method": 1,
    "custom_fields_to_calculate": "",
    "date_field": "transaction_date",
    "depth_level": "entry",
    "end_date": "2023-10-04",
    "period_type": None,
    "expression_iterations_count": 1,
    "filters": [
        {
            "content_type": "reports.transactionreport",
            "filtersListIndex": 0,
            "key": "entry_item_user_code",
            "name": "Transaction. Entry Item User Code",
            "options": {
                "enabled": True,
                "filter_type": "equal",
                "filter_values": [],
                "use_from_above": {
                    "attrs_entity_type": "balance-report",
                    "key": "user_code",
                },
            },
            "value_type": 10,
        },
        {
            "content_type": "portfolios.portfolio",
            "filtersListIndex": 1,
            "key": "portfolio.user_code",
            "name": "Portfolio. User code",
            "options": {
                "enabled": True,
                "filter_type": "equal",
                "filter_values": [],
                "use_from_above": {
                    "attrs_entity_type": "balance-report",
                    "key": "portfolio.user_code",
                },
            },
            "value_type": 10,
        },
        {
            "content_type": "accounts.account",
            "filtersListIndex": 2,
            "key": "entry_account.user_code",
            "name": "Transaction. Entry Account. User code",
            "options": {
                "enabled": True,
                "filter_type": "equal",
                "filter_values": [],
                "use_from_above": {
                    "attrs_entity_type": "balance-report",
                    "key": "account.user_code",
                },
            },
            "value_type": 10,
        },
        {
            "key": "instrument.maturity_date",
            "name": "Instrument. Maturity date",
            "value_type": 40,
            "content_type": "instruments.instrument",
            "options": {
                "filter_type": "equal",
                "filter_values": ["2022-01-01"],
                "use_from_above": {},
                "enabled": True,
            },
        },
    ],
    "portfolio_mode": 1,
    "portfolios": [1, 2, 6, 10, 9, 5, 4, 3],
    "portfolios_object": [
        {
            "deleted_user_code": None,
            "id": 1,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "-",
            "public_name": None,
            "short_name": "-",
            "user_code": "-",
        },
        {
            "deleted_user_code": None,
            "id": 2,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "Model",
            "public_name": "Model",
            "short_name": "Model",
            "user_code": "Model",
        },
        {
            "deleted_user_code": None,
            "id": 6,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "Model_Fn",
            "public_name": "Model_Fn",
            "short_name": "Model_Fn",
            "user_code": "Model_Fn",
        },
        {
            "deleted_user_code": None,
            "id": 10,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "New Test",
            "public_name": "New Test",
            "short_name": "New Test",
            "user_code": "New Test",
        },
        {
            "deleted_user_code": None,
            "id": 9,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "New portfolio",
            "public_name": "New portfolio",
            "short_name": "New portfolio",
            "user_code": "nportf",
        },
        {
            "deleted_user_code": None,
            "id": 5,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "Prop",
            "public_name": "Prop",
            "short_name": "Prop",
            "user_code": "Prop",
        },
        {
            "deleted_user_code": None,
            "id": 4,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "Register_test_1",
            "public_name": "Register_test_1",
            "short_name": "Register_test_1",
            "user_code": "Register_test_1",
        },
        {
            "deleted_user_code": None,
            "id": 3,
            "meta": {
                "app_label": "portfolios",
                "content_type": "portfolios.portfolio",
                "model_name": "portfolio",
                "space_code": "space00000",
            },
            "name": "Test Portfolio 2",
            "public_name": "Test Portfolio 2",
            "short_name": "TPRTF",
            "user_code": "T_PRTF",
        },
    ],
    "pricing_policy": 1,
    "report_date": "2022-02-08",
    "strategies1": [],
    "strategies1_object": [],
    "strategies2": [],
    "strategies2_object": [],
    "strategies3": [],
    "strategies3_object": [],
    "strategy1_mode": 0,
    "strategy2_mode": 0,
    "strategy3_mode": 0,
    "table_font_size": "small",
    "frontend_request_options": {
        "groups_types": [],
        "page": 1,
        "groups_values": [],
        "groups_order": "asc",
        "page_size": 60,
        "filter_settings": [
            {
                "key": "instrument.maturity_date",
                "filter_type": "equal",
                "value_type": 40,
                "value": ["2022-01-01"],
            }
        ],
        "columns": [
            {
                "___column_id": "136bfd9246003e0c46f8a9a83d5a8826",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_text_1",
                "layout_name": "Portfolio",
                "name": "Complex Transaction. Portfolio",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 0,
                "style": {"width": "341px"},
                "value_type": 10,
            },
            {
                "___column_id": "37573232cc8f8e871152adc27dd74d69",
                "content_type": "transactions.complextransaction",
                "isHidden": False,
                "key": "complex_transaction.code",
                "layout_name": "Trade ID",
                "name": "Complex Transaction. Code",
                "options": {
                    "sort": None,
                    "sort_mode": "default",
                    "sort_settings": {"mode": None},
                },
                "style": {"width": "100px"},
                "value_type": 20,
            },
            {
                "___column_id": "0371028dd282db3779a931a9f02769dd",
                "columns": True,
                "isHidden": False,
                "key": "entry_amount",
                "name": "Transaction. Entry Amount",
                "options": {
                    "numberFormat": {
                        "negative_color_format_id": 0,
                        "negative_format_id": 0,
                        "number_multiplier": None,
                        "number_prefix": "",
                        "number_suffix": "",
                        "percentage_format_id": 0,
                        "round_format_id": 3,
                        "subtotal_formula_id": 1,
                        "thousands_separator_format_id": 2,
                        "zero_format_id": 0,
                    },
                    "sort": None,
                    "sort_settings": {"mode": None},
                },
                "report_settings": {"subtotal_formula_id": 1},
                "style": {"width": "195px"},
                "value_type": 20,
            },
            {
                "___column_id": "948dc4afb985f82517b70cd9eb17ab75",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_date_1",
                "layout_name": "Date (Trade)",
                "name": "Complex Transaction. Date (Trade)",
                "options": {"sort": "ASC", "sort_settings": {"mode": None}},
                "orderNumber__": 24,
                "style": {"width": "100px"},
                "value_type": 40,
            },
            {
                "___column_id": "d90927a3c8f25df38c4e1bec29097df4",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_date_2",
                "layout_name": "Date (Value)",
                "name": "Complex Transaction. Date (Value)",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 25,
                "style": {"width": "100px"},
                "value_type": 40,
            },
            {
                "___column_id": "8534801cd988991d533936c2232bd865",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_date_3",
                "layout_name": "Date (Book)",
                "name": "Complex Transaction. Date (Book)",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 26,
                "style": {"width": "100px"},
                "value_type": 40,
            },
            {
                "___column_id": "b155e0cac393258eac5ba1b72819a4fc",
                "columns": True,
                "content_type": "transactions.transactiontype",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.transaction_type.name",
                "layout_name": "Transaction Type",
                "name": "Complex Transaction. Transaction Type. Name",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 0,
                "style": {"width": "225px"},
                "value_type": 10,
            },
            {
                "___column_id": "71f240c427db93602d9f230d896c8d17",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_text_4",
                "layout_name": "Instrument/Currency",
                "name": "Complex Transaction. Instrument",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 3,
                "style": {"width": "118px"},
                "value_type": 10,
            },
            {
                "___column_id": "a01c6a2c6d642e2fe2c6d35091616765",
                "columns": True,
                "content_type": "reports.transactionreport",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "position_size_with_sign",
                "layout_name": "Position/Quantity",
                "name": "Transaction. Position Size with sign",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 2,
                "report_settings": {
                    "negative_color_format_id": 1,
                    "negative_format_id": 1,
                    "number_multiplier": None,
                    "number_prefix": "",
                    "number_suffix": "",
                    "percentage_format_id": 0,
                    "round_format_id": 1,
                    "thousands_separator_format_id": 2,
                    "zero_format_id": 1,
                },
                "style": {"width": "100px"},
                "value_type": 20,
            },
            {
                "___column_id": "66d97c178f8747499a0083854a47eb8a",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_number_7",
                "layout_name": "Price",
                "name": "Complex Transaction. Traded Price",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 23,
                "style": {"width": "100px"},
                "value_type": 20,
            },
            {
                "___column_id": "0af49b3b463f39bd4fb22430e6e291f1",
                "columns": True,
                "content_type": "reports.transactionreport",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "carry_with_sign",
                "layout_name": "Accrued",
                "name": "Transaction. Carry with sign",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 5,
                "report_settings": {
                    "negative_color_format_id": 1,
                    "negative_format_id": 1,
                    "number_multiplier": None,
                    "number_prefix": "",
                    "number_suffix": "",
                    "percentage_format_id": 0,
                    "round_format_id": 1,
                    "thousands_separator_format_id": 2,
                    "zero_format_id": 1,
                },
                "style": {"width": "100px"},
                "value_type": 20,
            },
            {
                "___column_id": "3e6cb9f296d2f740b343f42f878bff4a",
                "columns": True,
                "content_type": "reports.transactionreport",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "cash_consideration",
                "layout_name": "Amount/Cash",
                "name": "Transaction. Cash consideration",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 3,
                "report_settings": {
                    "negative_color_format_id": 1,
                    "negative_format_id": 1,
                    "number_multiplier": None,
                    "number_prefix": "",
                    "number_suffix": "",
                    "percentage_format_id": 0,
                    "round_format_id": 1,
                    "thousands_separator_format_id": 2,
                    "zero_format_id": 1,
                },
                "style": {"width": "100px"},
                "value_type": 20,
            },
            {
                "___column_id": "56eb9439eeb9db157f90b1a508224eb4",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_text_3",
                "layout_name": "Account Cash",
                "name": "Complex Transaction. Account - Cash",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 2,
                "style": {"width": "100px"},
                "value_type": 10,
            },
            {
                "___column_id": "38875aab199b868d6aea49ea8bfd7584",
                "columns": True,
                "content_type": "transactions.complextransaction",
                "filters": False,
                "groups": False,
                "isHidden": False,
                "key": "complex_transaction.user_text_2",
                "layout_name": "Account Instrument",
                "name": "Complex Transaction. Account - Position",
                "options": {"sort": None, "sort_settings": {"mode": None}},
                "orderNumber__": 1,
                "style": {"width": "100px"},
                "value_type": 10,
            },
        ],
        "items_order": "asc",
    },
    "report_instance_id": 94,
}
