# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_member_interface_level'),
        ('reference_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencetablerow',
            name='reference_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reference_tables.ReferenceTable', verbose_name='reference table'),
        ),
        migrations.AlterUniqueTogether(
            name='referencetable',
            unique_together=set([('name', 'master_user')]),
        ),
    ]
