# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-15 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_tables', '0002_auto_20190814_1138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referencetablerow',
            unique_together=set([('reference_table', 'key')]),
        ),
    ]
