# Generated by Django 2.2.5 on 2020-01-16 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_userprofile_two_factor_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedConfigurationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('publicity_type', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Master User Only')], db_index=True, default=1, verbose_name='publicity type')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('linked_master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='linked master user')),
            ],
        ),
        migrations.CreateModel(
            name='InviteToSharedConfigurationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Sent'), (1, 'Accepted'), (2, 'Declined')], default=0)),
                ('member_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_invites_to_shared_configuration_files', to='users.Member', verbose_name='member from')),
                ('member_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_to_shared_configuration_files_to', to='users.Member', verbose_name='member to')),
                ('shared_configuration_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_sharing.SharedConfigurationFile', verbose_name='shared configuration file')),
            ],
        ),
    ]
