# Generated by Django 2.2.5 on 2020-01-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedconfigurationfile',
            old_name='author',
            new_name='user',
        ),
    ]
