# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_classifiers', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='strategies.Strategy'),
        ),
    ]
