# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        ('users', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy3userobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy3userobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy3subgroupuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy3Subgroup', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy3subgroupuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy3subgroupuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy3subgroupgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy3Subgroup', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy3subgroupgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy3subgroupgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy3subgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgroups', to='strategies.Strategy3Group'),
        ),
        migrations.AddField(
            model_name='strategy3subgroup',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy3_subgroups', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy3groupuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy3Group', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy3groupuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy3groupuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy3groupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy3', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy3groupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy3groupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy3groupgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy3Group', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy3groupgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy3groupgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy3group',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy3_groups', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies3', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='strategies.Strategy3Subgroup'),
        ),
        migrations.AddField(
            model_name='strategy2userobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy2', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy2userobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy2userobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy2subgroupuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy2Subgroup', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy2subgroupuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy2subgroupuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy2subgroupgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy2Subgroup', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy2subgroupgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy2subgroupgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy2subgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgroups', to='strategies.Strategy2Group'),
        ),
        migrations.AddField(
            model_name='strategy2subgroup',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy2_subgroups', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy2groupuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy2Group', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy2groupuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy2groupuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy2groupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy2', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy2groupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy2groupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy2groupgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy2Group', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy2groupgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy2groupgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy2group',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy2_groups', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies2', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='strategies.Strategy2Subgroup'),
        ),
        migrations.AddField(
            model_name='strategy1userobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy1', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy1userobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy1userobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy1subgroupuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy1Subgroup', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy1subgroupuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy1subgroupuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy1subgroupgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy1Subgroup', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy1subgroupgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy1subgroupgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy1subgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgroups', to='strategies.Strategy1Group'),
        ),
        migrations.AddField(
            model_name='strategy1subgroup',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy1_subgroups', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy1groupuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='strategies.Strategy1Group', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy1groupuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='strategy1groupuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy1groupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy1', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy1groupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy1groupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy1groupgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='strategies.Strategy1Group', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='strategy1groupgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='strategy1groupgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='strategy1group',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy1_groups', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies1', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='strategies.Strategy1Subgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3userobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3subgroupuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3subgroupgroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3subgroup',
            unique_together=set([('group', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3groupuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3groupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3groupgroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3group',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3',
            unique_together=set([('subgroup', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2userobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2subgroupuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2subgroupgroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2subgroup',
            unique_together=set([('group', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2groupuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2groupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2groupgroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2group',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2',
            unique_together=set([('subgroup', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1userobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1subgroupuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1subgroupgroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1subgroup',
            unique_together=set([('group', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1groupuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1groupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1groupgroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1group',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1',
            unique_together=set([('subgroup', 'user_code')]),
        ),
    ]
