# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategygroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategyuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
    ]
