# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strategies', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy1',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy1group',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy1subgroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy2',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy2group',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy2subgroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy3',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy3group',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='strategy3subgroup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
    ]
