# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_auto_20160525_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategy1userobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='strategy1userobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='strategy1userobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='strategy1userobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='strategy2userobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='strategy2userobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='strategy2userobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='strategy2userobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='strategy3userobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='strategy3userobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='strategy3userobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='strategy3userobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='strategyuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='strategyuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='strategyuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='strategyuserobjectpermission',
            name='permission',
        ),
        migrations.AlterModelOptions(
            name='strategy2groupobjectpermission',
            options={'verbose_name': 'strategies - 2 - group permission', 'verbose_name_plural': 'strategies - 2 - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='strategy3',
            options={'verbose_name': 'strategy - 3', 'verbose_name_plural': 'strategies - 3'},
        ),
        migrations.DeleteModel(
            name='Strategy1UserObjectPermission',
        ),
        migrations.DeleteModel(
            name='Strategy2UserObjectPermission',
        ),
        migrations.DeleteModel(
            name='Strategy3UserObjectPermission',
        ),
        migrations.DeleteModel(
            name='StrategyUserObjectPermission',
        ),
    ]
