# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160922_1432'),
        ('strategies', '0003_auto_20160914_0933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategy1',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy1subgroup',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy2subgroup',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategy3subgroup',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy1',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy1group',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy1subgroup',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy2',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy2group',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy2subgroup',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy3',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy3group',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='strategy3subgroup',
            index_together=set([('master_user', 'is_deleted')]),
        ),
    ]
