# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_auto_20160525_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
    ]
