# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_auto_20160525_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy1UserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'strategies - 1 - user permissions',
                'verbose_name': 'strategies - 1 - user permission',
            },
        ),
        migrations.CreateModel(
            name='Strategy2UserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'strategies - 2 - user permissions',
                'verbose_name': 'strategies - 2 - user permission',
            },
        ),
        migrations.CreateModel(
            name='Strategy3UserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'strategies - 3 - user permissions',
                'verbose_name': 'strategies - 3 - user permission',
            },
        ),
        migrations.AlterUniqueTogether(
            name='strategy',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='strategygroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='strategygroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='strategygroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='strategygroupobjectpermission',
            name='permission',
        ),
    ]
