# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_auto_20160628_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy1',
            options={'permissions': [('view_strategy1', 'Can view strategy1'), ('manage_strategy1', 'Can manage strategy1')], 'verbose_name': 'strategy - 1', 'verbose_name_plural': 'strategies - 1'},
        ),
        migrations.AlterModelOptions(
            name='strategy2',
            options={'permissions': [('view_strategy2', 'Can view strategy2'), ('manage_strategy2', 'Can manage strategy2')], 'verbose_name': 'strategy - 2', 'verbose_name_plural': 'strategies - 2'},
        ),
        migrations.AlterModelOptions(
            name='strategy3',
            options={'permissions': [('view_strategy3', 'Can view strategy3'), ('manage_strategy3', 'Can manage strategy3')], 'verbose_name': 'strategy - 3', 'verbose_name_plural': 'strategies - 3'},
        ),
    ]
