# Generated by Django 2.2.5 on 2021-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strategies', '0008_auto_20200819_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy1',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy1group',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy1subgroup',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy2',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy2group',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy2subgroup',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy3',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy3group',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='strategy3subgroup',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
    ]
