# Generated by Django 2.2.5 on 2021-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strategies', '0010_auto_20210526_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy1',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy1group',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy1subgroup',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy2',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy2group',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy2subgroup',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy3',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy3group',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='strategy3subgroup',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='short name'),
        ),
    ]
