from rest_framework import routers

import poms.reports.views as reports

router = routers.DefaultRouter()

router.register(
    "summary",
    reports.SummaryViewSet,
    "Summary",
)
router.register(
    "backend-balance-report",
    reports.BackendBalanceReportViewSet,
    "BackendBalanceReport",
)
router.register(
    "balance-report",
    reports.BalanceReportViewSet,
    "BalanceReport",
)
router.register(
    "balance-report/custom-field",
    reports.BalanceReportCustomFieldViewSet,
    "BalanceReportCustomField",
)
router.register(
    "backend-pl-report",
    reports.BackendPLReportViewSet,
    "BackendPLReport",
)
router.register(
    "pl-report",
    reports.PLReportViewSet,
    "PlReport",
)
router.register(
    "pl-report/custom-field",
    reports.PLReportCustomFieldViewSet,
    "PlReportCustomField",
)
router.register(
    "backend-transaction-report",
    reports.BackendTransactionReportViewSet,
    "BackendTransactionReport",
)
router.register(
    "transaction-report",
    reports.TransactionReportViewSet,
    "TransactionReport",
)
router.register(
    "transaction-report-sql",
    reports.TransactionReportViewSet,
    "TransactionReportSyncSql",
)
router.register(
    "transaction-report/custom-field",
    reports.TransactionReportCustomFieldViewSet,
    "TransactionReportCustomField",
)
router.register(
    "performance-report",
    reports.PerformanceReportViewSet,
    "PerformanceReport",
)
router.register(
    "price-history-check",
    reports.PriceHistoryCheckViewSet,
    "priceHistoryCheck",
)
router.register(
    "balance-report-instance",
    reports.BalanceReportInstanceViewSet,
    "balanceReportInstance",
)
router.register(
    "pl-report-instance",
    reports.PLReportInstanceViewSet,
    "plReportInstance",
)

# DEPRECATED
router.register(
    "balance-report-light",
    reports.BalanceReportLightViewSet,
    "BalanceReportLight",
)
router.register(
    "price-history-check-sql",
    reports.PriceHistoryCheckViewSet,
    "PriceHistoryCheckSql",
)
router.register(
    "pl-report-sql",
    reports.PLReportViewSet,
    "PlReportSyncSql",
)
router.register(
    "balance-report-sql",
    reports.BalanceReportViewSet,
    "BalanceReportSyncSql",
)
