# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_masteruser_transaction_type_group'),
        ('data_import', '0002_auto_20180113_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser'),
        ),
    ]
