# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_auto_20180121_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimportschema',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dataimportschema',
            name='target',
        ),
        migrations.AddField(
            model_name='dataimportschema',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
