# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-25 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_auto_20180124_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportschemafields',
            name='num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
