# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-30 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0009_auto_20180130_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimport',
            name='file',
        ),
    ]
