# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0011_auto_20180203_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportschema',
            name='error_handling',
            field=models.IntegerField(choices=[(0, 'break'), (1, 'continue')], default=0),
        ),
    ]
