# Generated by Django 4.1.3 on 2023-03-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_historicalrecord_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='context_url',
            field=models.TextField(blank=True, null=True, verbose_name='context_url'),
        ),
    ]
