# Generated by Django 4.1.3 on 2023-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_historicalrecord_context_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('change', 'Change'), ('delete', 'Delete'), ('recycle_bin', 'Recycle Bin')], default='change', max_length=25, verbose_name='action'),
        ),
    ]
