# Generated by Django 4.1.3 on 2023-04-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_alter_historicalrecord_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user code'),
        ),
    ]
