from rest_framework import routers

import poms.ui.views as ui

router = routers.DefaultRouter()

router.register(
    "user-interface-access",
    ui.UserInterfaceAccessModelViewSet,
    "user_interface_access",
)
router.register(
    "list-layout",
    ui.ListLayoutViewSet,
    "list_layout",
)
router.register(
    "template-layout",
    ui.TemplateLayoutViewSet,
    "template_layout",
)
router.register(
    "dashboard-layout",
    ui.DashboardLayoutViewSet,
    "dashboard_layout",
)
router.register(
    "member-layout",
    ui.MemberLayoutViewSet,
    "member_layout",
)
router.register(
    "mobile-layout",
    ui.MobileLayoutViewSet,
    "mobile_layout",
)
router.register(
    "draft",
    ui.DraftViewSet,
    "draft",
)
router.register(
    "edit-layout",
    ui.EditLayoutViewSet,
    "edit_layout",
)
router.register(
    "bookmark",
    ui.BookmarkViewSet,
    "bookmark",
)
router.register(
    "configuration-export-layout",
    ui.ConfigurationExportLayoutViewSet,
    "configuration_export_layout",
)
router.register(
    "complex-transaction-user-field",
    ui.ComplexTransactionUserFieldViewSet,
    "complex_transaction_user_field",
)
router.register(
    "transaction-user-field",
    ui.TransactionUserFieldViewSet,
    "transaction_user_field",
)
router.register(
    "instrument-user-field",
    ui.InstrumentUserFieldViewSet,
    "instrument_user_field",
)
router.register(
    "entity-tooltip",
    ui.EntityTooltipViewSet,
    "entity_tooltip",
)
router.register(
    "context-menu-layout",
    ui.ContextMenuLayoutViewSet,
    "context_menu_layout",
)
router.register(
    "color-palette",
    ui.ColorPaletteViewSet,
    "color_palette",
)
router.register(
    "cross-entity-attribute-extension",
    ui.CrossEntityAttributeExtensionViewSet,
    "cross_entity_attribute_extension",
)
router.register(
    "column-sort-data",
    ui.ColumnSortDataViewSet,
    "column_sort_data",
)
router.register(
    "system-attributes",
    ui.SystemAttributesViewSet,
    "system_attributes",
)

# DEPRECATED
router.register(
    "list-layout-light",
    ui.ListLayoutLightViewSet,
    "list_layout_light",
)

#TODO DEPRECATED delete in 1.15.0-rc
router.register(
    "portal-interface-access",
    ui.PortalInterfaceAccessViewSet,
    "portal_interface_access",
)
