# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion
import poms.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted user code')),
                ('reference_for_pricing', models.CharField(blank=True, default='', max_length=100, verbose_name='reference for pricing')),
                ('default_fx_rate', models.FloatField(default=1, verbose_name='default fx rate')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['user_code'],
                'permissions': [('manage_currency', 'Can manage currency')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('fx_rate', models.FloatField(default=1, verbose_name='fx rate')),
                ('procedure_modified_datetime', models.DateTimeField(blank=True, null=True, verbose_name='procedure_modified_datetime')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='currencies.currency', verbose_name='currency')),
            ],
            options={
                'verbose_name': 'currency history',
                'verbose_name_plural': 'currency histories',
                'ordering': ['date'],
            },
        ),
    ]
