# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'permissions': [('view_currency', 'Can view currency')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'counterparties - group permission',
                'verbose_name_plural': 'counterparties - group permissions',
            },
        ),
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='date')),
                ('fx_rate', models.FloatField(default=0.0, verbose_name='fx rate')),
            ],
            options={
                'verbose_name': 'currency history',
                'verbose_name_plural': 'currency histories',
                'permissions': [('view_currencyhistory', 'Can view currency history')],
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='currencies.Currency', verbose_name='content object')),
            ],
            options={
                'verbose_name': 'counterparties - user permission',
                'verbose_name_plural': 'counterparties - user permissions',
            },
        ),
    ]
