# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import poms.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('reference_for_pricing', models.CharField(blank=True, default='', max_length=100, verbose_name='reference for pricing')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'abstract': False,
                'verbose_name': 'currency',
                'permissions': [('view_currency', 'Can view currency'), ('manage_currency', 'Can manage currency')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'currencies - group permissions',
                'abstract': False,
                'verbose_name': 'currencies - group permission',
            },
        ),
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('fx_rate', models.FloatField(default=0.0, verbose_name='fx rate')),
            ],
            options={
                'verbose_name_plural': 'currency histories',
                'ordering': ['-date'],
                'verbose_name': 'currency history',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='currencies.Currency', verbose_name='content object')),
            ],
            options={
                'verbose_name_plural': 'currencies - user permissions',
                'abstract': False,
                'verbose_name': 'currencies - user permission',
            },
        ),
    ]
