# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('integrations', '0001_initial'),
        ('currencies', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies',
                                    to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='currency',
            name='price_download_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='integrations.PriceDownloadScheme', verbose_name='price download scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyhistory',
            unique_together=set([('currency', 'pricing_policy', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterIndexTogether(
            name='currency',
            index_together=set([('master_user', 'is_deleted')]),
        ),
    ]
