# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('currencies', '0002_auto_20160425_0912'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyhistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AddField(
            model_name='currencygroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='currencies.Currency', verbose_name='content object'),
        ),
        migrations.AddField(
            model_name='currencygroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='currencygroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='currency',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterIndexTogether(
            name='currencyhistory',
            index_together=set([('currency', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
