# Generated by Django 4.1.3 on 2023-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0004_alter_currencyhistory_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="user_code",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="user code"
            ),
        ),
    ]
