# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20160922_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['master_user', 'user_code'], 'permissions': [('view_currency', 'Can view currency'), ('manage_currency', 'Can manage currency')], 'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyhistory',
            options={'ordering': ['currency', 'pricing_policy', 'date'], 'verbose_name': 'currency history', 'verbose_name_plural': 'currency histories'},
        ),
    ]
