# Generated by Django 2.2.5 on 2019-09-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_currency_default_fx_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['user_code'], 'permissions': [('manage_currency', 'Can manage currency')], 'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
    ]
