# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160305_1110'),
        ('currencies', '0005_auto_20160311_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyhistory',
            name='master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_rates', to='users.MasterUser', verbose_name='master user'),
        ),
    ]
