# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_auto_20161003_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencygroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='currencygroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='currencygroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='currencygroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='currencyuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='currencyuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='currencyuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='currencyuserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='CurrencyGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='CurrencyUserObjectPermission',
        ),
    ]
