# Generated by Django 4.2.3 on 2023-11-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0016_instrument_owner_instrumenttype_owner_and_more'),
        ('currencies', '0007_currency_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.country', verbose_name='Country'),
        ),
    ]
