# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import poms.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_auto_20160531_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistory',
            name='date',
            field=models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date'),
        ),
    ]
