# Generated by Django 2.2.5 on 2020-03-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_auto_20191003_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
    ]
