# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_auto_20160621_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'permissions': [('view_currency', 'Can view currency'), ('manage_currency', 'Can manage currency')], 'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyhistory',
            options={'ordering': ['-date'], 'verbose_name': 'currency history', 'verbose_name_plural': 'currency histories'},
        ),
    ]
