# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0010_currency_actual_at_currency_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='created',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='currencyhistory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='currencyhistory',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='currencypricingpolicy',
            name='created',
        ),
        migrations.RemoveField(
            model_name='currencypricingpolicy',
            name='modified',
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='currencypricingpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencypricingpolicy',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
    ]
