# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('currencies', '0010_auto_20160404_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyhistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.PricingPolicy'),
        ),
    ]
