# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0012_auto_20160406_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyhistory',
            name='master_user',
        ),
    ]
