# Generated by Django 2.2.5 on 2020-12-18 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0013_auto_20200818_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='daily_pricing_model',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='price_download_scheme',
        ),
    ]
