# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160407_0945'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('currencies', '0013_remove_currencyhistory_master_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='currencies.Currency')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name_plural': 'counterparties - group permissions',
                'verbose_name': 'counterparties - group permission',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='currencies.Currency')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name_plural': 'counterparties - user permissions',
                'verbose_name': 'counterparties - user permission',
            },
        ),
    ]
