# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0025_instrument_isin'),
        ('currencies', '0014_currency_isin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='history_download_mode',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='isin',
        ),
        migrations.AddField(
            model_name='currency',
            name='daily_pricing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.DailyPricingModel', verbose_name='daily pricing model'),
        ),
    ]
