# Generated by Django 2.2.5 on 2021-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0014_auto_20201218_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistory',
            name='fx_rate',
            field=models.FloatField(default=1, validators=[], verbose_name='fx rate'),
        ),
    ]
