# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0015_auto_20160419_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencygroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='currencies.Currency', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='currencygroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='currencygroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='currencyhistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='currencies.Currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='currencyhistory',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='currencyhistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.PricingPolicy', verbose_name='pricing policy'),
        ),
        migrations.AlterField(
            model_name='currencyuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='currencies.Currency', verbose_name='content object'),
        ),
        migrations.AlterField(
            model_name='currencyuserobjectpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='currencyuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission'),
        ),
    ]
