# Generated by Django 2.2.5 on 2021-05-26 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0016_auto_20210312_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['user_code'], 'permissions': [('manage_currency', 'Can manage currency')],
                     'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyhistory',
            options={'ordering': ['date'], 'verbose_name': 'currency history',
                     'verbose_name_plural': 'currency histories'},
        ),
    ]
