# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0016_auto_20160420_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyhistory',
            name='pricing_policy',
        ),
    ]
