# Generated by Django 2.2.5 on 2021-08-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0017_auto_20210526_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyhistory',
            name='procedure_modified_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='procedure_modified_datetime'),
        ),
    ]
