# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0048_auto_20160421_1138'),
        ('currencies', '0017_remove_currencyhistory_pricing_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyhistory',
            name='pricing_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.PricingPolicy', verbose_name='pricing policy'),
        ),
    ]
