# Generated by Django 2.2.5 on 2022-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0020_auto_20220127_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='deleted_user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted user code'),
        ),
    ]
