# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_perms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='chats.Thread'),
        ),
        migrations.AlterField(
            model_name='threaduserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='chats.Thread'),
        ),
    ]
