# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('obj_perms', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericobjectpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType',
                                    verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='genericobjectpermission',
            name='object_id',
            field=models.BigIntegerField(verbose_name='object id'),
        ),
    ]
