# Generated by Django 2.2.5 on 2019-12-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0029_userprofile_two_factor_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.TextField(blank=True, default='', verbose_name='File URL')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
        ),
    ]
