# Generated by Django 2.2.5 on 2020-01-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_reports', '0002_filereport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filereport',
            name='content_type',
        ),
    ]
