# Generated by Django 2.2.5 on 2020-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_reports', '0003_remove_filereport_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereport',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
