# Generated by Django 2.2.5 on 2020-01-03 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_reports', '0004_filereport_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filereport',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='filereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
