# Generated by Django 4.0.6 on 2022-08-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_reports', '0005_auto_20200103_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereport',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
