# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('configuration_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationentityarchetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationentityarchetype',
            unique_together={('name', 'master_user', 'content_type')},
        ),
    ]
