# Generated by Django 4.2.3 on 2024-07-18 18:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import poms.explorer.models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinmarsDirectory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Path to the directory in the storage system",
                        max_length=2048,
                        unique=True,
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("mptt_level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "ordering": ["path"],
            },
            bases=(poms.explorer.models.ObjMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="finmarsfile",
            options={"ordering": ["path"]},
        ),
        migrations.RemoveConstraint(
            model_name="finmarsfile",
            name="unique_file_path",
        ),
        migrations.RemoveField(
            model_name="finmarsfile",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="finmarsfile",
            name="name",
        ),
        migrations.AlterField(
            model_name="finmarsfile",
            name="path",
            field=models.CharField(
                help_text="Path to the file in the storage system with name and extension",
                max_length=2048,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="finmarsdirectory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="explorer.finmarsdirectory",
            ),
        ),
        migrations.AddField(
            model_name="finmarsfile",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="explorer.finmarsdirectory",
            ),
        ),
    ]
