# Generated by Django 4.2.3 on 2024-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0003_remove_finmarsdirectory_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finmarsdirectory",
            name="is_file",
            field=models.BooleanField(
                default=False, help_text="Is this directory a file"
            ),
        ),
        migrations.AddField(
            model_name="finmarsdirectory",
            name="size",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Size of the file in bytes"
            ),
        ),
    ]
