# Generated by Django 4.2.3 on 2024-08-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0004_finmarsdirectory_is_file_finmarsdirectory_size"),
        ("instruments", "0026_alter_instrument_files_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinmarsFile",
        ),
    ]
