# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types',
                                    to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='account',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts',
                                    to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.AccountType', verbose_name='account type'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterIndexTogether(
            name='accounttype',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterIndexTogether(
            name='account',
            index_together=set([('master_user', 'is_deleted')]),
        ),
    ]
