# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20161205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_valid_for_all_portfolios',
            field=models.BooleanField(default=True, verbose_name='is valid for all portfolios'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is deleted'),
        ),
    ]
