# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_valid_for_all_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='accounts.AccountAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterField(
            model_name='accountclassifier',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='accounts.AccountAttributeType', verbose_name='attribute type'),
        ),
    ]
