# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160425_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountattributetype',
            options={'permissions': [('view_accountattributetype', 'Can view account attribute type')], 'verbose_name': 'account attribute type', 'verbose_name_plural': 'account attribute types'},
        ),
    ]
