# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160505_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountattributetypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountattributetypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accountattributetypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accountclassifieruserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountclassifieruserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountclassifieruserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accountclassifieruserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accounttypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accounttypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accounttypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accounttypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accountuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accountuserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='AccountAttributeTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountClassifierUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountUserObjectPermission',
        ),
    ]
