# Generated by Django 2.2.5 on 2019-09-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170512_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['user_code'], 'permissions': [('manage_account', 'Can manage account')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['user_code'], 'permissions': [('manage_accounttype', 'Can manage account type')], 'verbose_name': 'account type', 'verbose_name_plural': 'account types'},
        ),
    ]
