# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160525_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountclassifiergroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountclassifiergroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountclassifiergroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='accountclassifiergroupobjectpermission',
            name='permission',
        ),
        migrations.AlterField(
            model_name='accountattributetype',
            name='classifier_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.AccountClassifier', unique=True, verbose_name='classifier'),
        ),
        migrations.DeleteModel(
            name='AccountClassifierGroupObjectPermission',
        ),
    ]
