# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160525_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountclassifier',
            options={'verbose_name': 'account classifier', 'verbose_name_plural': 'account classifiers'},
        ),
        migrations.RemoveField(
            model_name='accountattributetype',
            name='classifier_root',
        ),
        migrations.AddField(
            model_name='accountclassifier',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='accounts.AccountAttributeType', verbose_name='attribute type'),
        ),
        migrations.AlterUniqueTogether(
            name='accountclassifier',
            unique_together=set([('attribute_type', 'user_code')]),
        ),
    ]
