# Generated by Django 4.2.3 on 2024-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_owner_accounttype_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='actual_at',
            field=models.DateTimeField(help_text='Show the Date that object is truth for, e.g. price created_at is 2024-07-10 but actually this price is 2024-01-01', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='account',
            name='external_id',
            field=models.CharField(help_text='how object is referenced in external system', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='blocked to any change (only from finmars frontend change is allowed)'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_manual_locked',
            field=models.BooleanField(default=False, help_text='just a flag to disable form on frontend'),
        ),
        migrations.AddField(
            model_name='account',
            name='source_origin',
            field=models.CharField(default='manual'),
        ),
        migrations.AddField(
            model_name='account',
            name='source_type',
            field=models.CharField(default='manual'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='deleted at'),
        ),
    ]
