# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160329_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='accountclassifier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='accountclassifier',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
    ]
