# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160908_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
