# Generated by Django 4.2.16 on 2024-11-19 20:08

from django.db import migrations, models
import poms.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_created_remove_account_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='resource_groups',
            field=poms.common.fields.ResourceGroupsField(base_field=models.CharField(max_length=1024), default=poms.common.fields.default_empty_list, size=None, verbose_name='list of resource groups user_codes, to which account belongs'),
        ),
    ]
