# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160404_1010'),
        ('accounts', '0009_auto_20160404_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tags', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name_plural': 'account tags',
                'permissions': [('view_accounttag', 'Can view account tag')],
                'verbose_name': 'account tag',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounts.AccountTag'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttag',
            unique_together=set([('master_user', 'name'), ('master_user', 'user_code')]),
        ),
    ]
