# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accountclassifier_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='accountattributetype',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='accountclassifier',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
    ]
