# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0002_auto_20160505_0837'),
        ('accounts', '0010_auto_20160525_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAttributeTypeUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='accounts.AccountAttributeType', verbose_name='content object')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'account attribute types - user permissions',
                'verbose_name': 'account attribute types - user permission',
            },
        ),
        migrations.CreateModel(
            name='AccountTypeUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='accounts.AccountType', verbose_name='content object')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'account types - user permissions',
                'verbose_name': 'account types - user permission',
            },
        ),
        migrations.CreateModel(
            name='AccountUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='accounts.Account', verbose_name='content object')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'accounts - user permissions',
                'verbose_name': 'accounts - user permission',
            },
        ),
        migrations.AlterUniqueTogether(
            name='accountuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='accounttypeuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='accountattributetypeuserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
    ]
