# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160404_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttag',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='accounttag',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short name'),
        ),
    ]
