# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160922_1432'),
        ('accounts', '0010_auto_20160914_0933'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='account',
            index_together=set([('master_user', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='accounttype',
            index_together=set([('master_user', 'is_deleted')]),
        ),
    ]
