# Generated by Django 2.2.5 on 2020-08-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200818_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'base_manager_name': 'objects', 'ordering': ['user_code'], 'permissions': [('manage_accounttype', 'Can manage account type')], 'verbose_name': 'account type', 'verbose_name_plural': 'account types'},
        ),
    ]
