# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160922_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['master_user', 'user_code'], 'permissions': [('view_account', 'Can view account'), ('manage_account', 'Can manage account')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountattribute',
            options={'ordering': ['content_object', 'attribute_type'], 'verbose_name': 'account attribute', 'verbose_name_plural': 'account attributes'},
        ),
        migrations.AlterModelOptions(
            name='accountattributetype',
            options={'ordering': ['master_user', 'name'], 'permissions': [('view_accountattributetype', 'Can view account attribute type'), ('manage_accountattributetype', 'Can manage account attribute type')], 'verbose_name': 'account attribute type', 'verbose_name_plural': 'account attribute types'},
        ),
        migrations.AlterModelOptions(
            name='accountclassifier',
            options={'ordering': ['attribute_type', 'tree_id', 'level', 'name'], 'verbose_name': 'account classifier', 'verbose_name_plural': 'account classifiers'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['master_user', 'user_code'], 'permissions': [('view_accounttype', 'Can view account type'), ('manage_accounttype', 'Can manage account type')], 'verbose_name': 'account type', 'verbose_name_plural': 'account types'},
        ),
    ]
