# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160531_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_account', 'Can view account'), ('manage_account', 'Can manage account')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountattributetype',
            options={'permissions': [('view_accountattributetype', 'Can view account attribute type'), ('manage_accountattributetype', 'Can manage account attribute type')], 'verbose_name': 'account attribute type', 'verbose_name_plural': 'account attribute types'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'permissions': [('view_accounttype', 'Can view account type'), ('manage_accounttype', 'Can manage account type')], 'verbose_name': 'account type', 'verbose_name_plural': 'account types'},
        ),
    ]
