# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20160406_0647'),
        ('accounts', '0011_auto_20160404_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountClassifier')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AttrScheme', verbose_name='attribute scheme')),
            ],
        ),
        migrations.CreateModel(
            name='AccountAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='classifiers',
        ),
        migrations.AddField(
            model_name='accountattrvalue',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='accountattrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountAttr'),
        ),
        migrations.AddField(
            model_name='accountattrvalue',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountClassifier'),
        ),
        migrations.AlterUniqueTogether(
            name='accountattrvalue',
            unique_together=set([('account', 'attr')]),
        ),
    ]
