# Generated by Django 2.2.5 on 2021-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0011_auto_20200819_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user code'),
        ),
    ]
