# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160704_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountclassifier',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountclassifier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='accountclassifier',
            name='public_name',
        ),
        migrations.RemoveField(
            model_name='accountclassifier',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='accountclassifier',
            name='user_code',
        ),
    ]
