# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20161003_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountattributetypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountattributetypegroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountattributetypegroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='accountattributetypegroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accountattributetypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountattributetypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountattributetypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accountattributetypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accountgroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='accountgroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accounttypegroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accounttypegroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accounttypegroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='accounttypegroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accounttypeuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accounttypeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accounttypeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accounttypeuserobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='accountuserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='accountuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accountuserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='AccountAttributeTypeGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountAttributeTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountTypeGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountTypeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='AccountUserObjectPermission',
        ),
    ]
