# Generated by Django 2.2.5 on 2022-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0014_auto_20211027_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created'),
        ),
    ]
