# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20161017_0828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountattribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='accountattribute',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='accountattribute',
            name='content_object',
        ),
        migrations.AlterUniqueTogether(
            name='accountattributetype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountattributetype',
            name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='accountattributetypeoption',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountattributetypeoption',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='accountattributetypeoption',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accountclassifier',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='accountclassifier',
            name='parent',
        ),
        migrations.DeleteModel(
            name='AccountAttribute',
        ),
        migrations.DeleteModel(
            name='AccountAttributeType',
        ),
        migrations.DeleteModel(
            name='AccountAttributeTypeOption',
        ),
        migrations.DeleteModel(
            name='AccountClassifier',
        ),
    ]
