# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20160418_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountattributetypeoption',
            name='order',
        ),
    ]
