from rest_framework import routers

import poms.portfolios.views as portfolios

router = routers.DefaultRouter()

router.register(
    "portfolio-class",
    portfolios.PortfolioClassViewSet,
)
router.register(
    "portfolio-type",
    portfolios.PortfolioTypeViewSet,
)
router.register(
    "portfolio-type-attribute-type",
    portfolios.PortfolioTypeAttributeTypeViewSet,
)
router.register(
    "portfolio-attribute-type",
    portfolios.PortfolioAttributeTypeViewSet,
    "portfolioattributetype",
)
router.register(
    "portfolio-classifier",
    portfolios.PortfolioClassifierViewSet,
    "portfolioclassifier",
)
router.register(
    "portfolio",
    portfolios.PortfolioViewSet,
    "portfolio",
)
router.register(
    "portfolio-register-attribute-type",
    portfolios.PortfolioRegisterAttributeTypeViewSet,
    "portfolioregisterattributetype",
)
router.register(
    "portfolio-register",
    portfolios.PortfolioRegisterViewSet,
    "portfolioregister",
)
router.register(
    "portfolio-register-record",
    portfolios.PortfolioRegisterRecordViewSet,
    "portfolioregisterrecord",
)
router.register(
    "portfolio-bundle",
    portfolios.PortfolioBundleViewSet,
    "portfoliobundle",
)
router.register(
    "first-transaction-date",
    portfolios.PortfolioFirstTransactionViewSet,
    "firsttransactiondate",
)
router.register(
    "portfolio-history",
    portfolios.PortfolioHistoryViewSet,
    "portfoliohistory",
)
router.register(
    "portfolio-reconcile-group",
    portfolios.PortfolioReconcileGroupViewSet,
    "portfolioreconcilegroup",
)
router.register(
    "portfolio-reconcile-history",
    portfolios.PortfolioReconcileHistoryViewSet,
    "portfolioreconcilehistory",
)
