# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0002_auto_20160824_0530'),
        ('counterparties', '0002_auto_20160824_0530'),
        ('chats', '0002_auto_20160824_0530'),
        ('users', '0001_initial'),
        ('instruments', '0002_auto_20160824_0530'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('accounts', '0002_auto_20160824_0530'),
        ('strategies', '0002_auto_20160824_0530'),
        ('currencies', '0002_auto_20160824_0530'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('account_types', models.ManyToManyField(blank=True, related_name='tags', to='accounts.AccountType', verbose_name='account types')),
                ('accounts', models.ManyToManyField(blank=True, related_name='tags', to='accounts.Account', verbose_name='accounts')),
                ('content_types', models.ManyToManyField(blank=True, related_name='tags', to='contenttypes.ContentType', verbose_name='content types')),
                ('counterparties', models.ManyToManyField(blank=True, related_name='tags', to='counterparties.Counterparty', verbose_name='counterparties')),
                ('counterparty_groups', models.ManyToManyField(blank=True, related_name='tags', to='counterparties.CounterpartyGroup', verbose_name='counterparty groups')),
                ('currencies', models.ManyToManyField(blank=True, related_name='tags', to='currencies.Currency', verbose_name='currencies')),
                ('instrument_types', models.ManyToManyField(blank=True, related_name='tags', to='instruments.InstrumentType', verbose_name='instrument types')),
                ('instruments', models.ManyToManyField(blank=True, related_name='tags', to='instruments.Instrument', verbose_name='instruments')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.MasterUser', verbose_name='master user')),
                ('portfolios', models.ManyToManyField(blank=True, related_name='tags', to='portfolios.Portfolio', verbose_name='portfolios')),
                ('responsible_groups', models.ManyToManyField(blank=True, related_name='tags', to='counterparties.ResponsibleGroup', verbose_name='responsible groups')),
                ('responsibles', models.ManyToManyField(blank=True, related_name='tags', to='counterparties.Responsible', verbose_name='responsibles')),
                ('strategies1', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy1', verbose_name='strategies1')),
                ('strategies2', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy2', verbose_name='strategies2')),
                ('strategies3', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy3', verbose_name='strategies3')),
                ('strategy1_groups', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy1Group', verbose_name='strategy1 groups')),
                ('strategy1_subgroups', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy1Subgroup', verbose_name='strategy1 subgroups')),
                ('strategy2_groups', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy2Group', verbose_name='strategy2 groups')),
                ('strategy2_subgroups', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy2Subgroup', verbose_name='strategy2 subgroups')),
                ('strategy3_groups', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy3Group', verbose_name='strategy3 groups')),
                ('strategy3_subgroups', models.ManyToManyField(blank=True, related_name='tags', to='strategies.Strategy3Subgroup', verbose_name='strategy3 subgroups')),
                ('thread_groups', models.ManyToManyField(blank=True, related_name='tags', to='chats.ThreadGroup')),
                ('threads', models.ManyToManyField(blank=True, related_name='tags', to='chats.Thread')),
            ],
            options={
                'verbose_name_plural': 'tags',
                'abstract': False,
                'verbose_name': 'tag',
                'permissions': [('view_tag', 'Can view tag'), ('manage_tag', 'Can manage tag')],
            },
        ),
        migrations.CreateModel(
            name='TagGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='tags.Tag', verbose_name='content object')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'verbose_name_plural': 'tags - group permissions',
                'abstract': False,
                'verbose_name': 'tags - group permission',
            },
        ),
        migrations.CreateModel(
            name='TagUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='tags.Tag', verbose_name='content object')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'verbose_name_plural': 'tags - user permissions',
                'abstract': False,
                'verbose_name': 'tags - user permission',
            },
        ),
    ]
