# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0002_auto_20160425_0912'),
        ('instruments', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('currencies', '0003_auto_20160425_0912'),
        ('strategies', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0002_auto_20160425_0912'),
    ]

    run_before = [
        ('strategies', '0002_auto_20160425_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('account_types', models.ManyToManyField(blank=True, related_name='tags', to='accounts.AccountType', verbose_name='account types')),
                ('accounts', models.ManyToManyField(blank=True, related_name='tags', to='accounts.Account', verbose_name='accounts')),
                ('content_types', models.ManyToManyField(blank=True, related_name='tags', to='contenttypes.ContentType', verbose_name='content types')),
                ('counterparties', models.ManyToManyField(blank=True, related_name='tags', to='counterparties.Counterparty', verbose_name='counterparties')),
                ('currencies', models.ManyToManyField(blank=True, related_name='tags', to='currencies.Currency', verbose_name='currencies')),
                ('instrument_types', models.ManyToManyField(blank=True, related_name='tags', to='instruments.InstrumentType', verbose_name='instrument types')),
                ('instruments', models.ManyToManyField(blank=True, related_name='tags', to='instruments.Instrument', verbose_name='instruments')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.MasterUser', verbose_name='master user')),
                ('portfolios', models.ManyToManyField(blank=True, related_name='tags', to='portfolios.Portfolio', verbose_name='portfolios')),
                ('responsibles', models.ManyToManyField(blank=True, related_name='tags', to='counterparties.Responsible', verbose_name='responsibles')),
                ('strategies', mptt.fields.TreeManyToManyField(blank=True, related_name='tags', to='strategies.Strategy', verbose_name='strategies')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'permissions': [('view_tag', 'Can view tag'), ('manage_tag', 'Can manage tag')],
            },
        ),
        migrations.CreateModel(
            name='TagGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='tags.Tag', verbose_name='content object')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'verbose_name': 'tags - group permission',
                'verbose_name_plural': 'tags - group permissions',
            },
        ),
        migrations.CreateModel(
            name='TagUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='tags.Tag', verbose_name='content object')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member', verbose_name='member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='permission')),
            ],
            options={
                'verbose_name': 'tags - user permission',
                'verbose_name_plural': 'tags - user permissions',
            },
        ),
    ]
