# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('content_types', models.ManyToManyField(blank=True, related_name='tags', to='contenttypes.ContentType', verbose_name='content types')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'abstract': False,
                'permissions': [('view_tag', 'Can view tag'), ('manage_tag', 'Can manage tag')],
                'verbose_name': 'tag',
                'ordering': ['user_code'],
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'tag links',
                'verbose_name': 'tag link',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
