# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='transaction_types',
            field=models.ManyToManyField(blank=True, related_name='tags', to='transactions.TransactionType', verbose_name='transaction types'),
        ),
        migrations.AlterUniqueTogether(
            name='taguserobjectpermission',
            unique_together=set([('content_object', 'member', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='taggroupobjectpermission',
            unique_together=set([('content_object', 'group', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
