# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20160406_0701'),
        ('counterparties', '0010_auto_20160406_0647'),
        ('currencies', '0013_remove_currencyhistory_master_user'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('counterparties', models.ManyToManyField(blank=True, related_name='tags2', to='counterparties.Counterparty')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_tags2', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name': 'counterparty tag',
                'permissions': [('view_counterpartytag', 'Can view counterparty tag')],
                'verbose_name_plural': 'counterparty tags',
            },
        ),
        migrations.CreateModel(
            name='CurrencyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('currencies', models.ManyToManyField(blank=True, related_name='tags2', to='currencies.Currency')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_tags2', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name': 'currency tag',
                'permissions': [('view_currencytag', 'Can view currency tag')],
                'verbose_name_plural': 'currency tags',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tags2', to='users.MasterUser', verbose_name='master user')),
                ('responsibles', models.ManyToManyField(blank=True, related_name='tags2', to='counterparties.Responsible')),
            ],
            options={
                'verbose_name': 'responsible tag',
                'permissions': [('view_responsibletag', 'Can view responsible tag')],
                'verbose_name_plural': 'responsible tags',
            },
        ),
        migrations.AlterUniqueTogether(
            name='responsibletag',
            unique_together=set([('master_user', 'name'), ('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='currencytag',
            unique_together=set([('master_user', 'name'), ('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartytag',
            unique_together=set([('master_user', 'name'), ('master_user', 'user_code')]),
        ),
    ]
