# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20160407_0657'),
        ('users', '0016_auto_20160406_0701'),
        ('strategies', '0007_auto_20160404_1051'),
        ('tags', '0002_auto_20160407_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_tags', to='users.MasterUser', verbose_name='master user')),
                ('strategies', mptt.fields.TreeManyToManyField(blank=True, related_name='tags', to='strategies.Strategy')),
            ],
            options={
                'verbose_name_plural': 'strategy tags',
                'verbose_name': 'strategy tag',
                'permissions': [('view_strategytag', 'Can view strategy tag')],
            },
        ),
        migrations.CreateModel(
            name='TransactionTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactiontype_tags', to='users.MasterUser', verbose_name='master user')),
                ('transaction_types', models.ManyToManyField(blank=True, related_name='tags', to='transactions.TransactionType')),
            ],
            options={
                'verbose_name_plural': 'transaction type tags',
                'verbose_name': 'transaction type tag',
                'permissions': [('view_transactiontypetag', 'Can view instrument type tag')],
            },
        ),
        migrations.AddField(
            model_name='commontag',
            name='transaction_types',
            field=models.ManyToManyField(blank=True, related_name='common_tags', to='transactions.TransactionType'),
        ),
        migrations.AlterField(
            model_name='accounttag',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='tags', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='accounttag',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tags', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='counterpartytag',
            name='counterparties',
            field=models.ManyToManyField(blank=True, related_name='tags', to='counterparties.Counterparty'),
        ),
        migrations.AlterField(
            model_name='counterpartytag',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_tags', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='currencytag',
            name='currencies',
            field=models.ManyToManyField(blank=True, related_name='tags', to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='currencytag',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_tags', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='instrumenttag',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='tags', to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumenttag',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_tags', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='instrumenttypetag',
            name='instrument_types',
            field=models.ManyToManyField(blank=True, related_name='tags', to='instruments.InstrumentType'),
        ),
        migrations.AlterField(
            model_name='instrumenttypetag',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumenttype_tags', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_tags', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='portfolios',
            field=models.ManyToManyField(blank=True, related_name='tags', to='portfolios.Portfolio'),
        ),
        migrations.AlterField(
            model_name='responsibletag',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tags', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='responsibletag',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='tags', to='counterparties.Responsible'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontypetag',
            unique_together=set([('master_user', 'user_code'), ('master_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='strategytag',
            unique_together=set([('master_user', 'user_code'), ('master_user', 'name')]),
        ),
    ]
