# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_transactiontypeaction_action_notes'),
        ('tags', '0002_auto_20160824_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='transaction_type_groups',
            field=models.ManyToManyField(blank=True, related_name='tags', to='transactions.TransactionTypeGroup', verbose_name='transaction type groups'),
        ),
    ]
