# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20160425_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taguserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='taguserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taguserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='taguserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='TagUserObjectPermission',
        ),
    ]
