# Generated by Django 2.1.12 on 2019-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_tag_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
    ]
