# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['user_code'], 'permissions': [('view_tag', 'Can view tag'), ('manage_tag', 'Can manage tag')], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
