# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_taglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='account_types',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='counterparties',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='counterparty_groups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='instrument_types',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='portfolios',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='responsible_groups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='responsibles',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategies1',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategies2',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategies3',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategy1_groups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategy1_subgroups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategy2_groups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategy2_subgroups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategy3_groups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='strategy3_subgroups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='thread_groups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='threads',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='transaction_type_groups',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='transaction_types',
        ),
    ]
