# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:41
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20160526_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='strategies1',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='tags', to='strategies.Strategy1', verbose_name='strategies 1'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='strategies2',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='tags', to='strategies.Strategy2', verbose_name='strategies 2'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='strategies3',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='tags', to='strategies.Strategy3', verbose_name='strategies 3'),
        ),
    ]
