# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20161014_1202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taggroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='taggroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='taggroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='taguserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='taguserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taguserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='taguserobjectpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='TagGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='TagUserObjectPermission',
        ),
    ]
