# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20160411_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': [('view_tag', 'Can view tag'), ('manage_tag', 'Can manage tag')], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
