# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_auto_20160531_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': [('view_tag', 'Can view tag'), ('manage_tag', 'Can manage tag')], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
