# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_auto_20160719_1221'),
        ('tags', '0010_auto_20160704_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='thread_groups',
            field=models.ManyToManyField(blank=True, related_name='tags', to='chats.ThreadGroup'),
        ),
        migrations.AddField(
            model_name='tag',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='tags', to='chats.Thread'),
        ),
    ]
