# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_key',
                 models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='public id')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='user agent')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='user ip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'session',
                'abstract': False,
                'verbose_name_plural': 'sessions',
                'ordering': ['expire_date'],
            },
        ),
    ]
