# Generated by Django 2.2.5 on 2020-07-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('http_sessions', '0002_session_current_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='current_master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.MasterUser', verbose_name='master user'),
        ),
    ]
