# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('http_sessions', '0002_auto_20161003_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['expire_date'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
    ]
