# Generated by Django 4.1.3 on 2022-12-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_reports', '0001_initial'),
        ('instruments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveSmallIntegerField(choices=[(0, 'General'), (1, 'Events'), (2, 'Transactions'), (3, 'Instruments'), (4, 'Data'), (5, 'Prices'), (6, 'Report'), (7, 'Import'), (8, 'Activity Log'), (9, 'Schedules'), (10, 'Other')], default=0, verbose_name='section')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Information'), (2, 'Warning'), (3, 'Error'), (4, 'Success')], default=1, verbose_name='type')),
                ('action_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Required'), (2, 'Required'), (3, 'Solved')], default=1, verbose_name='action status')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='performed by')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='target')),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.generatedevent', verbose_name='linked event')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SystemMessageMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is pinned')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='member')),
                ('system_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='system_messages.systemmessage', verbose_name='system message')),
            ],
        ),
        migrations.CreateModel(
            name='SystemMessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField(blank=True, default='', null=True, verbose_name='File URL')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='notes')),
                ('file_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_reports.filereport', verbose_name='file report')),
                ('system_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='system_messages.systemmessage', verbose_name='system message')),
            ],
        ),
    ]
