# Generated by Django 4.1.3 on 2023-02-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
        ('system_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='comment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='member')),
                ('system_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='system_messages.systemmessage', verbose_name='system message')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
