# Generated by Django 2.2.5 on 2020-11-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField(blank=True, default='', verbose_name='File URL')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('system_message',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments',
                                   to='system_messages.SystemMessage', verbose_name='system message')),
            ],
        ),
    ]
