# Generated by Django 2.2.5 on 2020-11-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('file_reports', '0005_auto_20200103_1330'),
        ('system_messages', '0002_systemmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessageattachment',
            name='file_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='file_reports.FileReport', verbose_name='file report'),
        ),
    ]
