# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_messages', '0002_systemmessagecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='systemmessagecomment',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='systemmessage',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.RenameField(
            model_name='systemmessagecomment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='systemmessagecomment',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
