# Generated by Django 2.2.5 on 2022-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_messages', '0004_auto_20201111_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], default='info',
                                   max_length=255, verbose_name='level'),
        )
    ]
