# Generated by Django 4.0.6 on 2022-08-22 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0080_alter_eventschedule_description_and_more'),
        ('users', '0043_ecosystemdefault_currency_pricing_scheme_and_more'),
        ('system_messages', '0005_auto_20220614_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemmessage',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='systemmessage',
            name='level',
        ),
        migrations.RemoveField(
            model_name='systemmessage',
            name='source',
        ),
        migrations.RemoveField(
            model_name='systemmessage',
            name='status',
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='linked_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='instruments.generatedevent', verbose_name='linked event'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='performed_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='performed by'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='section',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Events'), (2, 'Transactions'), (3, 'Instruments'), (4, 'Data'), (5, 'Prices'),
                         (6, 'Report'), (7, 'Import'), (8, 'Activity Log'), (9, 'Schedules')], default=0,
                verbose_name='section'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='target'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Information'), (2, 'Warning'), (3, 'Error'), (4, 'Success')], default=1,
                verbose_name='status'),
        ),
        migrations.CreateModel(
            name='SystemMessageMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Read'), (3, 'Solved')], default=1,
                                                            verbose_name='status')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is pinned')),
                ('member',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_messages',
                                   to='users.member', verbose_name='member')),
                ('system_message',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members',
                                   to='system_messages.systemmessage', verbose_name='system message')),
            ],
        ),
    ]
