# Generated by Django 4.0.6 on 2022-08-26 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('system_messages', '0008_alter_systemmessage_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmessage',
            options={'ordering': ['-created']},
        ),
    ]
