# Generated by Django 4.0.6 on 2022-10-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0043_ecosystemdefault_currency_pricing_scheme_and_more'),
        ('system_messages', '0010_alter_systemmessage_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessagemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member',
                                    verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='systemmessagemember',
            name='system_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_messages.systemmessage',
                                    verbose_name='system message'),
        ),
    ]
