# Generated by Django 4.0.6 on 2022-10-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_messages', '0011_alter_systemmessagemember_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessagemember',
            name='system_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='system_messages.systemmessage', verbose_name='system message'),
        ),
    ]
