# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='current_master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='current_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
