# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tokens', '0004_personalaccesstoken_access_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
    ]
