# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('is_system_task', models.BooleanField(default=False, verbose_name='is system task')),
                ('celery_task_id', models.CharField(max_length=255, null=True)),
                ('function_name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('I', 'INIT'), ('P', 'PENDING'), ('D', 'DONE'), ('E', 'ERROR'), ('T', 'TIMEOUT'), ('C', 'CANCELED'), ('X', 'TRANSACTIONS_ABORTED')], default='I', max_length=1, null=True, verbose_name='status')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('options', models.TextField(blank=True, null=True, verbose_name='options')),
                ('result', models.TextField(blank=True, null=True, verbose_name='result')),
                ('progress', models.TextField(blank=True, null=True, verbose_name='progress')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('verbose_name', models.CharField(max_length=255, null=True)),
                ('verbose_result', models.TextField(blank=True, null=True, verbose_name='verbose result')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CeleryTaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField(blank=True, default='', null=True, verbose_name='File URL')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='notes')),
                ('celery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='celery_tasks.celerytask', verbose_name='celery task')),
            ],
        ),
    ]
