# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_reports', '0001_initial'),
        ('celery_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytaskattachment',
            name='file_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_reports.filereport', verbose_name='file report'),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='file_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_reports.filereport', verbose_name='file report'),
        ),
    ]
