# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='task_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='task_type'),
        ),
    ]
