# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('users', '0001_initial'),
        ('celery_tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masteruser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='celery_tasks.celerytask', verbose_name='parent'),
        ),
    ]
