# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models
from rest_framework import settings


def remove_celery_tasks(apps, schema_editor):
    print('remove_duplicates here')

    CeleryTask = apps.get_model("celery_tasks", "CeleryTask")
    Member = apps.get_model('users', 'Member')

    for item in CeleryTask.objects.all():
        item.member = Member.objects.get(master_user=item.master_user, is_owner=True)
        item.save()


def rev(apps, schema_editor):
    # the reverse goes here if you want to copy company names into customer again if you migrate backwards.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('celery_tasks', '0003_auto_20190827_1107'),
    ]

    operations = [
        migrations.RunPython(remove_celery_tasks, rev)
    ]
