# Generated by Django 4.1.3 on 2023-03-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0004_celerytask_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(choices=[('I', 'INIT'), ('P', 'PENDING'), ('D', 'DONE'), ('E', 'ERROR'), ('T', 'TIMEOUT'), ('C', 'CANCELED'), ('X', 'TRANSACTIONS_ABORTED'), ('S', 'REQUEST_SENT'), ('W', 'WAIT_RESPONSE')], default='I', max_length=1, null=True, verbose_name='status'),
        ),
    ]
