# Generated by Django 2.2.5 on 2020-01-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_reports', '0005_auto_20200103_1330'),
        ('celery_tasks', '0006_auto_20190916_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='file_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_reports.FileReport', verbose_name='file report'),
        ),
    ]
