# Generated by Django 4.2.3 on 2023-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0007_celerytask_expiry_at_celerytask_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='worker_name',
            field=models.CharField(max_length=255, null=True, verbose_name='worker name'),
        ),
    ]
