# Generated by Django 4.2.3 on 2023-09-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0008_celerytask_worker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('worker_name', models.CharField(help_text='Name that will be used in celery worker command', max_length=255, null=True, verbose_name='worker name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('memory_limit', models.CharField(help_text='Memory limit for celery worker e.g. 2Gi', max_length=255, null=True, verbose_name='Memory Limit')),
                ('queue', models.TextField(blank=True, default='backend-general-queue,backend-background-queue', help_text='Comma separated list of queues that worker will listen to', null=True, verbose_name='Queue')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
