# Generated by Django 4.2.3 on 2023-09-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0010_celeryworker_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryworker',
            name='status',
            field=models.CharField(blank=True, default='unknown', help_text='Status of worker container', max_length=255, null=True, verbose_name='status'),
        ),
    ]
