# Generated by Django 2.2.5 on 2021-02-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('celery_tasks', '0011_auto_20210206_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='celery_task_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(
                choices=[('I', 'INIT'), ('P', 'PENDING'), ('D', 'DONE'), ('E', 'ERROR'), ('T', 'TIMEOUT')], default='I',
                max_length=1, null=True, verbose_name='status'),
        ),
    ]
