# Generated by Django 4.2.3 on 2023-09-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0011_celeryworker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryworker',
            name='status',
            field=models.TextField(blank=True, default='unknown', help_text='Status of worker container', null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='celeryworker',
            name='worker_name',
            field=models.CharField(default='worker01', help_text='Name that will be used in celery worker command', max_length=255, unique=True, verbose_name='worker name'),
            preserve_default=False,
        ),
    ]
