# Generated by Django 4.0.6 on 2022-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('celery_tasks', '0012_auto_20210206_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(
                choices=[('I', 'INIT'), ('P', 'PENDING'), ('D', 'DONE'), ('E', 'ERROR'), ('T', 'TIMEOUT'),
                         ('C', 'CANCELED')], default='I', max_length=1, null=True, verbose_name='status'),
        ),
    ]
