# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0012_alter_celeryworker_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='celeryworker',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='celerytask',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='celerytask',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='celeryworker',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='celeryworker',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
