# Generated by Django 4.0.6 on 2022-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('celery_tasks', '0013_celerytask_notes_alter_celerytask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(
                choices=[('I', 'INIT'), ('P', 'PENDING'), ('D', 'DONE'), ('E', 'ERROR'), ('T', 'TIMEOUT'),
                         ('C', 'CANCELED'), ('X', 'TRANSACTIONS ABORTED')], default='I', max_length=1, null=True,
                verbose_name='status'),
        ),
    ]
