# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_auto_20160407_0808'),
        ('strategies', '0007_auto_20160404_1051'),
        ('portfolios', '0017_auto_20160407_0808'),
        ('users', '0018_auto_20160407_0945'),
        ('counterparties', '0011_auto_20160407_0808'),
        ('transactions', '0026_auto_20160407_0808'),
        ('instruments', '0031_auto_20160407_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='accounts.AccountClassifier')),
                ('master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_accountattr_attrs', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.AccountAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='accounts.AccountClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterpartyAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='counterparties.CounterpartyClassifier')),
                ('master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_counterpartyattr_attrs', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterpartyAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.CounterpartyAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.CounterpartyClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='instruments.InstrumentClassifier')),
                ('master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_instrumentattr_attrs', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.InstrumentAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='instruments.InstrumentClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='instruments.Instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='portfolios.PortfolioClassifier')),
                ('master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_portfolioattr_attrs', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.PortfolioAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='portfolios.PortfolioClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='portfolios.Portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='counterparties.ResponsibleClassifier')),
                ('master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_responsibleattr_attrs', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.ResponsibleAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.ResponsibleClassifier')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.Responsible')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_transactionattr_attrs', to='users.MasterUser', verbose_name='master user')),
                ('strategy_cash', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_attrs', to='strategies.Strategy')),
                ('strategy_position', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_attrs', to='strategies.Strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.TransactionAttr')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='transactions.Transaction')),
                ('strategy_cash', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_attr_values', to='strategies.Strategy')),
                ('strategy_position', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_attr_values', to='strategies.Strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='transactionattrvalue',
            unique_together=set([('content_object', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattr',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattrvalue',
            unique_together=set([('content_object', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattr',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattrvalue',
            unique_together=set([('content_object', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattr',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattrvalue',
            unique_together=set([('content_object', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattr',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattrvalue',
            unique_together=set([('content_object', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattr',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='accountattrvalue',
            unique_together=set([('content_object', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='accountattr',
            unique_together=set([('master_user', 'user_code')]),
        ),
    ]
