# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_auto_20160406_0701'),
        ('transactions', '0025_auto_20160407_0657'),
        ('accounts', '0013_auto_20160407_0657'),
        ('counterparties', '0010_auto_20160406_0647'),
        ('instruments', '0030_auto_20160407_0657'),
        ('portfolios', '0016_auto_20160407_0657'),
        ('strategies', '0007_auto_20160404_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.AccountClassifier')),
            ],
        ),
        migrations.CreateModel(
            name='AccountAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Account')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='obj_attrs.AccountAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.AccountClassifier')),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartyAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='counterparties.CounterpartyClassifier')),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartyAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='obj_attrs.CounterpartyAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='counterparties.CounterpartyClassifier')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='counterparties.Counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instruments.InstrumentClassifier')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='obj_attrs.InstrumentAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instruments.InstrumentClassifier')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instruments.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portfolios.PortfolioClassifier')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='obj_attrs.PortfolioAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portfolios.PortfolioClassifier')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portfolios.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='counterparties.ResponsibleClassifier')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='obj_attrs.ResponsibleAttr')),
                ('classifier', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='counterparties.ResponsibleClassifier')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='counterparties.Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'verbose_name_plural': 'attribute schemes',
                'verbose_name': 'attribute scheme',
            },
        ),
        migrations.CreateModel(
            name='TransactionAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.Scheme', verbose_name='attribute scheme')),
                ('strategy_cash', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy')),
                ('strategy_position', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='obj_attrs.TransactionAttr')),
                ('strategy_cash', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy')),
                ('strategy_position', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.Strategy')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transactions.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='responsibleattr',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.Scheme', verbose_name='attribute scheme'),
        ),
        migrations.AddField(
            model_name='portfolioattr',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.Scheme', verbose_name='attribute scheme'),
        ),
        migrations.AddField(
            model_name='instrumentattr',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.Scheme', verbose_name='attribute scheme'),
        ),
        migrations.AddField(
            model_name='counterpartyattr',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.Scheme', verbose_name='attribute scheme'),
        ),
        migrations.AddField(
            model_name='accountattr',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.Scheme', verbose_name='attribute scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattrvalue',
            unique_together=set([('transaction', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheme',
            unique_together=set([('master_user', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattrvalue',
            unique_together=set([('responsible', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattrvalue',
            unique_together=set([('portfolio', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattrvalue',
            unique_together=set([('instrument', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattrvalue',
            unique_together=set([('counterparty', 'attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='accountattrvalue',
            unique_together=set([('account', 'attr')]),
        ),
    ]
