# Generated by Django 4.1.3 on 2022-12-07 21:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField(db_index=True, verbose_name='object id')),
                ('value_string', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='value (String)')),
                ('value_float', models.FloatField(blank=True, db_index=True, null=True, verbose_name='value (Float)')),
                ('value_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='value (Date)')),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
                'ordering': ['attribute_type'],
            },
        ),
        migrations.CreateModel(
            name='GenericAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (30, 'Classifier')], default=10, verbose_name='value type')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'System')], default=1, verbose_name='kind')),
                ('tooltip', models.TextField(blank=True, null=True, verbose_name='tooltip')),
                ('favorites', models.TextField(blank=True, null=True, verbose_name='favorites')),
                ('prefix', models.CharField(blank=True, max_length=255, null=True, verbose_name='prefix')),
                ('expr', models.CharField(blank=True, max_length=4096, null=True, verbose_name='expression')),
                ('can_recalculate', models.BooleanField(default=False, verbose_name='can recalculate')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'attribute type',
                'verbose_name_plural': 'attribute types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='obj_attrs.genericattributetype', verbose_name='attribute type')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='obj_attrs.genericclassifier', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'classifier',
                'verbose_name_plural': 'classifiers',
                'ordering': ['tree_id', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GenericAttributeTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='is hidden')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='obj_attrs.genericattributetype', verbose_name='attribute type')),
            ],
        ),
    ]
