# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountattr',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='accounts.AccountClassifier'),
        ),
        migrations.AlterField(
            model_name='accountattrvalue',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='accountattrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.AccountAttr'),
        ),
        migrations.AlterField(
            model_name='accountattrvalue',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='accounts.AccountClassifier'),
        ),
        migrations.AlterField(
            model_name='counterpartyattr',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='counterparties.CounterpartyClassifier'),
        ),
        migrations.AlterField(
            model_name='counterpartyattrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.CounterpartyAttr'),
        ),
        migrations.AlterField(
            model_name='counterpartyattrvalue',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.CounterpartyClassifier'),
        ),
        migrations.AlterField(
            model_name='counterpartyattrvalue',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.Counterparty'),
        ),
        migrations.AlterField(
            model_name='instrumentattr',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='instruments.InstrumentClassifier'),
        ),
        migrations.AlterField(
            model_name='instrumentattrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.InstrumentAttr'),
        ),
        migrations.AlterField(
            model_name='instrumentattrvalue',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='instruments.InstrumentClassifier'),
        ),
        migrations.AlterField(
            model_name='instrumentattrvalue',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='portfolioattr',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='portfolios.PortfolioClassifier'),
        ),
        migrations.AlterField(
            model_name='portfolioattrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.PortfolioAttr'),
        ),
        migrations.AlterField(
            model_name='portfolioattrvalue',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='portfolios.PortfolioClassifier'),
        ),
        migrations.AlterField(
            model_name='portfolioattrvalue',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='portfolios.Portfolio'),
        ),
        migrations.AlterField(
            model_name='responsibleattr',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='counterparties.ResponsibleClassifier'),
        ),
        migrations.AlterField(
            model_name='responsibleattrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.ResponsibleAttr'),
        ),
        migrations.AlterField(
            model_name='responsibleattrvalue',
            name='classifier',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.ResponsibleClassifier'),
        ),
        migrations.AlterField(
            model_name='responsibleattrvalue',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='counterparties.Responsible'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='transactionattr',
            name='strategy_cash',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_attrs', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactionattr',
            name='strategy_position',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_attrs', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactionattrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.TransactionAttr'),
        ),
        migrations.AlterField(
            model_name='transactionattrvalue',
            name='strategy_cash',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_attr_values', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactionattrvalue',
            name='strategy_position',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_attr_values', to='strategies.Strategy'),
        ),
        migrations.AlterField(
            model_name='transactionattrvalue',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='transactions.Transaction'),
        ),
    ]
