# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('obj_attrs', '0001_initial'),
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericattributetypeoption',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member',
                                    verbose_name='member'),
        ),
        migrations.AddField(
            model_name='genericattributetype',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='genericattributetype',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser',
                                    verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='genericattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_attrs.GenericAttributeType'),
        ),
        migrations.AddField(
            model_name='genericattribute',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='obj_attrs.GenericClassifier', verbose_name='classifier'),
        ),
        migrations.AddField(
            model_name='genericattribute',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='genericattributetypeoption',
            unique_together=set([('member', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='genericattributetype',
            unique_together=set([('master_user', 'content_type', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='genericattribute',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
