# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0002_auto_20160408_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicattributevalue',
            old_name='target_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='dynamicattributevalue',
            old_name='target_object_id',
            new_name='object_id',
        ),
        migrations.AlterField(
            model_name='dynamicattribute',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10),
        ),
    ]
