# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_auto_20161003_1409'),
        ('obj_attrs', '0002_auto_20161017_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericattribute',
            options={'ordering': ['attribute_type'], 'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
        migrations.AlterModelOptions(
            name='genericattributetype',
            options={'ordering': ['name'], 'verbose_name': 'attribute type', 'verbose_name_plural': 'attribute types'},
        ),
        migrations.AlterModelOptions(
            name='genericclassifier',
            options={'ordering': ['tree_id', 'level', 'name'], 'verbose_name': 'classifier', 'verbose_name_plural': 'classifiers'},
        ),
        migrations.AlterUniqueTogether(
            name='genericattributetype',
            unique_together=set([('master_user', 'content_type', 'name')]),
        ),
    ]
