# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-04 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0003_auto_20170125_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericattribute',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='value (Date)'),
        ),
        migrations.AlterField(
            model_name='genericattribute',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value (Float)'),
        ),
        migrations.AlterField(
            model_name='genericattribute',
            name='value_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='value (String)'),
        ),
    ]
