# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160407_0945'),
        ('obj_attrs', '0003_auto_20160408_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAttributeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='accountattr',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_accountattr_attrs', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='counterpartyattr',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_counterpartyattr_attrs', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='dynamicattribute',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='users.MasterUser'),
        ),
        migrations.AlterField(
            model_name='instrumentattr',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_instrumentattr_attrs', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='portfolioattr',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_portfolioattr_attrs', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='responsibleattr',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_responsibleattr_attrs', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AlterField(
            model_name='transactionattr',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_attrs_transactionattr_attrs', to='users.MasterUser', verbose_name='master user'),
        ),
        migrations.AddField(
            model_name='dynamicattributeorder',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='obj_attrs.DynamicAttribute'),
        ),
        migrations.AddField(
            model_name='dynamicattributeorder',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_orders', to='users.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicattributeorder',
            unique_together=set([('member', 'attribute')]),
        ),
    ]
