# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0004_auto_20160407_0832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountattr',
            unique_together=set([('scheme', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='counterpartyattr',
            unique_together=set([('scheme', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentattr',
            unique_together=set([('scheme', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioattr',
            unique_together=set([('scheme', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsibleattr',
            unique_together=set([('scheme', 'user_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='transactionattr',
            unique_together=set([('scheme', 'user_code')]),
        ),
    ]
