# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0006_dynamicattributegroupobjectpermission_dynamicattributeuserobjectpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicattributevalue',
            name='choices',
            field=models.ManyToManyField(blank=True, to='obj_attrs.DynamicAttributeChoice'),
        ),
        migrations.AlterField(
            model_name='dynamicattribute',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier'), (40, 'Choice'), (50, 'Choices')], default=10),
        ),
    ]
