# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-28 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('obj_attrs', '0007_remove_duplicates__20190828_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericattribute',
            unique_together=set([('attribute_type', 'object_id', 'content_type')]),
        ),
    ]
