# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0007_auto_20160408_0808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DynamicAttribute',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='DynamicAttributeChoice',
            new_name='AttributeChoice',
        ),
        migrations.RenameModel(
            old_name='DynamicAttributeGroupObjectPermission',
            new_name='AttributeGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='DynamicAttributeOrder',
            new_name='AttributeOrder',
        ),
        migrations.RenameModel(
            old_name='DynamicAttributeUserObjectPermission',
            new_name='AttributeUserObjectPermission',
        ),
        migrations.RenameModel(
            old_name='DynamicAttributeValue',
            new_name='AttributeValue',
        ),
        migrations.AlterModelOptions(
            name='attributegroupobjectpermission',
            options={'verbose_name': 'attributes - group permission', 'verbose_name_plural': 'attributes - group permissions'},
        ),
        migrations.AlterModelOptions(
            name='attributeuserobjectpermission',
            options={'verbose_name': 'attributes - user permission', 'verbose_name_plural': 'attributes - user permissions'},
        ),
    ]
