# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0008_auto_20160408_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'permissions': [('view_attribute', 'Can view attribute'), ('share_attribute', 'Can share attribute'), ('manage_attribute', 'Can manage attribute')]},
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='obj_attrs.Attribute'),
        ),
    ]
