# Generated by Django 2.2.5 on 2019-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0008_auto_20190828_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericclassifier',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='genericclassifier',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='genericclassifier',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
