# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0018_auto_20160407_0945'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('obj_attrs', '0012_auto_20160411_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='user code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='short name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (30, 'Classifier')], default=10)),
                ('order', models.IntegerField(default=0)),
                ('classifier_object_id', models.BigIntegerField(blank=True, null=True)),
                ('classifier_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_classifiers', to='contenttypes.ContentType')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_types', to='contenttypes.ContentType')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_types', to='users.MasterUser')),
            ],
            options={
                'permissions': [('view_attribute_type', 'Can view attribute_type'), ('share_attribute_type', 'Can share attribute_type'), ('manage_attribute_type', 'Can manage attribute_type')],
            },
        ),
        migrations.CreateModel(
            name='AttributeTypeGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='obj_attrs.AttributeType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'attribute types - group permission',
                'verbose_name_plural': 'attribute types - group permissions',
            },
        ),
        migrations.CreateModel(
            name='AttributeTypeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='obj_attrs.AttributeType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_orders', to='users.Member')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTypeUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='obj_attrs.AttributeType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'attribute types - user permission',
                'verbose_name_plural': 'attribute types - user permissions',
            },
        ),
        migrations.RemoveField(
            model_name='attributegroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='attributegroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='attributegroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='attributeorder',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attributeorder',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributeorder',
            name='member',
        ),
        migrations.RemoveField(
            model_name='attributeuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='attributeuserobjectpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='attributeuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='classifier_content_type',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='content_type',
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={},
        ),
        migrations.AddField(
            model_name='attribute',
            name='object_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='classifier_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_classifiers', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='AttributeGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='AttributeOrder',
        ),
        migrations.DeleteModel(
            name='AttributeUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='order',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='type',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='obj_attrs.AttributeType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attributetypeorder',
            unique_together=set([('member', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together=set([('master_user', 'content_type', 'name')]),
        ),
    ]
