# Generated by Django 2.2.5 on 2021-05-26 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0040_auto_20210409_1154'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('obj_attrs', '0014_genericattributetype_prefix'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericattributetype',
            unique_together={('master_user', 'content_type', 'user_code')},
        ),
    ]
