# Generated by Django 2.2.5 on 2021-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('obj_attrs', '0015_auto_20210526_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericattributetype',
            name='favorites',
            field=models.TextField(blank=True, null=True, verbose_name='favorites'),
        ),
    ]
