# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obj_attrs', '0015_auto_20160411_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='classifier_content_type',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attributetype',
            name='classifier_content_type',
        ),
        migrations.RemoveField(
            model_name='attributetype',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attributetype',
            name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='attributetypeorder',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attributetypeorder',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='attributetypeorder',
            name='member',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeType',
        ),
        migrations.DeleteModel(
            name='AttributeTypeOrder',
        ),
    ]
