# Generated by Django 2.2.5 on 2021-10-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('obj_attrs', '0016_genericattributetype_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericattributetype',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'System')], default=1,
                                                   verbose_name='kind'),
        ),
    ]
