# Generated by Django 2.2.5 on 2020-01-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPricingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('notes_for_user', models.TextField(blank=True, default='', verbose_name='notes for user')),
                ('error_handler', models.PositiveSmallIntegerField(choices=[(1, 'Skip'), (2, 'Default Price'), (3, 'Ask For Manual Entry'), (4, 'Add to Pricing Log')], default=1, verbose_name='error handler')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPricingSchemeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('input_type', models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'Single Parameter'), (3, 'Multiple Parameters')], default=1, verbose_name='input type')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPricingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('notes_for_user', models.TextField(blank=True, default='', verbose_name='notes for user')),
                ('error_handler', models.PositiveSmallIntegerField(choices=[(1, 'Skip'), (2, 'Default Price'), (3, 'Ask For Manual Entry'), (4, 'Add to Pricing Log')], default=1, verbose_name='error handler')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPricingSchemeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('input_type', models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'Single Parameter'), (3, 'Multiple Parameters')], default=1, verbose_name='input type')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPricingSchemeSingleParameterFormulaParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type')),
                ('instrument_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.InstrumentPricingScheme', verbose_name='Instrument Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPricingSchemeMultipleParametersFormulaParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('instrument_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.InstrumentPricingScheme', verbose_name='Instrument Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPricingSchemeManualPricingParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(max_length=255)),
                ('instrument_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.InstrumentPricingScheme', verbose_name='Instrument Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPricingSchemeBloombergParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type')),
                ('bid0', models.CharField(blank=True, max_length=50, verbose_name='bid0')),
                ('bid1', models.CharField(blank=True, max_length=50, verbose_name='bid1')),
                ('bid_multiplier', models.FloatField(default=1.0, verbose_name='bid multiplier')),
                ('ask0', models.CharField(blank=True, max_length=50, verbose_name='ask0')),
                ('ask1', models.CharField(blank=True, max_length=50, verbose_name='ask1')),
                ('ask_multiplier', models.FloatField(default=1.0, verbose_name='ask multiplier')),
                ('last0', models.CharField(blank=True, max_length=50, verbose_name='last0')),
                ('last1', models.CharField(blank=True, max_length=50, verbose_name='last1')),
                ('last_multiplier', models.FloatField(default=1.0, verbose_name='last multiplier')),
                ('instrument_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.InstrumentPricingScheme', verbose_name='Instrument Pricing Scheme')),
            ],
        ),
        migrations.AddField(
            model_name='instrumentpricingscheme',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.InstrumentPricingSchemeType', verbose_name='type'),
        ),
        migrations.CreateModel(
            name='CurrencyPricingSchemeSingleParameterFormulaParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type')),
                ('currency_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.CurrencyPricingScheme', verbose_name='Currency Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPricingSchemeMultipleParametersFormulaParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('currency_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.CurrencyPricingScheme', verbose_name='Currency Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPricingSchemeManualPricingParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(max_length=255)),
                ('currency_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.CurrencyPricingScheme', verbose_name='Currency Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPricingSchemeBloombergParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type')),
                ('fxrate', models.CharField(blank=True, max_length=50, verbose_name='FX-rate')),
                ('fxrate_multiplier', models.FloatField(default=1.0, verbose_name='FX-rate multiplier')),
                ('currency_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.CurrencyPricingScheme', verbose_name='Currency Pricing Scheme')),
            ],
        ),
        migrations.AddField(
            model_name='currencypricingscheme',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.CurrencyPricingSchemeType', verbose_name='type'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentpricingscheme',
            unique_together={('name', 'master_user')},
        ),
        migrations.AlterUniqueTogether(
            name='currencypricingscheme',
            unique_together={('name', 'master_user')},
        ),
    ]
