# Generated by Django 4.1.3 on 2022-12-07 21:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

import poms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0001_initial'),
        ('currencies', '0001_initial'),
        ('instruments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name="PriceHistoryError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=poms.common.utils.date_now,
                        verbose_name="date",
                    ),
                ),
                (
                    "principal_price",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="principal price",
                    ),
                ),
                (
                    "accrued_price",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="accrued price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("E", "Error"),
                            ("S", "Skip"),
                            ("C", "Created"),
                            ("O", "Overwritten"),
                            ("R", "Requested"),
                        ],
                        default="E",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_text",
                    models.TextField(blank=True, default="", verbose_name="error text"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instruments.instrument",
                        verbose_name="instrument",
                    ),
                ),
                (
                    "master_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.masteruser",
                        verbose_name="master user",
                    ),
                ),
                (
                    "pricing_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instruments.pricingpolicy",
                        verbose_name="pricing policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyHistoryError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=poms.common.utils.date_now,
                        verbose_name="date",
                    ),
                ),
                (
                    "fx_rate",
                    models.FloatField(
                        blank=True, default=None, null=True, verbose_name="fx rate"
                    ),
                ),
                (
                    "error_text",
                    models.TextField(blank=True, default="", verbose_name="error text"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("E", "Error"),
                            ("S", "Skip"),
                            ("C", "Created"),
                            ("O", "Overwritten"),
                            ("R", "Requested"),
                        ],
                        default="E",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                        verbose_name="currency",
                    ),
                ),
                (
                    "master_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.masteruser",
                        verbose_name="master user",
                    ),
                ),
                (
                    "pricing_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instruments.pricingpolicy",
                        verbose_name="pricing policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
