# Generated by Django 2.2.5 on 2020-01-31 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('notes_for_user', models.TextField(blank=True, default='', verbose_name='notes for user')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
            ],
            options={
                'unique_together': {('name', 'master_user')},
            },
        ),
    ]
