# Generated by Django 4.2.3 on 2024-08-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyhistoryerror',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='pricehistoryerror',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='currencyhistoryerror',
            name='created',
        ),
        migrations.RemoveField(
            model_name='currencyhistoryerror',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='pricehistoryerror',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pricehistoryerror',
            name='modified',
        ),
        migrations.AddField(
            model_name='currencyhistoryerror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyhistoryerror',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='pricehistoryerror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricehistoryerror',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
    ]
