# Generated by Django 2.2.5 on 2020-02-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricingprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedure',
            name='accrual_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='accrual date from'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='accrual_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='accrual date to'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_balance_date',
            field=models.DateField(blank=True, null=True, verbose_name='price balance date'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='price date from'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='price date to'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_fill_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='price fill days'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_override_existed',
            field=models.BooleanField(default=True, verbose_name='price override existed'),
        ),
    ]
