# Generated by Django 4.1.3 on 2023-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_currencypricingscheme_public_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypricingscheme',
            name='configuration_code',
            field=models.CharField(max_length=255, verbose_name='Configuration Code'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingscheme',
            name='configuration_code',
            field=models.CharField(max_length=255, verbose_name='Configuration Code'),
        ),
    ]
