# Generated by Django 2.2.5 on 2020-02-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pricing', '0010_auto_20200205_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProcedureResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedure',
                                   verbose_name='procedure')),
            ],
        ),
    ]
