# Generated by Django 2.2.5 on 2020-02-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0018_auto_20200205_1433'),
        ('pricing', '0011_pricingprocedureresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProcedureBloombergResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('instrument_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('ask_parameters', models.CharField(blank=True, max_length=255, null=True, verbose_name='ask parameters')),
                ('ask_value', models.FloatField(blank=True, null=True, verbose_name='ask value')),
                ('bid_parameters', models.CharField(blank=True, max_length=255, null=True, verbose_name='bid parameters')),
                ('bid_value', models.FloatField(blank=True, null=True, verbose_name='bid value')),
                ('last_parameters', models.CharField(blank=True, max_length=255, null=True, verbose_name='last parameters')),
                ('last_value', models.FloatField(blank=True, null=True, verbose_name='last value')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument', verbose_name='instrument')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedure', verbose_name='procedure')),
            ],
        ),
        migrations.DeleteModel(
            name='PricingProcedureResult',
        ),
    ]
