# Generated by Django 2.2.5 on 2020-02-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0018_auto_20200205_1433'),
        ('users', '0029_userprofile_two_factor_verification'),
        ('pricing', '0013_auto_20200211_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricingprocedurebloombergresult',
            unique_together={('master_user', 'instrument', 'date', 'pricing_policy')},
        ),
    ]
