# Generated by Django 2.2.5 on 2020-02-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_auto_20200217_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedure',
            name='accrual_is_active',
            field=models.BooleanField(default=False, verbose_name='accrual is active'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_is_active',
            field=models.BooleanField(default=False, verbose_name='price is active'),
        ),
    ]
