# Generated by Django 2.2.5 on 2020-02-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_auto_20200218_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypricingscheme',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='currencypricingscheme',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='currencypricingscheme',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='currencypricingscheme',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
        migrations.AddField(
            model_name='instrumentpricingscheme',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='instrumentpricingscheme',
            name='public_name',
            field=models.CharField(blank=True, help_text='used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name'),
        ),
        migrations.AddField(
            model_name='instrumentpricingscheme',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='instrumentpricingscheme',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='user code'),
        ),
    ]
