# Generated by Django 2.2.5 on 2020-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_auto_20200218_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedure',
            name='instrument_filters',
            field=models.TextField(blank=True, default='', verbose_name='instrument filters'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='pricing_policy_filters',
            field=models.TextField(blank=True, default='', verbose_name='pricing policy filters'),
        ),
    ]
