# Generated by Django 2.2.5 on 2020-02-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_auto_20191003_1346'),
        ('instruments', '0018_auto_20200205_1433'),
        ('pricing', '0021_auto_20200218_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencypricingpolicy',
            unique_together={('currency', 'pricing_policy')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentpricingpolicy',
            unique_together={('instrument', 'pricing_policy')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttypepricingpolicy',
            unique_together={('instrument_type', 'pricing_policy')},
        ),
    ]
