# Generated by Django 2.2.5 on 2020-02-26 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('pricing', '0027_auto_20200221_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProcedureInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('I', 'Init'), ('P', 'Pending'), ('D', 'Done'), ('E', 'Error')], default='I', max_length=1, verbose_name='status')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedure', verbose_name='pricing procedure')),
            ],
        ),
    ]
