# Generated by Django 2.2.5 on 2020-02-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pricing', '0028_pricingprocedureinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingprocedurebloombergresult',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedureInstance',
                                    verbose_name='procedure'),
        ),
    ]
