# Generated by Django 2.2.5 on 2020-02-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0018_auto_20200205_1433'),
        ('users', '0029_userprofile_two_factor_verification'),
        ('currencies', '0008_auto_20191003_1346'),
        ('pricing', '0029_auto_20200226_0644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PricingProcedureBloombergResult',
            new_name='PricingProcedureBloombergInstrumentResult',
        ),
        migrations.AddField(
            model_name='pricingprocedureinstance',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PricingProcedureBloombergCurrencyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('currency_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('fx_rate_parameters', models.CharField(blank=True, max_length=255, null=True, verbose_name='fx rate parameters')),
                ('fx_rate_value', models.FloatField(blank=True, null=True, verbose_name='fx rate value')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency', verbose_name='currency')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedureInstance', verbose_name='procedure')),
            ],
            options={
                'unique_together': {('master_user', 'currency', 'date', 'pricing_policy')},
            },
        ),
    ]
