# Generated by Django 2.2.5 on 2020-02-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0018_auto_20200205_1433'),
        ('users', '0029_userprofile_two_factor_verification'),
        ('currencies', '0008_auto_20191003_1346'),
        ('pricing', '0032_auto_20200227_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricingprocedurebloombergcurrencyresult',
            unique_together={('master_user', 'currency', 'date', 'pricing_policy', 'procedure')},
        ),
        migrations.AlterUniqueTogether(
            name='pricingprocedurebloomberginstrumentresult',
            unique_together={('master_user', 'instrument', 'date', 'pricing_policy', 'procedure')},
        ),
    ]
