# Generated by Django 2.2.5 on 2020-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0034_currencypricingschemewtradeparameters_instrumentpricingschemewtradeparameters_pricingprocedurewtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypricingschemebloombergparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='error text expr'),
        ),
        migrations.AddField(
            model_name='currencypricingschememultipleparametersformulaparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='error text expr'),
        ),
        migrations.AddField(
            model_name='currencypricingschemesingleparameterformulaparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='error text expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemebloombergparameters',
            name='accrual_calculation_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not applicable'), (2, 'As per Accrual Schedule'), (3, 'As per Formula')], default=1, verbose_name='accrual calculation method'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemebloombergparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='accrual error text expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemebloombergparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='accrual expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemebloombergparameters',
            name='accrual_historical',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='accrual historical'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemebloombergparameters',
            name='accrual_yesterday',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='accrual yesterday'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemebloombergparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='pricing error text expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='accrual_calculation_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not applicable'), (2, 'As per Accrual Schedule'), (3, 'As per Formula')], default=1, verbose_name='accrual calculation method'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='accrual error text expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='accrual expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='pricing error text'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='accrual_calculation_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not applicable'), (2, 'As per Accrual Schedule'), (3, 'As per Formula')], default=1, verbose_name='accrual calculation method'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='accrual error text expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='accrual expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='pricing error text'),
        ),
    ]
