# Generated by Django 2.2.5 on 2020-03-03 11:23

from django.db import migrations, models
import django.db.models.deletion
import poms.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('currencies', '0008_auto_20191003_1346'),
        ('instruments', '0018_auto_20200205_1433'),
        ('pricing', '0036_auto_20200302_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='accrual_parameters',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='accrual parameters'),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='accrual_value',
            field=models.FloatField(blank=True, null=True, verbose_name='accrual value'),
        ),
        migrations.CreateModel(
            name='InstrumentPriceHistoryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('principal_price', models.FloatField(default=0.0, verbose_name='principal price')),
                ('accrued_price', models.FloatField(default=0.0, verbose_name='accrued price')),
                ('price_error_text', models.TextField(blank=True, default='', verbose_name='price error text')),
                ('accrual_error_text', models.TextField(blank=True, default='', verbose_name='accrual error text')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument', verbose_name='instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('pricing_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.InstrumentPricingScheme', verbose_name='pricing scheme')),
                ('procedure_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedureInstance', verbose_name='pricing procedure instance')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyFxHistoryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=poms.common.utils.date_now, verbose_name='date')),
                ('fx_rate', models.FloatField(default=0.0, verbose_name='fx rate')),
                ('error_text', models.TextField(blank=True, default='', verbose_name='error text')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency', verbose_name='currency')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('pricing_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.CurrencyPricingScheme', verbose_name='pricing scheme')),
                ('procedure_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedureInstance', verbose_name='pricing procedure instance')),
            ],
        ),
    ]
