# Generated by Django 2.2.5 on 2020-03-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0037_auto_20200303_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedurebloombergcurrencyresult',
            name='pricing_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.CurrencyPricingScheme', verbose_name='pricing scheme'),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='pricing_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.InstrumentPricingScheme', verbose_name='pricing scheme'),
        ),
        migrations.AddField(
            model_name='pricingprocedurewtradecurrencyresult',
            name='pricing_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.CurrencyPricingScheme', verbose_name='pricing scheme'),
        ),
        migrations.AddField(
            model_name='pricingprocedurewtradeinstrumentresult',
            name='pricing_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.InstrumentPricingScheme', verbose_name='pricing scheme'),
        ),
    ]
