# Generated by Django 2.2.5 on 2020-03-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_two_factor_verification'),
        ('instruments', '0018_auto_20200205_1433'),
        ('currencies', '0008_auto_20191003_1346'),
        ('pricing', '0038_auto_20200303_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencyFxHistoryError',
            new_name='CurrencyHistoryError',
        ),
        migrations.RenameModel(
            old_name='InstrumentPriceHistoryError',
            new_name='PriceHistoryError',
        ),
    ]
