# Generated by Django 2.2.5 on 2020-03-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0040_auto_20200304_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingProcedureWtradeCurrencyResult',
        ),
    ]
