# Generated by Django 2.2.5 on 2020-03-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_auto_20191003_1346'),
        ('users', '0029_userprofile_two_factor_verification'),
        ('instruments', '0018_auto_20200205_1433'),
        ('pricing', '0041_delete_pricingprocedurewtradecurrencyresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPricingSchemeFixerParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type')),
                ('currency_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.CurrencyPricingScheme', verbose_name='Currency Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='PricingProcedureFixerCurrencyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('currency_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('close_value', models.FloatField(blank=True, null=True, verbose_name='close value')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency', verbose_name='currency')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('pricing_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.CurrencyPricingScheme', verbose_name='pricing scheme')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedureInstance', verbose_name='procedure')),
            ],
            options={
                'unique_together': {('master_user', 'currency', 'date', 'pricing_policy', 'procedure')},
            },
        ),
        migrations.DeleteModel(
            name='CurrencyPricingSchemeWtradeParameters',
        ),
    ]
