# Generated by Django 2.2.5 on 2020-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0042_auto_20200311_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypricingschemefixerparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='error text expr'),
        ),
    ]
