# Generated by Django 2.2.5 on 2020-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0043_currencypricingschemefixerparameters_error_text_expr'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentpricingschemewtradeparameters',
            name='accrual_calculation_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not applicable'), (2, 'As per Accrual Schedule'), (3, 'As per Formula')], default=1, verbose_name='accrual calculation method'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemewtradeparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='accrual error text expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemewtradeparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='accrual expr'),
        ),
        migrations.AddField(
            model_name='instrumentpricingschemewtradeparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='pricing error text expr'),
        ),
    ]
