# Generated by Django 2.2.5 on 2020-03-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0046_pricingparentprocedureinstance_pricing_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingprocedureinstance',
            name='parent_procedure_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='pricing.PricingParentProcedureInstance', verbose_name='parent pricing procedure'),
        ),
    ]
