# Generated by Django 2.2.5 on 2020-03-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0048_auto_20200317_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingparentprocedureinstance',
            options={'ordering': ['created']},
        ),
    ]
