# Generated by Django 2.2.5 on 2020-03-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0049_auto_20200318_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingparentprocedureinstance',
            options={'ordering': ['-created']},
        ),
    ]
