# Generated by Django 2.2.5 on 2020-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0050_auto_20200318_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedure',
            name='instrument_type_filters',
            field=models.TextField(blank=True, default='', verbose_name='instrument type filters'),
        ),
    ]
