# Generated by Django 2.2.5 on 2020-04-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0053_auto_20200402_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingprocedure',
            name='instrument_filters',
        ),
        migrations.RemoveField(
            model_name='pricingprocedure',
            name='price_balance_date',
        ),
        migrations.RemoveField(
            model_name='pricingprocedure',
            name='price_balance_date_expr',
        ),
        migrations.RemoveField(
            model_name='pricingprocedure',
            name='price_override_existed',
        ),
    ]
