# Generated by Django 2.2.5 on 2020-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0054_auto_20200427_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedure',
            name='currency_pricing_condition_filters',
            field=models.TextField(blank=True, default='', verbose_name='currency pricing condition filters'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='currency_pricing_scheme_filters',
            field=models.TextField(blank=True, default='', verbose_name='currency pricing scheme filters'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='instrument_pricing_condition_filters',
            field=models.TextField(blank=True, default='', verbose_name='instrument pricing condition filters'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='instrument_pricing_scheme_filters',
            field=models.TextField(blank=True, default='', verbose_name='instrument pricing scheme filters'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='portfolio_filters',
            field=models.TextField(blank=True, default='', verbose_name='portfolio filters'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_get_accrued_prices',
            field=models.BooleanField(default=False, verbose_name='price get accrued prices'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_get_fx_rates',
            field=models.BooleanField(default=False, verbose_name='price get fx rates'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_get_principal_prices',
            field=models.BooleanField(default=False, verbose_name='price get principal prices'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_overwrite_accrued_prices',
            field=models.BooleanField(default=False, verbose_name='price overwrite accrued prices'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_overwrite_fx_rates',
            field=models.BooleanField(default=False, verbose_name='price overwrite fx rates'),
        ),
        migrations.AddField(
            model_name='pricingprocedure',
            name='price_overwrite_principal_prices',
            field=models.BooleanField(default=False, verbose_name='price overwrite principal prices'),
        ),
    ]
