# Generated by Django 2.2.5 on 2020-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0056_auto_20200429_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedureinstance',
            name='action_verbose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedureinstance',
            name='provider_verbose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
