# Generated by Django 2.2.5 on 2020-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0058_pricingprocedure_currency_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingprocedure',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created by User'), (2, 'Created by Instrument'), (3, 'Created by Currency')], default=1, verbose_name='type'),
        ),
    ]
