# Generated by Django 2.2.5 on 2020-05-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0022_auto_20200406_1520'),
        ('users', '0029_userprofile_two_factor_verification'),
        ('pricing', '0059_auto_20200514_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentPricingSchemeAlphavParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('pricing_error_text_expr', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='pricing error text expr')),
                ('accrual_calculation_method', models.PositiveSmallIntegerField(choices=[(1, 'Not applicable'), (2, 'As per Accrual Schedule'), (3, 'As per Formula')], default=1, verbose_name='accrual calculation method')),
                ('accrual_expr', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='accrual expr')),
                ('accrual_error_text_expr', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='accrual error text expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type')),
                ('instrument_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.InstrumentPricingScheme', verbose_name='Instrument Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='PricingProcedureAlphavInstrumentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('instrument_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('close_value', models.FloatField(blank=True, null=True, verbose_name='close value')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument', verbose_name='instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('pricing_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.InstrumentPricingScheme', verbose_name='pricing scheme')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedureInstance', verbose_name='procedure')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('master_user', 'instrument', 'date', 'pricing_policy', 'procedure')},
            },
        ),
    ]
