# Generated by Django 2.2.5 on 2020-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0062_pricehistoryerror_error_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedureinstance',
            name='error_prices_count',
            field=models.IntegerField(default=0, verbose_name='error prices count'),
        ),
        migrations.AddField(
            model_name='pricingprocedureinstance',
            name='successful_prices_count',
            field=models.IntegerField(default=0, verbose_name='successful prices count'),
        ),
    ]
