# Generated by Django 2.2.5 on 2020-07-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0063_auto_20200526_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentForwardsPricingSchemeBloombergParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('pricing_error_text_expr', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='pricing error text expr')),
                ('accrual_calculation_method', models.PositiveSmallIntegerField(choices=[(1, 'Not applicable'), (2, 'As per Accrual Schedule'), (3, 'As per Formula')], default=1, verbose_name='accrual calculation method')),
                ('accrual_expr', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='accrual expr')),
                ('accrual_error_text_expr', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='accrual error text expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10, verbose_name='value type')),
                ('price_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='price code')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='json data')),
                ('instrument_pricing_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.InstrumentPricingScheme', verbose_name='Instrument Pricing Scheme')),
            ],
        ),
    ]
