# Generated by Django 2.2.5 on 2020-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0064_instrumentforwardspricingschemebloombergparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedureinstance',
            name='error_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='error code'),
        ),
        migrations.AddField(
            model_name='pricingprocedureinstance',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='error message'),
        ),
    ]
