# Generated by Django 2.2.5 on 2020-07-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0023_auto_20200525_1351'),
        ('users', '0033_userprofile_active_master_user'),
        ('pricing', '0065_auto_20200708_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProcedureBloombergForwardInstrumentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('instrument_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('price_code_parameters', models.CharField(blank=True, max_length=255, null=True, verbose_name='ask parameters')),
                ('price_code_value', models.FloatField(blank=True, null=True, verbose_name='ask value')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument', verbose_name='instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser', verbose_name='master user')),
                ('pricing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy', verbose_name='pricing policy')),
                ('pricing_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.InstrumentPricingScheme', verbose_name='pricing scheme')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PricingProcedureInstance', verbose_name='procedure')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('master_user', 'instrument', 'date', 'pricing_policy', 'procedure', 'reference')},
            },
        ),
    ]
