# Generated by Django 2.2.5 on 2020-07-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0069_pricingprocedurebloombergforwardinstrumentresult_tenor_clause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingprocedurebloombergforwardinstrumentresult',
            name='tenor_clause',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tenor clause'),
        ),
    ]
