# Generated by Django 2.2.5 on 2020-09-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_auto_20200922_0643'),
        ('schedules', '0006_delete_pricingschedule'),
        ('pricing', '0070_auto_20200717_0913'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricingprocedure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricingprocedure',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='pricingprocedureinstance',
            name='master_user',
        ),
        migrations.RemoveField(
            model_name='pricingprocedureinstance',
            name='parent_procedure_instance',
        ),
        migrations.RemoveField(
            model_name='pricingprocedureinstance',
            name='pricing_procedure',
        ),
        migrations.AlterField(
            model_name='currencyhistoryerror',
            name='procedure_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='pricing procedure instance'),
        ),
        migrations.AlterField(
            model_name='pricehistoryerror',
            name='procedure_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='pricing procedure instance'),
        ),
        migrations.AlterField(
            model_name='pricingprocedurealphavinstrumentresult',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='procedure'),
        ),
        migrations.AlterField(
            model_name='pricingprocedurebloombergcurrencyresult',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='procedure'),
        ),
        migrations.AlterField(
            model_name='pricingprocedurebloombergforwardinstrumentresult',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='procedure'),
        ),
        migrations.AlterField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='procedure'),
        ),
        migrations.AlterField(
            model_name='pricingprocedurefixercurrencyresult',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='procedure'),
        ),
        migrations.AlterField(
            model_name='pricingprocedurewtradeinstrumentresult',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.PricingProcedureInstance', verbose_name='procedure'),
        ),
        migrations.DeleteModel(
            name='PricingParentProcedureInstance',
        ),
        migrations.DeleteModel(
            name='PricingProcedure',
        ),
        migrations.DeleteModel(
            name='PricingProcedureInstance',
        ),
    ]
