# Generated by Django 2.2.5 on 2021-08-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pricing', '0073_auto_20210312_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistoryerror',
            name='procedure_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='procedures.PricingProcedureInstance',
                                    verbose_name='pricing procedure instance'),
        ),
        migrations.AlterField(
            model_name='currencyhistoryerror',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('S', 'Skip'), ('C', 'Created'), ('O', 'Overwritten')],
                                   default='E', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pricehistoryerror',
            name='procedure_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='procedures.PricingProcedureInstance',
                                    verbose_name='pricing procedure instance'),
        ),
        migrations.AlterField(
            model_name='pricehistoryerror',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('S', 'Skip'), ('C', 'Created'), ('O', 'Overwritten')],
                                   default='E', max_length=1, verbose_name='status'),
        ),
    ]
