# Generated by Django 2.2.5 on 2021-09-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0063_remove_eventscheduleaction_transaction_type_old'),
        ('procedures', '0016_auto_20210312_1647'),
        ('users', '0040_auto_20210409_1154'),
        ('pricing', '0074_auto_20210827_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentPricingSchemeCbondsParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(blank=True, default='', max_length=1024, verbose_name='expr')),
                ('pricing_error_text_expr', models.CharField(blank=True, default='', max_length=1024, null=True,
                                                             verbose_name='pricing error text expr')),
                ('accrual_calculation_method', models.PositiveSmallIntegerField(
                    choices=[(1, 'Not applicable'), (2, 'As per Accrual Schedule'), (3, 'As per Formula')], default=1,
                    verbose_name='accrual calculation method')),
                ('accrual_expr',
                 models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='accrual expr')),
                ('accrual_error_text_expr', models.CharField(blank=True, default='', max_length=1024, null=True,
                                                             verbose_name='accrual error text expr')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value_type',
                 models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date')], default=10,
                                                  verbose_name='value type')),
                ('instrument_pricing_scheme',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.InstrumentPricingScheme',
                                   verbose_name='Instrument Pricing Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='PricingProcedureCbondsInstrumentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('instrument_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
                ('instrument',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument',
                                   verbose_name='instrument')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MasterUser',
                                                  verbose_name='master user')),
                ('pricing_policy',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.PricingPolicy',
                                   verbose_name='pricing policy')),
                ('pricing_scheme',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='pricing.InstrumentPricingScheme', verbose_name='pricing scheme')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='procedures.PricingProcedureInstance', verbose_name='procedure')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('master_user', 'instrument', 'date', 'pricing_policy', 'procedure')},
            },
        ),
    ]
