# Generated by Django 2.2.5 on 2021-12-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pricing', '0082_auto_20211222_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprocedurealphavinstrumentresult',
            name='close_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloombergcurrencyresult',
            name='fx_rate_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloombergforwardinstrumentresult',
            name='price_code_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='accrual_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='ask_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='bid_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurebloomberginstrumentresult',
            name='last_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurecbondsinstrumentresult',
            name='close_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurecbondsinstrumentresult',
            name='high_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurecbondsinstrumentresult',
            name='low_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurecbondsinstrumentresult',
            name='open_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurecbondsinstrumentresult',
            name='volume_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurefixercurrencyresult',
            name='close_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurewtradeinstrumentresult',
            name='close_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurewtradeinstrumentresult',
            name='high_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurewtradeinstrumentresult',
            name='low_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurewtradeinstrumentresult',
            name='open_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingprocedurewtradeinstrumentresult',
            name='volume_value_error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
