# Generated by Django 2.2.5 on 2022-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pricing', '0085_auto_20220127_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistoryerror',
            name='created',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='pricehistoryerror',
            name='created',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='created'),
        ),
    ]
