# Generated by Django 4.0.6 on 2022-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pricing', '0087_auto_20220127_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypricingschemebloombergparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='error text expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschemebloombergparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschemecbondsparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='error text expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschemecbondsparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschemefixerparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='error text expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschemefixerparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschememultipleparametersformulaparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='error text expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschememultipleparametersformulaparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschemesingleparameterformulaparameters',
            name='error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='error text expr'),
        ),
        migrations.AlterField(
            model_name='currencypricingschemesingleparameterformulaparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentforwardspricingschemebloombergparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='accrual error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentforwardspricingschemebloombergparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='accrual expr'),
        ),
        migrations.AlterField(
            model_name='instrumentforwardspricingschemebloombergparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentforwardspricingschemebloombergparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='pricing error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemealphavparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='accrual error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemealphavparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='accrual expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemealphavparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemealphavparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='pricing error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemebloombergparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='accrual error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemebloombergparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='accrual expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemebloombergparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemebloombergparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='pricing error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemecbondsparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='accrual error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemecbondsparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='accrual expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemecbondsparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemecbondsparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='pricing error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='accrual error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='accrual expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschememultipleparametersformulaparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='pricing error text'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='accrual error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='accrual expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemesingleparameterformulaparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='pricing error text'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemewtradeparameters',
            name='accrual_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='accrual error text expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemewtradeparameters',
            name='accrual_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='accrual expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemewtradeparameters',
            name='expr',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='expr'),
        ),
        migrations.AlterField(
            model_name='instrumentpricingschemewtradeparameters',
            name='pricing_error_text_expr',
            field=models.CharField(blank=True, default='', max_length=2048, null=True,
                                   verbose_name='pricing error text expr'),
        ),
    ]
