name: Docker workflow

on:
  workflow_call:
    inputs:
      tag_latest:
        required: false
        type: boolean
        default: false
      version:
        required: true
        type: string
    secrets:
      CI_REGISTRY_USER:
        required: true
      CI_REGISTRY_PASSWORD:
        required: true
      CI_REGISTRY_IMAGE:
        required: true

jobs:
  release:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build and push image with attestations
        run: |
          TAG="${{ inputs.version }}"
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --tag ${{ secrets.CI_REGISTRY_IMAGE }}:$TAG \
            --sbom=true \
            --provenance=true \
            --pull \
            --no-cache \
            .
        
      - name: Tag and push as latest (with attestations)
        if: inputs.tag_latest == true
        run: |
          TAG="${{ inputs.version }}"
          # Re-tag using buildx to maintain attestations
          docker buildx imagetools create \
            --tag ${{ secrets.CI_REGISTRY_IMAGE }}:latest \
            ${{ secrets.CI_REGISTRY_IMAGE }}:$TAG
