name: CI for all commits

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff (format check)
        run: ruff format --check

      - name: Run Ruff (lint + auto-fix)
        run: ruff check

  test:
    uses: ./.github/workflows/tests.yml
